DROP VIEW IF EXISTS `v_benhnhan_nt_datt`;
CREATE VIEW `v_benhnhan_nt_datt` AS
select A.HSBA_SOVAOVIEN, A.HSTHTOAN_NGAYTT as NGAYGIOTT, A.HSTHTOAN_KHOA AS MAKHOA
from hs_thtoan A, hsba B
where A.HSBA_SOVAOVIEN = B.HSBA_SOVAOVIEN
AND B.DOITUONG_MA = 2
AND A.HSTHTOAN_DATT = 1 AND B.HSBA_DACHUYENBHYT = 0
group by A.HSBA_SOVAOVIEN order by A.HSBA_SOVAOVIEN asc
;