DROP VIEW IF EXISTS `v_thuoc_NgoaiTru`;
CREATE VIEW `v_thuoc_NgoaiTru` AS
SELECT B.TIEPDON_MA, A.THUOCPHONGKHAM_MATHUOC, D.DMTHUOC_PLBHYT stt_nh, D.DMTHUOC_MA ma_hieu,
(A.THUOCPHONGKHAM_SOLUONG - coalesce(A.THUOCPHONGKHAM_TRA,0)) sl, A.THUOCPHONGKHAM_DONGIATT gia,
coalesce(A.THUOCPHONGKHAM_DONGIABH,0) gia_bhxh, coalesce(A.THUOCPHONGKHAM_TIENBNTRA,0) tien_bn,
coalesce(A.THUOCPHONGKHAM_THANHTIEN,0) tong_tien,
(A.THUOCPHONGKHAM_SOLUONG - coalesce(A.THUOCPHONGKHAM_TRA,0))*( A.THUOCPHONGKHAM_DONGIATT-coalesce(A.THUOCPHONGKHAM_DONGIABH,0)) as tien_chenh,
(coalesce(A.THUOCPHONGKHAM_THANHTIEN,0) - coalesce(A.THUOCPHONGKHAM_TIENBNTRA,0)) as tien_bhxh
FROM thuoc_phong_kham A, v_benhnhan_ngt_datt B, tham_kham C, dm_thuoc D
WHERE B.TIEPDON_MA = C.TIEPDON_MA
AND A.THUOCPHONGKHAM_THAMKHAM = C.THAMKHAM_MA
AND A.THUOCPHONGKHAM_MATHUOC = D.DMTHUOC_MASO
AND (A.THUOCPHONGKHAM_LOAI = 1 or A.THUOCPHONGKHAM_LOAI = 3)
ORDER BY B.TIEPDON_MA asc;