DROP VIEW IF EXISTS `v_thuoc_NoiTru`;
CREATE VIEW `v_thuoc_NoiTru` AS
SELECT B.HSBA_SOVAOVIEN, C.KHOA_MA ma_khoa, A.THUOCNOITRU_NGAYGIO, A.THUOCNOITRU_MATHUOC, D.DMTHUOC_PLBHYT stt_nh, D.DMTHUOC_MA ma_hieu,(A.THUOCNOITRU_SOLUONG - coalesce(A.THUOCNOITRU_TRA,0)) sl, A.THUOCNOITRU_DONGIATT gia,
coalesce(A.THUOCNOITRU_DONGIABH,0) gia_bhxh, coalesce(A.THUOCNOITRU_TIENBNTRA,0) tien_bn,
coalesce(A.THUOCNOITRU_THANHTIEN,0) tong_tien,
(A.THUOCNOITRU_SOLUONG - coalesce(A.THUOCNOITRU_TRA,0))*( A.THUOCNOITRU_DONGIATT-coalesce(A.THUOCNOITRU_DONGIABH,0)) as tien_chenh,
(coalesce(A.THUOCNOITRU_THANHTIEN,0) - coalesce(A.THUOCNOITRU_TIENBNTRA,0)) tien_bhxh
FROM thuoc_noi_tru A, v_benhnhan_nt_datt B, hsba_khoa C, dm_thuoc D
WHERE B.HSBA_SOVAOVIEN = C.HSBA_SOVAOVIEN
AND A.HSBA_KHOA = C.HSBAKHOA_MASO
AND A.THUOCNOITRU_MATHUOC = D.DMTHUOC_MASO
AND A.THUOCDONGY_MASO IS NULL
group by B.HSBA_SOVAOVIEN, A.THUOCNOITRU_MATHUOC
ORDER BY B.HSBA_SOVAOVIEN asc, C.KHOA_MA asc, A.THUOCNOITRU_NGAYGIO asc;