CREATE TABLE `hsba_bien_ban_hoi_chan_phau_thuat` (
  `HSBABBHCPT_MASO` int(11) NOT NULL auto_increment,
  `HSBA_SOVAOVIEN` varchar(17) character set utf8 collate utf8_unicode_ci NOT NULL,
  `HSBABBHCPT_CHANDOAN` varchar(512) character set utf8 collate utf8_unicode_ci default NULL,
  `HSBABBHCPT_NGAYCAP` date default NULL,
  `NHANVIEN_MA` int(11) unsigned default NULL,
  `HSBABBHCPT_NGAYGIOCN` datetime default NULL,
  `HSBABBHCPT_MA` varchar(11) default NULL,
  `HSBABBHCPT_NGAYTGHC` datetime default NULL,
  `HSBABBHCPT_NGAYVAOVIEN` datetime default NULL,
  `HSBABBHCPT_NGAYPTTT` datetime default NULL,
  `HSBABBHCPT_CHUANDOANMA` int(10) unsigned default NULL,
  `HSBABBHCPT_PHUONGPHAP` int(10) unsigned default NULL,
  `HSBABBHCPT_PHUONGPHAP_VOCAM` int(10) unsigned default NULL,
  `HSBABBHCPT_THUKY` int(10) unsigned default NULL,
  `HSBABBHCPT_LDVV` varchar(500) default NULL,
  `HSBABBHCPT_TOMTAT` varchar(500) default NULL,
  `HSBABBHCPT_YKIEN` varchar(500) default NULL,
  `HSBABBHCPT_TIENLUONG` varchar(500) default NULL,
  `HSBABBHCPT_KHOAHOICHAN` int(10) unsigned default NULL,
  `HSBABBHCPT_HINHTHUC` int(10) unsigned default NULL,
  `HSBABBHCPT_DTSPT` varchar(500) default NULL,
  PRIMARY KEY  (`HSBABBHCPT_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_CHANDOAN` (`HSBABBHCPT_CHUANDOANMA`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_KHOAHOICHAN` (`HSBABBHCPT_KHOAHOICHAN`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_NHANVIENMA` (`NHANVIEN_MA`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PHUONG_PHAP` (`HSBABBHCPT_PHUONGPHAP`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_THUKY` (`HSBABBHCPT_THUKY`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_VOCAM` (`HSBABBHCPT_PHUONGPHAP_VOCAM`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_CHANDOAN` FOREIGN KEY (`HSBABBHCPT_CHUANDOANMA`) REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_KHOAHOICHAN` FOREIGN KEY (`HSBABBHCPT_KHOAHOICHAN`) REFERENCES `dm_khoa` (`DMKHOA_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_NHANVIENMA` FOREIGN KEY (`NHANVIEN_MA`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PHUONG_PHAP` FOREIGN KEY (`HSBABBHCPT_PHUONGPHAP`) REFERENCES `dt_dm_phau_thuat` (`DTDMPHAUTHUAT_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_SOVAOVIEN` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_THUKY` FOREIGN KEY (`HSBABBHCPT_THUKY`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_VOCAM` FOREIGN KEY (`HSBABBHCPT_PHUONGPHAP_VOCAM`) REFERENCES `dt_dm_vo_cam` (`DTDMVOCAM_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `hsba_bien_ban_hoi_chan_phau_thuat_gm` (
  `HSBABBHCPTGM_MASO` int(11) NOT NULL auto_increment,
  `HSBABBHCPT_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBABBHCPTGM_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_GM_BIENBAN` (`HSBABBHCPT_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_GM_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_GM_BIENBAN` FOREIGN KEY (`HSBABBHCPT_MASO`) REFERENCES `hsba_bien_ban_hoi_chan_phau_thuat` (`HSBABBHCPT_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_GM_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `hsba_bien_ban_hoi_chan_phau_thuat_ptv` (
  `HSBABBHCPTPTV_MASO` int(11) NOT NULL auto_increment,
  `HSBABBHCPT_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBABBHCPTPTV_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PTV_BIENBAN` (`HSBABBHCPT_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PTV_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PTV_BIENBAN` FOREIGN KEY (`HSBABBHCPT_MASO`) REFERENCES `hsba_bien_ban_hoi_chan_phau_thuat` (`HSBABBHCPT_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_PTV_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `hsba_bien_ban_hoi_chan_phau_thuat_tpk` (
  `HSBABBHCPTTPK_MASO` int(11) NOT NULL auto_increment,
  `HSBABBHCPT_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBABBHCPTTPK_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_TPK_BIENBAN` (`HSBABBHCPT_MASO`),
  KEY `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_TPK_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_TPK_BIENBAN` FOREIGN KEY (`HSBABBHCPT_MASO`) REFERENCES `hsba_bien_ban_hoi_chan_phau_thuat` (`HSBABBHCPT_MASO`),
  CONSTRAINT `FK_HSBA_BIEN_BAN_HOI_CHAN_PHAU_THUAT_TPK_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `yte_sequence` (`SEQUENCE_NAME_MA`,`SEQUENCE_CURRENT_VALUE`,`SEQUENCE_CURRENT_NEXT`,`SEQUENCE_STEP`) VALUES 
  ('MABIEN_BAN_HOI_CHAN_PHAU_THUAT',1,2,1);