ALTER TABLE `hsba_khoa` ADD COLUMN `DMTANG_MASO` INTEGER UNSIGNED AFTER `HSBAKHOA_LAN`,
 ADD CONSTRAINT `FK_hsba_khoa_tang` FOREIGN KEY `FK_hsba_khoa_tang` (`DMTANG_MASO`)
    REFERENCES `dm_tang` (`DMTANG_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
