ALTER TABLE `thuoc_noi_tru` ADD COLUMN `THUOCNOITRU_CHIDAN` VARCHAR(512) AFTER `THUOCNOITRU_THANHTIEN`;
ALTER TABLE `thuoc_noi_tru_xuat_vien` ADD COLUMN `THUOCNOITRUXV_CHIDAN` VARCHAR(512) AFTER `THUOCDONGY_MASO`;

ALTER TABLE `thuoc_noi_tru` DROP COLUMN `THUOCNOITRU_CHIDANMASO`, DROP FOREIGN KEY `FK_THUOC_NOI_TRU_THUOCNOITRU_CHIDAN`;
ALTER TABLE `thuoc_noi_tru` ADD COLUMN `THUOCNOITRU_CHIDANMA` VARCHAR(45) AFTER `THUOCNOITRU_THANHTIEN`;

ALTER TABLE `thuoc_noi_tru_xuat_vien` DROP COLUMN `THUOCNOITRUXV_CHIDANMASO`,
 DROP FOREIGN KEY `FK_THUOC_NOI_TRU_XV_CHIDAN`;
ALTER TABLE `thuoc_noi_tru_xuat_vien` ADD COLUMN `THUOCNOITRUXV_CHIDANMA` VARCHAR(45) AFTER `THUOCDONGY_MASO`;
