ALTER TABLE `db_ytdt_bd`.`dt_dm_cls_bang_gia` ADD COLUMN `DMCLSBG_SOML` INTEGER UNSIGNED AFTER `DMCLSBG_LOAIPTTT`;

ALTER TABLE `db_ytdt_bd`.`cls_mo` ADD COLUMN `CLSMO_LOAI2` VARCHAR(5) AFTER `CLSMO_DONGIABNTRA`,
 ADD COLUMN `CLSMO_SOML` INTEGER UNSIGNED AFTER `CLSMO_LOAI2`;

ALTER TABLE `db_ytdt_bd`.`cls_kham` ADD COLUMN `CLSKHAM_LOAI2` VARCHAR(5) AFTER `CLSKHAM_HH_AHG`,
 ADD COLUMN `CLSKHAM_SOML` INTEGER UNSIGNED AFTER `CLSKHAM_LOAI2`;


