ALTER TABLE `db_ytdt_bd`.`hsba_chi_tiet_phukhoa` 
MODIFY COLUMN `HSBACTPHUKHOA_SINHDUTHANG` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTPHUKHOA_SINHDENON` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTPHUKHOA_SINHNAOHUT` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTPHUKHOA_SINHSONG` VARCHAR(20) DEFAULT NULL;


ALTER TABLE `db_ytdt_bd`.`hsba_chi_tiet_nhikhoa` 
MODIFY COLUMN `HSBACTNHIKHOA_SINHDUTHANG` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTNHIKHOA_SINHDENON` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTNHIKHOA_SINHNAOHUT` VARCHAR(20) DEFAULT NULL,
MODIFY COLUMN `HSBACTNHIKHOA_SINHSONG` VARCHAR(20) DEFAULT NULL;
