ALTER TABLE `db_ytdt_bd`.`hsba` 
ADD COLUMN `HSBA_KHOADANGDT_CM` INT(10) UNSIGNED DEFAULT NULL AFTER `HSBA_KHOADANGDT`,
ADD INDEX `FK_HSBA_HSBA_KHOADANGDT_CM` USING BTREE(`HSBA_KHOADANGDT_CM`),
ADD CONSTRAINT `FK_HSBA_HSBA_KHOADANGDT_CM` FOREIGN KEY `FK_HSBA_HSBA_KHOADANGDT_CM` (`HSBA_KHOADANGDT_CM`)
    REFERENCES `dm_khoa` (`DMKHOA_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
