ALTER TABLE cls_kham ADD COLUMN `CLSKHAM_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE cls_kham ADD COLUMN `CLSKHAM_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE cls_mo ADD COLUMN `CLSMO_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE cls_mo ADD COLUMN `CLSMO_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0;
