insert into cau_hinh(CHBV_NAME, CHBV_GIATRI, CHBV_NGAYGIOCN, CHBV_CHON, CHBV_MASO) values('BA_LUU_PREFIX', 'CL',1,1,11);

insert into yte_sequence(SEQUENCE_NAME_MA, SEQUENCE_CURRENT_VALUE, SEQUENCE_CURRENT_NEXT, SEQUENCE_STEP, SEQUENCE_RESET_YEAR) VALUES('BA_CAPCUULUU',1,2,1,1);