ALTER TABLE db_ytdt_bd.thuoc_noi_tru
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_HSBA_KHOA,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCDONGY,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_BACSI,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_HANGSX,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_KHO,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_KHOA,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_MAPHIEUDT,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_MAPHONG,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_MATHUOC,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_NGUON,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_NHANVIENCN,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_PHANLOAI,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_QUOCGIA,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_THUOCNOITRU_THUNGAN,
 ADD THUOCNOITRU_CHIDANMASO INT(10) UNSIGNED AFTER DMBAITHUOC_MASO;
ALTER TABLE db_ytdt_bd.thuoc_noi_tru
 ADD CONSTRAINT FK_THUOC_NOI_TRU_HSBA_KHOA FOREIGN KEY (HSBA_KHOA) REFERENCES db_ytdt_bd.hsba_khoa (HSBAKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCDONGY FOREIGN KEY (THUOCDONGY_MASO) REFERENCES db_ytdt_bd.thuoc_dong_y_noi_tru (THUOCDONGY_MASO) ON UPDATE RESTRICT ON DELETE SET NULL,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_BACSI FOREIGN KEY (THUOCNOITRU_BACSI) REFERENCES db_ytdt_bd.dt_dm_nhan_vien (DTDMNHANVIEN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_HANGSX FOREIGN KEY (THUOCNOITRU_HANGSX) REFERENCES db_ytdt_bd.dm_nha_san_xuat (DMNHASANXUAT_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_KHO FOREIGN KEY (THUOCNOITRU_KHO) REFERENCES db_ytdt_bd.dm_khoa (DMKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_KHOA FOREIGN KEY (THUOCNOITRU_KHOA) REFERENCES db_ytdt_bd.dm_khoa (DMKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_MAPHIEUDT FOREIGN KEY (THUOCNOITRU_MAPHIEUDT) REFERENCES db_ytdt_bd.phieu_du_tru (PHIEUDT_MA) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_MAPHONG FOREIGN KEY (THUOCNOITRU_MAPHONG) REFERENCES db_ytdt_bd.dt_dm_cls_bang_gia (DTDMCLSBG_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_MATHUOC FOREIGN KEY (THUOCNOITRU_MATHUOC) REFERENCES db_ytdt_bd.dm_thuoc (DMTHUOC_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_NGUON FOREIGN KEY (THUOCNOITRU_NGUON) REFERENCES db_ytdt_bd.dm_nguon_chuong_trinh (DMNCT_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_NHANVIENCN FOREIGN KEY (THUOCNOITRU_NHANVIENCN) REFERENCES db_ytdt_bd.dt_dm_nhan_vien (DTDMNHANVIEN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_PHANLOAI FOREIGN KEY (THUOCNOITRU_PHANLOAI) REFERENCES db_ytdt_bd.dm_phan_loai_thuoc (DMPHANLOAITHUOC_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_QUOCGIA FOREIGN KEY (THUOCNOITRU_QUOCGIA) REFERENCES db_ytdt_bd.dm_quoc_gia (DMQUOCGIA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_THUNGAN FOREIGN KEY (THUOCNOITRU_THUNGAN) REFERENCES db_ytdt_bd.dt_dm_nhan_vien (DTDMNHANVIEN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_THUOCNOITRU_CHIDAN FOREIGN KEY (THUOCNOITRU_CHIDANMASO) REFERENCES db_ytdt_bd.dt_dm_chi_dan (DTDMCHIDAN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT;


ALTER TABLE db_ytdt_bd.thuoc_noi_tru_xuat_vien
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_BACSI,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_DONGY,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_HSBA_KHOA,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_KHOA,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_MAPHONG,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_MATHUOC,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_NHANVIENCN,
 DROP FOREIGN KEY FK_THUOC_NOI_TRU_XV_PHANLOAI,
 ADD THUOCNOITRUXV_CHIDANMASO INT(10) UNSIGNED AFTER THUOCDONGY_MASO;
ALTER TABLE db_ytdt_bd.thuoc_noi_tru_xuat_vien
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_BACSI FOREIGN KEY (THUOCNOITRUXV_BACSI) REFERENCES db_ytdt_bd.dt_dm_nhan_vien (DTDMNHANVIEN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_DONGY FOREIGN KEY (THUOCDONGY_MASO) REFERENCES db_ytdt_bd.thuoc_dong_y_noi_tru (THUOCDONGY_MASO) ON UPDATE RESTRICT ON DELETE SET NULL,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_HSBA_KHOA FOREIGN KEY (HSBA_KHOA) REFERENCES db_ytdt_bd.hsba_khoa (HSBAKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_KHOA FOREIGN KEY (THUOCNOITRUXV_KHOA) REFERENCES db_ytdt_bd.dm_khoa (DMKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_MAPHONG FOREIGN KEY (THUOCNOITRUXV_MAPHONG) REFERENCES db_ytdt_bd.dt_dm_cls_bang_gia (DTDMCLSBG_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_MATHUOC FOREIGN KEY (THUOCNOITRUXV_MATHUOC) REFERENCES db_ytdt_bd.dm_thuoc (DMTHUOC_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_NHANVIENCN FOREIGN KEY (THUOCNOITRUXV_NHANVIENCN) REFERENCES db_ytdt_bd.dt_dm_nhan_vien (DTDMNHANVIEN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_PHANLOAI FOREIGN KEY (THUOCNOITRUXV_PHANLOAI) REFERENCES db_ytdt_bd.dm_phan_loai_thuoc (DMPHANLOAITHUOC_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK_THUOC_NOI_TRU_XV_CHIDAN FOREIGN KEY (THUOCNOITRUXV_CHIDANMASO) REFERENCES db_ytdt_bd.dt_dm_chi_dan (DTDMCHIDAN_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT;
