ALTER TABLE phieu_du_tru ADD COLUMN PHIEUDT_LOAIPHIEU VARCHAR(45) AFTER DMLOAITHUOC_MASO;

ALTER TABLE phieu_xuat_kho ADD COLUMN PHIEUXUATKHO_LOAIPHIEU VARCHAR(45) AFTER DMLOAITHUOC_MASO;

ALTER TABLE phieu_tra_kho ADD COLUMN PHIEUTRAKHO_LOAIPHIEU VARCHAR(45) AFTER DMLOAITHUOC_MASO;
