DROP VIEW IF EXISTS `v_solieusudung_khoa_kho`;
CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_solieusudung_khoa_kho` AS SELECT TNT.THUOCNOITRU_NGAYGIO NGAY, hsba.DOITUONG_MA DOITUONG,
TNT.THUOCNOITRU_KHO KHOAXUAT, TNT.THUOCNOITRU_KHOA KHOANHAN, T.DMTHUOC_MA, T.DMTHUOC_TEN,
CONCAT(T.DMTHUOC_TEN," ",if(T.DMTHUOC_HAMLUONG is NULL,"",T.DMTHUOC_HAMLUONG))  TENHANG, DVT.DMDONVITINH_TEN,QG.DMQUOCGIA_MA,
LT.DMLOAITHUOC_MA, TNT.THUOCNOITRU_SOLUONG  SOLUONG, TNT.THUOCNOITRU_DONGIABH  DONGIA,
LT.DMLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_TEN
FROM THUOC_NOI_TRU TNT
INNER JOIN HSBA_KHOA hsbak ON TNT.HSBA_KHOA = hsbak.HSBAKHOA_MASO
INNER JOIN HSBA hsba ON hsbak.HSBA_SOVAOVIEN = hsba.HSBA_SOVAOVIEN
INNER JOIN PHIEU_DU_TRU PDT ON TNT.THUOCNOITRU_MAPHIEUDT = PDT.PHIEUDT_MA
INNER JOIN DM_THUOC T on (TNT.THUOCNOITRU_MATHUOC = T.DMTHUOC_MASO)
INNER JOIN DM_DON_VI_TINH DVT on (T.DMDONVITINH_MASO = DVT.DMDONVITINH_MASO)
INNER JOIN DM_PHAN_LOAI_THUOC PLT on (T.DMPHANLOAITHUOC_MASO = PLT.DMPHANLOAITHUOC_MASO)
INNER JOIN DM_LOAI_THUOC LT on (PLT.DMLOAITHUOC_MASO = LT.DMLOAITHUOC_MASO)
INNER JOIN DM_QUOC_GIA QG on (TNT.THUOCNOITRU_QUOCGIA = QG.DMQUOCGIA_MASO)
WHERE THUOCNOITRU_MAPHIEUPDTTRA IS NULL
AND PDT.PHIEUDT_DAXUAT = 1

UNION ALL

SELECT THUOCNOITRU_NGAYGIO NGAY, hsba.DOITUONG_MA DOITUONG,
TNT.THUOCNOITRU_KHO KHOAXUAT, TNT.THUOCNOITRU_KHOA KHOANHAN, T.DMTHUOC_MA, T.DMTHUOC_TEN,
CONCAT(T.DMTHUOC_TEN," ",if(T.DMTHUOC_HAMLUONG is NULL,"",T.DMTHUOC_HAMLUONG)) TENHANG, DVT.DMDONVITINH_TEN,QG.DMQUOCGIA_MA,
LT.DMLOAITHUOC_MA, TNT.THUOCNOITRU_SOLUONG SOLUONG, TNT.THUOCNOITRU_DONGIABH DONGIA,
LT.DMLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_TEN
FROM THUOC_NOI_TRU TNT
INNER JOIN HSBA_KHOA hsbak ON TNT.HSBA_KHOA = hsbak.HSBAKHOA_MASO
INNER JOIN HSBA hsba ON hsbak.HSBA_SOVAOVIEN = hsba.HSBA_SOVAOVIEN
INNER JOIN PHIEU_DU_TRU PDT ON TNT.THUOCNOITRU_MAPHIEUPDTTRA = PDT.PHIEUDT_MA
INNER JOIN DM_THUOC T on (TNT.THUOCNOITRU_MATHUOC = T.DMTHUOC_MASO)
INNER JOIN DM_DON_VI_TINH DVT on (T.DMDONVITINH_MASO = DVT.DMDONVITINH_MASO)
INNER JOIN DM_PHAN_LOAI_THUOC PLT on (T.DMPHANLOAITHUOC_MASO = PLT.DMPHANLOAITHUOC_MASO)
INNER JOIN DM_LOAI_THUOC LT on (PLT.DMLOAITHUOC_MASO = LT.DMLOAITHUOC_MASO)
INNER JOIN DM_QUOC_GIA QG on (TNT.THUOCNOITRU_QUOCGIA = QG.DMQUOCGIA_MASO)
WHERE TNT.THUOCNOITRU_MAPHIEUPDTTRA IS NOT NULL

UNION ALL

SELECT THUOCNOITRU_NGAYGIO NGAY, hsba.DOITUONG_MA DOITUONG, THUOCNOITRU_KHOA KHOAXUAT, THUOCNOITRU_KHOA KHOANHAN, T.DMTHUOC_MA, T.DMTHUOC_TEN,
CONCAT(T.DMTHUOC_TEN," ",if(T.DMTHUOC_HAMLUONG is NULL,"",T.DMTHUOC_HAMLUONG)) TENHANG, DVT.DMDONVITINH_TEN,QG.DMQUOCGIA_MA,
LT.DMLOAITHUOC_MA, TNT.THUOCNOITRU_SOLUONG SOLUONG, TNT.THUOCNOITRU_DONGIABH DONGIA,
LT.DMLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_TEN
FROM THUOC_NOI_TRU TNT
INNER JOIN HSBA_KHOA hsbak ON TNT.HSBA_KHOA = hsbak.HSBAKHOA_MASO
INNER JOIN HSBA hsba ON hsbak.HSBA_SOVAOVIEN = hsba.HSBA_SOVAOVIEN
INNER JOIN DM_THUOC T on (TNT.THUOCNOITRU_MATHUOC = T.DMTHUOC_MASO)
INNER JOIN DM_DON_VI_TINH DVT on (T.DMDONVITINH_MASO = DVT.DMDONVITINH_MASO)
INNER JOIN DM_PHAN_LOAI_THUOC PLT on (T.DMPHANLOAITHUOC_MASO = PLT.DMPHANLOAITHUOC_MASO)
INNER JOIN DM_LOAI_THUOC LT on (PLT.DMLOAITHUOC_MASO = LT.DMLOAITHUOC_MASO)
INNER JOIN DM_QUOC_GIA QG on (TNT.THUOCNOITRU_QUOCGIA = QG.DMQUOCGIA_MASO)
WHERE TNT.THUOCNOITRU_MAPHIEU IS NOT NULL
AND TNT.THUOCNOITRU_TUTRUC_PDT = 2

UNION ALL

SELECT THUOCNOITRU_NGAYGIO NGAY, hsba.DOITUONG_MA DOITUONG, THUOCNOITRU_KHOA KHOAXUAT, THUOCNOITRU_KHOA KHOANHAN, T.DMTHUOC_MA, T.DMTHUOC_TEN,
CONCAT(T.DMTHUOC_TEN," ",if(T.DMTHUOC_HAMLUONG is NULL,"",T.DMTHUOC_HAMLUONG)) TENHANG, DVT.DMDONVITINH_TEN,QG.DMQUOCGIA_MA,
LT.DMLOAITHUOC_MA, TNT.THUOCNOITRU_SOLUONG SOLUONG, TNT.THUOCNOITRU_DONGIABH DONGIA,
LT.DMLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_MASO, PLT.DMPHANLOAITHUOC_TEN
FROM THUOC_NOI_TRU TNT
INNER JOIN HSBA_KHOA hsbak ON TNT.HSBA_KHOA = hsbak.HSBAKHOA_MASO
INNER JOIN HSBA hsba ON hsbak.HSBA_SOVAOVIEN = hsba.HSBA_SOVAOVIEN
INNER JOIN DM_THUOC T on (TNT.THUOCNOITRU_MATHUOC = T.DMTHUOC_MASO)
INNER JOIN DM_DON_VI_TINH DVT on (T.DMDONVITINH_MASO = DVT.DMDONVITINH_MASO)
INNER JOIN DM_PHAN_LOAI_THUOC PLT on (T.DMPHANLOAITHUOC_MASO = PLT.DMPHANLOAITHUOC_MASO)
INNER JOIN DM_LOAI_THUOC LT on (PLT.DMLOAITHUOC_MASO = LT.DMLOAITHUOC_MASO)
INNER JOIN DM_QUOC_GIA QG on (TNT.THUOCNOITRU_QUOCGIA = QG.DMQUOCGIA_MASO)
WHERE TNT.THUOCNOITRU_TUTRUC_PDT = 1;