ALTER TABLE `db_ytdt_bd`.`hsba_chuyen_mon`
 ADD COLUMN `HSBACM_BENHPHU2` INT(10) UNSIGNED AFTER `HSBACM_BENHPHU`,
 ADD COLUMN `HSBACM_BENHPHU3` INT(10) UNSIGNED AFTER `HSBACM_BENHPHU2`,
 ADD COLUMN `HSBACM_BENHPHU4` INT(10) UNSIGNED AFTER `HSBACM_BENHPHU3`,
 ADD COLUMN `HSBACM_BENHPHU5` INT(10) UNSIGNED AFTER `HSBACM_BENHPHU4`,
 ADD CONSTRAINT `FK_HSBA_CHUYEN_MON_BENHPHU2` FOREIGN KEY `FK_HSBA_CHUYEN_MON_BENHPHU2` (`HSBACM_BENHPHU2`)
    REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
 ADD CONSTRAINT `FK_HSBA_CHUYEN_MON_BENHPHU3` FOREIGN KEY `FK_HSBA_CHUYEN_MON_BENHPHU3` (`HSBACM_BENHPHU3`)
    REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
 ADD CONSTRAINT `FK_HSBA_CHUYEN_MON_BENHPHU4` FOREIGN KEY `FK_HSBA_CHUYEN_MON_BENHPHU4` (`HSBACM_BENHPHU4`)
    REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
 ADD CONSTRAINT `FK_HSBA_CHUYEN_MON_BENHPHU5` FOREIGN KEY `FK_HSBA_CHUYEN_MON_BENHPHU5` (`HSBACM_BENHPHU5`)
    REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
