CREATE TABLE `thuoc_dong_y_ngoai_tru` (
  `THUOCDONGY_MASO` int(11) NOT NULL AUTO_INCREMENT,
  `TIEPDON_MA` varchar(17) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `THUOCDONGY_THAMKHAM` int(10) unsigned NOT NULL,
  `THUOCDONGY_KHOA` int(10) unsigned NOT NULL,
  `DMBAITHUOC_MASO` int(11) NOT NULL,
  `THUOCDONGY_LOAI` varchar(4) DEFAULT NULL COMMENT 'LOAI PHIEU (1. THUOC BAN KHAM, 2. KE TOA VE, 3. QUAY BENH VIEN)',
  `THUOCDONGY_SOLUONG` double unsigned NOT NULL,
  `THUOCDONGY_DONGIA` double NOT NULL,
  `THUOCDONGY_NGAYGIOCN` datetime DEFAULT NULL,
  `THUOCDONGY_NHANVIENCN` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`THUOCDONGY_MASO`),
  KEY `FK_THUOC_DONGY_THUOCDONGY_KHOA` (`THUOCDONGY_KHOA`),
  KEY `FK_THUOC_DONGY_THUOCDONGY_NHANVIENCN` (`THUOCDONGY_NHANVIENCN`),
  KEY `FK_THUOC_DONGY_DMBAITHUOC_MASO` (`DMBAITHUOC_MASO`),
  KEY `FK_THUOC_DONGY_TIEPDON_MA` (`TIEPDON_MA`),
  KEY `FK_THUOC_DONGY_THAMKHAm` (`THUOCDONGY_THAMKHAM`),
  CONSTRAINT `FK_THUOC_DONGY_THUOCDONGY_KHOA` FOREIGN KEY (`THUOCDONGY_KHOA`) REFERENCES `dm_khoa` (`DMKHOA_MASO`),
  CONSTRAINT `FK_THUOC_DONGY_DMBAITHUOC_MASO` FOREIGN KEY (`DMBAITHUOC_MASO`) REFERENCES `dm_bai_thuoc` (`DMBAITHUOC_MASO`),
  CONSTRAINT `FK_THUOC_DONGY_THUOCDONGY_NHANVIENCN` FOREIGN KEY (`THUOCDONGY_NHANVIENCN`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_THUOC_DONGY_TIEPDON_MA` FOREIGN KEY (`TIEPDON_MA`) REFERENCES `tiep_don` (`TIEPDON_MA`),
  CONSTRAINT `FK_THUOC_DONGY_THAMKHAm` FOREIGN KEY (`THUOCDONGY_THAMKHAM`) REFERENCES `tham_kham` (`THAMKHAM_MA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `thuoc_dong_y_noi_tru` (
  `THUOCDONGY_MASO` int(11) NOT NULL AUTO_INCREMENT,
  `HSBA_SOVAOVIEN` varchar(17) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `THUOCDONGY_KHOA` int(10) unsigned NOT NULL,
  `DMBAITHUOC_MASO` int(11) NOT NULL,
  `THUOCDONGY_LOAI` varchar(4) DEFAULT NULL COMMENT 'LOAI PHIEU (0. Pdt, 1. Tu truc, 2. Ke toa xuat vien)',
  `THUOCDONGY_SOLUONG` double unsigned NOT NULL,
  `THUOCDONGY_DONGIA` double NOT NULL,
  `THUOCDONGY_NGAYGIOCN` datetime DEFAULT NULL,
  `THUOCDONGY_NHANVIENCN` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`THUOCDONGY_MASO`),
  KEY `FK_THUOC_DONGYNT_THUOCDONGY_KHOA` (`THUOCDONGY_KHOA`),
  KEY `FK_THUOC_DONGYNT_THUOCDONGY_NHANVIENCN` (`THUOCDONGY_NHANVIENCN`),
  KEY `FK_THUOC_DONGYNT_DMBAITHUOC_MASO` (`DMBAITHUOC_MASO`),
  KEY `FK_THUOC_DONGYNT_HSBA_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  CONSTRAINT `FK_THUOC_DONGYNT_THUOCDONGY_KHOA` FOREIGN KEY (`THUOCDONGY_KHOA`) REFERENCES `dm_khoa` (`DMKHOA_MASO`),
  CONSTRAINT `FK_THUOC_DONGYNT_DMBAITHUOC_MASO` FOREIGN KEY (`DMBAITHUOC_MASO`) REFERENCES `dm_bai_thuoc` (`DMBAITHUOC_MASO`),
  CONSTRAINT `FK_THUOC_DONGYNT_THUOCDONGY_NHANVIENCN` FOREIGN KEY (`THUOCDONGY_NHANVIENCN`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_THUOC_DONGYNT_HSBA_SOVAOVIEN` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

ALTER TABLE `thuoc_dong_y_ngoai_tru` ADD COLUMN `THUOCDONGY_TYLEBH` DOUBLE AFTER `THUOCDONGY_NHANVIENCN`,
 ADD COLUMN `THUOCDONGY_TIENBNTRA` DOUBLE AFTER `THUOCDONGY_TYLEBH`;

ALTER TABLE `thuoc_dong_y_noi_tru` ADD COLUMN `THUOCDONGY_TYLEBH` DOUBLE AFTER `THUOCDONGY_NHANVIENCN`,
 ADD COLUMN `THUOCDONGY_TIENBNTRA` DOUBLE AFTER `THUOCDONGY_TYLEBH`;

ALTER TABLE `thuoc_phong_kham` ADD COLUMN `THUOCDONGY_MASO` INTEGER AFTER `THUOCPHONGKHAM_MAPHIEUDT`,
 ADD CONSTRAINT `FK_THUOC_PHONG_KHAM_THUOCPHONGKHAM_THUOCDONGY` FOREIGN KEY `FK_THUOC_PHONG_KHAM_THUOCPHONGKHAM_THUOCDONGY` (`THUOCDONGY_MASO`)
    REFERENCES `thuoc_dong_y_ngoai_tru` (`THUOCDONGY_MASO`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;


ALTER TABLE `thuoc_noi_tru` ADD COLUMN `THUOCDONGY_MASO` INTEGER AFTER `THUOCNOITRU_TIENBNTRA`,
 ADD CONSTRAINT `FK_THUOC_NOI_TRU_THUOCDONGY` FOREIGN KEY `FK_THUOC_NOI_TRU_THUOCDONGY` (`THUOCDONGY_MASO`)
    REFERENCES `thuoc_dong_y_noi_tru` (`THUOCDONGY_MASO`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

ALTER TABLE `thuoc_noi_tru_xuat_vien` ADD COLUMN `THUOCDONGY_MASO` INTEGER AFTER `THUOCNOITRUXV_STT`,
 ADD CONSTRAINT `FK_THUOC_NOI_TRU_XV_DONGY` FOREIGN KEY `FK_THUOC_NOI_TRU_XV_DONGY` (`THUOCDONGY_MASO`)
    REFERENCES `thuoc_dong_y_noi_tru` (`THUOCDONGY_MASO`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;
ALTER TABLE `thuoc_phong_kham` ADD COLUMN `DMBAITHUOC_MASO` INTEGER AFTER `THUOCDONGY_MASO`;

ALTER TABLE `thuoc_noi_tru` ADD COLUMN `DMBAITHUOC_MASO` INTEGER AFTER `THUOCDONGY_MASO`;