ALTER TABLE `db_ytdt_bd`.`thuoc_phong_kham` ADD COLUMN `THUOCPHONGKHAM_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Don gia da lam tron ' AFTER `DMBAITHUOC_MASO`,
 ADD COLUMN `THUOCPHONGKHAM_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Thanh tien = dongiatt x soluong (lam tron so)' AFTER `THUOCPHONGKHAM_DONGIATT`;

ALTER TABLE `db_ytdt_bd`.`thuoc_noi_tru` ADD COLUMN `THUOCNOITRU_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Don gia da lam tron' AFTER `DMDOITUONG_MASO`,
 ADD COLUMN `THUOCNOITRU_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Thanh tien = dongiatt x soluong (lam tron so)' AFTER `THUOCNOITRU_DONGIATT`;

ALTER TABLE `db_ytdt_bd`.`thuoc_dong_y_noi_tru` ADD COLUMN `THUOCDONGY_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Don gia da lam tron' AFTER `THUOCDONGY_TIENBNTRA`,
 ADD COLUMN `THUOCDONGY_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Thanh tien = dongiatt x soluong (lam tron so)' AFTER `THUOCDONGY_DONGIATT`;

ALTER TABLE `db_ytdt_bd`.`thuoc_dong_y_ngoai_tru` ADD COLUMN `THUOCDONGY_DONGIATT` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Don gia da lam trong' AFTER `THUOCDONGY_TIENBNTRA`,
 ADD COLUMN `THUOCDONGY_THANHTIEN` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Thanh tien = dongaitt x soluong (lam tron so)' AFTER `THUOCDONGY_DONGIATT`;