DROP  TABLE IF EXISTS  `db_ytdt_bd`.`hsba_lap_trich_bien_ban_hoi_chan_bacsi`;
DROP  TABLE IF EXISTS  `db_ytdt_bd`.`hsba_lap_trich_bien_ban_hoi_chan`;
DROP  TABLE IF EXISTS  `db_ytdt_bd`.`hsba_phieu_phau_thuat_thu_thuat_bacsi`;
DROP  TABLE IF EXISTS  `db_ytdt_bd`.`hsba_phieu_phau_thuat_thu_thuat_bacsigm`;
DROP  TABLE IF EXISTS  `db_ytdt_bd`.`hsba_phieu_phau_thuat_thu_thuat`;


CREATE TABLE `hsba_lap_trich_bien_ban_hoi_chan` (
  `HSBALTBBHC_MASO` int(11) NOT NULL auto_increment,
  `HSBA_SOVAOVIEN` varchar(17) character set utf8 collate utf8_unicode_ci NOT NULL,
  `HSBALTBBHC_NGAYCAP` date default NULL,
  `NHANVIEN_MA` int(11) unsigned default NULL,
  `HSBALTBBHC_NGAYGIOCN` datetime default NULL,
  `HSBALTBBHC_MA` varchar(11) default NULL,
  `HSBALTBBHC_THOIGIANHOICHAN` datetime default NULL,
  `HSBALTBBHC_CHUANDOANMA` int(10) unsigned default NULL,
  `HSBALTBBHC_PHUONGPHAP_VOCAM` int(10) unsigned default NULL,
  `HSBALTBBHC_CHUTOA` int(10) unsigned default NULL,
  `HSBALTBBHC_THUKY` int(10) unsigned default NULL,
  `HSBALTBBHC_TOMTAT` varchar(1000) default NULL,
  `HSBALTBBHC_KETLUAN` varchar(1000) default NULL,
  `HSBALTBBHC_HUONGDANDIEUTRI` varchar(1000) default NULL,
  PRIMARY KEY  (`HSBALTBBHC_MASO`),
  KEY `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_CHANDOAN` (`HSBALTBBHC_CHUANDOANMA`),
  KEY `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  KEY `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_CHUTOA` (`HSBALTBBHC_CHUTOA`),
  KEY `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_THUKY` (`HSBALTBBHC_THUKY`),
  CONSTRAINT `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_CHANDOAN` FOREIGN KEY (`HSBALTBBHC_CHUANDOANMA`) REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`),
  CONSTRAINT `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_CHUTOA` FOREIGN KEY (`HSBALTBBHC_CHUTOA`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_SOVAOVIEN` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`),
  CONSTRAINT `FK_LAP_TRICH_BIEN_BAN_HOI_CHAN_THUKY` FOREIGN KEY (`HSBALTBBHC_THUKY`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `hsba_lap_trich_bien_ban_hoi_chan_bacsi` (
  `HSBALTBBHCBS_MASO` int(11) NOT NULL auto_increment,
  `HSBALTBBHC_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBALTBBHCBS_MASO`),
  KEY `FK_HSBA_LAP_TRICH_BIEN_BAN_HOI_CHAN_BACSI_LAPTRICH` (`HSBALTBBHC_MASO`),
  KEY `FK_HSBA_LAP_TRICH_BIEN_BAN_HOI_CHAN_BACSI_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_LAP_TRICH_BIEN_BAN_HOI_CHAN_BACSI_LAPTRICH` FOREIGN KEY (`HSBALTBBHC_MASO`) REFERENCES `hsba_lap_trich_bien_ban_hoi_chan` (`HSBALTBBHC_MASO`),
  CONSTRAINT `FK_HSBA_LAP_TRICH_BIEN_BAN_HOI_CHAN_BACSI_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `hsba_phieu_phau_thuat_thu_thuat` (
  `HSBAPPTTT_MASO` int(11) NOT NULL auto_increment,
  `HSBA_SOVAOVIEN` varchar(17) character set utf8 collate utf8_unicode_ci NOT NULL,
  `HSBAPPTTT_CHANDOAN` varchar(512) character set utf8 collate utf8_unicode_ci default NULL,
  `HSBAPPTTT_NGAYCAP` date default NULL,
  `NHANVIEN_MA` int(11) unsigned default NULL,
  `HSBAPPTTT_NGAYGIOCN` datetime default NULL,
  `HSBAPPTTT_MA` varchar(11) default NULL,
  `HSBAPPTTT_NGAYCX` datetime default NULL,
  `HSBAPPTTT_NGAYVAOVIEN` datetime default NULL,
  `HSBAPPTTT_NGAYPTTT` datetime default NULL,
  `HSBAPPTTT_CHUANDOANMA_TRUOC` int(10) unsigned default NULL,
  `HSBAPPTTT_CHUANDOANMA_SAU` int(10) unsigned default NULL,
  `HSBAPPTTT_PHUONGPHAP` int(10) unsigned default NULL,
  `HSBAPPTTT_LOAI` int(10) unsigned default NULL,
  `HSBAPPTTT_PHUONGPHAP_VOCAM` int(10) unsigned default NULL,
  `HSBAPPTTT_BACSI` int(10) unsigned default NULL,
  `HSBAPPTTT_BACSI_GMHS` int(10) unsigned default NULL,
  `HSBAPPTTT_MOTA_LUOCDO` varchar(2000) default NULL,
  `HSBAPPTTT_DANLUU` varchar(500) default NULL,
  `HSBAPPTTT_BAC` varchar(500) default NULL,
  `HSBAPPTTT_NGAYRUT` datetime default NULL,
  `HSBAPPTTT_NGAYCATCHI` datetime default NULL,
  `HSBAPPTTT_KHAC` varchar(500) default NULL,
  `HSBAPPTTT_TRINHTU` varchar(2000) default NULL,
  `HSBAPPTTT_LOAIPTTT` varchar(200) default NULL,
  PRIMARY KEY  (`HSBAPPTTT_MASO`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_CHUANDOANMA_SAU` (`HSBAPPTTT_CHUANDOANMA_SAU`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_PHUONGPHAP` (`HSBAPPTTT_PHUONGPHAP`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_LOAI` (`HSBAPPTTT_LOAI`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_PHUONGPHAP_VOCAM` (`HSBAPPTTT_PHUONGPHAP_VOCAM`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI` (`HSBAPPTTT_BACSI`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_GMHS` (`HSBAPPTTT_BACSI_GMHS`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_CHUANDOANMA_TRUOC` (`HSBAPPTTT_CHUANDOANMA_TRUOC`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_HSBA_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_NHANVIEN_MA` (`NHANVIEN_MA`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI` FOREIGN KEY (`HSBAPPTTT_BACSI`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_GMHS` FOREIGN KEY (`HSBAPPTTT_BACSI_GMHS`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_CHUANDOANMA_SAU` FOREIGN KEY (`HSBAPPTTT_CHUANDOANMA_SAU`) REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_CHUANDOANMA_TRUOC` FOREIGN KEY (`HSBAPPTTT_CHUANDOANMA_TRUOC`) REFERENCES `dm_benh_icd` (`DMBENHICD_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_HSBA_SOVAOVIEN` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_LOAI` FOREIGN KEY (`HSBAPPTTT_LOAI`) REFERENCES `dt_dm_loai_phau_thuat` (`DTDMLOAIPT_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_NHANVIEN_MA` FOREIGN KEY (`NHANVIEN_MA`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_PHUONGPHAP` FOREIGN KEY (`HSBAPPTTT_PHUONGPHAP`) REFERENCES `dt_dm_phau_thuat` (`DTDMPHAUTHUAT_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_PHUONGPHAP_VOCAM` FOREIGN KEY (`HSBAPPTTT_PHUONGPHAP_VOCAM`) REFERENCES `dt_dm_vo_cam` (`DTDMVOCAM_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `hsba_phieu_phau_thuat_thu_thuat_bacsi` (
  `HSBAPPTTTBS_MASO` int(11) NOT NULL auto_increment,
  `HSBAPPTTT_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBAPPTTTBS_MASO`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_PHIEU` (`HSBAPPTTT_MASO`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSI_PHIEU` FOREIGN KEY (`HSBAPPTTT_MASO`) REFERENCES `hsba_phieu_phau_thuat_thu_thuat` (`HSBAPPTTT_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `hsba_phieu_phau_thuat_thu_thuat_bacsigm` (
  `HSBAPPTTTBSGM_MASO` int(11) NOT NULL auto_increment,
  `HSBAPPTTT_MASO` int(11) default NULL,
  `DTDMNHANVIEN_MASO` int(10) unsigned default NULL,
  PRIMARY KEY  (`HSBAPPTTTBSGM_MASO`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSIGM_PHIEU` (`HSBAPPTTT_MASO`),
  KEY `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSIGM_NHANVIEN` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSIGM_NHANVIEN` FOREIGN KEY (`DTDMNHANVIEN_MASO`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_BACSIGM_PHIEU` FOREIGN KEY (`HSBAPPTTT_MASO`) REFERENCES `hsba_phieu_phau_thuat_thu_thuat` (`HSBAPPTTT_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


INSERT INTO db_ytdt_bd.yte_sequence
(SEQUENCE_NAME_MA, SEQUENCE_CURRENT_VALUE, SEQUENCE_CURRENT_NEXT, SEQUENCE_STEP) 
VALUES ('MALAP_TRICH_BIEN_BAN_HOI_CHAN', 1, 2, 1);
