ALTER TABLE thuoc_noi_tru ADD COLUMN `DMDOITUONG_MASO` INTEGER UNSIGNED AFTER `THUOCNOITRU_CHIDANMASO`,
 ADD CONSTRAINT `FK_THUOC_NOI_TRU_DMDOITUONG_MASO` FOREIGN KEY `FK_THUOC_NOI_TRU_DMDOITUONG_MASO` (`DMDOITUONG_MASO`)
    REFERENCES `dm_doi_tuong` (`DMDOITUONG_MASO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;