ALTER TABLE db_ytdt_bd.hsba_phieu_phau_thuat_thu_thuat
 ADD HSBAPPTTT_KHOACHIDINH INT(10) UNSIGNED AFTER HSBAPPTTT_LOAIPTTT;
ALTER TABLE db_ytdt_bd.hsba_phieu_phau_thuat_thu_thuat
 ADD CONSTRAINT FK_HSBA_PHIEU_PHAU_THUAT_THU_THUAT_KHOACHIDINH FOREIGN KEY (HSBAPPTTT_KHOACHIDINH) REFERENCES db_ytdt_bd.dm_khoa (DMKHOA_MASO) ON UPDATE RESTRICT ON DELETE RESTRICT;
