ALTER TABLE db_ytdt_bd.to_dieu_tri
  ADD TODIEUTRI_TENBS VARCHAR(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci AFTER HSBA_SOVAOVIEN;
ALTER TABLE db_ytdt_bd.phieu_cham_soc
 ADD PHIEUCHAMSOC_TENBS VARCHAR(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci AFTER HSBA_SOVAOVIEN;