-- update cho moi DB
ALTER TABLE `thuoc_phong_kham` MODIFY COLUMN `THUOCPHONGKHAM_MATHUOC` INTEGER UNSIGNED NOT NULL;
ALTER TABLE `thuoc_noi_tru` MODIFY COLUMN `THUOCNOITRU_MATHUOC` INTEGER UNSIGNED NOT NULL;
