DROP TABLE `tmp_baocao_thekho`;
CREATE TABLE `tmp_baocao_thekho` (
  `STT` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NGAYTHANG` DATETIME NOT NULL,
  `CHUNGTUNXT` VARCHAR(45) NOT NULL,
  `PHIEUNHAPKHO` VARCHAR(45) NOT NULL,
  `LOAIPHIEU` VARCHAR(1) NOT NULL,
  `DIENGIAI` VARCHAR(512),
  `SOLUONGNHAP` DOUBLE,
  `THANHTIENNHAP` DOUBLE,
  `SOLUONGXUAT` DOUBLE,
  `THANHTIENXUAT` DOUBLE,
  `SOLUONGTON` DOUBLE,
  `THANHTIENTON` DOUBLE,
  PRIMARY KEY (`STT`)
)
ENGINE = InnoDB;