ALTER TABLE `db_ytdt_bd`.`hsba_giay_tom_tat` 
MODIFY COLUMN `HSBAGTT_XNCLS` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
MODIFY COLUMN `HSBAGTT_QTDT` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
