CREATE TABLE `hsba_giay_chung_nhan` (
  `HSBAGCN_MASO` int(11) NOT NULL auto_increment,
  `HSBA_SOVAOVIEN` varchar(17) character set utf8 collate utf8_unicode_ci NOT NULL,
  `NHANVIEN_MA` int(10) unsigned default NULL,
  `HSBAGCN_BACSI` int(10) unsigned default NULL,
  `HSBAGCN_NGAYGIOCN` datetime default NULL,
  `HSBAGCN_MA` varchar(11) default NULL,
  `HSBAGCN_NGAYCMT` date default NULL,
  `HSBAGCN_NGAYCAP` date default NULL,
  `HSBAGCN_NOICMT` varchar(512) character set utf8 collate utf8_unicode_ci default NULL,
  PRIMARY KEY  (`HSBAGCN_MASO`),
  KEY `FK_HSBA_GIAY_CHUNG_NHAN_NHANVIEN_MA` (`NHANVIEN_MA`),
  KEY `FK_HSBA_GIAY_CHUNG_NHAN_HSBA_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  KEY `FK_HSBA_GIAY_CHUNG_NHAN_HSBA_BACSI` (`HSBAGCN_BACSI`),
  CONSTRAINT `FK_HSBA_GIAY_CHUNG_NHAN_NHANVIEN_MA` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`),
  CONSTRAINT `FK_HSBA_GIAY_CHUNG_NHAN_HSBA_SOVAOVIEN` FOREIGN KEY (`NHANVIEN_MA`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_HSBA_GIAY_CHUNG_NHAN_HSBA_BACSI` FOREIGN KEY (`HSBAGCN_BACSI`) REFERENCES `dt_dm_nhan_vien` (`DTDMNHANVIEN_MASO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO yte_sequence( SEQUENCE_NAME_MA, SEQUENCE_CURRENT_VALUE, SEQUENCE_CURRENT_NEXT, SEQUENCE_STEP) VALUES('MAPHIEU_CHUNG_NHAN',1,2,1);
