DROP TABLE IF EXISTS `phieu_xuat_bh_xuat_vien`;
CREATE TABLE  `phieu_xuat_bh_xuat_vien` (
  `PHIEUXUATBHXV_MA` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `HSBA_SOVAOVIEN` varchar(17) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `PHIEUXUATBHXV_NGAYLAP` date NOT NULL,
  `DTDMNHANVIEN_PHAT` int(10) unsigned DEFAULT NULL,
  `PHIEUXUATBHXV_THANHTIEN` double DEFAULT NULL,
  `DMKHOA_MASO` int(10) unsigned DEFAULT NULL,
  `DTDMNHANVIEN_CN` int(10) unsigned DEFAULT NULL,
  `PHIEUXUATBHXV_NGAYGIOCN` datetime DEFAULT NULL,
  `PHIEUXUATBHXV_NGAYGIOPHAT` datetime DEFAULT NULL,
  PRIMARY KEY (`PHIEUXUATBHXV_MA`),
  KEY `FK_PHIEU_XUAT_BHXV_HSBA_SOVAOVIEN` (`HSBA_SOVAOVIEN`),
  KEY `FK_PHIEU_XUAT_BHXV_DTDMNHANVIEN_PHAT` (`DTDMNHANVIEN_PHAT`),
  KEY `FK_PHIEU_XUAT_BHXV_DTDMNHANVIEN_CN` (`DTDMNHANVIEN_CN`),
  KEY `FK_PHIEU_XUAT_BHXV_DMKHOA` (`DMKHOA_MASO`) USING BTREE,
  CONSTRAINT `FK_PHIEU_XUAT_BHXV_DMKHOA` FOREIGN KEY (`DMKHOA_MASO`) REFERENCES `dm_khoa` (`DMKHOA_MASO`),
  CONSTRAINT `FK_PHIEU_XUAT_BHXV_DTDMNHANVIEN_CN` FOREIGN KEY (`DTDMNHANVIEN_CN`) REFERENCES `dt_dm_nhan_vien` 

(`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_PHIEU_XUAT_BHXV_DTDMNHANVIEN_PHAT` FOREIGN KEY (`DTDMNHANVIEN_PHAT`) REFERENCES `dt_dm_nhan_vien` 

(`DTDMNHANVIEN_MASO`),
  CONSTRAINT `FK_PHIEU_XUAT_BHXV_HSBA_SOVAOVIEN` FOREIGN KEY (`HSBA_SOVAOVIEN`) REFERENCES `hsba` (`HSBA_SOVAOVIEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `ct_xuat_bh_xuat_vien`;
CREATE TABLE  `ct_xuat_bh_xuat_vien` (
  `CTXUATBHXV_MA` int(11) NOT NULL AUTO_INCREMENT,
  `PHIEUXUATBHXV_MA` varchar(11) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `CTXUATBHXV_SOLUONG` double DEFAULT NULL,
  `CTXUATBHXV_MALK` varchar(100) DEFAULT NULL,
  `DMTHUOC_MASO` int(10) unsigned DEFAULT NULL,
  `DMNCT_MASO` int(10) unsigned DEFAULT NULL,
  `DMNGUONKINHPHI_MASO` int(10) unsigned DEFAULT NULL,
  `DMQUOCGIA_MASO` int(10) unsigned DEFAULT NULL,
  `DMNHASANXUAT_MASO` int(10) unsigned DEFAULT NULL,
  `CTXUATBHXV_NAMNHAP` varchar(4) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CTXUATBHXV_NGAYHANDUNG` varchar(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CTXUATBHXV_THANGHANDUNG` varchar(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CTXUATBHXV_NAMHANDUNG` varchar(4) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `CTXUATBHXV_DONGIA` double DEFAULT NULL,
  `CTXUATBHXV_LO` double DEFAULT NULL,
  `CTXUATBHXV_SODANGKY` double DEFAULT NULL,
  `CTXUATBHXV_NGAYGIOCN` datetime DEFAULT NULL,
  `TONKHO_MA` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`CTXUATBHXV_MA`),
  KEY `FK_CT_XUAT_BHXV_DMNHASANXUAT_MASO` (`DMNHASANXUAT_MASO`),
  KEY `FK_CT_XUAT_BHXV_DMNCT_MASO` (`DMNCT_MASO`),
  KEY `FK_CT_XUAT_BHXV_DMTHUOC_MASO` (`DMTHUOC_MASO`),
  KEY `FK_CT_XUAT_BHXV_DMNGUONKINHPHI_MASO` (`DMNGUONKINHPHI_MASO`),
  KEY `FK_CT_XUAT_BHXV_DMQUOCGIA_MASO` (`DMQUOCGIA_MASO`),
  KEY `FK_CT_XUAT_BHXV_PHIEUXUATBHXV_MA` (`PHIEUXUATBHXV_MA`),
  CONSTRAINT `FK_CT_XUAT_BHXV_DMNCT_MASO` FOREIGN KEY (`DMNCT_MASO`) REFERENCES `dm_nguon_chuong_trinh` (`DMNCT_MASO`),
  CONSTRAINT `FK_CT_XUAT_BHXV_DMNGUONKINHPHI_MASO` FOREIGN KEY (`DMNGUONKINHPHI_MASO`) REFERENCES `dm_nguon_kinh_phi` 

(`DMNGUONKINHPHI_MASO`),
  CONSTRAINT `FK_CT_XUAT_BHXV_DMNHASANXUAT_MASO` FOREIGN KEY (`DMNHASANXUAT_MASO`) REFERENCES `dm_nha_san_xuat` 

(`DMNHASANXUAT_MASO`),
  CONSTRAINT `FK_CT_XUAT_BHXV_DMQUOCGIA_MASO` FOREIGN KEY (`DMQUOCGIA_MASO`) REFERENCES `dm_quoc_gia` (`DMQUOCGIA_MASO`),
  CONSTRAINT `FK_CT_XUAT_BHXV_DMTHUOC_MASO` FOREIGN KEY (`DMTHUOC_MASO`) REFERENCES `dm_thuoc` (`DMTHUOC_MASO`),
  CONSTRAINT `FK_CT_XUAT_BHXV_PHIEUXUATBHXV_MA` FOREIGN KEY (`PHIEUXUATBHXV_MA`) REFERENCES `phieu_xuat_bh_xuat_vien` 

(`PHIEUXUATBHXV_MA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `yte_sequence` (`SEQUENCE_NAME_MA`,`SEQUENCE_CURRENT_VALUE`,`SEQUENCE_CURRENT_NEXT`,`SEQUENCE_STEP`) VALUES ('MAPHIEU_XUATVIEN',1,2,1);
