CREATE TABLE "DB_YTDT_BD"."BA_NGOAI_TRU_YHCT"
  (
    "BANT_YHCT_MA"         VARCHAR2(11 CHAR) NOT NULL ENABLE,
    "BANT_YHCT_LYDOVAOV"   VARCHAR2(512 CHAR),
    "BANT_YHCT_QTBENHLY"   VARCHAR2(512 CHAR),
    "BANT_YHCT_TSUBENHBT"  VARCHAR2(512 CHAR),
    "BANT_YHCT_TSUBENHGD"  VARCHAR2(512 CHAR),
    "BANT_YHCT_BPBIBENH"   VARCHAR2(512 CHAR),
    "BANT_YHCT_XNCANTHIET" VARCHAR2(255 CHAR),
    "BANT_YHCT_VONGCHAN"   VARCHAR2(255 CHAR),
    "BANT_YHCT_VANCHAN"    VARCHAR2(255 CHAR),
    "BANT_YHCT_VANCHAN2"   VARCHAR2(255 CHAR),
    "BANT_YHCT_THIETCHAN"  VARCHAR2(255 CHAR),
    "BANT_YHCT_CDBENHDANH" VARCHAR2(255 CHAR),
    "BANT_YHCT_CDTANGPHU"  VARCHAR2(255 CHAR),
    "BANT_YHCT_CDBATCUONG" VARCHAR2(255 CHAR),
    "BANT_YHCT_CDNGNHAN"   VARCHAR2(255 CHAR),
    "BANT_YHCT_DTPHEPCHUA" VARCHAR2(255 CHAR),
    "BANT_YHCT_DTPHTHUOC"  VARCHAR2(255 CHAR),
    "BANT_YHCT_DTPHHUYET"  VARCHAR2(255 CHAR),
    "BANT_YHCT_DTXOABOP"   VARCHAR2(255 CHAR),
    "BANT_YHCT_DTCDATNHA"  VARCHAR2(255 CHAR),
    "BANT_YHCT_DTCDHLTNHA" VARCHAR2(255 CHAR),
    "BANT_YHCT_TIENLUONG"  VARCHAR2(255 CHAR),
    "BANT_YHCT_KQCLSCHINH" VARCHAR2(255 CHAR),
    "BANT_YHCT_KQGPBENH"   VARCHAR2(255 CHAR),
    "BANT_YHCT_PT_YHHD"    VARCHAR2(255 CHAR),
    "BANT_YHCT_PT_YHCT"    VARCHAR2(255 CHAR),
    "BANT_YHCT_CDRV_YHHD"  VARCHAR2(255 CHAR),
    "BANT_YHCT_CDRV_YHCT"  VARCHAR2(255 CHAR),
    "BANT_YHCT_HDT_CDTT"   VARCHAR2(512 CHAR),
    "BANT_YHCT_BSDIEUTRI"  NUMBER(10,0),
    "BANT_YHCT_THAMKHAM"   NUMBER(10,0),
    "BANT_YHCT_BENHNHAN"   VARCHAR2(17 CHAR),
    "BANT_YHCT_SOTHEBH"    VARCHAR2(50 CHAR),
    "BANT_YHCT_BANKHAM"    NUMBER(10,0),
    "BANT_YHCT_SOVAOVIEN"  VARCHAR2(17 CHAR),
    CONSTRAINT "BA_NGOAI_TRU_YHCT_PK" PRIMARY KEY ("BANT_YHCT_MA") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "BA_NGOAI_TRU_YHCT_BKHAM" FOREIGN KEY ("BANT_YHCT_BANKHAM") REFERENCES "DB_YTDT_BD"."DT_DM_BAN_KHAM" ("DTDMBANKHAM_MASO") ENABLE,
    CONSTRAINT "BA_NGOAI_TRU_YHCT_BN" FOREIGN KEY ("BANT_YHCT_BENHNHAN") REFERENCES "DB_YTDT_BD"."BENH_NHAN" ("BENHNHAN_MA") ENABLE,
    CONSTRAINT "BA_NGOAI_TRU_YHCT_BSI" FOREIGN KEY ("BANT_YHCT_BSDIEUTRI") REFERENCES "DB_YTDT_BD"."DT_DM_NHAN_VIEN" ("DTDMNHANVIEN_MASO") ENABLE,
    CONSTRAINT "BA_NGOAI_TRU_YHCT_TKHAM" FOREIGN KEY ("BANT_YHCT_THAMKHAM") REFERENCES "DB_YTDT_BD"."THAM_KHAM" ("THAMKHAM_MA") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
