insert into cau_hinh(CHBV_NAME, CHBV_GIATRI, CHBV_NGAYGIOCN, CHBV_CHON, CHBV_MASO) values('BA_DTNGT_PREFIX', 'NG',1,1,12);

insert into yte_sequence(SEQUENCE_NAME_MA, SEQUENCE_CURRENT_VALUE, SEQUENCE_CURRENT_NEXT, SEQUENCE_STEP, SEQUENCE_RESET_YEAR) VALUES('BA_DTNGOAITRU',1,2,1,1);