ALTER TABLE `db_ytdt_bd`.`hsba_chuyen_vien` 
MODIFY COLUMN `HSBACV_XETNGHIEM` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
MODIFY COLUMN `HSBACV_THUOCDADUNG` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;

ALTER TABLE `db_ytdt_bd`.`giay_cv_nb_bhyt` 
MODIFY COLUMN `GCVBHYT_TEMP1` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
MODIFY COLUMN `GCVBHYT_TEMP2` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
