-- Chay rieng tung buoc

-- Buoc 1
CREATE TABLE "DB_YTDT_BD"."YTE_LOG"
  (
    "LOG_ID"  NUMBER NOT NULL ENABLE,
    "USER_ID" VARCHAR2(10 BYTE),
    "DATE_TIME" DATE,
    "FORM"       VARCHAR2(100 BYTE),
    "OBJECT_ID"  VARCHAR2(20 BYTE),
    "LOG_STRING" VARCHAR2(512 BYTE),
    "LIST_DATA"  VARCHAR2(2048 BYTE),
    CONSTRAINT "YTE_LOG_PK" PRIMARY KEY ("LOG_ID") ENABLE
  );
  

-- Buoc 2
CREATE SEQUENCE YTE_LOG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


-- Buoc 3
CREATE OR REPLACE TRIGGER "DB_YTDT_BD"."YTE_LOG_SEQ_TRI" BEFORE
  INSERT ON YTE_LOG FOR EACH ROW BEGIN
  SELECT YTE_LOG_SEQ.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
END YTE_LOG_SEQ_TRI;


-- Buoc 4
ALTER TRIGGER "DB_YTDT_BD"."YTE_LOG_SEQ_TRI" ENABLE;
