ALTER TABLE DB_YTDT_BD.HSBA
 ADD (TANG_DANGDT  NUMBER(10))
;

ALTER TABLE DB_YTDT_BD.HSBA
 ADD CONSTRAINT FK_HSBA_DMTANG_MASO
  FOREIGN KEY (TANG_DANGDT) 
  REFERENCES DB_YTDT_BD.DM_TANG (DMTANG_MASO)
  ENABLE VALIDATE
;

