ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI1_DONVI NUMBER(10, 0) );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI1_TUYEN VARCHAR2(10) );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI1_TUNGAY DATE );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI1_DENNGAY DATE );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI2_TUNGAY DATE );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (DIEUTRI2_DENNGAY DATE );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (GCVBHYT_HUONGDIEUTRI VARCHAR2(512) );

ALTER TABLE GIAY_CV_NB_BHYT 
ADD (GCVBHYT_NGAYGIOCHUYEN DATE );

CREATE INDEX IX_GCVBHYT_DT1_DONVI ON GIAY_CV_NB_BHYT (DIEUTRI1_DONVI ASC);

ALTER TABLE GIAY_CV_NB_BHYT
ADD CONSTRAINT FK_GCVBHYT_DT1_DONVI FOREIGN KEY
(
  DIEUTRI1_DONVI 
)
REFERENCES DM_BENH_VIEN
(
  DMBENHVIEN_MASO 
)
ENABLE;
