CREATE OR REPLACE   VIEW V_BC_TON
AS
SELECT CONCAT_WS(' ',DMTHUOC_TEN, DMTHUOC_HAMLUONG,
N.DMNCT_MA,DMT.DMQUOCGIA_MA) AS
TEN_HANG,TONKHO_MALIENKET,
    T.DMTHUOC_MASO , PLT.DMPHANLOAITHUOC_MA, DMPHANLOAITHUOC_TEN AS TENPHANLOAI,
   L.DMLOAITHUOC_MASO, DMLOAITHUOC_TEN AS TENLOAI,
   T.DMKHOA_MASO ,DMKHOA_TEN,
   T.DMNHASANXUAT_MASO,DMNHASANXUAT_TEN ,
   T.DMNCT_MASO,DMNCT_TEN,
   T.TONKHO_NAMNHAP,
   T.DMNGUONKINHPHI_MASO, DMNGUONKINHPHI_TEN ,
   DV.DMDONVITINH_TEN,
   T.TONKHO_DONGIA,
   T.TONKHO_NGAYGIOCN,
   IF(ISNULL(T.TONKHO_TONDAU),0,T.TONKHO_TONDAU) AS SL_TONDAU,
   IF(ISNULL(T.TONKHO_NHAP),0,T.TONKHO_NHAP) AS SL_NHAP,
   IF(ISNULL(TONKHO_TRA),0,TONKHO_TRA) AS SL_TRA,
   IF(ISNULL(TONKHO_XUAT),0,TONKHO_XUAT) AS SL_XUAT,
   0 AS SL_THANHLY,
   IF(ISNULL(TONKHO_TON),0,TONKHO_TON) AS SL_TONCUOI
   FROM ((((((TON_KHO T LEFT JOIN DM_THUOC TH ON T.DMTHUOC_MASO = TH.DMTHUOC_MASO 
   LEFT JOIN DM_PHAN_LOAI_THUOC PLT ON TH.DMPHANLOAITHUOC_MASO = PLT.DMPHANLOAITHUOC_MASO) 
LEFT JOIN DM_LOAI_THUOC L ON L.DMLOAITHUOC_MASO = PLT.DMLOAITHUOC_MASO)
LEFT JOIN DM_NGUON_CHUONG_TRINH N ON T.DMNCT_MASO = N.DMNCT_MASO)
LEFT JOIN DM_NGUON_KINH_PHI K ON T.DMNGUONKINHPHI_MASO = K.DMNGUONKINHPHI_MASO )
LEFT JOIN DM_KHOA KH ON T.DMKHOA_MASO = KH.DMKHOA_MASO)
LEFT JOIN DM_NHA_SAN_XUAT SX ON T.DMNHASANXUAT_MASO = SX.DMNHASANXUAT_MASO)
LEFT JOIN DM_DON_VI_TINH DV ON TH.DMDONVITINH_MASO = DV.DMDONVITINH_MASO
LEFT JOIN DM_QUOC_GIA DMT ON DMT.DMQUOCGIA_MASO = T.DMQUOCGIA_MASO ;

CREATE OR REPLACE  VIEW V_TONDAU_LIENKET
AS
SELECT  DISTINCT  TONKHO_MALIENKET, DMTHUOC_MASO, MONTH(TONKHO_NGAYGIOCN)
AS THANG, YEAR(TONKHO_NGAYGIOCN) AS NAM  ,TONKHO_DONGIA,
IF(ISNULL(TONKHO_TONDAU),0,TONKHO_TONDAU) AS SL_TONDAU
FROM TON_KHO ;

CREATE OR REPLACE  VIEW V_TONDAU_DMTHUOC
AS
/*  Tinh SL cua tung  DM Thuoc ton dau*/
SELECT  DMTHUOC_MASO, THANG, NAM, SUM(SL_TONDAU) AS SL_TONDAU,
SUM(SL_TONDAU * TONKHO_DONGIA) AS TT_TONDAU
FROM V_TONDAU_LIENKET
GROUP BY DMTHUOC_MASO, THANG, NAM;

CREATE OR REPLACE VIEW V_BC_TON_GHEP
AS
SELECT TONKHO_MALIENKET,CONCAT_WS(' ',DMTHUOC_TEN, DMTHUOC_HAMLUONG,
N.DMNCT_MA,QG.DMQUOCGIA_MA) AS TEN_HANG,
T.DMTHUOC_MASO,  TPL.DMPHANLOAITHUOC_MASO, L.DMLOAITHUOC_MA,
T.DMKHOA_MASO ,T.DMNHASANXUAT_MASO,T.DMNCT_MASO,T.TONKHO_NAMNHAP,
T.DMNGUONKINHPHI_MASO, DT.DMDONVITINH_TEN, T.TONKHO_DONGIA,
T.TONKHO_NGAYGIOCN,
V.SL_TONDAU, V.TT_TONDAU,
IF(ISNULL(T.TONKHO_NHAP),0,T.TONKHO_NHAP) AS SL_NHAP,
IF(ISNULL(T.TONKHO_NHAP),0,T.TONKHO_NHAP) * T.TONKHO_DONGIA AS TT_NHAP,
IF(ISNULL(TONKHO_TRA),0,TONKHO_TRA) AS SL_TRA,
IF(ISNULL(TONKHO_TRA),0,TONKHO_TRA)  * T.TONKHO_DONGIA AS TT_TRA,
IF(ISNULL(TONKHO_XUAT),0,TONKHO_XUAT) AS SL_XUAT,
IF(ISNULL(TONKHO_XUAT),0,TONKHO_XUAT) * T.TONKHO_DONGIA AS TT_XUAT,
0 AS SL_THANHLY  , 0 AS TT_THANHLY
 FROM (((TON_KHO T LEFT JOIN DM_THUOC D ON T.DMTHUOC_MASO =
D.DMTHUOC_MASO)
 LEFT JOIN  DM_DON_VI_TINH DT ON D.DMDONVITINH_MASO = DT.DMDONVITINH_MASO)
 LEFT JOIN DM_PHAN_LOAI_THUOC TPL ON D.DMPHANLOAITHUOC_MASO = TPL.DMPHANLOAITHUOC_MASO)
 LEFT JOIN DM_LOAI_THUOC  L ON TPL.DMLOAITHUOC_MASO  = L.DMLOAITHUOC_MASO
 LEFT JOIN V_TONDAU_DMTHUOC V ON T.DMTHUOC_MASO = V.DMTHUOC_MASO 
 LEFT JOIN DM_NGUON_CHUONG_TRINH N ON T.DMNCT_MASO = N.DMNCT_MASO 
 LEFT JOIN DM_QUOC_GIA QG ON QG.DMQUOCGIA_MASO = T.DMQUOCGIA_MASO AND
MONTH(T.TONKHO_NGAYGIOCN) = V.THANG AND YEAR(T.TONKHO_NGAYGIOCN) = V.NAM;

CREATE OR REPLACE  VIEW V_TONDAU_PHANLOAI
AS
/*  Tinh SL cua tung  DM Thuoc ton dau*/
SELECT  TPL.DMPHANLOAITHUOC_MASO, THANG, NAM, SUM(SL_TONDAU) AS SL_TONDAU,
SUM(SL_TONDAU * TONKHO_DONGIA) AS TT_TONDAU
FROM V_TONDAU_LIENKET V LEFT JOIN DM_THUOC D ON V.DMTHUOC_MASO =
D.DMTHUOC_MASO left join DM_PHAN_LOAI_THUOC TPL  ON D.DMPHANLOAITHUOC_MASO
= TPL.DMPHANLOAITHUOC_MASO
GROUP BY DMPHANLOAITHUOC_MASO, THANG, NAM;


