package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmBaoQuanThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_BAO_QUAN_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMBAOQUANTHUOC_MA"))
public class DmBaoQuanThuoc implements java.io.Serializable {

	private Integer dmbaoquanthuocMaso;
	private String dmbaoquanthuocMa;
	private String dmbaoquanthuocMaphu;
	private String dmbaoquanthuocTen;
	private String dmbaoquanthuocGhichu;
	private String nhanvienCn;
	private Double dmbaoquanthuocNgaygiocn;
	private Boolean dmbaoquanthuocDt;
	private Boolean dmbaoquanthuocQl;
	private Boolean dmbaoquanthuocDp;
	private Set<DmThuoc> dmThuocs = new HashSet<DmThuoc>(0);
	private Set<DmThuoc> dmThuocs_1 = new HashSet<DmThuoc>(0);

	public DmBaoQuanThuoc() {
	}

	public DmBaoQuanThuoc(String dmbaoquanthuocMa, String dmbaoquanthuocTen,
			String nhanvienCn) {
		this.dmbaoquanthuocMa = dmbaoquanthuocMa;
		this.dmbaoquanthuocTen = dmbaoquanthuocTen;
		this.nhanvienCn = nhanvienCn;
	}

	public DmBaoQuanThuoc(String dmbaoquanthuocMa, String dmbaoquanthuocMaphu,
			String dmbaoquanthuocTen, String dmbaoquanthuocGhichu,
			String nhanvienCn, Double dmbaoquanthuocNgaygiocn,
			Boolean dmbaoquanthuocDt, Boolean dmbaoquanthuocQl,
			Boolean dmbaoquanthuocDp, Set<DmThuoc> dmThuocs,
			Set<DmThuoc> dmThuocs_1) {
		this.dmbaoquanthuocMa = dmbaoquanthuocMa;
		this.dmbaoquanthuocMaphu = dmbaoquanthuocMaphu;
		this.dmbaoquanthuocTen = dmbaoquanthuocTen;
		this.dmbaoquanthuocGhichu = dmbaoquanthuocGhichu;
		this.nhanvienCn = nhanvienCn;
		this.dmbaoquanthuocNgaygiocn = dmbaoquanthuocNgaygiocn;
		this.dmbaoquanthuocDt = dmbaoquanthuocDt;
		this.dmbaoquanthuocQl = dmbaoquanthuocQl;
		this.dmbaoquanthuocDp = dmbaoquanthuocDp;
		this.dmThuocs = dmThuocs;
		this.dmThuocs_1 = dmThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_BAO_QUAN_THUOC")
	@SequenceGenerator(name = "DM_BAO_QUAN_THUOC", sequenceName = "DM_BAO_QUAN_THUOC_DMBAOQUANTHU", allocationSize = 1)
	@Column(name = "DMBAOQUANTHUOC_MASO", unique = true, nullable = false)
	public Integer getDmbaoquanthuocMaso() {
		return this.dmbaoquanthuocMaso;
	}

	public void setDmbaoquanthuocMaso(Integer dmbaoquanthuocMaso) {
		this.dmbaoquanthuocMaso = dmbaoquanthuocMaso;
	}

	@Column(name = "DMBAOQUANTHUOC_MA", unique = true, nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getDmbaoquanthuocMa() {
		return this.dmbaoquanthuocMa;
	}

	public void setDmbaoquanthuocMa(String dmbaoquanthuocMa) {
		this.dmbaoquanthuocMa = dmbaoquanthuocMa;
	}

	@Column(name = "DMBAOQUANTHUOC_MAPHU", length = 4)
	@Length(max = 4)
	public String getDmbaoquanthuocMaphu() {
		return this.dmbaoquanthuocMaphu;
	}

	public void setDmbaoquanthuocMaphu(String dmbaoquanthuocMaphu) {
		this.dmbaoquanthuocMaphu = dmbaoquanthuocMaphu;
	}

	@Column(name = "DMBAOQUANTHUOC_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmbaoquanthuocTen() {
		return this.dmbaoquanthuocTen;
	}

	public void setDmbaoquanthuocTen(String dmbaoquanthuocTen) {
		this.dmbaoquanthuocTen = dmbaoquanthuocTen;
	}

	@Column(name = "DMBAOQUANTHUOC_GHICHU", length = 250)
	@Length(max = 250)
	public String getDmbaoquanthuocGhichu() {
		return this.dmbaoquanthuocGhichu;
	}

	public void setDmbaoquanthuocGhichu(String dmbaoquanthuocGhichu) {
		this.dmbaoquanthuocGhichu = dmbaoquanthuocGhichu;
	}

	@Column(name = "NHANVIEN_CN", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getNhanvienCn() {
		return this.nhanvienCn;
	}

	public void setNhanvienCn(String nhanvienCn) {
		this.nhanvienCn = nhanvienCn;
	}

	@Column(name = "DMBAOQUANTHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmbaoquanthuocNgaygiocn() {
		return this.dmbaoquanthuocNgaygiocn;
	}

	public void setDmbaoquanthuocNgaygiocn(Double dmbaoquanthuocNgaygiocn) {
		this.dmbaoquanthuocNgaygiocn = dmbaoquanthuocNgaygiocn;
	}

	@Column(name = "DMBAOQUANTHUOC_DT")
	public Boolean getDmbaoquanthuocDt() {
		return this.dmbaoquanthuocDt;
	}

	public void setDmbaoquanthuocDt(Boolean dmbaoquanthuocDt) {
		this.dmbaoquanthuocDt = dmbaoquanthuocDt;
	}

	@Column(name = "DMBAOQUANTHUOC_QL")
	public Boolean getDmbaoquanthuocQl() {
		return this.dmbaoquanthuocQl;
	}

	public void setDmbaoquanthuocQl(Boolean dmbaoquanthuocQl) {
		this.dmbaoquanthuocQl = dmbaoquanthuocQl;
	}

	@Column(name = "DMBAOQUANTHUOC_DP")
	public Boolean getDmbaoquanthuocDp() {
		return this.dmbaoquanthuocDp;
	}

	public void setDmbaoquanthuocDp(Boolean dmbaoquanthuocDp) {
		this.dmbaoquanthuocDp = dmbaoquanthuocDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmBaoQuanThuoc")
	public Set<DmThuoc> getDmThuocs() {
		return this.dmThuocs;
	}

	public void setDmThuocs(Set<DmThuoc> dmThuocs) {
		this.dmThuocs = dmThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmBaoQuanThuoc")
	public Set<DmThuoc> getDmThuocs_1() {
		return this.dmThuocs_1;
	}

	public void setDmThuocs_1(Set<DmThuoc> dmThuocs_1) {
		this.dmThuocs_1 = dmThuocs_1;
	}

}
