package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmBenhIcd generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_BENH_ICD", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMBENHICD_MA"))
public class DmBenhIcd implements java.io.Serializable {

	private Integer dmbenhicdMaso;
	private DmBenhVn dmBenhVn;
	private DmChuongBenh dmChuongBenh;
	private String dmbenhicdMa;
	private String dmbenhicdMachung;
	private Boolean dmbenhicdTacnhan;
	private String dmbenhicdLienhe;
	private Double dmbenhicdNgaygiocn;
	private Boolean dmbenhicdQl;
	private Boolean dmbenhicdDt;
	private Boolean dmbenhicdDp;
	private String dmbenhicdTen;
	private String dmbenhicdTienganh;
	private Short dmbenhicdSs;

	public DmBenhIcd() {
	}

	public DmBenhIcd(String dmbenhicdMa, String dmbenhicdTen) {
		this.dmbenhicdMa = dmbenhicdMa;
		this.dmbenhicdTen = dmbenhicdTen;
	}

	public DmBenhIcd(DmBenhVn dmBenhVn, DmChuongBenh dmChuongBenh,
			String dmbenhicdMa, String dmbenhicdMachung,
			Boolean dmbenhicdTacnhan, String dmbenhicdLienhe,
			Double dmbenhicdNgaygiocn, Boolean dmbenhicdQl,
			Boolean dmbenhicdDt, Boolean dmbenhicdDp, String dmbenhicdTen,
			String dmbenhicdTienganh, Short dmbenhicdSs) {
		this.dmBenhVn = dmBenhVn;
		this.dmChuongBenh = dmChuongBenh;
		this.dmbenhicdMa = dmbenhicdMa;
		this.dmbenhicdMachung = dmbenhicdMachung;
		this.dmbenhicdTacnhan = dmbenhicdTacnhan;
		this.dmbenhicdLienhe = dmbenhicdLienhe;
		this.dmbenhicdNgaygiocn = dmbenhicdNgaygiocn;
		this.dmbenhicdQl = dmbenhicdQl;
		this.dmbenhicdDt = dmbenhicdDt;
		this.dmbenhicdDp = dmbenhicdDp;
		this.dmbenhicdTen = dmbenhicdTen;
		this.dmbenhicdTienganh = dmbenhicdTienganh;
		this.dmbenhicdSs = dmbenhicdSs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_BENH_ICD_DMBENHICD")
	@SequenceGenerator(name = "DM_BENH_ICD_DMBENHICD", sequenceName = "DM_BENH_ICD_DMBENHICD_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMBENHICD_MASO", unique = true, nullable = false)
	public Integer getDmbenhicdMaso() {
		return this.dmbenhicdMaso;
	}

	public void setDmbenhicdMaso(Integer dmbenhicdMaso) {
		this.dmbenhicdMaso = dmbenhicdMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMBENHICD_BENHVN")
	public DmBenhVn getDmBenhVn() {
		return this.dmBenhVn;
	}

	public void setDmBenhVn(DmBenhVn dmBenhVn) {
		this.dmBenhVn = dmBenhVn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMCHUONGBENH_MASO")
	public DmChuongBenh getDmChuongBenh() {
		return this.dmChuongBenh;
	}

	public void setDmChuongBenh(DmChuongBenh dmChuongBenh) {
		this.dmChuongBenh = dmChuongBenh;
	}

	@Column(name = "DMBENHICD_MA", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getDmbenhicdMa() {
		return this.dmbenhicdMa;
	}

	public void setDmbenhicdMa(String dmbenhicdMa) {
		this.dmbenhicdMa = dmbenhicdMa;
	}

	@Column(name = "DMBENHICD_MACHUNG", length = 7)
	@Length(max = 7)
	public String getDmbenhicdMachung() {
		return this.dmbenhicdMachung;
	}

	public void setDmbenhicdMachung(String dmbenhicdMachung) {
		this.dmbenhicdMachung = dmbenhicdMachung;
	}

	@Column(name = "DMBENHICD_TACNHAN")
	public Boolean getDmbenhicdTacnhan() {
		return this.dmbenhicdTacnhan;
	}

	public void setDmbenhicdTacnhan(Boolean dmbenhicdTacnhan) {
		this.dmbenhicdTacnhan = dmbenhicdTacnhan;
	}

	@Column(name = "DMBENHICD_LIENHE", length = 5)
	@Length(max = 5)
	public String getDmbenhicdLienhe() {
		return this.dmbenhicdLienhe;
	}

	public void setDmbenhicdLienhe(String dmbenhicdLienhe) {
		this.dmbenhicdLienhe = dmbenhicdLienhe;
	}

	@Column(name = "DMBENHICD_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmbenhicdNgaygiocn() {
		return this.dmbenhicdNgaygiocn;
	}

	public void setDmbenhicdNgaygiocn(Double dmbenhicdNgaygiocn) {
		this.dmbenhicdNgaygiocn = dmbenhicdNgaygiocn;
	}

	@Column(name = "DMBENHICD_QL")
	public Boolean getDmbenhicdQl() {
		return this.dmbenhicdQl;
	}

	public void setDmbenhicdQl(Boolean dmbenhicdQl) {
		this.dmbenhicdQl = dmbenhicdQl;
	}

	@Column(name = "DMBENHICD_DT")
	public Boolean getDmbenhicdDt() {
		return this.dmbenhicdDt;
	}

	public void setDmbenhicdDt(Boolean dmbenhicdDt) {
		this.dmbenhicdDt = dmbenhicdDt;
	}

	@Column(name = "DMBENHICD_DP")
	public Boolean getDmbenhicdDp() {
		return this.dmbenhicdDp;
	}

	public void setDmbenhicdDp(Boolean dmbenhicdDp) {
		this.dmbenhicdDp = dmbenhicdDp;
	}

	@Column(name = "DMBENHICD_TEN", nullable = false, length = 512)
	@NotNull
	@Length(max = 512)
	public String getDmbenhicdTen() {
		return this.dmbenhicdTen;
	}

	public void setDmbenhicdTen(String dmbenhicdTen) {
		this.dmbenhicdTen = dmbenhicdTen;
	}

	@Column(name = "DMBENHICD_TIENGANH", length = 512)
	@Length(max = 512)
	public String getDmbenhicdTienganh() {
		return this.dmbenhicdTienganh;
	}

	public void setDmbenhicdTienganh(String dmbenhicdTienganh) {
		this.dmbenhicdTienganh = dmbenhicdTienganh;
	}

	@Column(name = "DMBENHICD_SS")
	public Short getDmbenhicdSs() {
		return this.dmbenhicdSs;
	}

	public void setDmbenhicdSs(Short dmbenhicdSs) {
		this.dmbenhicdSs = dmbenhicdSs;
	}

}
