package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmBenhVien generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_BENH_VIEN", catalog = "DB_YTDT_BD")
public class DmBenhVien implements java.io.Serializable {

	private Integer dmbenhvienMaso;
	private DmTinh dmTinh;
	private DmVungMien dmVungMien;
	private DmLoaiBenhVien dmLoaiBenhVien;
	private DmHuyen dmHuyen;
	private DmTuyen dmTuyen;
	private String dmbenhvienMa;
	private String dmbenhvienTen;
	private String dmbenhvienDienthoai;
	private String dmbenhvienDiachi;
	private Boolean dmbenhvienChuyendi;
	private Boolean dmbenhvienChuyenden;
	private Double dmbenhvienNgaygiocn;
	private Boolean dmbenhvienQl;
	private Boolean dmbenhvienDt;
	private Boolean dmbenhvienDp;
	private String dmBenhvienPrefixma;
	private Byte dmbenhvienDefault;

	public DmBenhVien() {
	}

	public DmBenhVien(String dmbenhvienMa, String dmbenhvienTen) {
		this.dmbenhvienMa = dmbenhvienMa;
		this.dmbenhvienTen = dmbenhvienTen;
	}

	public DmBenhVien(DmTinh dmTinh, DmVungMien dmVungMien,
			DmLoaiBenhVien dmLoaiBenhVien, DmHuyen dmHuyen, DmTuyen dmTuyen,
			String dmbenhvienMa, String dmbenhvienTen,
			String dmbenhvienDienthoai, String dmbenhvienDiachi,
			Boolean dmbenhvienChuyendi, Boolean dmbenhvienChuyenden,
			Double dmbenhvienNgaygiocn, Boolean dmbenhvienQl,
			Boolean dmbenhvienDt, Boolean dmbenhvienDp,
			String dmBenhvienPrefixma, Byte dmbenhvienDefault) {
		this.dmTinh = dmTinh;
		this.dmVungMien = dmVungMien;
		this.dmLoaiBenhVien = dmLoaiBenhVien;
		this.dmHuyen = dmHuyen;
		this.dmTuyen = dmTuyen;
		this.dmbenhvienMa = dmbenhvienMa;
		this.dmbenhvienTen = dmbenhvienTen;
		this.dmbenhvienDienthoai = dmbenhvienDienthoai;
		this.dmbenhvienDiachi = dmbenhvienDiachi;
		this.dmbenhvienChuyendi = dmbenhvienChuyendi;
		this.dmbenhvienChuyenden = dmbenhvienChuyenden;
		this.dmbenhvienNgaygiocn = dmbenhvienNgaygiocn;
		this.dmbenhvienQl = dmbenhvienQl;
		this.dmbenhvienDt = dmbenhvienDt;
		this.dmbenhvienDp = dmbenhvienDp;
		this.dmBenhvienPrefixma = dmBenhvienPrefixma;
		this.dmbenhvienDefault = dmbenhvienDefault;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_BENH_VIEN_DMBENHVIEN_MASO")
	@SequenceGenerator(name = "DM_BENH_VIEN_DMBENHVIEN_MASO", sequenceName = "DM_BENH_VIEN_DMBENHVIEN_MASO_S", allocationSize = 1)
	@Column(name = "DMBENHVIEN_MASO", unique = true, nullable = false)
	public Integer getDmbenhvienMaso() {
		return this.dmbenhvienMaso;
	}

	public void setDmbenhvienMaso(Integer dmbenhvienMaso) {
		this.dmbenhvienMaso = dmbenhvienMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTINH_MASO")
	public DmTinh getDmTinh() {
		return this.dmTinh;
	}

	public void setDmTinh(DmTinh dmTinh) {
		this.dmTinh = dmTinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMVUNGMIEN_MASO")
	public DmVungMien getDmVungMien() {
		return this.dmVungMien;
	}

	public void setDmVungMien(DmVungMien dmVungMien) {
		this.dmVungMien = dmVungMien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMLOAIBV_MASO")
	public DmLoaiBenhVien getDmLoaiBenhVien() {
		return this.dmLoaiBenhVien;
	}

	public void setDmLoaiBenhVien(DmLoaiBenhVien dmLoaiBenhVien) {
		this.dmLoaiBenhVien = dmLoaiBenhVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMHUYEN_MASO")
	public DmHuyen getDmHuyen() {
		return this.dmHuyen;
	}

	public void setDmHuyen(DmHuyen dmHuyen) {
		this.dmHuyen = dmHuyen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTUYEN_MASO")
	public DmTuyen getDmTuyen() {
		return this.dmTuyen;
	}

	public void setDmTuyen(DmTuyen dmTuyen) {
		this.dmTuyen = dmTuyen;
	}

	@Column(name = "DMBENHVIEN_MA", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDmbenhvienMa() {
		return this.dmbenhvienMa;
	}

	public void setDmbenhvienMa(String dmbenhvienMa) {
		this.dmbenhvienMa = dmbenhvienMa;
	}

	@Column(name = "DMBENHVIEN_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmbenhvienTen() {
		return this.dmbenhvienTen;
	}

	public void setDmbenhvienTen(String dmbenhvienTen) {
		this.dmbenhvienTen = dmbenhvienTen;
	}

	@Column(name = "DMBENHVIEN_DIENTHOAI", length = 10)
	@Length(max = 10)
	public String getDmbenhvienDienthoai() {
		return this.dmbenhvienDienthoai;
	}

	public void setDmbenhvienDienthoai(String dmbenhvienDienthoai) {
		this.dmbenhvienDienthoai = dmbenhvienDienthoai;
	}

	@Column(name = "DMBENHVIEN_DIACHI", length = 250)
	@Length(max = 250)
	public String getDmbenhvienDiachi() {
		return this.dmbenhvienDiachi;
	}

	public void setDmbenhvienDiachi(String dmbenhvienDiachi) {
		this.dmbenhvienDiachi = dmbenhvienDiachi;
	}

	@Column(name = "DMBENHVIEN_CHUYENDI")
	public Boolean getDmbenhvienChuyendi() {
		return this.dmbenhvienChuyendi;
	}

	public void setDmbenhvienChuyendi(Boolean dmbenhvienChuyendi) {
		this.dmbenhvienChuyendi = dmbenhvienChuyendi;
	}

	@Column(name = "DMBENHVIEN_CHUYENDEN")
	public Boolean getDmbenhvienChuyenden() {
		return this.dmbenhvienChuyenden;
	}

	public void setDmbenhvienChuyenden(Boolean dmbenhvienChuyenden) {
		this.dmbenhvienChuyenden = dmbenhvienChuyenden;
	}

	@Column(name = "DMBENHVIEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmbenhvienNgaygiocn() {
		return this.dmbenhvienNgaygiocn;
	}

	public void setDmbenhvienNgaygiocn(Double dmbenhvienNgaygiocn) {
		this.dmbenhvienNgaygiocn = dmbenhvienNgaygiocn;
	}

	@Column(name = "DMBENHVIEN_QL")
	public Boolean getDmbenhvienQl() {
		return this.dmbenhvienQl;
	}

	public void setDmbenhvienQl(Boolean dmbenhvienQl) {
		this.dmbenhvienQl = dmbenhvienQl;
	}

	@Column(name = "DMBENHVIEN_DT")
	public Boolean getDmbenhvienDt() {
		return this.dmbenhvienDt;
	}

	public void setDmbenhvienDt(Boolean dmbenhvienDt) {
		this.dmbenhvienDt = dmbenhvienDt;
	}

	@Column(name = "DMBENHVIEN_DP")
	public Boolean getDmbenhvienDp() {
		return this.dmbenhvienDp;
	}

	public void setDmbenhvienDp(Boolean dmbenhvienDp) {
		this.dmbenhvienDp = dmbenhvienDp;
	}

	@Column(name = "DM_BENHVIEN_PREFIXMA", length = 2)
	@Length(max = 2)
	public String getDmBenhvienPrefixma() {
		return this.dmBenhvienPrefixma;
	}

	public void setDmBenhvienPrefixma(String dmBenhvienPrefixma) {
		this.dmBenhvienPrefixma = dmBenhvienPrefixma;
	}

	@Column(name = "DMBENHVIEN_DEFAULT")
	public Byte getDmbenhvienDefault() {
		return this.dmbenhvienDefault;
	}

	public void setDmbenhvienDefault(Byte dmbenhvienDefault) {
		this.dmbenhvienDefault = dmbenhvienDefault;
	}

}
