package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmBenhTruyenNhiem generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_BENH_TRUYEN_NHIEM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMBTN_ICD10"))
public class DmBenhTruyenNhiem implements java.io.Serializable {

	private Integer dmbtnMaso;
	private DmLoaiBenhTruyenNhiem dmLoaiBenhTruyenNhiem;
	private DmBenhVn dmBenhVn;
	private String dmbtnIcd10;
	private String dmbtnTc;
	private String dmbtnYtdt;
	private String dmbtnGhichu;
	private boolean dmbtnChon;
	private Double dmbtnNgaygiocn;

	public DmBenhTruyenNhiem() {
	}

	public DmBenhTruyenNhiem(boolean dmbtnChon) {
		this.dmbtnChon = dmbtnChon;
	}

	public DmBenhTruyenNhiem(DmLoaiBenhTruyenNhiem dmLoaiBenhTruyenNhiem,
			DmBenhVn dmBenhVn, String dmbtnIcd10, String dmbtnTc,
			String dmbtnYtdt, String dmbtnGhichu, boolean dmbtnChon,
			Double dmbtnNgaygiocn) {
		this.dmLoaiBenhTruyenNhiem = dmLoaiBenhTruyenNhiem;
		this.dmBenhVn = dmBenhVn;
		this.dmbtnIcd10 = dmbtnIcd10;
		this.dmbtnTc = dmbtnTc;
		this.dmbtnYtdt = dmbtnYtdt;
		this.dmbtnGhichu = dmbtnGhichu;
		this.dmbtnChon = dmbtnChon;
		this.dmbtnNgaygiocn = dmbtnNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_BENH_TRUYEN_NHIEM_DMBTN")
	@SequenceGenerator(name = "DM_BENH_TRUYEN_NHIEM_DMBTN", sequenceName = "DM_BENH_TRUYEN_NHIEM_DMBTN_MAS", allocationSize = 1)
	@Column(name = "DMBTN_MASO", unique = true, nullable = false)
	public Integer getDmbtnMaso() {
		return this.dmbtnMaso;
	}

	public void setDmbtnMaso(Integer dmbtnMaso) {
		this.dmbtnMaso = dmbtnMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMLBTN_MASO")
	public DmLoaiBenhTruyenNhiem getDmLoaiBenhTruyenNhiem() {
		return this.dmLoaiBenhTruyenNhiem;
	}

	public void setDmLoaiBenhTruyenNhiem(
			DmLoaiBenhTruyenNhiem dmLoaiBenhTruyenNhiem) {
		this.dmLoaiBenhTruyenNhiem = dmLoaiBenhTruyenNhiem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMBENHVN_MASO")
	public DmBenhVn getDmBenhVn() {
		return this.dmBenhVn;
	}

	public void setDmBenhVn(DmBenhVn dmBenhVn) {
		this.dmBenhVn = dmBenhVn;
	}

	@Column(name = "DMBTN_ICD10", unique = true, length = 15)
	@Length(max = 15)
	public String getDmbtnIcd10() {
		return this.dmbtnIcd10;
	}

	public void setDmbtnIcd10(String dmbtnIcd10) {
		this.dmbtnIcd10 = dmbtnIcd10;
	}

	@Column(name = "DMBTN_TC", length = 50)
	@Length(max = 50)
	public String getDmbtnTc() {
		return this.dmbtnTc;
	}

	public void setDmbtnTc(String dmbtnTc) {
		this.dmbtnTc = dmbtnTc;
	}

	@Column(name = "DMBTN_YTDT", length = 50)
	@Length(max = 50)
	public String getDmbtnYtdt() {
		return this.dmbtnYtdt;
	}

	public void setDmbtnYtdt(String dmbtnYtdt) {
		this.dmbtnYtdt = dmbtnYtdt;
	}

	@Column(name = "DMBTN_GHICHU", length = 100)
	@Length(max = 100)
	public String getDmbtnGhichu() {
		return this.dmbtnGhichu;
	}

	public void setDmbtnGhichu(String dmbtnGhichu) {
		this.dmbtnGhichu = dmbtnGhichu;
	}

	@Column(name = "DMBTN_CHON", nullable = false)
	@NotNull
	public boolean isDmbtnChon() {
		return this.dmbtnChon;
	}

	public void setDmbtnChon(boolean dmbtnChon) {
		this.dmbtnChon = dmbtnChon;
	}

	@Column(name = "DMBTN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmbtnNgaygiocn() {
		return this.dmbtnNgaygiocn;
	}

	public void setDmbtnNgaygiocn(Double dmbtnNgaygiocn) {
		this.dmbtnNgaygiocn = dmbtnNgaygiocn;
	}

}
