package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmCachDungThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_CACH_DUNG_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMCACHDUNGTHUOC_MA"))
public class DmCachDungThuoc implements java.io.Serializable {

	private Integer dmcachdungthuocMaso;
	private String dmcachdungthuocMa;
	private String dmcachdungthuocMaphu;
	private String dmcachdungthuocTen;
	private Double dmcachdungthuocNgaygiocn;
	private Boolean dmcachdungthuocDt;
	private Boolean dmcachdungthuocQl;
	private Boolean dmcachdungthuocDp;
	private Set<DmThuoc> dmThuocs = new HashSet<DmThuoc>(0);
	private Set<DmThuoc> dmThuocs_1 = new HashSet<DmThuoc>(0);

	public DmCachDungThuoc() {
	}

	public DmCachDungThuoc(String dmcachdungthuocMa, String dmcachdungthuocTen) {
		this.dmcachdungthuocMa = dmcachdungthuocMa;
		this.dmcachdungthuocTen = dmcachdungthuocTen;
	}

	public DmCachDungThuoc(String dmcachdungthuocMa,
			String dmcachdungthuocMaphu, String dmcachdungthuocTen,
			Double dmcachdungthuocNgaygiocn, Boolean dmcachdungthuocDt,
			Boolean dmcachdungthuocQl, Boolean dmcachdungthuocDp,
			Set<DmThuoc> dmThuocs, Set<DmThuoc> dmThuocs_1) {
		this.dmcachdungthuocMa = dmcachdungthuocMa;
		this.dmcachdungthuocMaphu = dmcachdungthuocMaphu;
		this.dmcachdungthuocTen = dmcachdungthuocTen;
		this.dmcachdungthuocNgaygiocn = dmcachdungthuocNgaygiocn;
		this.dmcachdungthuocDt = dmcachdungthuocDt;
		this.dmcachdungthuocQl = dmcachdungthuocQl;
		this.dmcachdungthuocDp = dmcachdungthuocDp;
		this.dmThuocs = dmThuocs;
		this.dmThuocs_1 = dmThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_CACH_DUNG_THUOC")
	@SequenceGenerator(name = "DM_CACH_DUNG_THUOC", sequenceName = "DM_CACH_DUNG_THUOC_DMCACHDUNGT", allocationSize = 1)
	@Column(name = "DMCACHDUNGTHUOC_MASO", unique = true, nullable = false)
	public Integer getDmcachdungthuocMaso() {
		return this.dmcachdungthuocMaso;
	}

	public void setDmcachdungthuocMaso(Integer dmcachdungthuocMaso) {
		this.dmcachdungthuocMaso = dmcachdungthuocMaso;
	}

	@Column(name = "DMCACHDUNGTHUOC_MA", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDmcachdungthuocMa() {
		return this.dmcachdungthuocMa;
	}

	public void setDmcachdungthuocMa(String dmcachdungthuocMa) {
		this.dmcachdungthuocMa = dmcachdungthuocMa;
	}

	@Column(name = "DMCACHDUNGTHUOC_MAPHU", length = 4)
	@Length(max = 4)
	public String getDmcachdungthuocMaphu() {
		return this.dmcachdungthuocMaphu;
	}

	public void setDmcachdungthuocMaphu(String dmcachdungthuocMaphu) {
		this.dmcachdungthuocMaphu = dmcachdungthuocMaphu;
	}

	@Column(name = "DMCACHDUNGTHUOC_TEN", nullable = false, length = 36)
	@NotNull
	@Length(max = 36)
	public String getDmcachdungthuocTen() {
		return this.dmcachdungthuocTen;
	}

	public void setDmcachdungthuocTen(String dmcachdungthuocTen) {
		this.dmcachdungthuocTen = dmcachdungthuocTen;
	}

	@Column(name = "DMCACHDUNGTHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmcachdungthuocNgaygiocn() {
		return this.dmcachdungthuocNgaygiocn;
	}

	public void setDmcachdungthuocNgaygiocn(Double dmcachdungthuocNgaygiocn) {
		this.dmcachdungthuocNgaygiocn = dmcachdungthuocNgaygiocn;
	}

	@Column(name = "DMCACHDUNGTHUOC_DT")
	public Boolean getDmcachdungthuocDt() {
		return this.dmcachdungthuocDt;
	}

	public void setDmcachdungthuocDt(Boolean dmcachdungthuocDt) {
		this.dmcachdungthuocDt = dmcachdungthuocDt;
	}

	@Column(name = "DMCACHDUNGTHUOC_QL")
	public Boolean getDmcachdungthuocQl() {
		return this.dmcachdungthuocQl;
	}

	public void setDmcachdungthuocQl(Boolean dmcachdungthuocQl) {
		this.dmcachdungthuocQl = dmcachdungthuocQl;
	}

	@Column(name = "DMCACHDUNGTHUOC_DP")
	public Boolean getDmcachdungthuocDp() {
		return this.dmcachdungthuocDp;
	}

	public void setDmcachdungthuocDp(Boolean dmcachdungthuocDp) {
		this.dmcachdungthuocDp = dmcachdungthuocDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmCachDungThuoc")
	public Set<DmThuoc> getDmThuocs() {
		return this.dmThuocs;
	}

	public void setDmThuocs(Set<DmThuoc> dmThuocs) {
		this.dmThuocs = dmThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmCachDungThuoc")
	public Set<DmThuoc> getDmThuocs_1() {
		return this.dmThuocs_1;
	}

	public void setDmThuocs_1(Set<DmThuoc> dmThuocs_1) {
		this.dmThuocs_1 = dmThuocs_1;
	}

}
