package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmChucVu generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_CHUC_VU", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMCHUCVU_MA"))
public class DmChucVu implements java.io.Serializable {

	private Integer dmchucvuMaso;
	private String dmchucvuMa;
	private String dmchucvuTen;
	private String dmchucvuTenbc;
	private Short dmchucvuHesopc;
	private Short dmchucvuThutu;
	private Double dmchucvuNgaygiocn;
	private Boolean dmchucvuQl;
	private Boolean dmchucvuDt;
	private Boolean dmchucvuDp;

	public DmChucVu() {
	}

	public DmChucVu(String dmchucvuTen, String dmchucvuTenbc) {
		this.dmchucvuTen = dmchucvuTen;
		this.dmchucvuTenbc = dmchucvuTenbc;
	}

	public DmChucVu(String dmchucvuMa, String dmchucvuTen,
			String dmchucvuTenbc, Short dmchucvuHesopc, Short dmchucvuThutu,
			Double dmchucvuNgaygiocn, Boolean dmchucvuQl, Boolean dmchucvuDt,
			Boolean dmchucvuDp) {
		this.dmchucvuMa = dmchucvuMa;
		this.dmchucvuTen = dmchucvuTen;
		this.dmchucvuTenbc = dmchucvuTenbc;
		this.dmchucvuHesopc = dmchucvuHesopc;
		this.dmchucvuThutu = dmchucvuThutu;
		this.dmchucvuNgaygiocn = dmchucvuNgaygiocn;
		this.dmchucvuQl = dmchucvuQl;
		this.dmchucvuDt = dmchucvuDt;
		this.dmchucvuDp = dmchucvuDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_CHUC_VU")
	@SequenceGenerator(name = "DM_CHUC_VU", sequenceName = "DM_CHUC_VU_DMCHUCVU_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMCHUCVU_MASO", unique = true, nullable = false)
	public Integer getDmchucvuMaso() {
		return this.dmchucvuMaso;
	}

	public void setDmchucvuMaso(Integer dmchucvuMaso) {
		this.dmchucvuMaso = dmchucvuMaso;
	}

	@Column(name = "DMCHUCVU_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmchucvuMa() {
		return this.dmchucvuMa;
	}

	public void setDmchucvuMa(String dmchucvuMa) {
		this.dmchucvuMa = dmchucvuMa;
	}

	@Column(name = "DMCHUCVU_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmchucvuTen() {
		return this.dmchucvuTen;
	}

	public void setDmchucvuTen(String dmchucvuTen) {
		this.dmchucvuTen = dmchucvuTen;
	}

	@Column(name = "DMCHUCVU_TENBC", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmchucvuTenbc() {
		return this.dmchucvuTenbc;
	}

	public void setDmchucvuTenbc(String dmchucvuTenbc) {
		this.dmchucvuTenbc = dmchucvuTenbc;
	}

	@Column(name = "DMCHUCVU_HESOPC")
	public Short getDmchucvuHesopc() {
		return this.dmchucvuHesopc;
	}

	public void setDmchucvuHesopc(Short dmchucvuHesopc) {
		this.dmchucvuHesopc = dmchucvuHesopc;
	}

	@Column(name = "DMCHUCVU_THUTU")
	public Short getDmchucvuThutu() {
		return this.dmchucvuThutu;
	}

	public void setDmchucvuThutu(Short dmchucvuThutu) {
		this.dmchucvuThutu = dmchucvuThutu;
	}

	@Column(name = "DMCHUCVU_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmchucvuNgaygiocn() {
		return this.dmchucvuNgaygiocn;
	}

	public void setDmchucvuNgaygiocn(Double dmchucvuNgaygiocn) {
		this.dmchucvuNgaygiocn = dmchucvuNgaygiocn;
	}

	@Column(name = "DMCHUCVU_QL")
	public Boolean getDmchucvuQl() {
		return this.dmchucvuQl;
	}

	public void setDmchucvuQl(Boolean dmchucvuQl) {
		this.dmchucvuQl = dmchucvuQl;
	}

	@Column(name = "DMCHUCVU_DT")
	public Boolean getDmchucvuDt() {
		return this.dmchucvuDt;
	}

	public void setDmchucvuDt(Boolean dmchucvuDt) {
		this.dmchucvuDt = dmchucvuDt;
	}

	@Column(name = "DMCHUCVU_DP")
	public Boolean getDmchucvuDp() {
		return this.dmchucvuDp;
	}

	public void setDmchucvuDp(Boolean dmchucvuDp) {
		this.dmchucvuDp = dmchucvuDp;
	}

}
