package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmChuongBenh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_CHUONG_BENH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMCHUONGBENH_MA"))
public class DmChuongBenh implements java.io.Serializable {

	private Integer dmchuongbenhMaso;
	private String dmchuongbenhMa;
	private String dmbenhicdMa;
	private String dmchuongbenhTen;
	private Double dmchuongbenhNgaygiocn;
	private Boolean dmchuongbenhDt;
	private Boolean dmchuongbenhQl;
	private Boolean dmchuongbenhDp;
	private Set<DmBenhVn> dmBenhVns = new HashSet<DmBenhVn>(0);
	private Set<DmBenhIcd> dmBenhIcds = new HashSet<DmBenhIcd>(0);
	private Set<DmBenhVn> dmBenhVns_1 = new HashSet<DmBenhVn>(0);

	public DmChuongBenh() {
	}

	public DmChuongBenh(String dmchuongbenhTen) {
		this.dmchuongbenhTen = dmchuongbenhTen;
	}

	public DmChuongBenh(String dmchuongbenhMa, String dmbenhicdMa,
			String dmchuongbenhTen, Double dmchuongbenhNgaygiocn,
			Boolean dmchuongbenhDt, Boolean dmchuongbenhQl,
			Boolean dmchuongbenhDp, Set<DmBenhVn> dmBenhVns,
			Set<DmBenhIcd> dmBenhIcds, Set<DmBenhVn> dmBenhVns_1) {
		this.dmchuongbenhMa = dmchuongbenhMa;
		this.dmbenhicdMa = dmbenhicdMa;
		this.dmchuongbenhTen = dmchuongbenhTen;
		this.dmchuongbenhNgaygiocn = dmchuongbenhNgaygiocn;
		this.dmchuongbenhDt = dmchuongbenhDt;
		this.dmchuongbenhQl = dmchuongbenhQl;
		this.dmchuongbenhDp = dmchuongbenhDp;
		this.dmBenhVns = dmBenhVns;
		this.dmBenhIcds = dmBenhIcds;
		this.dmBenhVns_1 = dmBenhVns_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_CHUONG_BENH")
	@SequenceGenerator(name = "DM_CHUONG_BENH", sequenceName = "DM_CHUONG_BENH_DMCHUONGBENH_MA", allocationSize = 1)
	@Column(name = "DMCHUONGBENH_MASO", unique = true, nullable = false)
	public Integer getDmchuongbenhMaso() {
		return this.dmchuongbenhMaso;
	}

	public void setDmchuongbenhMaso(Integer dmchuongbenhMaso) {
		this.dmchuongbenhMaso = dmchuongbenhMaso;
	}

	@Column(name = "DMCHUONGBENH_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmchuongbenhMa() {
		return this.dmchuongbenhMa;
	}

	public void setDmchuongbenhMa(String dmchuongbenhMa) {
		this.dmchuongbenhMa = dmchuongbenhMa;
	}

	@Column(name = "DMBENHICD_MA", length = 10)
	@Length(max = 10)
	public String getDmbenhicdMa() {
		return this.dmbenhicdMa;
	}

	public void setDmbenhicdMa(String dmbenhicdMa) {
		this.dmbenhicdMa = dmbenhicdMa;
	}

	@Column(name = "DMCHUONGBENH_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmchuongbenhTen() {
		return this.dmchuongbenhTen;
	}

	public void setDmchuongbenhTen(String dmchuongbenhTen) {
		this.dmchuongbenhTen = dmchuongbenhTen;
	}

	@Column(name = "DMCHUONGBENH_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmchuongbenhNgaygiocn() {
		return this.dmchuongbenhNgaygiocn;
	}

	public void setDmchuongbenhNgaygiocn(Double dmchuongbenhNgaygiocn) {
		this.dmchuongbenhNgaygiocn = dmchuongbenhNgaygiocn;
	}

	@Column(name = "DMCHUONGBENH_DT")
	public Boolean getDmchuongbenhDt() {
		return this.dmchuongbenhDt;
	}

	public void setDmchuongbenhDt(Boolean dmchuongbenhDt) {
		this.dmchuongbenhDt = dmchuongbenhDt;
	}

	@Column(name = "DMCHUONGBENH_QL")
	public Boolean getDmchuongbenhQl() {
		return this.dmchuongbenhQl;
	}

	public void setDmchuongbenhQl(Boolean dmchuongbenhQl) {
		this.dmchuongbenhQl = dmchuongbenhQl;
	}

	@Column(name = "DMCHUONGBENH_DP")
	public Boolean getDmchuongbenhDp() {
		return this.dmchuongbenhDp;
	}

	public void setDmchuongbenhDp(Boolean dmchuongbenhDp) {
		this.dmchuongbenhDp = dmchuongbenhDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmChuongBenh")
	public Set<DmBenhVn> getDmBenhVns() {
		return this.dmBenhVns;
	}

	public void setDmBenhVns(Set<DmBenhVn> dmBenhVns) {
		this.dmBenhVns = dmBenhVns;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmChuongBenh")
	public Set<DmBenhIcd> getDmBenhIcds() {
		return this.dmBenhIcds;
	}

	public void setDmBenhIcds(Set<DmBenhIcd> dmBenhIcds) {
		this.dmBenhIcds = dmBenhIcds;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmChuongBenh")
	public Set<DmBenhVn> getDmBenhVns_1() {
		return this.dmBenhVns_1;
	}

	public void setDmBenhVns_1(Set<DmBenhVn> dmBenhVns_1) {
		this.dmBenhVns_1 = dmBenhVns_1;
	}

}
