package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmDanToc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_DAN_TOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMDANTOC_MA"))
public class DmDanToc implements java.io.Serializable {

	private Integer dmdantocMaso;
	private String dmdantocMa;
	private String dmdantocTen;
	private Boolean dmdantocDefa;
	private Boolean dmdantocMienphi;
	private Double dmdantocNgaygiocn;
	private Boolean dmdantocChon;

	public DmDanToc() {
	}

	public DmDanToc(String dmdantocMa, String dmdantocTen) {
		this.dmdantocMa = dmdantocMa;
		this.dmdantocTen = dmdantocTen;
	}

	public DmDanToc(String dmdantocMa, String dmdantocTen,
			Boolean dmdantocDefa, Boolean dmdantocMienphi,
			Double dmdantocNgaygiocn, Boolean dmdantocChon) {
		this.dmdantocMa = dmdantocMa;
		this.dmdantocTen = dmdantocTen;
		this.dmdantocDefa = dmdantocDefa;
		this.dmdantocMienphi = dmdantocMienphi;
		this.dmdantocNgaygiocn = dmdantocNgaygiocn;
		this.dmdantocChon = dmdantocChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_DAN_TOC")
	@SequenceGenerator(name = "DM_DAN_TOC", sequenceName = "DM_DAN_TOC_DMDANTOC_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMDANTOC_MASO", unique = true, nullable = false)
	public Integer getDmdantocMaso() {
		return this.dmdantocMaso;
	}

	public void setDmdantocMaso(Integer dmdantocMaso) {
		this.dmdantocMaso = dmdantocMaso;
	}

	@Column(name = "DMDANTOC_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmdantocMa() {
		return this.dmdantocMa;
	}

	public void setDmdantocMa(String dmdantocMa) {
		this.dmdantocMa = dmdantocMa;
	}

	@Column(name = "DMDANTOC_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmdantocTen() {
		return this.dmdantocTen;
	}

	public void setDmdantocTen(String dmdantocTen) {
		this.dmdantocTen = dmdantocTen;
	}

	@Column(name = "DMDANTOC_DEFA")
	public Boolean getDmdantocDefa() {
		return this.dmdantocDefa;
	}

	public void setDmdantocDefa(Boolean dmdantocDefa) {
		this.dmdantocDefa = dmdantocDefa;
	}

	@Column(name = "DMDANTOC_MIENPHI")
	public Boolean getDmdantocMienphi() {
		return this.dmdantocMienphi;
	}

	public void setDmdantocMienphi(Boolean dmdantocMienphi) {
		this.dmdantocMienphi = dmdantocMienphi;
	}

	@Column(name = "DMDANTOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmdantocNgaygiocn() {
		return this.dmdantocNgaygiocn;
	}

	public void setDmdantocNgaygiocn(Double dmdantocNgaygiocn) {
		this.dmdantocNgaygiocn = dmdantocNgaygiocn;
	}

	@Column(name = "DMDANTOC_CHON")
	public Boolean getDmdantocChon() {
		return this.dmdantocChon;
	}

	public void setDmdantocChon(Boolean dmdantocChon) {
		this.dmdantocChon = dmdantocChon;
	}

}
