package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmDieuTri generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_DIEU_TRI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMDIEUTRI_MA"))
public class DmDieuTri implements java.io.Serializable {

	private Integer dmdieutriMaso;
	private String dmdieutriMa;
	private String dmdieutriTen;
	private String dmdieutriDiengiai2;
	private Boolean dmdieutriDefa;
	private Double dmdieutriNgaygiocn;
	private Boolean dmdieutriQl;
	private Boolean dmdieutriDt;
	private Boolean dmdieutriDp;
	private String dmdieutriDiengiai1;

	public DmDieuTri() {
	}

	public DmDieuTri(String dmdieutriMa, String dmdieutriTen) {
		this.dmdieutriMa = dmdieutriMa;
		this.dmdieutriTen = dmdieutriTen;
	}

	public DmDieuTri(String dmdieutriMa, String dmdieutriTen,
			String dmdieutriDiengiai2, Boolean dmdieutriDefa,
			Double dmdieutriNgaygiocn, Boolean dmdieutriQl,
			Boolean dmdieutriDt, Boolean dmdieutriDp, String dmdieutriDiengiai1) {
		this.dmdieutriMa = dmdieutriMa;
		this.dmdieutriTen = dmdieutriTen;
		this.dmdieutriDiengiai2 = dmdieutriDiengiai2;
		this.dmdieutriDefa = dmdieutriDefa;
		this.dmdieutriNgaygiocn = dmdieutriNgaygiocn;
		this.dmdieutriQl = dmdieutriQl;
		this.dmdieutriDt = dmdieutriDt;
		this.dmdieutriDp = dmdieutriDp;
		this.dmdieutriDiengiai1 = dmdieutriDiengiai1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_DIEU_TRI")
	@SequenceGenerator(name = "DM_DIEU_TRI", sequenceName = "DM_DIEU_TRI_DMDIEUTRI_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMDIEUTRI_MASO", unique = true, nullable = false)
	public Integer getDmdieutriMaso() {
		return this.dmdieutriMaso;
	}

	public void setDmdieutriMaso(Integer dmdieutriMaso) {
		this.dmdieutriMaso = dmdieutriMaso;
	}

	@Column(name = "DMDIEUTRI_MA", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getDmdieutriMa() {
		return this.dmdieutriMa;
	}

	public void setDmdieutriMa(String dmdieutriMa) {
		this.dmdieutriMa = dmdieutriMa;
	}

	@Column(name = "DMDIEUTRI_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmdieutriTen() {
		return this.dmdieutriTen;
	}

	public void setDmdieutriTen(String dmdieutriTen) {
		this.dmdieutriTen = dmdieutriTen;
	}

	@Column(name = "DMDIEUTRI_DIENGIAI2", length = 250)
	@Length(max = 250)
	public String getDmdieutriDiengiai2() {
		return this.dmdieutriDiengiai2;
	}

	public void setDmdieutriDiengiai2(String dmdieutriDiengiai2) {
		this.dmdieutriDiengiai2 = dmdieutriDiengiai2;
	}

	@Column(name = "DMDIEUTRI_DEFA")
	public Boolean getDmdieutriDefa() {
		return this.dmdieutriDefa;
	}

	public void setDmdieutriDefa(Boolean dmdieutriDefa) {
		this.dmdieutriDefa = dmdieutriDefa;
	}

	@Column(name = "DMDIEUTRI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmdieutriNgaygiocn() {
		return this.dmdieutriNgaygiocn;
	}

	public void setDmdieutriNgaygiocn(Double dmdieutriNgaygiocn) {
		this.dmdieutriNgaygiocn = dmdieutriNgaygiocn;
	}

	@Column(name = "DMDIEUTRI_QL")
	public Boolean getDmdieutriQl() {
		return this.dmdieutriQl;
	}

	public void setDmdieutriQl(Boolean dmdieutriQl) {
		this.dmdieutriQl = dmdieutriQl;
	}

	@Column(name = "DMDIEUTRI_DT")
	public Boolean getDmdieutriDt() {
		return this.dmdieutriDt;
	}

	public void setDmdieutriDt(Boolean dmdieutriDt) {
		this.dmdieutriDt = dmdieutriDt;
	}

	@Column(name = "DMDIEUTRI_DP")
	public Boolean getDmdieutriDp() {
		return this.dmdieutriDp;
	}

	public void setDmdieutriDp(Boolean dmdieutriDp) {
		this.dmdieutriDp = dmdieutriDp;
	}

	@Column(name = "DMDIEUTRI_DIENGIAI1", length = 250)
	@Length(max = 250)
	public String getDmdieutriDiengiai1() {
		return this.dmdieutriDiengiai1;
	}

	public void setDmdieutriDiengiai1(String dmdieutriDiengiai1) {
		this.dmdieutriDiengiai1 = dmdieutriDiengiai1;
	}

}
