package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;

/**
 * DmDonVi generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_DON_VI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMDONVI_MA"))
public class DmDonVi implements java.io.Serializable {

	private Integer dmdonviMaso;
	private DmTinh dmTinh;
	private DmXa dmXa;
	private DmHuyen dmHuyen;
	private DmTuyen dmTuyen;
	private String dmdonviMa;
	private String dmdonviTen;
	private String dmdonviTenbaocao;
	private String dmdonviSonhatuyenduong;
	private String dmdonviDienthoai;
	private String dmdonviDvquanlytructiep;
	private Double dmdonviNgaygiocn;
	private Boolean dmdonviChon;
	private String dmdonviUrl;
	private Set<DmTuyenDonVi> dmTuyenDonVis = new HashSet<DmTuyenDonVi>(0);
	private Set<DmTuyenDonVi> dmTuyenDonVis_1 = new HashSet<DmTuyenDonVi>(0);

	public DmDonVi() {
	}

	public DmDonVi(DmTinh dmTinh, DmXa dmXa, DmHuyen dmHuyen, DmTuyen dmTuyen,
			String dmdonviMa, String dmdonviTen, String dmdonviTenbaocao,
			String dmdonviSonhatuyenduong, String dmdonviDienthoai,
			String dmdonviDvquanlytructiep, Double dmdonviNgaygiocn,
			Boolean dmdonviChon, String dmdonviUrl,
			Set<DmTuyenDonVi> dmTuyenDonVis, Set<DmTuyenDonVi> dmTuyenDonVis_1) {
		this.dmTinh = dmTinh;
		this.dmXa = dmXa;
		this.dmHuyen = dmHuyen;
		this.dmTuyen = dmTuyen;
		this.dmdonviMa = dmdonviMa;
		this.dmdonviTen = dmdonviTen;
		this.dmdonviTenbaocao = dmdonviTenbaocao;
		this.dmdonviSonhatuyenduong = dmdonviSonhatuyenduong;
		this.dmdonviDienthoai = dmdonviDienthoai;
		this.dmdonviDvquanlytructiep = dmdonviDvquanlytructiep;
		this.dmdonviNgaygiocn = dmdonviNgaygiocn;
		this.dmdonviChon = dmdonviChon;
		this.dmdonviUrl = dmdonviUrl;
		this.dmTuyenDonVis = dmTuyenDonVis;
		this.dmTuyenDonVis_1 = dmTuyenDonVis_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_DON_VI")
	@SequenceGenerator(name = "DM_DON_VI", sequenceName = "DM_DON_VI_DMDONVI_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMDONVI_MASO", unique = true, nullable = false)
	public Integer getDmdonviMaso() {
		return this.dmdonviMaso;
	}

	public void setDmdonviMaso(Integer dmdonviMaso) {
		this.dmdonviMaso = dmdonviMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTINH_MASO")
	public DmTinh getDmTinh() {
		return this.dmTinh;
	}

	public void setDmTinh(DmTinh dmTinh) {
		this.dmTinh = dmTinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMXA_MASO")
	public DmXa getDmXa() {
		return this.dmXa;
	}

	public void setDmXa(DmXa dmXa) {
		this.dmXa = dmXa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMHUYEN_MASO")
	public DmHuyen getDmHuyen() {
		return this.dmHuyen;
	}

	public void setDmHuyen(DmHuyen dmHuyen) {
		this.dmHuyen = dmHuyen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTUYEN_MASO")
	public DmTuyen getDmTuyen() {
		return this.dmTuyen;
	}

	public void setDmTuyen(DmTuyen dmTuyen) {
		this.dmTuyen = dmTuyen;
	}

	@Column(name = "DMDONVI_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmdonviMa() {
		return this.dmdonviMa;
	}

	public void setDmdonviMa(String dmdonviMa) {
		this.dmdonviMa = dmdonviMa;
	}

	@Column(name = "DMDONVI_TEN", length = 100)
	@Length(max = 100)
	public String getDmdonviTen() {
		return this.dmdonviTen;
	}

	public void setDmdonviTen(String dmdonviTen) {
		this.dmdonviTen = dmdonviTen;
	}

	@Column(name = "DMDONVI_TENBAOCAO", length = 50)
	@Length(max = 50)
	public String getDmdonviTenbaocao() {
		return this.dmdonviTenbaocao;
	}

	public void setDmdonviTenbaocao(String dmdonviTenbaocao) {
		this.dmdonviTenbaocao = dmdonviTenbaocao;
	}

	@Column(name = "DMDONVI_SONHATUYENDUONG", length = 200)
	@Length(max = 200)
	public String getDmdonviSonhatuyenduong() {
		return this.dmdonviSonhatuyenduong;
	}

	public void setDmdonviSonhatuyenduong(String dmdonviSonhatuyenduong) {
		this.dmdonviSonhatuyenduong = dmdonviSonhatuyenduong;
	}

	@Column(name = "DMDONVI_DIENTHOAI", length = 15)
	@Length(max = 15)
	public String getDmdonviDienthoai() {
		return this.dmdonviDienthoai;
	}

	public void setDmdonviDienthoai(String dmdonviDienthoai) {
		this.dmdonviDienthoai = dmdonviDienthoai;
	}

	@Column(name = "DMDONVI_DVQUANLYTRUCTIEP", length = 100)
	@Length(max = 100)
	public String getDmdonviDvquanlytructiep() {
		return this.dmdonviDvquanlytructiep;
	}

	public void setDmdonviDvquanlytructiep(String dmdonviDvquanlytructiep) {
		this.dmdonviDvquanlytructiep = dmdonviDvquanlytructiep;
	}

	@Column(name = "DMDONVI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmdonviNgaygiocn() {
		return this.dmdonviNgaygiocn;
	}

	public void setDmdonviNgaygiocn(Double dmdonviNgaygiocn) {
		this.dmdonviNgaygiocn = dmdonviNgaygiocn;
	}

	@Column(name = "DMDONVI_CHON")
	public Boolean getDmdonviChon() {
		return this.dmdonviChon;
	}

	public void setDmdonviChon(Boolean dmdonviChon) {
		this.dmdonviChon = dmdonviChon;
	}

	@Column(name = "DMDONVI_URL", length = 128)
	@Length(max = 128)
	public String getDmdonviUrl() {
		return this.dmdonviUrl;
	}

	public void setDmdonviUrl(String dmdonviUrl) {
		this.dmdonviUrl = dmdonviUrl;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonVi")
	public Set<DmTuyenDonVi> getDmTuyenDonVis() {
		return this.dmTuyenDonVis;
	}

	public void setDmTuyenDonVis(Set<DmTuyenDonVi> dmTuyenDonVis) {
		this.dmTuyenDonVis = dmTuyenDonVis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonVi")
	public Set<DmTuyenDonVi> getDmTuyenDonVis_1() {
		return this.dmTuyenDonVis_1;
	}

	public void setDmTuyenDonVis_1(Set<DmTuyenDonVi> dmTuyenDonVis_1) {
		this.dmTuyenDonVis_1 = dmTuyenDonVis_1;
	}

}
