package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmDoiTuong generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_DOI_TUONG", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMDOITUONG_MA"))
public class DmDoiTuong implements java.io.Serializable {

	private Integer dmdoituongMaso;
	private String dmdoituongMa;
	private String dmdoituongMagom;
	private Integer dmdoituongThutubc;
	private String dmdoituongTen;
	private Boolean dmdoituongChon1;
	private Boolean dmdoituongChon2;
	private Boolean dmdoituongKhobhyt;
	private Boolean dmdoituongKhole;
	private Boolean dmdoituongKhochinh;
	private String dmdoituongBenhan;
	private Boolean dmdoituongThuphi;
	private Boolean dmdoituongTieuhao;
	private Boolean dmdoituongDinhduong;
	private Float dmdoituongTylemien;
	private String dmdoituongTenbc;
	private String dmdoituongMauphieu;
	private Double dmdoituongNgaygiocn;
	private Boolean dmdoituongDt;
	private Boolean dmdoituongQl;
	private Boolean dmdoituongDp;

	public DmDoiTuong() {
	}

	public DmDoiTuong(String dmdoituongMa, String dmdoituongTen) {
		this.dmdoituongMa = dmdoituongMa;
		this.dmdoituongTen = dmdoituongTen;
	}

	public DmDoiTuong(String dmdoituongMa, String dmdoituongMagom,
			Integer dmdoituongThutubc, String dmdoituongTen,
			Boolean dmdoituongChon1, Boolean dmdoituongChon2,
			Boolean dmdoituongKhobhyt, Boolean dmdoituongKhole,
			Boolean dmdoituongKhochinh, String dmdoituongBenhan,
			Boolean dmdoituongThuphi, Boolean dmdoituongTieuhao,
			Boolean dmdoituongDinhduong, Float dmdoituongTylemien,
			String dmdoituongTenbc, String dmdoituongMauphieu,
			Double dmdoituongNgaygiocn, Boolean dmdoituongDt,
			Boolean dmdoituongQl, Boolean dmdoituongDp) {
		this.dmdoituongMa = dmdoituongMa;
		this.dmdoituongMagom = dmdoituongMagom;
		this.dmdoituongThutubc = dmdoituongThutubc;
		this.dmdoituongTen = dmdoituongTen;
		this.dmdoituongChon1 = dmdoituongChon1;
		this.dmdoituongChon2 = dmdoituongChon2;
		this.dmdoituongKhobhyt = dmdoituongKhobhyt;
		this.dmdoituongKhole = dmdoituongKhole;
		this.dmdoituongKhochinh = dmdoituongKhochinh;
		this.dmdoituongBenhan = dmdoituongBenhan;
		this.dmdoituongThuphi = dmdoituongThuphi;
		this.dmdoituongTieuhao = dmdoituongTieuhao;
		this.dmdoituongDinhduong = dmdoituongDinhduong;
		this.dmdoituongTylemien = dmdoituongTylemien;
		this.dmdoituongTenbc = dmdoituongTenbc;
		this.dmdoituongMauphieu = dmdoituongMauphieu;
		this.dmdoituongNgaygiocn = dmdoituongNgaygiocn;
		this.dmdoituongDt = dmdoituongDt;
		this.dmdoituongQl = dmdoituongQl;
		this.dmdoituongDp = dmdoituongDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_DOI_TUONG")
	@SequenceGenerator(name = "DM_DOI_TUONG", sequenceName = "DM_DOI_TUONG_DMDOITUONG_MASO_S", allocationSize = 1)
	@Column(name = "DMDOITUONG_MASO", unique = true, nullable = false)
	public Integer getDmdoituongMaso() {
		return this.dmdoituongMaso;
	}

	public void setDmdoituongMaso(Integer dmdoituongMaso) {
		this.dmdoituongMaso = dmdoituongMaso;
	}

	@Column(name = "DMDOITUONG_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmdoituongMa() {
		return this.dmdoituongMa;
	}

	public void setDmdoituongMa(String dmdoituongMa) {
		this.dmdoituongMa = dmdoituongMa;
	}

	@Column(name = "DMDOITUONG_MAGOM", length = 4)
	@Length(max = 4)
	public String getDmdoituongMagom() {
		return this.dmdoituongMagom;
	}

	public void setDmdoituongMagom(String dmdoituongMagom) {
		this.dmdoituongMagom = dmdoituongMagom;
	}

	@Column(name = "DMDOITUONG_THUTUBC")
	public Integer getDmdoituongThutubc() {
		return this.dmdoituongThutubc;
	}

	public void setDmdoituongThutubc(Integer dmdoituongThutubc) {
		this.dmdoituongThutubc = dmdoituongThutubc;
	}

	@Column(name = "DMDOITUONG_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDmdoituongTen() {
		return this.dmdoituongTen;
	}

	public void setDmdoituongTen(String dmdoituongTen) {
		this.dmdoituongTen = dmdoituongTen;
	}

	@Column(name = "DMDOITUONG_CHON1")
	public Boolean getDmdoituongChon1() {
		return this.dmdoituongChon1;
	}

	public void setDmdoituongChon1(Boolean dmdoituongChon1) {
		this.dmdoituongChon1 = dmdoituongChon1;
	}

	@Column(name = "DMDOITUONG_CHON2")
	public Boolean getDmdoituongChon2() {
		return this.dmdoituongChon2;
	}

	public void setDmdoituongChon2(Boolean dmdoituongChon2) {
		this.dmdoituongChon2 = dmdoituongChon2;
	}

	@Column(name = "DMDOITUONG_KHOBHYT")
	public Boolean getDmdoituongKhobhyt() {
		return this.dmdoituongKhobhyt;
	}

	public void setDmdoituongKhobhyt(Boolean dmdoituongKhobhyt) {
		this.dmdoituongKhobhyt = dmdoituongKhobhyt;
	}

	@Column(name = "DMDOITUONG_KHOLE")
	public Boolean getDmdoituongKhole() {
		return this.dmdoituongKhole;
	}

	public void setDmdoituongKhole(Boolean dmdoituongKhole) {
		this.dmdoituongKhole = dmdoituongKhole;
	}

	@Column(name = "DMDOITUONG_KHOCHINH")
	public Boolean getDmdoituongKhochinh() {
		return this.dmdoituongKhochinh;
	}

	public void setDmdoituongKhochinh(Boolean dmdoituongKhochinh) {
		this.dmdoituongKhochinh = dmdoituongKhochinh;
	}

	@Column(name = "DMDOITUONG_BENHAN", length = 1)
	@Length(max = 1)
	public String getDmdoituongBenhan() {
		return this.dmdoituongBenhan;
	}

	public void setDmdoituongBenhan(String dmdoituongBenhan) {
		this.dmdoituongBenhan = dmdoituongBenhan;
	}

	@Column(name = "DMDOITUONG_THUPHI")
	public Boolean getDmdoituongThuphi() {
		return this.dmdoituongThuphi;
	}

	public void setDmdoituongThuphi(Boolean dmdoituongThuphi) {
		this.dmdoituongThuphi = dmdoituongThuphi;
	}

	@Column(name = "DMDOITUONG_TIEUHAO")
	public Boolean getDmdoituongTieuhao() {
		return this.dmdoituongTieuhao;
	}

	public void setDmdoituongTieuhao(Boolean dmdoituongTieuhao) {
		this.dmdoituongTieuhao = dmdoituongTieuhao;
	}

	@Column(name = "DMDOITUONG_DINHDUONG")
	public Boolean getDmdoituongDinhduong() {
		return this.dmdoituongDinhduong;
	}

	public void setDmdoituongDinhduong(Boolean dmdoituongDinhduong) {
		this.dmdoituongDinhduong = dmdoituongDinhduong;
	}

	@Column(name = "DMDOITUONG_TYLEMIEN", precision = 12, scale = 0)
	public Float getDmdoituongTylemien() {
		return this.dmdoituongTylemien;
	}

	public void setDmdoituongTylemien(Float dmdoituongTylemien) {
		this.dmdoituongTylemien = dmdoituongTylemien;
	}

	@Column(name = "DMDOITUONG_TENBC", length = 18)
	@Length(max = 18)
	public String getDmdoituongTenbc() {
		return this.dmdoituongTenbc;
	}

	public void setDmdoituongTenbc(String dmdoituongTenbc) {
		this.dmdoituongTenbc = dmdoituongTenbc;
	}

	@Column(name = "DMDOITUONG_MAUPHIEU", length = 4)
	@Length(max = 4)
	public String getDmdoituongMauphieu() {
		return this.dmdoituongMauphieu;
	}

	public void setDmdoituongMauphieu(String dmdoituongMauphieu) {
		this.dmdoituongMauphieu = dmdoituongMauphieu;
	}

	@Column(name = "DMDOITUONG_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmdoituongNgaygiocn() {
		return this.dmdoituongNgaygiocn;
	}

	public void setDmdoituongNgaygiocn(Double dmdoituongNgaygiocn) {
		this.dmdoituongNgaygiocn = dmdoituongNgaygiocn;
	}

	@Column(name = "DMDOITUONG_DT")
	public Boolean getDmdoituongDt() {
		return this.dmdoituongDt;
	}

	public void setDmdoituongDt(Boolean dmdoituongDt) {
		this.dmdoituongDt = dmdoituongDt;
	}

	@Column(name = "DMDOITUONG_QL")
	public Boolean getDmdoituongQl() {
		return this.dmdoituongQl;
	}

	public void setDmdoituongQl(Boolean dmdoituongQl) {
		this.dmdoituongQl = dmdoituongQl;
	}

	@Column(name = "DMDOITUONG_DP")
	public Boolean getDmdoituongDp() {
		return this.dmdoituongDp;
	}

	public void setDmdoituongDp(Boolean dmdoituongDp) {
		this.dmdoituongDp = dmdoituongDp;
	}

}
