package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmDonViTinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_DON_VI_TINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMDONVITINH_MA"))
public class DmDonViTinh implements java.io.Serializable {

	private Integer dmdonvitinhMaso;
	private String dmdonvitinhMa;
	private String dmdonvitinhTen;
	private String dmdonvitinhDtich;
	private String dmdonvitinhDacdiem;
	private Double dmdonvitinhNgaygiocn;
	private Boolean dmdonvitinhDt;
	private Boolean dmdonvitinhDp;
	private Boolean dmdonvitinhQl;
	private Set<DmThuoc> dmThuocs = new HashSet<DmThuoc>(0);
	private Set<DtDmLoaiThucPham> dtDmLoaiThucPhams = new HashSet<DtDmLoaiThucPham>(
			0);
	private Set<DtDmChiDanDvt> dtDmChiDanDvts = new HashSet<DtDmChiDanDvt>(0);
	private Set<DtDmChiDanDvt> dtDmChiDanDvts_1 = new HashSet<DtDmChiDanDvt>(0);
	private Set<DmThuoc> dmThuocs_1 = new HashSet<DmThuoc>(0);

	public DmDonViTinh() {
	}

	public DmDonViTinh(String dmdonvitinhMa, String dmdonvitinhTen) {
		this.dmdonvitinhMa = dmdonvitinhMa;
		this.dmdonvitinhTen = dmdonvitinhTen;
	}

	public DmDonViTinh(String dmdonvitinhMa, String dmdonvitinhTen,
			String dmdonvitinhDtich, String dmdonvitinhDacdiem,
			Double dmdonvitinhNgaygiocn, Boolean dmdonvitinhDt,
			Boolean dmdonvitinhDp, Boolean dmdonvitinhQl,
			Set<DmThuoc> dmThuocs, Set<DtDmLoaiThucPham> dtDmLoaiThucPhams,
			Set<DtDmChiDanDvt> dtDmChiDanDvts,
			Set<DtDmChiDanDvt> dtDmChiDanDvts_1, Set<DmThuoc> dmThuocs_1) {
		this.dmdonvitinhMa = dmdonvitinhMa;
		this.dmdonvitinhTen = dmdonvitinhTen;
		this.dmdonvitinhDtich = dmdonvitinhDtich;
		this.dmdonvitinhDacdiem = dmdonvitinhDacdiem;
		this.dmdonvitinhNgaygiocn = dmdonvitinhNgaygiocn;
		this.dmdonvitinhDt = dmdonvitinhDt;
		this.dmdonvitinhDp = dmdonvitinhDp;
		this.dmdonvitinhQl = dmdonvitinhQl;
		this.dmThuocs = dmThuocs;
		this.dtDmLoaiThucPhams = dtDmLoaiThucPhams;
		this.dtDmChiDanDvts = dtDmChiDanDvts;
		this.dtDmChiDanDvts_1 = dtDmChiDanDvts_1;
		this.dmThuocs_1 = dmThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_DON_VI_TINH")
	@SequenceGenerator(name = "DM_DON_VI_TINH", sequenceName = "DM_DON_VI_TINH_DMDONVITINH_MAS", allocationSize = 1)
	@Column(name = "DMDONVITINH_MASO", unique = true, nullable = false)
	public Integer getDmdonvitinhMaso() {
		return this.dmdonvitinhMaso;
	}

	public void setDmdonvitinhMaso(Integer dmdonvitinhMaso) {
		this.dmdonvitinhMaso = dmdonvitinhMaso;
	}

	@Column(name = "DMDONVITINH_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmdonvitinhMa() {
		return this.dmdonvitinhMa;
	}

	public void setDmdonvitinhMa(String dmdonvitinhMa) {
		this.dmdonvitinhMa = dmdonvitinhMa;
	}

	@Column(name = "DMDONVITINH_TEN", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDmdonvitinhTen() {
		return this.dmdonvitinhTen;
	}

	public void setDmdonvitinhTen(String dmdonvitinhTen) {
		this.dmdonvitinhTen = dmdonvitinhTen;
	}

	@Column(name = "DMDONVITINH_DTICH", length = 250)
	@Length(max = 250)
	public String getDmdonvitinhDtich() {
		return this.dmdonvitinhDtich;
	}

	public void setDmdonvitinhDtich(String dmdonvitinhDtich) {
		this.dmdonvitinhDtich = dmdonvitinhDtich;
	}

	@Column(name = "DMDONVITINH_DACDIEM", length = 250)
	@Length(max = 250)
	public String getDmdonvitinhDacdiem() {
		return this.dmdonvitinhDacdiem;
	}

	public void setDmdonvitinhDacdiem(String dmdonvitinhDacdiem) {
		this.dmdonvitinhDacdiem = dmdonvitinhDacdiem;
	}

	@Column(name = "DMDONVITINH_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmdonvitinhNgaygiocn() {
		return this.dmdonvitinhNgaygiocn;
	}

	public void setDmdonvitinhNgaygiocn(Double dmdonvitinhNgaygiocn) {
		this.dmdonvitinhNgaygiocn = dmdonvitinhNgaygiocn;
	}

	@Column(name = "DMDONVITINH_DT")
	public Boolean getDmdonvitinhDt() {
		return this.dmdonvitinhDt;
	}

	public void setDmdonvitinhDt(Boolean dmdonvitinhDt) {
		this.dmdonvitinhDt = dmdonvitinhDt;
	}

	@Column(name = "DMDONVITINH_DP")
	public Boolean getDmdonvitinhDp() {
		return this.dmdonvitinhDp;
	}

	public void setDmdonvitinhDp(Boolean dmdonvitinhDp) {
		this.dmdonvitinhDp = dmdonvitinhDp;
	}

	@Column(name = "DMDONVITINH_QL")
	public Boolean getDmdonvitinhQl() {
		return this.dmdonvitinhQl;
	}

	public void setDmdonvitinhQl(Boolean dmdonvitinhQl) {
		this.dmdonvitinhQl = dmdonvitinhQl;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonViTinh")
	public Set<DmThuoc> getDmThuocs() {
		return this.dmThuocs;
	}

	public void setDmThuocs(Set<DmThuoc> dmThuocs) {
		this.dmThuocs = dmThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonViTinh")
	public Set<DtDmLoaiThucPham> getDtDmLoaiThucPhams() {
		return this.dtDmLoaiThucPhams;
	}

	public void setDtDmLoaiThucPhams(Set<DtDmLoaiThucPham> dtDmLoaiThucPhams) {
		this.dtDmLoaiThucPhams = dtDmLoaiThucPhams;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonViTinh")
	public Set<DtDmChiDanDvt> getDtDmChiDanDvts() {
		return this.dtDmChiDanDvts;
	}

	public void setDtDmChiDanDvts(Set<DtDmChiDanDvt> dtDmChiDanDvts) {
		this.dtDmChiDanDvts = dtDmChiDanDvts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonViTinh")
	public Set<DtDmChiDanDvt> getDtDmChiDanDvts_1() {
		return this.dtDmChiDanDvts_1;
	}

	public void setDtDmChiDanDvts_1(Set<DtDmChiDanDvt> dtDmChiDanDvts_1) {
		this.dtDmChiDanDvts_1 = dtDmChiDanDvts_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmDonViTinh")
	public Set<DmThuoc> getDmThuocs_1() {
		return this.dmThuocs_1;
	}

	public void setDmThuocs_1(Set<DmThuoc> dmThuocs_1) {
		this.dmThuocs_1 = dmThuocs_1;
	}

}
