package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmGioiTinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_GIOI_TINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMGT_MA"))
public class DmGioiTinh implements java.io.Serializable {

	private Integer dmgtMaso;
	private String dmgtMa;
	private String dmgtTen;
	private Boolean dmgtDefa;
	private String dmgtGhichu;
	private Double dmgtNgaygiocn;
	private boolean dmgtChon;

	public DmGioiTinh() {
	}

	public DmGioiTinh(String dmgtMa, String dmgtTen, boolean dmgtChon) {
		this.dmgtMa = dmgtMa;
		this.dmgtTen = dmgtTen;
		this.dmgtChon = dmgtChon;
	}

	public DmGioiTinh(String dmgtMa, String dmgtTen, Boolean dmgtDefa,
			String dmgtGhichu, Double dmgtNgaygiocn, boolean dmgtChon) {
		this.dmgtMa = dmgtMa;
		this.dmgtTen = dmgtTen;
		this.dmgtDefa = dmgtDefa;
		this.dmgtGhichu = dmgtGhichu;
		this.dmgtNgaygiocn = dmgtNgaygiocn;
		this.dmgtChon = dmgtChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_GIOI_TINH")
	@SequenceGenerator(name = "DM_GIOI_TINH", sequenceName = "DM_GIOI_TINH_DMGT_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMGT_MASO", unique = true, nullable = false)
	public Integer getDmgtMaso() {
		return this.dmgtMaso;
	}

	public void setDmgtMaso(Integer dmgtMaso) {
		this.dmgtMaso = dmgtMaso;
	}

	@Column(name = "DMGT_MA", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDmgtMa() {
		return this.dmgtMa;
	}

	public void setDmgtMa(String dmgtMa) {
		this.dmgtMa = dmgtMa;
	}

	@Column(name = "DMGT_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDmgtTen() {
		return this.dmgtTen;
	}

	public void setDmgtTen(String dmgtTen) {
		this.dmgtTen = dmgtTen;
	}

	@Column(name = "DMGT_DEFA")
	public Boolean getDmgtDefa() {
		return this.dmgtDefa;
	}

	public void setDmgtDefa(Boolean dmgtDefa) {
		this.dmgtDefa = dmgtDefa;
	}

	@Column(name = "DMGT_GHICHU", length = 50)
	@Length(max = 50)
	public String getDmgtGhichu() {
		return this.dmgtGhichu;
	}

	public void setDmgtGhichu(String dmgtGhichu) {
		this.dmgtGhichu = dmgtGhichu;
	}

	@Column(name = "DMGT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmgtNgaygiocn() {
		return this.dmgtNgaygiocn;
	}

	public void setDmgtNgaygiocn(Double dmgtNgaygiocn) {
		this.dmgtNgaygiocn = dmgtNgaygiocn;
	}

	@Column(name = "DMGT_CHON", nullable = false)
	@NotNull
	public boolean isDmgtChon() {
		return this.dmgtChon;
	}

	public void setDmgtChon(boolean dmgtChon) {
		this.dmgtChon = dmgtChon;
	}

}
