package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmHinhThucXuLy generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_HINH_THUC_XU_LY", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMHINHTHUCXULY_MA"))
public class DmHinhThucXuLy implements java.io.Serializable {

	private Integer dmhinhthucxulyMaso;
	private String dmhinhthucxulyMa;
	private String dmhinhthucxulyTen;
	private Double dmhinhthucxulyNgaygiocn;
	private Boolean dmhinhthucxulyDt;
	private Boolean dmhinhthucxulyDp;
	private Boolean dmhinhthucxulyQl;

	public DmHinhThucXuLy() {
	}

	public DmHinhThucXuLy(String dmhinhthucxulyTen) {
		this.dmhinhthucxulyTen = dmhinhthucxulyTen;
	}

	public DmHinhThucXuLy(String dmhinhthucxulyMa, String dmhinhthucxulyTen,
			Double dmhinhthucxulyNgaygiocn, Boolean dmhinhthucxulyDt,
			Boolean dmhinhthucxulyDp, Boolean dmhinhthucxulyQl) {
		this.dmhinhthucxulyMa = dmhinhthucxulyMa;
		this.dmhinhthucxulyTen = dmhinhthucxulyTen;
		this.dmhinhthucxulyNgaygiocn = dmhinhthucxulyNgaygiocn;
		this.dmhinhthucxulyDt = dmhinhthucxulyDt;
		this.dmhinhthucxulyDp = dmhinhthucxulyDp;
		this.dmhinhthucxulyQl = dmhinhthucxulyQl;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_HINH_THUC_XU_LY")
	@SequenceGenerator(name = "DM_HINH_THUC_XU_LY", sequenceName = "DM_HINH_THUC_XU_LY_DMHINHTHUCX", allocationSize = 1)
	@Column(name = "DMHINHTHUCXULY_MASO", unique = true, nullable = false)
	public Integer getDmhinhthucxulyMaso() {
		return this.dmhinhthucxulyMaso;
	}

	public void setDmhinhthucxulyMaso(Integer dmhinhthucxulyMaso) {
		this.dmhinhthucxulyMaso = dmhinhthucxulyMaso;
	}

	@Column(name = "DMHINHTHUCXULY_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmhinhthucxulyMa() {
		return this.dmhinhthucxulyMa;
	}

	public void setDmhinhthucxulyMa(String dmhinhthucxulyMa) {
		this.dmhinhthucxulyMa = dmhinhthucxulyMa;
	}

	@Column(name = "DMHINHTHUCXULY_TEN", nullable = false, length = 300)
	@NotNull
	@Length(max = 300)
	public String getDmhinhthucxulyTen() {
		return this.dmhinhthucxulyTen;
	}

	public void setDmhinhthucxulyTen(String dmhinhthucxulyTen) {
		this.dmhinhthucxulyTen = dmhinhthucxulyTen;
	}

	@Column(name = "DMHINHTHUCXULY_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmhinhthucxulyNgaygiocn() {
		return this.dmhinhthucxulyNgaygiocn;
	}

	public void setDmhinhthucxulyNgaygiocn(Double dmhinhthucxulyNgaygiocn) {
		this.dmhinhthucxulyNgaygiocn = dmhinhthucxulyNgaygiocn;
	}

	@Column(name = "DMHINHTHUCXULY_DT")
	public Boolean getDmhinhthucxulyDt() {
		return this.dmhinhthucxulyDt;
	}

	public void setDmhinhthucxulyDt(Boolean dmhinhthucxulyDt) {
		this.dmhinhthucxulyDt = dmhinhthucxulyDt;
	}

	@Column(name = "DMHINHTHUCXULY_DP")
	public Boolean getDmhinhthucxulyDp() {
		return this.dmhinhthucxulyDp;
	}

	public void setDmhinhthucxulyDp(Boolean dmhinhthucxulyDp) {
		this.dmhinhthucxulyDp = dmhinhthucxulyDp;
	}

	@Column(name = "DMHINHTHUCXULY_QL")
	public Boolean getDmhinhthucxulyQl() {
		return this.dmhinhthucxulyQl;
	}

	public void setDmhinhthucxulyQl(Boolean dmhinhthucxulyQl) {
		this.dmhinhthucxulyQl = dmhinhthucxulyQl;
	}

}
