package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmHocVi generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_HOC_VI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMHOCVI_MA"))
public class DmHocVi implements java.io.Serializable {

	private Integer dmhocviMaso;
	private DmNhomHocVi dmNhomHocVi;
	private String dmhocviMa;
	private String dmhocviTen;
	private String dmhocviTenbc;
	private Boolean dmhocviDaihoc;
	private Short dmhocviThutu;
	private Double dmhocviNgaygiocn;
	private Boolean dmhocviQl;
	private Boolean dmhocviDt;
	private Boolean dmhocviDp;
	private Set<DtDmNhanVien> dtDmNhanViens = new HashSet<DtDmNhanVien>(0);
	private Set<DtDmNhanVien> dtDmNhanViens_1 = new HashSet<DtDmNhanVien>(0);

	public DmHocVi() {
	}

	public DmHocVi(String dmhocviMa, String dmhocviTen) {
		this.dmhocviMa = dmhocviMa;
		this.dmhocviTen = dmhocviTen;
	}

	public DmHocVi(DmNhomHocVi dmNhomHocVi, String dmhocviMa,
			String dmhocviTen, String dmhocviTenbc, Boolean dmhocviDaihoc,
			Short dmhocviThutu, Double dmhocviNgaygiocn, Boolean dmhocviQl,
			Boolean dmhocviDt, Boolean dmhocviDp,
			Set<DtDmNhanVien> dtDmNhanViens, Set<DtDmNhanVien> dtDmNhanViens_1) {
		this.dmNhomHocVi = dmNhomHocVi;
		this.dmhocviMa = dmhocviMa;
		this.dmhocviTen = dmhocviTen;
		this.dmhocviTenbc = dmhocviTenbc;
		this.dmhocviDaihoc = dmhocviDaihoc;
		this.dmhocviThutu = dmhocviThutu;
		this.dmhocviNgaygiocn = dmhocviNgaygiocn;
		this.dmhocviQl = dmhocviQl;
		this.dmhocviDt = dmhocviDt;
		this.dmhocviDp = dmhocviDp;
		this.dtDmNhanViens = dtDmNhanViens;
		this.dtDmNhanViens_1 = dtDmNhanViens_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_HOC_VI")
	@SequenceGenerator(name = "DM_HOC_VI", sequenceName = "DM_HOC_VI_DMHOCVI_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMHOCVI_MASO", unique = true, nullable = false)
	public Integer getDmhocviMaso() {
		return this.dmhocviMaso;
	}

	public void setDmhocviMaso(Integer dmhocviMaso) {
		this.dmhocviMaso = dmhocviMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNHOMHOCVI_MASO")
	public DmNhomHocVi getDmNhomHocVi() {
		return this.dmNhomHocVi;
	}

	public void setDmNhomHocVi(DmNhomHocVi dmNhomHocVi) {
		this.dmNhomHocVi = dmNhomHocVi;
	}

	@Column(name = "DMHOCVI_MA", unique = true, nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDmhocviMa() {
		return this.dmhocviMa;
	}

	public void setDmhocviMa(String dmhocviMa) {
		this.dmhocviMa = dmhocviMa;
	}

	@Column(name = "DMHOCVI_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmhocviTen() {
		return this.dmhocviTen;
	}

	public void setDmhocviTen(String dmhocviTen) {
		this.dmhocviTen = dmhocviTen;
	}

	@Column(name = "DMHOCVI_TENBC", length = 250)
	@Length(max = 250)
	public String getDmhocviTenbc() {
		return this.dmhocviTenbc;
	}

	public void setDmhocviTenbc(String dmhocviTenbc) {
		this.dmhocviTenbc = dmhocviTenbc;
	}

	@Column(name = "DMHOCVI_DAIHOC")
	public Boolean getDmhocviDaihoc() {
		return this.dmhocviDaihoc;
	}

	public void setDmhocviDaihoc(Boolean dmhocviDaihoc) {
		this.dmhocviDaihoc = dmhocviDaihoc;
	}

	@Column(name = "DMHOCVI_THUTU")
	public Short getDmhocviThutu() {
		return this.dmhocviThutu;
	}

	public void setDmhocviThutu(Short dmhocviThutu) {
		this.dmhocviThutu = dmhocviThutu;
	}

	@Column(name = "DMHOCVI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmhocviNgaygiocn() {
		return this.dmhocviNgaygiocn;
	}

	public void setDmhocviNgaygiocn(Double dmhocviNgaygiocn) {
		this.dmhocviNgaygiocn = dmhocviNgaygiocn;
	}

	@Column(name = "DMHOCVI_QL")
	public Boolean getDmhocviQl() {
		return this.dmhocviQl;
	}

	public void setDmhocviQl(Boolean dmhocviQl) {
		this.dmhocviQl = dmhocviQl;
	}

	@Column(name = "DMHOCVI_DT")
	public Boolean getDmhocviDt() {
		return this.dmhocviDt;
	}

	public void setDmhocviDt(Boolean dmhocviDt) {
		this.dmhocviDt = dmhocviDt;
	}

	@Column(name = "DMHOCVI_DP")
	public Boolean getDmhocviDp() {
		return this.dmhocviDp;
	}

	public void setDmhocviDp(Boolean dmhocviDp) {
		this.dmhocviDp = dmhocviDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHocVi")
	public Set<DtDmNhanVien> getDtDmNhanViens() {
		return this.dtDmNhanViens;
	}

	public void setDtDmNhanViens(Set<DtDmNhanVien> dtDmNhanViens) {
		this.dtDmNhanViens = dtDmNhanViens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHocVi")
	public Set<DtDmNhanVien> getDtDmNhanViens_1() {
		return this.dtDmNhanViens_1;
	}

	public void setDtDmNhanViens_1(Set<DtDmNhanVien> dtDmNhanViens_1) {
		this.dtDmNhanViens_1 = dtDmNhanViens_1;
	}

}
