package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmHuyen generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_HUYEN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMHUYEN_MA"))
public class DmHuyen implements java.io.Serializable {

	private Integer dmhuyenMaso;
	private DmTinh dmTinh;
	private String dmhuyenMa;
	private String dmhuyenTen;
	private Boolean dmhuyenDefa;
	private Double dmhuyenNgaygiocn;
	private Boolean dmhuyenChon;
	private Set<DmXa> dmXas = new HashSet<DmXa>(0);
	private Set<DmXa> dmXas_1 = new HashSet<DmXa>(0);
	private Set<DmDonVi> dmDonVis = new HashSet<DmDonVi>(0);
	private Set<DmDonVi> dmDonVis_1 = new HashSet<DmDonVi>(0);
	private Set<DmBenhVien> dmBenhViens = new HashSet<DmBenhVien>(0);
	private Set<DmBenhVien> dmBenhViens_1 = new HashSet<DmBenhVien>(0);

	public DmHuyen() {
	}

	public DmHuyen(DmTinh dmTinh, String dmhuyenMa, String dmhuyenTen) {
		this.dmTinh = dmTinh;
		this.dmhuyenMa = dmhuyenMa;
		this.dmhuyenTen = dmhuyenTen;
	}

	public DmHuyen(DmTinh dmTinh, String dmhuyenMa, String dmhuyenTen,
			Boolean dmhuyenDefa, Double dmhuyenNgaygiocn, Boolean dmhuyenChon,
			Set<DmXa> dmXas, Set<DmXa> dmXas_1, Set<DmDonVi> dmDonVis,
			Set<DmDonVi> dmDonVis_1, Set<DmBenhVien> dmBenhViens,
			Set<DmBenhVien> dmBenhViens_1) {
		this.dmTinh = dmTinh;
		this.dmhuyenMa = dmhuyenMa;
		this.dmhuyenTen = dmhuyenTen;
		this.dmhuyenDefa = dmhuyenDefa;
		this.dmhuyenNgaygiocn = dmhuyenNgaygiocn;
		this.dmhuyenChon = dmhuyenChon;
		this.dmXas = dmXas;
		this.dmXas_1 = dmXas_1;
		this.dmDonVis = dmDonVis;
		this.dmDonVis_1 = dmDonVis_1;
		this.dmBenhViens = dmBenhViens;
		this.dmBenhViens_1 = dmBenhViens_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_HUYEN")
	@SequenceGenerator(name = "DM_HUYEN", sequenceName = "DM_HUYEN_DMHUYEN_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMHUYEN_MASO", unique = true, nullable = false)
	public Integer getDmhuyenMaso() {
		return this.dmhuyenMaso;
	}

	public void setDmhuyenMaso(Integer dmhuyenMaso) {
		this.dmhuyenMaso = dmhuyenMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTINH_MASO", nullable = false)
	@NotNull
	public DmTinh getDmTinh() {
		return this.dmTinh;
	}

	public void setDmTinh(DmTinh dmTinh) {
		this.dmTinh = dmTinh;
	}

	@Column(name = "DMHUYEN_MA", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getDmhuyenMa() {
		return this.dmhuyenMa;
	}

	public void setDmhuyenMa(String dmhuyenMa) {
		this.dmhuyenMa = dmhuyenMa;
	}

	@Column(name = "DMHUYEN_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDmhuyenTen() {
		return this.dmhuyenTen;
	}

	public void setDmhuyenTen(String dmhuyenTen) {
		this.dmhuyenTen = dmhuyenTen;
	}

	@Column(name = "DMHUYEN_DEFA")
	public Boolean getDmhuyenDefa() {
		return this.dmhuyenDefa;
	}

	public void setDmhuyenDefa(Boolean dmhuyenDefa) {
		this.dmhuyenDefa = dmhuyenDefa;
	}

	@Column(name = "DMHUYEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmhuyenNgaygiocn() {
		return this.dmhuyenNgaygiocn;
	}

	public void setDmhuyenNgaygiocn(Double dmhuyenNgaygiocn) {
		this.dmhuyenNgaygiocn = dmhuyenNgaygiocn;
	}

	@Column(name = "DMHUYEN_CHON")
	public Boolean getDmhuyenChon() {
		return this.dmhuyenChon;
	}

	public void setDmhuyenChon(Boolean dmhuyenChon) {
		this.dmhuyenChon = dmhuyenChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmXa> getDmXas() {
		return this.dmXas;
	}

	public void setDmXas(Set<DmXa> dmXas) {
		this.dmXas = dmXas;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmXa> getDmXas_1() {
		return this.dmXas_1;
	}

	public void setDmXas_1(Set<DmXa> dmXas_1) {
		this.dmXas_1 = dmXas_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmDonVi> getDmDonVis() {
		return this.dmDonVis;
	}

	public void setDmDonVis(Set<DmDonVi> dmDonVis) {
		this.dmDonVis = dmDonVis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmDonVi> getDmDonVis_1() {
		return this.dmDonVis_1;
	}

	public void setDmDonVis_1(Set<DmDonVi> dmDonVis_1) {
		this.dmDonVis_1 = dmDonVis_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmBenhVien> getDmBenhViens() {
		return this.dmBenhViens;
	}

	public void setDmBenhViens(Set<DmBenhVien> dmBenhViens) {
		this.dmBenhViens = dmBenhViens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmHuyen")
	public Set<DmBenhVien> getDmBenhViens_1() {
		return this.dmBenhViens_1;
	}

	public void setDmBenhViens_1(Set<DmBenhVien> dmBenhViens_1) {
		this.dmBenhViens_1 = dmBenhViens_1;
	}

}
