package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmKetQuaDieuTri generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_KET_QUA_DIEU_TRI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMKQDT_MA"))
public class DmKetQuaDieuTri implements java.io.Serializable {

	private Integer dmkqdtMaso;
	private String dmkqdtMa;
	private String dmkqdtTen;
	private String dmkqdtGhichu;
	private Double dmkqdtNgaygiocn;
	private Boolean dmkqdtDt;
	private Boolean dmkqdtQl;
	private Boolean dmkqdtDp;

	public DmKetQuaDieuTri() {
	}

	public DmKetQuaDieuTri(String dmkqdtMa, String dmkqdtTen) {
		this.dmkqdtMa = dmkqdtMa;
		this.dmkqdtTen = dmkqdtTen;
	}

	public DmKetQuaDieuTri(String dmkqdtMa, String dmkqdtTen,
			String dmkqdtGhichu, Double dmkqdtNgaygiocn, Boolean dmkqdtDt,
			Boolean dmkqdtQl, Boolean dmkqdtDp) {
		this.dmkqdtMa = dmkqdtMa;
		this.dmkqdtTen = dmkqdtTen;
		this.dmkqdtGhichu = dmkqdtGhichu;
		this.dmkqdtNgaygiocn = dmkqdtNgaygiocn;
		this.dmkqdtDt = dmkqdtDt;
		this.dmkqdtQl = dmkqdtQl;
		this.dmkqdtDp = dmkqdtDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_KET_QUA_DIEU_TRI")
	@SequenceGenerator(name = "DM_KET_QUA_DIEU_TRI", sequenceName = "DM_KET_QUA_DIEU_TRI_DMKQDT_MAS", allocationSize = 1)
	@Column(name = "DMKQDT_MASO", unique = true, nullable = false)
	public Integer getDmkqdtMaso() {
		return this.dmkqdtMaso;
	}

	public void setDmkqdtMaso(Integer dmkqdtMaso) {
		this.dmkqdtMaso = dmkqdtMaso;
	}

	@Column(name = "DMKQDT_MA", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDmkqdtMa() {
		return this.dmkqdtMa;
	}

	public void setDmkqdtMa(String dmkqdtMa) {
		this.dmkqdtMa = dmkqdtMa;
	}

	@Column(name = "DMKQDT_TEN", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDmkqdtTen() {
		return this.dmkqdtTen;
	}

	public void setDmkqdtTen(String dmkqdtTen) {
		this.dmkqdtTen = dmkqdtTen;
	}

	@Column(name = "DMKQDT_GHICHU", length = 100)
	@Length(max = 100)
	public String getDmkqdtGhichu() {
		return this.dmkqdtGhichu;
	}

	public void setDmkqdtGhichu(String dmkqdtGhichu) {
		this.dmkqdtGhichu = dmkqdtGhichu;
	}

	@Column(name = "DMKQDT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmkqdtNgaygiocn() {
		return this.dmkqdtNgaygiocn;
	}

	public void setDmkqdtNgaygiocn(Double dmkqdtNgaygiocn) {
		this.dmkqdtNgaygiocn = dmkqdtNgaygiocn;
	}

	@Column(name = "DMKQDT_DT")
	public Boolean getDmkqdtDt() {
		return this.dmkqdtDt;
	}

	public void setDmkqdtDt(Boolean dmkqdtDt) {
		this.dmkqdtDt = dmkqdtDt;
	}

	@Column(name = "DMKQDT_QL")
	public Boolean getDmkqdtQl() {
		return this.dmkqdtQl;
	}

	public void setDmkqdtQl(Boolean dmkqdtQl) {
		this.dmkqdtQl = dmkqdtQl;
	}

	@Column(name = "DMKQDT_DP")
	public Boolean getDmkqdtDp() {
		return this.dmkqdtDp;
	}

	public void setDmkqdtDp(Boolean dmkqdtDp) {
		this.dmkqdtDp = dmkqdtDp;
	}

}
