package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmKhoaBc generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_KHOA_BC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMKHOABC_MA"))
public class DmKhoaBc implements java.io.Serializable {

	private Integer dmkhoabcMaso;
	private String dmkhoabcMa;
	private short dmkhoabcMabyt;
	private short dmkhoabcMabyt3;
	private String dmkhoabcTen;
	private Short dmkhoabcNhom;
	private short dmkhoabcThutucbc;
	private Double dmkhoabcNgaygiocn;

	public DmKhoaBc() {
	}

	public DmKhoaBc(short dmkhoabcMabyt, short dmkhoabcMabyt3,
			String dmkhoabcTen, short dmkhoabcThutucbc) {
		this.dmkhoabcMabyt = dmkhoabcMabyt;
		this.dmkhoabcMabyt3 = dmkhoabcMabyt3;
		this.dmkhoabcTen = dmkhoabcTen;
		this.dmkhoabcThutucbc = dmkhoabcThutucbc;
	}

	public DmKhoaBc(String dmkhoabcMa, short dmkhoabcMabyt,
			short dmkhoabcMabyt3, String dmkhoabcTen, Short dmkhoabcNhom,
			short dmkhoabcThutucbc, Double dmkhoabcNgaygiocn) {
		this.dmkhoabcMa = dmkhoabcMa;
		this.dmkhoabcMabyt = dmkhoabcMabyt;
		this.dmkhoabcMabyt3 = dmkhoabcMabyt3;
		this.dmkhoabcTen = dmkhoabcTen;
		this.dmkhoabcNhom = dmkhoabcNhom;
		this.dmkhoabcThutucbc = dmkhoabcThutucbc;
		this.dmkhoabcNgaygiocn = dmkhoabcNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_KHOA_BC")
	@SequenceGenerator(name = "DM_KHOA_BC", sequenceName = "DM_KHOA_BC_DMKHOABC_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMKHOABC_MASO", unique = true, nullable = false)
	public Integer getDmkhoabcMaso() {
		return this.dmkhoabcMaso;
	}

	public void setDmkhoabcMaso(Integer dmkhoabcMaso) {
		this.dmkhoabcMaso = dmkhoabcMaso;
	}

	@Column(name = "DMKHOABC_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmkhoabcMa() {
		return this.dmkhoabcMa;
	}

	public void setDmkhoabcMa(String dmkhoabcMa) {
		this.dmkhoabcMa = dmkhoabcMa;
	}

	@Column(name = "DMKHOABC_MABYT", nullable = false)
	@NotNull
	public short getDmkhoabcMabyt() {
		return this.dmkhoabcMabyt;
	}

	public void setDmkhoabcMabyt(short dmkhoabcMabyt) {
		this.dmkhoabcMabyt = dmkhoabcMabyt;
	}

	@Column(name = "DMKHOABC_MABYT3", nullable = false)
	@NotNull
	public short getDmkhoabcMabyt3() {
		return this.dmkhoabcMabyt3;
	}

	public void setDmkhoabcMabyt3(short dmkhoabcMabyt3) {
		this.dmkhoabcMabyt3 = dmkhoabcMabyt3;
	}

	@Column(name = "DMKHOABC_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmkhoabcTen() {
		return this.dmkhoabcTen;
	}

	public void setDmkhoabcTen(String dmkhoabcTen) {
		this.dmkhoabcTen = dmkhoabcTen;
	}

	@Column(name = "DMKHOABC_NHOM")
	public Short getDmkhoabcNhom() {
		return this.dmkhoabcNhom;
	}

	public void setDmkhoabcNhom(Short dmkhoabcNhom) {
		this.dmkhoabcNhom = dmkhoabcNhom;
	}

	@Column(name = "DMKHOABC_THUTUCBC", nullable = false)
	@NotNull
	public short getDmkhoabcThutucbc() {
		return this.dmkhoabcThutucbc;
	}

	public void setDmkhoabcThutucbc(short dmkhoabcThutucbc) {
		this.dmkhoabcThutucbc = dmkhoabcThutucbc;
	}

	@Column(name = "DMKHOABC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmkhoabcNgaygiocn() {
		return this.dmkhoabcNgaygiocn;
	}

	public void setDmkhoabcNgaygiocn(Double dmkhoabcNgaygiocn) {
		this.dmkhoabcNgaygiocn = dmkhoabcNgaygiocn;
	}

}
