package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmKhoa generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_KHOA", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMKHOA_MA"))
public class DmKhoa implements java.io.Serializable {

	private Integer dmkhoaMaso;
	private DmLoaiKhoa dmLoaiKhoa;
	private DmKhoaByt dmKhoaBytByDmkhoaMabyt3;
	private DmKhoaByt dmKhoaBytByDmkhoaMabyt;
	private DmNhomKhoa dmNhomKhoa;
	private DmKhoa dmKhoa;
	private String dmkhoaMa;
	private String dmkhoaCon;
	private String dmkhoaKyhieu;
	private String dmkhoaMakhoada;
	private String dmkhoaTen;
	private String dmkhoaTen2;
	private String dmkhoaTenbc;
	private Boolean dmkhoaCls;
	private String dmkhoaDienthoai;
	private Boolean dmkhoaNoitru;
	private Boolean dmkhoaKham;
	private Boolean dmkhoaNgoaitru;
	private Boolean dmkhoaKhamicd;
	private Boolean dmkhoaKhamcc;
	private Boolean dmkhoaSotret;
	private Boolean dmkhoaPhthuat;
	private Boolean dmkhoaNhappt;
	private Integer dmkhoaGiuongkh;
	private Integer dmkhoaGiuongtk;
	private Boolean dmkhoaYeucau;
	private Boolean dmkhoaCapmau;
	private Boolean dmkhoaDuoc;
	private Boolean dmkhoaThuphi;
	private Integer dmkhoaCum;
	private Double dmkhoaGiatran;
	private Boolean dmkhoaTienganh;
	private Integer dmkhoaThutu;
	private Boolean dmkhoaDvvesinh;
	private Double dmkhoaNgaygiocn;
	private Boolean dmkhoaQl;
	private Boolean dmkhoaDt;
	private Boolean dmkhoaDp;
	private String dmkhoaKho;
	private String dmkhoaTinhchat;
	private Byte dmkhoaDakhoa;
	private Set<DtDmBanKham> dtDmBanKhams = new HashSet<DtDmBanKham>(0);
	private Set<DtDmKho> dtDmKhos = new HashSet<DtDmKho>(0);
	private Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas = new HashSet<DtDmNhanvienKhoa>(
			0);
	private Set<DtDmPhongMo> dtDmPhongMos = new HashSet<DtDmPhongMo>(0);
	private Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1 = new HashSet<DtDmNhanvienKhoa>(
			0);
	private Set<DmKhoa> dmKhoas = new HashSet<DmKhoa>(0);
	private Set<DtDmKho> dtDmKhos_1 = new HashSet<DtDmKho>(0);
	private Set<DonMien> donMiens = new HashSet<DonMien>(0);
	private Set<DtDmClsKhoa> dtDmClsKhoas = new HashSet<DtDmClsKhoa>(0);
	private Set<DtDmBuong> dtDmBuongs = new HashSet<DtDmBuong>(0);
	private Set<DtDmKhach> dtDmKhachs = new HashSet<DtDmKhach>(0);
	private Set<DtDmKhach> dtDmKhachs_1 = new HashSet<DtDmKhach>(0);
	private Set<DmKhoa> dmKhoas_1 = new HashSet<DmKhoa>(0);
	private Set<DtDmPhongMo> dtDmPhongMos_1 = new HashSet<DtDmPhongMo>(0);

	public DmKhoa() {
	}

	public DmKhoa(String dmkhoaMa, String dmkhoaTen) {
		this.dmkhoaMa = dmkhoaMa;
		this.dmkhoaTen = dmkhoaTen;
	}

	public DmKhoa(DmLoaiKhoa dmLoaiKhoa, DmKhoaByt dmKhoaBytByDmkhoaMabyt3,
			DmKhoaByt dmKhoaBytByDmkhoaMabyt, DmNhomKhoa dmNhomKhoa,
			DmKhoa dmKhoa, String dmkhoaMa, String dmkhoaCon,
			String dmkhoaKyhieu, String dmkhoaMakhoada, String dmkhoaTen,
			String dmkhoaTen2, String dmkhoaTenbc, Boolean dmkhoaCls,
			String dmkhoaDienthoai, Boolean dmkhoaNoitru, Boolean dmkhoaKham,
			Boolean dmkhoaNgoaitru, Boolean dmkhoaKhamicd,
			Boolean dmkhoaKhamcc, Boolean dmkhoaSotret, Boolean dmkhoaPhthuat,
			Boolean dmkhoaNhappt, Integer dmkhoaGiuongkh,
			Integer dmkhoaGiuongtk, Boolean dmkhoaYeucau, Boolean dmkhoaCapmau,
			Boolean dmkhoaDuoc, Boolean dmkhoaThuphi, Integer dmkhoaCum,
			Double dmkhoaGiatran, Boolean dmkhoaTienganh, Integer dmkhoaThutu,
			Boolean dmkhoaDvvesinh, Double dmkhoaNgaygiocn, Boolean dmkhoaQl,
			Boolean dmkhoaDt, Boolean dmkhoaDp, String dmkhoaKho,
			String dmkhoaTinhchat, Byte dmkhoaDakhoa,
			Set<DtDmBanKham> dtDmBanKhams, Set<DtDmKho> dtDmKhos,
			Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas,
			Set<DtDmPhongMo> dtDmPhongMos,
			Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1, Set<DmKhoa> dmKhoas,
			Set<DtDmKho> dtDmKhos_1, Set<DonMien> donMiens,
			Set<DtDmClsKhoa> dtDmClsKhoas, Set<DtDmBuong> dtDmBuongs,
			Set<DtDmKhach> dtDmKhachs, Set<DtDmKhach> dtDmKhachs_1,
			Set<DmKhoa> dmKhoas_1, Set<DtDmPhongMo> dtDmPhongMos_1) {
		this.dmLoaiKhoa = dmLoaiKhoa;
		this.dmKhoaBytByDmkhoaMabyt3 = dmKhoaBytByDmkhoaMabyt3;
		this.dmKhoaBytByDmkhoaMabyt = dmKhoaBytByDmkhoaMabyt;
		this.dmNhomKhoa = dmNhomKhoa;
		this.dmKhoa = dmKhoa;
		this.dmkhoaMa = dmkhoaMa;
		this.dmkhoaCon = dmkhoaCon;
		this.dmkhoaKyhieu = dmkhoaKyhieu;
		this.dmkhoaMakhoada = dmkhoaMakhoada;
		this.dmkhoaTen = dmkhoaTen;
		this.dmkhoaTen2 = dmkhoaTen2;
		this.dmkhoaTenbc = dmkhoaTenbc;
		this.dmkhoaCls = dmkhoaCls;
		this.dmkhoaDienthoai = dmkhoaDienthoai;
		this.dmkhoaNoitru = dmkhoaNoitru;
		this.dmkhoaKham = dmkhoaKham;
		this.dmkhoaNgoaitru = dmkhoaNgoaitru;
		this.dmkhoaKhamicd = dmkhoaKhamicd;
		this.dmkhoaKhamcc = dmkhoaKhamcc;
		this.dmkhoaSotret = dmkhoaSotret;
		this.dmkhoaPhthuat = dmkhoaPhthuat;
		this.dmkhoaNhappt = dmkhoaNhappt;
		this.dmkhoaGiuongkh = dmkhoaGiuongkh;
		this.dmkhoaGiuongtk = dmkhoaGiuongtk;
		this.dmkhoaYeucau = dmkhoaYeucau;
		this.dmkhoaCapmau = dmkhoaCapmau;
		this.dmkhoaDuoc = dmkhoaDuoc;
		this.dmkhoaThuphi = dmkhoaThuphi;
		this.dmkhoaCum = dmkhoaCum;
		this.dmkhoaGiatran = dmkhoaGiatran;
		this.dmkhoaTienganh = dmkhoaTienganh;
		this.dmkhoaThutu = dmkhoaThutu;
		this.dmkhoaDvvesinh = dmkhoaDvvesinh;
		this.dmkhoaNgaygiocn = dmkhoaNgaygiocn;
		this.dmkhoaQl = dmkhoaQl;
		this.dmkhoaDt = dmkhoaDt;
		this.dmkhoaDp = dmkhoaDp;
		this.dmkhoaKho = dmkhoaKho;
		this.dmkhoaTinhchat = dmkhoaTinhchat;
		this.dmkhoaDakhoa = dmkhoaDakhoa;
		this.dtDmBanKhams = dtDmBanKhams;
		this.dtDmKhos = dtDmKhos;
		this.dtDmNhanvienKhoas = dtDmNhanvienKhoas;
		this.dtDmPhongMos = dtDmPhongMos;
		this.dtDmNhanvienKhoas_1 = dtDmNhanvienKhoas_1;
		this.dmKhoas = dmKhoas;
		this.dtDmKhos_1 = dtDmKhos_1;
		this.donMiens = donMiens;
		this.dtDmClsKhoas = dtDmClsKhoas;
		this.dtDmBuongs = dtDmBuongs;
		this.dtDmKhachs = dtDmKhachs;
		this.dtDmKhachs_1 = dtDmKhachs_1;
		this.dmKhoas_1 = dmKhoas_1;
		this.dtDmPhongMos_1 = dtDmPhongMos_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_KHOA")
	@SequenceGenerator(name = "DM_KHOA", sequenceName = "DM_KHOA_DMKHOA_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMKHOA_MASO", unique = true, nullable = false)
	public Integer getDmkhoaMaso() {
		return this.dmkhoaMaso;
	}

	public void setDmkhoaMaso(Integer dmkhoaMaso) {
		this.dmkhoaMaso = dmkhoaMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMLOAIKHOA_MA")
	public DmLoaiKhoa getDmLoaiKhoa() {
		return this.dmLoaiKhoa;
	}

	public void setDmLoaiKhoa(DmLoaiKhoa dmLoaiKhoa) {
		this.dmLoaiKhoa = dmLoaiKhoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MABYT3")
	public DmKhoaByt getDmKhoaBytByDmkhoaMabyt3() {
		return this.dmKhoaBytByDmkhoaMabyt3;
	}

	public void setDmKhoaBytByDmkhoaMabyt3(DmKhoaByt dmKhoaBytByDmkhoaMabyt3) {
		this.dmKhoaBytByDmkhoaMabyt3 = dmKhoaBytByDmkhoaMabyt3;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MABYT")
	public DmKhoaByt getDmKhoaBytByDmkhoaMabyt() {
		return this.dmKhoaBytByDmkhoaMabyt;
	}

	public void setDmKhoaBytByDmkhoaMabyt(DmKhoaByt dmKhoaBytByDmkhoaMabyt) {
		this.dmKhoaBytByDmkhoaMabyt = dmKhoaBytByDmkhoaMabyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNHOMKHOA_MASO")
	public DmNhomKhoa getDmNhomKhoa() {
		return this.dmNhomKhoa;
	}

	public void setDmNhomKhoa(DmNhomKhoa dmNhomKhoa) {
		this.dmNhomKhoa = dmNhomKhoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MAKHOAS")
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@Column(name = "DMKHOA_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmkhoaMa() {
		return this.dmkhoaMa;
	}

	public void setDmkhoaMa(String dmkhoaMa) {
		this.dmkhoaMa = dmkhoaMa;
	}

	@Column(name = "DMKHOA_CON", length = 3)
	@Length(max = 3)
	public String getDmkhoaCon() {
		return this.dmkhoaCon;
	}

	public void setDmkhoaCon(String dmkhoaCon) {
		this.dmkhoaCon = dmkhoaCon;
	}

	@Column(name = "DMKHOA_KYHIEU", length = 3)
	@Length(max = 3)
	public String getDmkhoaKyhieu() {
		return this.dmkhoaKyhieu;
	}

	public void setDmkhoaKyhieu(String dmkhoaKyhieu) {
		this.dmkhoaKyhieu = dmkhoaKyhieu;
	}

	@Column(name = "DMKHOA_MAKHOADA", length = 3)
	@Length(max = 3)
	public String getDmkhoaMakhoada() {
		return this.dmkhoaMakhoada;
	}

	public void setDmkhoaMakhoada(String dmkhoaMakhoada) {
		this.dmkhoaMakhoada = dmkhoaMakhoada;
	}

	@Column(name = "DMKHOA_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDmkhoaTen() {
		return this.dmkhoaTen;
	}

	public void setDmkhoaTen(String dmkhoaTen) {
		this.dmkhoaTen = dmkhoaTen;
	}

	@Column(name = "DMKHOA_TEN2", length = 50)
	@Length(max = 50)
	public String getDmkhoaTen2() {
		return this.dmkhoaTen2;
	}

	public void setDmkhoaTen2(String dmkhoaTen2) {
		this.dmkhoaTen2 = dmkhoaTen2;
	}

	@Column(name = "DMKHOA_TENBC", length = 50)
	@Length(max = 50)
	public String getDmkhoaTenbc() {
		return this.dmkhoaTenbc;
	}

	public void setDmkhoaTenbc(String dmkhoaTenbc) {
		this.dmkhoaTenbc = dmkhoaTenbc;
	}

	@Column(name = "DMKHOA_CLS")
	public Boolean getDmkhoaCls() {
		return this.dmkhoaCls;
	}

	public void setDmkhoaCls(Boolean dmkhoaCls) {
		this.dmkhoaCls = dmkhoaCls;
	}

	@Column(name = "DMKHOA_DIENTHOAI", length = 12)
	@Length(max = 12)
	public String getDmkhoaDienthoai() {
		return this.dmkhoaDienthoai;
	}

	public void setDmkhoaDienthoai(String dmkhoaDienthoai) {
		this.dmkhoaDienthoai = dmkhoaDienthoai;
	}

	@Column(name = "DMKHOA_NOITRU")
	public Boolean getDmkhoaNoitru() {
		return this.dmkhoaNoitru;
	}

	public void setDmkhoaNoitru(Boolean dmkhoaNoitru) {
		this.dmkhoaNoitru = dmkhoaNoitru;
	}

	@Column(name = "DMKHOA_KHAM")
	public Boolean getDmkhoaKham() {
		return this.dmkhoaKham;
	}

	public void setDmkhoaKham(Boolean dmkhoaKham) {
		this.dmkhoaKham = dmkhoaKham;
	}

	@Column(name = "DMKHOA_NGOAITRU")
	public Boolean getDmkhoaNgoaitru() {
		return this.dmkhoaNgoaitru;
	}

	public void setDmkhoaNgoaitru(Boolean dmkhoaNgoaitru) {
		this.dmkhoaNgoaitru = dmkhoaNgoaitru;
	}

	@Column(name = "DMKHOA_KHAMICD")
	public Boolean getDmkhoaKhamicd() {
		return this.dmkhoaKhamicd;
	}

	public void setDmkhoaKhamicd(Boolean dmkhoaKhamicd) {
		this.dmkhoaKhamicd = dmkhoaKhamicd;
	}

	@Column(name = "DMKHOA_KHAMCC")
	public Boolean getDmkhoaKhamcc() {
		return this.dmkhoaKhamcc;
	}

	public void setDmkhoaKhamcc(Boolean dmkhoaKhamcc) {
		this.dmkhoaKhamcc = dmkhoaKhamcc;
	}

	@Column(name = "DMKHOA_SOTRET")
	public Boolean getDmkhoaSotret() {
		return this.dmkhoaSotret;
	}

	public void setDmkhoaSotret(Boolean dmkhoaSotret) {
		this.dmkhoaSotret = dmkhoaSotret;
	}

	@Column(name = "DMKHOA_PHTHUAT")
	public Boolean getDmkhoaPhthuat() {
		return this.dmkhoaPhthuat;
	}

	public void setDmkhoaPhthuat(Boolean dmkhoaPhthuat) {
		this.dmkhoaPhthuat = dmkhoaPhthuat;
	}

	@Column(name = "DMKHOA_NHAPPT")
	public Boolean getDmkhoaNhappt() {
		return this.dmkhoaNhappt;
	}

	public void setDmkhoaNhappt(Boolean dmkhoaNhappt) {
		this.dmkhoaNhappt = dmkhoaNhappt;
	}

	@Column(name = "DMKHOA_GIUONGKH")
	public Integer getDmkhoaGiuongkh() {
		return this.dmkhoaGiuongkh;
	}

	public void setDmkhoaGiuongkh(Integer dmkhoaGiuongkh) {
		this.dmkhoaGiuongkh = dmkhoaGiuongkh;
	}

	@Column(name = "DMKHOA_GIUONGTK")
	public Integer getDmkhoaGiuongtk() {
		return this.dmkhoaGiuongtk;
	}

	public void setDmkhoaGiuongtk(Integer dmkhoaGiuongtk) {
		this.dmkhoaGiuongtk = dmkhoaGiuongtk;
	}

	@Column(name = "DMKHOA_YEUCAU")
	public Boolean getDmkhoaYeucau() {
		return this.dmkhoaYeucau;
	}

	public void setDmkhoaYeucau(Boolean dmkhoaYeucau) {
		this.dmkhoaYeucau = dmkhoaYeucau;
	}

	@Column(name = "DMKHOA_CAPMAU")
	public Boolean getDmkhoaCapmau() {
		return this.dmkhoaCapmau;
	}

	public void setDmkhoaCapmau(Boolean dmkhoaCapmau) {
		this.dmkhoaCapmau = dmkhoaCapmau;
	}

	@Column(name = "DMKHOA_DUOC")
	public Boolean getDmkhoaDuoc() {
		return this.dmkhoaDuoc;
	}

	public void setDmkhoaDuoc(Boolean dmkhoaDuoc) {
		this.dmkhoaDuoc = dmkhoaDuoc;
	}

	@Column(name = "DMKHOA_THUPHI")
	public Boolean getDmkhoaThuphi() {
		return this.dmkhoaThuphi;
	}

	public void setDmkhoaThuphi(Boolean dmkhoaThuphi) {
		this.dmkhoaThuphi = dmkhoaThuphi;
	}

	@Column(name = "DMKHOA_CUM")
	public Integer getDmkhoaCum() {
		return this.dmkhoaCum;
	}

	public void setDmkhoaCum(Integer dmkhoaCum) {
		this.dmkhoaCum = dmkhoaCum;
	}

	@Column(name = "DMKHOA_GIATRAN", precision = 22, scale = 0)
	public Double getDmkhoaGiatran() {
		return this.dmkhoaGiatran;
	}

	public void setDmkhoaGiatran(Double dmkhoaGiatran) {
		this.dmkhoaGiatran = dmkhoaGiatran;
	}

	@Column(name = "DMKHOA_TIENGANH")
	public Boolean getDmkhoaTienganh() {
		return this.dmkhoaTienganh;
	}

	public void setDmkhoaTienganh(Boolean dmkhoaTienganh) {
		this.dmkhoaTienganh = dmkhoaTienganh;
	}

	@Column(name = "DMKHOA_THUTU")
	public Integer getDmkhoaThutu() {
		return this.dmkhoaThutu;
	}

	public void setDmkhoaThutu(Integer dmkhoaThutu) {
		this.dmkhoaThutu = dmkhoaThutu;
	}

	@Column(name = "DMKHOA_DVVESINH")
	public Boolean getDmkhoaDvvesinh() {
		return this.dmkhoaDvvesinh;
	}

	public void setDmkhoaDvvesinh(Boolean dmkhoaDvvesinh) {
		this.dmkhoaDvvesinh = dmkhoaDvvesinh;
	}

	@Column(name = "DMKHOA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmkhoaNgaygiocn() {
		return this.dmkhoaNgaygiocn;
	}

	public void setDmkhoaNgaygiocn(Double dmkhoaNgaygiocn) {
		this.dmkhoaNgaygiocn = dmkhoaNgaygiocn;
	}

	@Column(name = "DMKHOA_QL")
	public Boolean getDmkhoaQl() {
		return this.dmkhoaQl;
	}

	public void setDmkhoaQl(Boolean dmkhoaQl) {
		this.dmkhoaQl = dmkhoaQl;
	}

	@Column(name = "DMKHOA_DT")
	public Boolean getDmkhoaDt() {
		return this.dmkhoaDt;
	}

	public void setDmkhoaDt(Boolean dmkhoaDt) {
		this.dmkhoaDt = dmkhoaDt;
	}

	@Column(name = "DMKHOA_DP")
	public Boolean getDmkhoaDp() {
		return this.dmkhoaDp;
	}

	public void setDmkhoaDp(Boolean dmkhoaDp) {
		this.dmkhoaDp = dmkhoaDp;
	}

	@Column(name = "DMKHOA_KHO", length = 45)
	@Length(max = 45)
	public String getDmkhoaKho() {
		return this.dmkhoaKho;
	}

	public void setDmkhoaKho(String dmkhoaKho) {
		this.dmkhoaKho = dmkhoaKho;
	}

	@Column(name = "DMKHOA_TINHCHAT")
	public String getDmkhoaTinhchat() {
		return this.dmkhoaTinhchat;
	}

	public void setDmkhoaTinhchat(String dmkhoaTinhchat) {
		this.dmkhoaTinhchat = dmkhoaTinhchat;
	}

	@Column(name = "DMKHOA_DAKHOA")
	public Byte getDmkhoaDakhoa() {
		return this.dmkhoaDakhoa;
	}

	public void setDmkhoaDakhoa(Byte dmkhoaDakhoa) {
		this.dmkhoaDakhoa = dmkhoaDakhoa;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmBanKham> getDtDmBanKhams() {
		return this.dtDmBanKhams;
	}

	public void setDtDmBanKhams(Set<DtDmBanKham> dtDmBanKhams) {
		this.dtDmBanKhams = dtDmBanKhams;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmKho> getDtDmKhos() {
		return this.dtDmKhos;
	}

	public void setDtDmKhos(Set<DtDmKho> dtDmKhos) {
		this.dtDmKhos = dtDmKhos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmNhanvienKhoa> getDtDmNhanvienKhoas() {
		return this.dtDmNhanvienKhoas;
	}

	public void setDtDmNhanvienKhoas(Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas) {
		this.dtDmNhanvienKhoas = dtDmNhanvienKhoas;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmPhongMo> getDtDmPhongMos() {
		return this.dtDmPhongMos;
	}

	public void setDtDmPhongMos(Set<DtDmPhongMo> dtDmPhongMos) {
		this.dtDmPhongMos = dtDmPhongMos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmNhanvienKhoa> getDtDmNhanvienKhoas_1() {
		return this.dtDmNhanvienKhoas_1;
	}

	public void setDtDmNhanvienKhoas_1(Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1) {
		this.dtDmNhanvienKhoas_1 = dtDmNhanvienKhoas_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DmKhoa> getDmKhoas() {
		return this.dmKhoas;
	}

	public void setDmKhoas(Set<DmKhoa> dmKhoas) {
		this.dmKhoas = dmKhoas;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmKho> getDtDmKhos_1() {
		return this.dtDmKhos_1;
	}

	public void setDtDmKhos_1(Set<DtDmKho> dtDmKhos_1) {
		this.dtDmKhos_1 = dtDmKhos_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DonMien> getDonMiens() {
		return this.donMiens;
	}

	public void setDonMiens(Set<DonMien> donMiens) {
		this.donMiens = donMiens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmClsKhoa> getDtDmClsKhoas() {
		return this.dtDmClsKhoas;
	}

	public void setDtDmClsKhoas(Set<DtDmClsKhoa> dtDmClsKhoas) {
		this.dtDmClsKhoas = dtDmClsKhoas;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmBuong> getDtDmBuongs() {
		return this.dtDmBuongs;
	}

	public void setDtDmBuongs(Set<DtDmBuong> dtDmBuongs) {
		this.dtDmBuongs = dtDmBuongs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmKhach> getDtDmKhachs() {
		return this.dtDmKhachs;
	}

	public void setDtDmKhachs(Set<DtDmKhach> dtDmKhachs) {
		this.dtDmKhachs = dtDmKhachs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmKhach> getDtDmKhachs_1() {
		return this.dtDmKhachs_1;
	}

	public void setDtDmKhachs_1(Set<DtDmKhach> dtDmKhachs_1) {
		this.dtDmKhachs_1 = dtDmKhachs_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DmKhoa> getDmKhoas_1() {
		return this.dmKhoas_1;
	}

	public void setDmKhoas_1(Set<DmKhoa> dmKhoas_1) {
		this.dmKhoas_1 = dmKhoas_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoa")
	public Set<DtDmPhongMo> getDtDmPhongMos_1() {
		return this.dtDmPhongMos_1;
	}

	public void setDtDmPhongMos_1(Set<DtDmPhongMo> dtDmPhongMos_1) {
		this.dtDmPhongMos_1 = dtDmPhongMos_1;
	}

}
