package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmKhoaByt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_KHOA_BYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMKHOABYT_MA"))
public class DmKhoaByt implements java.io.Serializable {

	private Integer dmkhoabytMaso;
	private String dmkhoabytMa;
	private String dmkhoabytMabyt3;
	private String dmkhoabytTen;
	private Integer dmkhoabytNhom;
	private Integer dmkhoabytThutubc;
	private Double dmkhoabytNgaygiocn;
	private Boolean dmkhoabytDt;
	private Boolean dmkhoabytQl;
	private Boolean dmkhoabytDp;
	private Set<DmKhoa> dmKhoasForDmkhoaMabyt = new HashSet<DmKhoa>(0);
	private Set<DmKhoa> dmKhoasForDmkhoaMabyt3 = new HashSet<DmKhoa>(0);

	public DmKhoaByt() {
	}

	public DmKhoaByt(String dmkhoabytMa, String dmkhoabytTen) {
		this.dmkhoabytMa = dmkhoabytMa;
		this.dmkhoabytTen = dmkhoabytTen;
	}

	public DmKhoaByt(String dmkhoabytMa, String dmkhoabytMabyt3,
			String dmkhoabytTen, Integer dmkhoabytNhom,
			Integer dmkhoabytThutubc, Double dmkhoabytNgaygiocn,
			Boolean dmkhoabytDt, Boolean dmkhoabytQl, Boolean dmkhoabytDp,
			Set<DmKhoa> dmKhoasForDmkhoaMabyt,
			Set<DmKhoa> dmKhoasForDmkhoaMabyt3) {
		this.dmkhoabytMa = dmkhoabytMa;
		this.dmkhoabytMabyt3 = dmkhoabytMabyt3;
		this.dmkhoabytTen = dmkhoabytTen;
		this.dmkhoabytNhom = dmkhoabytNhom;
		this.dmkhoabytThutubc = dmkhoabytThutubc;
		this.dmkhoabytNgaygiocn = dmkhoabytNgaygiocn;
		this.dmkhoabytDt = dmkhoabytDt;
		this.dmkhoabytQl = dmkhoabytQl;
		this.dmkhoabytDp = dmkhoabytDp;
		this.dmKhoasForDmkhoaMabyt = dmKhoasForDmkhoaMabyt;
		this.dmKhoasForDmkhoaMabyt3 = dmKhoasForDmkhoaMabyt3;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_KHOA_BYT")
	@SequenceGenerator(name = "DM_KHOA_BYT", sequenceName = "DM_KHOA_BYT_DMKHOABYT_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMKHOABYT_MASO", unique = true, nullable = false)
	public Integer getDmkhoabytMaso() {
		return this.dmkhoabytMaso;
	}

	public void setDmkhoabytMaso(Integer dmkhoabytMaso) {
		this.dmkhoabytMaso = dmkhoabytMaso;
	}

	@Column(name = "DMKHOABYT_MA", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDmkhoabytMa() {
		return this.dmkhoabytMa;
	}

	public void setDmkhoabytMa(String dmkhoabytMa) {
		this.dmkhoabytMa = dmkhoabytMa;
	}

	@Column(name = "DMKHOABYT_MABYT3", length = 15)
	@Length(max = 15)
	public String getDmkhoabytMabyt3() {
		return this.dmkhoabytMabyt3;
	}

	public void setDmkhoabytMabyt3(String dmkhoabytMabyt3) {
		this.dmkhoabytMabyt3 = dmkhoabytMabyt3;
	}

	@Column(name = "DMKHOABYT_TEN", nullable = false, length = 512)
	@NotNull
	@Length(max = 512)
	public String getDmkhoabytTen() {
		return this.dmkhoabytTen;
	}

	public void setDmkhoabytTen(String dmkhoabytTen) {
		this.dmkhoabytTen = dmkhoabytTen;
	}

	@Column(name = "DMKHOABYT_NHOM")
	public Integer getDmkhoabytNhom() {
		return this.dmkhoabytNhom;
	}

	public void setDmkhoabytNhom(Integer dmkhoabytNhom) {
		this.dmkhoabytNhom = dmkhoabytNhom;
	}

	@Column(name = "DMKHOABYT_THUTUBC")
	public Integer getDmkhoabytThutubc() {
		return this.dmkhoabytThutubc;
	}

	public void setDmkhoabytThutubc(Integer dmkhoabytThutubc) {
		this.dmkhoabytThutubc = dmkhoabytThutubc;
	}

	@Column(name = "DMKHOABYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmkhoabytNgaygiocn() {
		return this.dmkhoabytNgaygiocn;
	}

	public void setDmkhoabytNgaygiocn(Double dmkhoabytNgaygiocn) {
		this.dmkhoabytNgaygiocn = dmkhoabytNgaygiocn;
	}

	@Column(name = "DMKHOABYT_DT")
	public Boolean getDmkhoabytDt() {
		return this.dmkhoabytDt;
	}

	public void setDmkhoabytDt(Boolean dmkhoabytDt) {
		this.dmkhoabytDt = dmkhoabytDt;
	}

	@Column(name = "DMKHOABYT_QL")
	public Boolean getDmkhoabytQl() {
		return this.dmkhoabytQl;
	}

	public void setDmkhoabytQl(Boolean dmkhoabytQl) {
		this.dmkhoabytQl = dmkhoabytQl;
	}

	@Column(name = "DMKHOABYT_DP")
	public Boolean getDmkhoabytDp() {
		return this.dmkhoabytDp;
	}

	public void setDmkhoabytDp(Boolean dmkhoabytDp) {
		this.dmkhoabytDp = dmkhoabytDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoaBytByDmkhoaMabyt")
	public Set<DmKhoa> getDmKhoasForDmkhoaMabyt() {
		return this.dmKhoasForDmkhoaMabyt;
	}

	public void setDmKhoasForDmkhoaMabyt(Set<DmKhoa> dmKhoasForDmkhoaMabyt) {
		this.dmKhoasForDmkhoaMabyt = dmKhoasForDmkhoaMabyt;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmKhoaBytByDmkhoaMabyt3")
	public Set<DmKhoa> getDmKhoasForDmkhoaMabyt3() {
		return this.dmKhoasForDmkhoaMabyt3;
	}

	public void setDmKhoasForDmkhoaMabyt3(Set<DmKhoa> dmKhoasForDmkhoaMabyt3) {
		this.dmKhoasForDmkhoaMabyt3 = dmKhoasForDmkhoaMabyt3;
	}

}
