package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmLoaiThietBi generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_LOAI_THIET_BI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMLOAITHIETBI_MA"))
public class DmLoaiThietBi implements java.io.Serializable {

	private Integer dmloaithietbiMaso;
	private String dmloaithietbiMa;
	private String dmloaithietbiTen;
	private Double dmloaithietbiNgaygiocn;
	private Boolean dmloaithietbiDt;
	private Boolean dmloaithietbiQl;
	private Boolean dmloaithietbiDp;

	public DmLoaiThietBi() {
	}

	public DmLoaiThietBi(String dmloaithietbiTen) {
		this.dmloaithietbiTen = dmloaithietbiTen;
	}

	public DmLoaiThietBi(String dmloaithietbiMa, String dmloaithietbiTen,
			Double dmloaithietbiNgaygiocn, Boolean dmloaithietbiDt,
			Boolean dmloaithietbiQl, Boolean dmloaithietbiDp) {
		this.dmloaithietbiMa = dmloaithietbiMa;
		this.dmloaithietbiTen = dmloaithietbiTen;
		this.dmloaithietbiNgaygiocn = dmloaithietbiNgaygiocn;
		this.dmloaithietbiDt = dmloaithietbiDt;
		this.dmloaithietbiQl = dmloaithietbiQl;
		this.dmloaithietbiDp = dmloaithietbiDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_LOAI_THIET_BI")
	@SequenceGenerator(name = "DM_LOAI_THIET_BI", sequenceName = "DM_LOAI_THIET_BI_DMLOAITHIETBI", allocationSize = 1)
	@Column(name = "DMLOAITHIETBI_MASO", unique = true, nullable = false)
	public Integer getDmloaithietbiMaso() {
		return this.dmloaithietbiMaso;
	}

	public void setDmloaithietbiMaso(Integer dmloaithietbiMaso) {
		this.dmloaithietbiMaso = dmloaithietbiMaso;
	}

	@Column(name = "DMLOAITHIETBI_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmloaithietbiMa() {
		return this.dmloaithietbiMa;
	}

	public void setDmloaithietbiMa(String dmloaithietbiMa) {
		this.dmloaithietbiMa = dmloaithietbiMa;
	}

	@Column(name = "DMLOAITHIETBI_TEN", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDmloaithietbiTen() {
		return this.dmloaithietbiTen;
	}

	public void setDmloaithietbiTen(String dmloaithietbiTen) {
		this.dmloaithietbiTen = dmloaithietbiTen;
	}

	@Column(name = "DMLOAITHIETBI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmloaithietbiNgaygiocn() {
		return this.dmloaithietbiNgaygiocn;
	}

	public void setDmloaithietbiNgaygiocn(Double dmloaithietbiNgaygiocn) {
		this.dmloaithietbiNgaygiocn = dmloaithietbiNgaygiocn;
	}

	@Column(name = "DMLOAITHIETBI_DT")
	public Boolean getDmloaithietbiDt() {
		return this.dmloaithietbiDt;
	}

	public void setDmloaithietbiDt(Boolean dmloaithietbiDt) {
		this.dmloaithietbiDt = dmloaithietbiDt;
	}

	@Column(name = "DMLOAITHIETBI_QL")
	public Boolean getDmloaithietbiQl() {
		return this.dmloaithietbiQl;
	}

	public void setDmloaithietbiQl(Boolean dmloaithietbiQl) {
		this.dmloaithietbiQl = dmloaithietbiQl;
	}

	@Column(name = "DMLOAITHIETBI_DP")
	public Boolean getDmloaithietbiDp() {
		return this.dmloaithietbiDp;
	}

	public void setDmloaithietbiDp(Boolean dmloaithietbiDp) {
		this.dmloaithietbiDp = dmloaithietbiDp;
	}

}
