package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmLoaiSinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_LOAI_SINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMLOAISINH_MA"))
public class DmLoaiSinh implements java.io.Serializable {

	private Integer dmloaisinhMaso;
	private String dmloaisinhMa;
	private String dmloaisinhTen;
	private Double dmloaisinhNgaygiocn;
	private Boolean dmloaisinhDt;
	private Boolean dmloaisinhQl;
	private Boolean dmloaisinhDp;

	public DmLoaiSinh() {
	}

	public DmLoaiSinh(String dmloaisinhMa, String dmloaisinhTen) {
		this.dmloaisinhMa = dmloaisinhMa;
		this.dmloaisinhTen = dmloaisinhTen;
	}

	public DmLoaiSinh(String dmloaisinhMa, String dmloaisinhTen,
			Double dmloaisinhNgaygiocn, Boolean dmloaisinhDt,
			Boolean dmloaisinhQl, Boolean dmloaisinhDp) {
		this.dmloaisinhMa = dmloaisinhMa;
		this.dmloaisinhTen = dmloaisinhTen;
		this.dmloaisinhNgaygiocn = dmloaisinhNgaygiocn;
		this.dmloaisinhDt = dmloaisinhDt;
		this.dmloaisinhQl = dmloaisinhQl;
		this.dmloaisinhDp = dmloaisinhDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_LOAI_SINH")
	@SequenceGenerator(name = "DM_LOAI_SINH", sequenceName = "DM_LOAI_SINH_DMLOAISINH_MASO_S", allocationSize = 1)
	@Column(name = "DMLOAISINH_MASO", unique = true, nullable = false)
	public Integer getDmloaisinhMaso() {
		return this.dmloaisinhMaso;
	}

	public void setDmloaisinhMaso(Integer dmloaisinhMaso) {
		this.dmloaisinhMaso = dmloaisinhMaso;
	}

	@Column(name = "DMLOAISINH_MA", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getDmloaisinhMa() {
		return this.dmloaisinhMa;
	}

	public void setDmloaisinhMa(String dmloaisinhMa) {
		this.dmloaisinhMa = dmloaisinhMa;
	}

	@Column(name = "DMLOAISINH_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmloaisinhTen() {
		return this.dmloaisinhTen;
	}

	public void setDmloaisinhTen(String dmloaisinhTen) {
		this.dmloaisinhTen = dmloaisinhTen;
	}

	@Column(name = "DMLOAISINH_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmloaisinhNgaygiocn() {
		return this.dmloaisinhNgaygiocn;
	}

	public void setDmloaisinhNgaygiocn(Double dmloaisinhNgaygiocn) {
		this.dmloaisinhNgaygiocn = dmloaisinhNgaygiocn;
	}

	@Column(name = "DMLOAISINH_DT")
	public Boolean getDmloaisinhDt() {
		return this.dmloaisinhDt;
	}

	public void setDmloaisinhDt(Boolean dmloaisinhDt) {
		this.dmloaisinhDt = dmloaisinhDt;
	}

	@Column(name = "DMLOAISINH_QL")
	public Boolean getDmloaisinhQl() {
		return this.dmloaisinhQl;
	}

	public void setDmloaisinhQl(Boolean dmloaisinhQl) {
		this.dmloaisinhQl = dmloaisinhQl;
	}

	@Column(name = "DMLOAISINH_DP")
	public Boolean getDmloaisinhDp() {
		return this.dmloaisinhDp;
	}

	public void setDmloaisinhDp(Boolean dmloaisinhDp) {
		this.dmloaisinhDp = dmloaisinhDp;
	}

}
