package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmLoaiThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_LOAI_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMLOAITHUOC_MA"))
public class DmLoaiThuoc implements java.io.Serializable {

	private Integer dmloaithuocMaso;
	private String dmloaithuocMa;
	private String dmloaithuocTen;
	private String dmloaithuocQuyen;
	private Double dmloaithuocNgaygiocn;
	private Boolean dmloaithuocDt;
	private Boolean dmloaithuocQl;
	private Boolean dmloaithuocDp;
	private Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs = new HashSet<DmNhomBaoCaoLoaiThuoc>(
			0);
	private Set<DmPhanLoaiThuoc> dmPhanLoaiThuocs = new HashSet<DmPhanLoaiThuoc>(
			0);
	private Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1 = new HashSet<DmNhomBaoCaoLoaiThuoc>(
			0);

	public DmLoaiThuoc() {
	}

	public DmLoaiThuoc(String dmloaithuocMa, String dmloaithuocTen) {
		this.dmloaithuocMa = dmloaithuocMa;
		this.dmloaithuocTen = dmloaithuocTen;
	}

	public DmLoaiThuoc(String dmloaithuocMa, String dmloaithuocTen,
			String dmloaithuocQuyen, Double dmloaithuocNgaygiocn,
			Boolean dmloaithuocDt, Boolean dmloaithuocQl,
			Boolean dmloaithuocDp,
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs,
			Set<DmPhanLoaiThuoc> dmPhanLoaiThuocs,
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1) {
		this.dmloaithuocMa = dmloaithuocMa;
		this.dmloaithuocTen = dmloaithuocTen;
		this.dmloaithuocQuyen = dmloaithuocQuyen;
		this.dmloaithuocNgaygiocn = dmloaithuocNgaygiocn;
		this.dmloaithuocDt = dmloaithuocDt;
		this.dmloaithuocQl = dmloaithuocQl;
		this.dmloaithuocDp = dmloaithuocDp;
		this.dmNhomBaoCaoLoaiThuocs = dmNhomBaoCaoLoaiThuocs;
		this.dmPhanLoaiThuocs = dmPhanLoaiThuocs;
		this.dmNhomBaoCaoLoaiThuocs_1 = dmNhomBaoCaoLoaiThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_LOAI_THUOC")
	@SequenceGenerator(name = "DM_LOAI_THUOC", sequenceName = "DM_LOAI_THUOC_DMLOAITHUOC_MASO", allocationSize = 1)
	@Column(name = "DMLOAITHUOC_MASO", unique = true, nullable = false)
	public Integer getDmloaithuocMaso() {
		return this.dmloaithuocMaso;
	}

	public void setDmloaithuocMaso(Integer dmloaithuocMaso) {
		this.dmloaithuocMaso = dmloaithuocMaso;
	}

	@Column(name = "DMLOAITHUOC_MA", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDmloaithuocMa() {
		return this.dmloaithuocMa;
	}

	public void setDmloaithuocMa(String dmloaithuocMa) {
		this.dmloaithuocMa = dmloaithuocMa;
	}

	@Column(name = "DMLOAITHUOC_TEN", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDmloaithuocTen() {
		return this.dmloaithuocTen;
	}

	public void setDmloaithuocTen(String dmloaithuocTen) {
		this.dmloaithuocTen = dmloaithuocTen;
	}

	@Column(name = "DMLOAITHUOC_QUYEN", length = 3)
	@Length(max = 3)
	public String getDmloaithuocQuyen() {
		return this.dmloaithuocQuyen;
	}

	public void setDmloaithuocQuyen(String dmloaithuocQuyen) {
		this.dmloaithuocQuyen = dmloaithuocQuyen;
	}

	@Column(name = "DMLOAITHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmloaithuocNgaygiocn() {
		return this.dmloaithuocNgaygiocn;
	}

	public void setDmloaithuocNgaygiocn(Double dmloaithuocNgaygiocn) {
		this.dmloaithuocNgaygiocn = dmloaithuocNgaygiocn;
	}

	@Column(name = "DMLOAITHUOC_DT")
	public Boolean getDmloaithuocDt() {
		return this.dmloaithuocDt;
	}

	public void setDmloaithuocDt(Boolean dmloaithuocDt) {
		this.dmloaithuocDt = dmloaithuocDt;
	}

	@Column(name = "DMLOAITHUOC_QL")
	public Boolean getDmloaithuocQl() {
		return this.dmloaithuocQl;
	}

	public void setDmloaithuocQl(Boolean dmloaithuocQl) {
		this.dmloaithuocQl = dmloaithuocQl;
	}

	@Column(name = "DMLOAITHUOC_DP")
	public Boolean getDmloaithuocDp() {
		return this.dmloaithuocDp;
	}

	public void setDmloaithuocDp(Boolean dmloaithuocDp) {
		this.dmloaithuocDp = dmloaithuocDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmLoaiThuoc")
	public Set<DmNhomBaoCaoLoaiThuoc> getDmNhomBaoCaoLoaiThuocs() {
		return this.dmNhomBaoCaoLoaiThuocs;
	}

	public void setDmNhomBaoCaoLoaiThuocs(
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs) {
		this.dmNhomBaoCaoLoaiThuocs = dmNhomBaoCaoLoaiThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmLoaiThuoc")
	public Set<DmPhanLoaiThuoc> getDmPhanLoaiThuocs() {
		return this.dmPhanLoaiThuocs;
	}

	public void setDmPhanLoaiThuocs(Set<DmPhanLoaiThuoc> dmPhanLoaiThuocs) {
		this.dmPhanLoaiThuocs = dmPhanLoaiThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmLoaiThuoc")
	public Set<DmNhomBaoCaoLoaiThuoc> getDmNhomBaoCaoLoaiThuocs_1() {
		return this.dmNhomBaoCaoLoaiThuocs_1;
	}

	public void setDmNhomBaoCaoLoaiThuocs_1(
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1) {
		this.dmNhomBaoCaoLoaiThuocs_1 = dmNhomBaoCaoLoaiThuocs_1;
	}

}
