package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmLoaiNguonChuongTrinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_LOAI_NGUON_CHUONG_TRINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMLNCT_MA"))
public class DmLoaiNguonChuongTrinh implements java.io.Serializable {

	private Integer dmlnctMaso;
	private String dmlnctMa;
	private String dmlnctTen;
	private String dmlnctGhichu;
	private Boolean dmlnctDt;
	private Boolean dmlnctQl;
	private Boolean dmlnctDp;
	private Double dmlnctNgaygiocn;
	private Set<DmNguonChuongTrinh> dmNguonChuongTrinhs = new HashSet<DmNguonChuongTrinh>(
			0);
	private Set<DmNguonChuongTrinh> dmNguonChuongTrinhs_1 = new HashSet<DmNguonChuongTrinh>(
			0);

	public DmLoaiNguonChuongTrinh() {
	}

	public DmLoaiNguonChuongTrinh(String dmlnctMa) {
		this.dmlnctMa = dmlnctMa;
	}

	public DmLoaiNguonChuongTrinh(String dmlnctMa, String dmlnctTen,
			String dmlnctGhichu, Boolean dmlnctDt, Boolean dmlnctQl,
			Boolean dmlnctDp, Double dmlnctNgaygiocn,
			Set<DmNguonChuongTrinh> dmNguonChuongTrinhs,
			Set<DmNguonChuongTrinh> dmNguonChuongTrinhs_1) {
		this.dmlnctMa = dmlnctMa;
		this.dmlnctTen = dmlnctTen;
		this.dmlnctGhichu = dmlnctGhichu;
		this.dmlnctDt = dmlnctDt;
		this.dmlnctQl = dmlnctQl;
		this.dmlnctDp = dmlnctDp;
		this.dmlnctNgaygiocn = dmlnctNgaygiocn;
		this.dmNguonChuongTrinhs = dmNguonChuongTrinhs;
		this.dmNguonChuongTrinhs_1 = dmNguonChuongTrinhs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_LOAI_NGUON_CHUONG_TRINH")
	@SequenceGenerator(name = "DM_LOAI_NGUON_CHUONG_TRINH", sequenceName = "DM_LOAI_NGUON_CHUONG_TRINH_DML", allocationSize = 1)
	@Column(name = "DMLNCT_MASO", unique = true, nullable = false)
	public Integer getDmlnctMaso() {
		return this.dmlnctMaso;
	}

	public void setDmlnctMaso(Integer dmlnctMaso) {
		this.dmlnctMaso = dmlnctMaso;
	}

	@Column(name = "DMLNCT_MA", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDmlnctMa() {
		return this.dmlnctMa;
	}

	public void setDmlnctMa(String dmlnctMa) {
		this.dmlnctMa = dmlnctMa;
	}

	@Column(name = "DMLNCT_TEN", length = 100)
	@Length(max = 100)
	public String getDmlnctTen() {
		return this.dmlnctTen;
	}

	public void setDmlnctTen(String dmlnctTen) {
		this.dmlnctTen = dmlnctTen;
	}

	@Column(name = "DMLNCT_GHICHU", length = 100)
	@Length(max = 100)
	public String getDmlnctGhichu() {
		return this.dmlnctGhichu;
	}

	public void setDmlnctGhichu(String dmlnctGhichu) {
		this.dmlnctGhichu = dmlnctGhichu;
	}

	@Column(name = "DMLNCT_DT")
	public Boolean getDmlnctDt() {
		return this.dmlnctDt;
	}

	public void setDmlnctDt(Boolean dmlnctDt) {
		this.dmlnctDt = dmlnctDt;
	}

	@Column(name = "DMLNCT_QL")
	public Boolean getDmlnctQl() {
		return this.dmlnctQl;
	}

	public void setDmlnctQl(Boolean dmlnctQl) {
		this.dmlnctQl = dmlnctQl;
	}

	@Column(name = "DMLNCT_DP")
	public Boolean getDmlnctDp() {
		return this.dmlnctDp;
	}

	public void setDmlnctDp(Boolean dmlnctDp) {
		this.dmlnctDp = dmlnctDp;
	}

	@Column(name = "DMLNCT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmlnctNgaygiocn() {
		return this.dmlnctNgaygiocn;
	}

	public void setDmlnctNgaygiocn(Double dmlnctNgaygiocn) {
		this.dmlnctNgaygiocn = dmlnctNgaygiocn;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmLoaiNguonChuongTrinh")
	public Set<DmNguonChuongTrinh> getDmNguonChuongTrinhs() {
		return this.dmNguonChuongTrinhs;
	}

	public void setDmNguonChuongTrinhs(
			Set<DmNguonChuongTrinh> dmNguonChuongTrinhs) {
		this.dmNguonChuongTrinhs = dmNguonChuongTrinhs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmLoaiNguonChuongTrinh")
	public Set<DmNguonChuongTrinh> getDmNguonChuongTrinhs_1() {
		return this.dmNguonChuongTrinhs_1;
	}

	public void setDmNguonChuongTrinhs_1(
			Set<DmNguonChuongTrinh> dmNguonChuongTrinhs_1) {
		this.dmNguonChuongTrinhs_1 = dmNguonChuongTrinhs_1;
	}

}
