package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmLoaiHoSo generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy=false)

@Table(name = "DM_LOAI_HO_SO", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMLOAIHOSO_MA"))
public class DmLoaiHoSo implements java.io.Serializable {

	private int dmloaihosoMaso;
	private String dmloaihosoMa;
	private String dmloaihosoTen;
	private String dmloaihosoGhichu;
	private Double dmloaihosoNgaygiocn;
	private Boolean dmloaihosoDt;
	private Boolean dmloaihosoQl;
	private Boolean dmloaihosoDp;

	public DmLoaiHoSo() {
	}

	public DmLoaiHoSo(int dmloaihosoMaso) {
		this.dmloaihosoMaso = dmloaihosoMaso;
	}

	public DmLoaiHoSo(int dmloaihosoMaso, String dmloaihosoMa,
			String dmloaihosoTen, String dmloaihosoGhichu,
			Double dmloaihosoNgaygiocn, Boolean dmloaihosoDt,
			Boolean dmloaihosoQl, Boolean dmloaihosoDp) {
		this.dmloaihosoMaso = dmloaihosoMaso;
		this.dmloaihosoMa = dmloaihosoMa;
		this.dmloaihosoTen = dmloaihosoTen;
		this.dmloaihosoGhichu = dmloaihosoGhichu;
		this.dmloaihosoNgaygiocn = dmloaihosoNgaygiocn;
		this.dmloaihosoDt = dmloaihosoDt;
		this.dmloaihosoQl = dmloaihosoQl;
		this.dmloaihosoDp = dmloaihosoDp;
	}

	@Id
	@Column(name = "DMLOAIHOSO_MASO", unique = true, nullable = false)
	@NotNull
	public int getDmloaihosoMaso() {
		return this.dmloaihosoMaso;
	}

	public void setDmloaihosoMaso(int dmloaihosoMaso) {
		this.dmloaihosoMaso = dmloaihosoMaso;
	}

	@Column(name = "DMLOAIHOSO_MA", unique = true, length = 15)
	@Length(max = 15)
	public String getDmloaihosoMa() {
		return this.dmloaihosoMa;
	}

	public void setDmloaihosoMa(String dmloaihosoMa) {
		this.dmloaihosoMa = dmloaihosoMa;
	}

	@Column(name = "DMLOAIHOSO_TEN", length = 100)
	@Length(max = 100)
	public String getDmloaihosoTen() {
		return this.dmloaihosoTen;
	}

	public void setDmloaihosoTen(String dmloaihosoTen) {
		this.dmloaihosoTen = dmloaihosoTen;
	}

	@Column(name = "DMLOAIHOSO_GHICHU", length = 100)
	@Length(max = 100)
	public String getDmloaihosoGhichu() {
		return this.dmloaihosoGhichu;
	}

	public void setDmloaihosoGhichu(String dmloaihosoGhichu) {
		this.dmloaihosoGhichu = dmloaihosoGhichu;
	}

	@Column(name = "DMLOAIHOSO_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmloaihosoNgaygiocn() {
		return this.dmloaihosoNgaygiocn;
	}

	public void setDmloaihosoNgaygiocn(Double dmloaihosoNgaygiocn) {
		this.dmloaihosoNgaygiocn = dmloaihosoNgaygiocn;
	}

	@Column(name = "DMLOAIHOSO_DT")
	public Boolean getDmloaihosoDt() {
		return this.dmloaihosoDt;
	}

	public void setDmloaihosoDt(Boolean dmloaihosoDt) {
		this.dmloaihosoDt = dmloaihosoDt;
	}

	@Column(name = "DMLOAIHOSO_QL")
	public Boolean getDmloaihosoQl() {
		return this.dmloaihosoQl;
	}

	public void setDmloaihosoQl(Boolean dmloaihosoQl) {
		this.dmloaihosoQl = dmloaihosoQl;
	}

	@Column(name = "DMLOAIHOSO_DP")
	public Boolean getDmloaihosoDp() {
		return this.dmloaihosoDp;
	}

	public void setDmloaihosoDp(Boolean dmloaihosoDp) {
		this.dmloaihosoDp = dmloaihosoDp;
	}

}
