package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNgheNghiep generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NGHE_NGHIEP", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNGHENGHIEP_MA"))
public class DmNgheNghiep implements java.io.Serializable {

	private Integer dmnghenghiepMaso;
	private DmNgheNghiepBaoCao dmNgheNghiepBaoCao;
	private String dmnghenghiepMa;
	private String dmnghenghiepTen;
	private String dmnghenghiepPhanloai2;
	private Integer dmnghenghiepAgemin;
	private Integer dmnghenghiepAgemax;
	private Double dmnghenghiepNgaygiocn;
	private Boolean dmnghenghiepQl;
	private Boolean dmnghenghiepDt;
	private Boolean dmnghenghiepDp;

	public DmNgheNghiep() {
	}

	public DmNgheNghiep(String dmnghenghiepMa, String dmnghenghiepTen) {
		this.dmnghenghiepMa = dmnghenghiepMa;
		this.dmnghenghiepTen = dmnghenghiepTen;
	}

	public DmNgheNghiep(DmNgheNghiepBaoCao dmNgheNghiepBaoCao,
			String dmnghenghiepMa, String dmnghenghiepTen,
			String dmnghenghiepPhanloai2, Integer dmnghenghiepAgemin,
			Integer dmnghenghiepAgemax, Double dmnghenghiepNgaygiocn,
			Boolean dmnghenghiepQl, Boolean dmnghenghiepDt,
			Boolean dmnghenghiepDp) {
		this.dmNgheNghiepBaoCao = dmNgheNghiepBaoCao;
		this.dmnghenghiepMa = dmnghenghiepMa;
		this.dmnghenghiepTen = dmnghenghiepTen;
		this.dmnghenghiepPhanloai2 = dmnghenghiepPhanloai2;
		this.dmnghenghiepAgemin = dmnghenghiepAgemin;
		this.dmnghenghiepAgemax = dmnghenghiepAgemax;
		this.dmnghenghiepNgaygiocn = dmnghenghiepNgaygiocn;
		this.dmnghenghiepQl = dmnghenghiepQl;
		this.dmnghenghiepDt = dmnghenghiepDt;
		this.dmnghenghiepDp = dmnghenghiepDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NGHE_NGHIEP")
	@SequenceGenerator(name = "DM_NGHE_NGHIEP", sequenceName = "DM_NGHE_NGHIEP_DMNGHENGHIEP_MA", allocationSize = 1)
	@Column(name = "DMNGHENGHIEP_MASO", unique = true, nullable = false)
	public Integer getDmnghenghiepMaso() {
		return this.dmnghenghiepMaso;
	}

	public void setDmnghenghiepMaso(Integer dmnghenghiepMaso) {
		this.dmnghenghiepMaso = dmnghenghiepMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNGHENGHIEP_PHANLOAI")
	public DmNgheNghiepBaoCao getDmNgheNghiepBaoCao() {
		return this.dmNgheNghiepBaoCao;
	}

	public void setDmNgheNghiepBaoCao(DmNgheNghiepBaoCao dmNgheNghiepBaoCao) {
		this.dmNgheNghiepBaoCao = dmNgheNghiepBaoCao;
	}

	@Column(name = "DMNGHENGHIEP_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmnghenghiepMa() {
		return this.dmnghenghiepMa;
	}

	public void setDmnghenghiepMa(String dmnghenghiepMa) {
		this.dmnghenghiepMa = dmnghenghiepMa;
	}

	@Column(name = "DMNGHENGHIEP_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmnghenghiepTen() {
		return this.dmnghenghiepTen;
	}

	public void setDmnghenghiepTen(String dmnghenghiepTen) {
		this.dmnghenghiepTen = dmnghenghiepTen;
	}

	@Column(name = "DMNGHENGHIEP_PHANLOAI2", length = 2)
	@Length(max = 2)
	public String getDmnghenghiepPhanloai2() {
		return this.dmnghenghiepPhanloai2;
	}

	public void setDmnghenghiepPhanloai2(String dmnghenghiepPhanloai2) {
		this.dmnghenghiepPhanloai2 = dmnghenghiepPhanloai2;
	}

	@Column(name = "DMNGHENGHIEP_AGEMIN")
	public Integer getDmnghenghiepAgemin() {
		return this.dmnghenghiepAgemin;
	}

	public void setDmnghenghiepAgemin(Integer dmnghenghiepAgemin) {
		this.dmnghenghiepAgemin = dmnghenghiepAgemin;
	}

	@Column(name = "DMNGHENGHIEP_AGEMAX")
	public Integer getDmnghenghiepAgemax() {
		return this.dmnghenghiepAgemax;
	}

	public void setDmnghenghiepAgemax(Integer dmnghenghiepAgemax) {
		this.dmnghenghiepAgemax = dmnghenghiepAgemax;
	}

	@Column(name = "DMNGHENGHIEP_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnghenghiepNgaygiocn() {
		return this.dmnghenghiepNgaygiocn;
	}

	public void setDmnghenghiepNgaygiocn(Double dmnghenghiepNgaygiocn) {
		this.dmnghenghiepNgaygiocn = dmnghenghiepNgaygiocn;
	}

	@Column(name = "DMNGHENGHIEP_QL")
	public Boolean getDmnghenghiepQl() {
		return this.dmnghenghiepQl;
	}

	public void setDmnghenghiepQl(Boolean dmnghenghiepQl) {
		this.dmnghenghiepQl = dmnghenghiepQl;
	}

	@Column(name = "DMNGHENGHIEP_DT")
	public Boolean getDmnghenghiepDt() {
		return this.dmnghenghiepDt;
	}

	public void setDmnghenghiepDt(Boolean dmnghenghiepDt) {
		this.dmnghenghiepDt = dmnghenghiepDt;
	}

	@Column(name = "DMNGHENGHIEP_DP")
	public Boolean getDmnghenghiepDp() {
		return this.dmnghenghiepDp;
	}

	public void setDmnghenghiepDp(Boolean dmnghenghiepDp) {
		this.dmnghenghiepDp = dmnghenghiepDp;
	}

}
