package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNguonKinhPhi generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NGUON_KINH_PHI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNGUONKINHPHI_MA"))
public class DmNguonKinhPhi implements java.io.Serializable {

	private Integer dmnguonkinhphiMaso;
	private String dmnguonkinhphiMa;
	private String dmnguonkinhphiTen;
	private Double dmnguonkinhphiNgaygiocn;
	private Boolean dmnguonkinhphiQl;
	private Boolean dmnguonkinhphiDt;
	private Boolean dmnguonkinhphiDp;
	private Set<DtDmKhach> dtDmKhachs = new HashSet<DtDmKhach>(0);
	private Set<DtDmKhach> dtDmKhachs_1 = new HashSet<DtDmKhach>(0);

	public DmNguonKinhPhi() {
	}

	public DmNguonKinhPhi(String dmnguonkinhphiMa, String dmnguonkinhphiTen) {
		this.dmnguonkinhphiMa = dmnguonkinhphiMa;
		this.dmnguonkinhphiTen = dmnguonkinhphiTen;
	}

	public DmNguonKinhPhi(String dmnguonkinhphiMa, String dmnguonkinhphiTen,
			Double dmnguonkinhphiNgaygiocn, Boolean dmnguonkinhphiQl,
			Boolean dmnguonkinhphiDt, Boolean dmnguonkinhphiDp,
			Set<DtDmKhach> dtDmKhachs, Set<DtDmKhach> dtDmKhachs_1) {
		this.dmnguonkinhphiMa = dmnguonkinhphiMa;
		this.dmnguonkinhphiTen = dmnguonkinhphiTen;
		this.dmnguonkinhphiNgaygiocn = dmnguonkinhphiNgaygiocn;
		this.dmnguonkinhphiQl = dmnguonkinhphiQl;
		this.dmnguonkinhphiDt = dmnguonkinhphiDt;
		this.dmnguonkinhphiDp = dmnguonkinhphiDp;
		this.dtDmKhachs = dtDmKhachs;
		this.dtDmKhachs_1 = dtDmKhachs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NGUON_KINH_PHI")
	@SequenceGenerator(name = "DM_NGUON_KINH_PHI", sequenceName = "DM_NGUON_KINH_PHI_DMNGUONKINHP", allocationSize = 1)
	@Column(name = "DMNGUONKINHPHI_MASO", unique = true, nullable = false)
	public Integer getDmnguonkinhphiMaso() {
		return this.dmnguonkinhphiMaso;
	}

	public void setDmnguonkinhphiMaso(Integer dmnguonkinhphiMaso) {
		this.dmnguonkinhphiMaso = dmnguonkinhphiMaso;
	}

	@Column(name = "DMNGUONKINHPHI_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmnguonkinhphiMa() {
		return this.dmnguonkinhphiMa;
	}

	public void setDmnguonkinhphiMa(String dmnguonkinhphiMa) {
		this.dmnguonkinhphiMa = dmnguonkinhphiMa;
	}

	@Column(name = "DMNGUONKINHPHI_TEN", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDmnguonkinhphiTen() {
		return this.dmnguonkinhphiTen;
	}

	public void setDmnguonkinhphiTen(String dmnguonkinhphiTen) {
		this.dmnguonkinhphiTen = dmnguonkinhphiTen;
	}

	@Column(name = "DMNGUONKINHPHI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnguonkinhphiNgaygiocn() {
		return this.dmnguonkinhphiNgaygiocn;
	}

	public void setDmnguonkinhphiNgaygiocn(Double dmnguonkinhphiNgaygiocn) {
		this.dmnguonkinhphiNgaygiocn = dmnguonkinhphiNgaygiocn;
	}

	@Column(name = "DMNGUONKINHPHI_QL")
	public Boolean getDmnguonkinhphiQl() {
		return this.dmnguonkinhphiQl;
	}

	public void setDmnguonkinhphiQl(Boolean dmnguonkinhphiQl) {
		this.dmnguonkinhphiQl = dmnguonkinhphiQl;
	}

	@Column(name = "DMNGUONKINHPHI_DT")
	public Boolean getDmnguonkinhphiDt() {
		return this.dmnguonkinhphiDt;
	}

	public void setDmnguonkinhphiDt(Boolean dmnguonkinhphiDt) {
		this.dmnguonkinhphiDt = dmnguonkinhphiDt;
	}

	@Column(name = "DMNGUONKINHPHI_DP")
	public Boolean getDmnguonkinhphiDp() {
		return this.dmnguonkinhphiDp;
	}

	public void setDmnguonkinhphiDp(Boolean dmnguonkinhphiDp) {
		this.dmnguonkinhphiDp = dmnguonkinhphiDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNguonKinhPhi")
	public Set<DtDmKhach> getDtDmKhachs() {
		return this.dtDmKhachs;
	}

	public void setDtDmKhachs(Set<DtDmKhach> dtDmKhachs) {
		this.dtDmKhachs = dtDmKhachs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNguonKinhPhi")
	public Set<DtDmKhach> getDtDmKhachs_1() {
		return this.dtDmKhachs_1;
	}

	public void setDtDmKhachs_1(Set<DtDmKhach> dtDmKhachs_1) {
		this.dtDmKhachs_1 = dtDmKhachs_1;
	}

}
