package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNgheNghiepBaoCao generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NGHE_NGHIEP_BAO_CAO", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNGHENGHIEPBC_MA"))
public class DmNgheNghiepBaoCao implements java.io.Serializable {

	private Integer dmnghenghiepbcMaso;
	private String dmnghenghiepbcMa;
	private String dmnghenghiepbcTen;
	private Double dmnghenghiepbcNgaygiocn;
	private Boolean dmnghenghiepbcQl;
	private Boolean dmnghenghiepbcDt;
	private Boolean dmnghenghiepbcDp;
	private Set<DmNgheNghiep> dmNgheNghieps = new HashSet<DmNgheNghiep>(0);
	private Set<DmNgheNghiep> dmNgheNghieps_1 = new HashSet<DmNgheNghiep>(0);

	public DmNgheNghiepBaoCao() {
	}

	public DmNgheNghiepBaoCao(String dmnghenghiepbcMa, String dmnghenghiepbcTen) {
		this.dmnghenghiepbcMa = dmnghenghiepbcMa;
		this.dmnghenghiepbcTen = dmnghenghiepbcTen;
	}

	public DmNgheNghiepBaoCao(String dmnghenghiepbcMa,
			String dmnghenghiepbcTen, Double dmnghenghiepbcNgaygiocn,
			Boolean dmnghenghiepbcQl, Boolean dmnghenghiepbcDt,
			Boolean dmnghenghiepbcDp, Set<DmNgheNghiep> dmNgheNghieps,
			Set<DmNgheNghiep> dmNgheNghieps_1) {
		this.dmnghenghiepbcMa = dmnghenghiepbcMa;
		this.dmnghenghiepbcTen = dmnghenghiepbcTen;
		this.dmnghenghiepbcNgaygiocn = dmnghenghiepbcNgaygiocn;
		this.dmnghenghiepbcQl = dmnghenghiepbcQl;
		this.dmnghenghiepbcDt = dmnghenghiepbcDt;
		this.dmnghenghiepbcDp = dmnghenghiepbcDp;
		this.dmNgheNghieps = dmNgheNghieps;
		this.dmNgheNghieps_1 = dmNgheNghieps_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NGHE_NGHIEP_BAO_CAO")
	@SequenceGenerator(name = "DM_NGHE_NGHIEP_BAO_CAO", sequenceName = "DM_NGHE_NGHIEP_BAO_CAO_DMNGHEN", allocationSize = 1)
	@Column(name = "DMNGHENGHIEPBC_MASO", unique = true, nullable = false)
	public Integer getDmnghenghiepbcMaso() {
		return this.dmnghenghiepbcMaso;
	}

	public void setDmnghenghiepbcMaso(Integer dmnghenghiepbcMaso) {
		this.dmnghenghiepbcMaso = dmnghenghiepbcMaso;
	}

	@Column(name = "DMNGHENGHIEPBC_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmnghenghiepbcMa() {
		return this.dmnghenghiepbcMa;
	}

	public void setDmnghenghiepbcMa(String dmnghenghiepbcMa) {
		this.dmnghenghiepbcMa = dmnghenghiepbcMa;
	}

	@Column(name = "DMNGHENGHIEPBC_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmnghenghiepbcTen() {
		return this.dmnghenghiepbcTen;
	}

	public void setDmnghenghiepbcTen(String dmnghenghiepbcTen) {
		this.dmnghenghiepbcTen = dmnghenghiepbcTen;
	}

	@Column(name = "DMNGHENGHIEPBC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnghenghiepbcNgaygiocn() {
		return this.dmnghenghiepbcNgaygiocn;
	}

	public void setDmnghenghiepbcNgaygiocn(Double dmnghenghiepbcNgaygiocn) {
		this.dmnghenghiepbcNgaygiocn = dmnghenghiepbcNgaygiocn;
	}

	@Column(name = "DMNGHENGHIEPBC_QL")
	public Boolean getDmnghenghiepbcQl() {
		return this.dmnghenghiepbcQl;
	}

	public void setDmnghenghiepbcQl(Boolean dmnghenghiepbcQl) {
		this.dmnghenghiepbcQl = dmnghenghiepbcQl;
	}

	@Column(name = "DMNGHENGHIEPBC_DT")
	public Boolean getDmnghenghiepbcDt() {
		return this.dmnghenghiepbcDt;
	}

	public void setDmnghenghiepbcDt(Boolean dmnghenghiepbcDt) {
		this.dmnghenghiepbcDt = dmnghenghiepbcDt;
	}

	@Column(name = "DMNGHENGHIEPBC_DP")
	public Boolean getDmnghenghiepbcDp() {
		return this.dmnghenghiepbcDp;
	}

	public void setDmnghenghiepbcDp(Boolean dmnghenghiepbcDp) {
		this.dmnghenghiepbcDp = dmnghenghiepbcDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNgheNghiepBaoCao")
	public Set<DmNgheNghiep> getDmNgheNghieps() {
		return this.dmNgheNghieps;
	}

	public void setDmNgheNghieps(Set<DmNgheNghiep> dmNgheNghieps) {
		this.dmNgheNghieps = dmNgheNghieps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNgheNghiepBaoCao")
	public Set<DmNgheNghiep> getDmNgheNghieps_1() {
		return this.dmNgheNghieps_1;
	}

	public void setDmNgheNghieps_1(Set<DmNgheNghiep> dmNgheNghieps_1) {
		this.dmNgheNghieps_1 = dmNgheNghieps_1;
	}

}
