package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNhomBaoCaoThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NHOM_BAO_CAO_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNHOMBCTHUOC_MA"))
public class DmNhomBaoCaoThuoc implements java.io.Serializable {

	private Integer dmnhombcthuocMaso;
	private String dmnhombcthuocMa;
	private String dmnhombcthuocMaphu;
	private String dmnhombcthuocTen;
	private String dmnhombcthuocThutu;
	private String dmnhombcthuocGhichu;
	private String dmnhanvienCn;
	private Double dmnhombcthuocNgaygiocn;
	private Boolean dmnhombcthuocDt;
	private Boolean dmnhombcthuocQl;
	private Boolean dmnhombcthuocDp;
	private Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs = new HashSet<DmNhomBaoCaoLoaiThuoc>(
			0);
	private Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1 = new HashSet<DmNhomBaoCaoLoaiThuoc>(
			0);
	private Set<DmPhanNhomThuoc> dmPhanNhomThuocs = new HashSet<DmPhanNhomThuoc>(
			0);
	private Set<DmPhanNhomThuoc> dmPhanNhomThuocs_1 = new HashSet<DmPhanNhomThuoc>(
			0);

	public DmNhomBaoCaoThuoc() {
	}

	public DmNhomBaoCaoThuoc(String dmnhombcthuocMa, String dmnhombcthuocTen) {
		this.dmnhombcthuocMa = dmnhombcthuocMa;
		this.dmnhombcthuocTen = dmnhombcthuocTen;
	}

	public DmNhomBaoCaoThuoc(String dmnhombcthuocMa, String dmnhombcthuocMaphu,
			String dmnhombcthuocTen, String dmnhombcthuocThutu,
			String dmnhombcthuocGhichu, String dmnhanvienCn,
			Double dmnhombcthuocNgaygiocn, Boolean dmnhombcthuocDt,
			Boolean dmnhombcthuocQl, Boolean dmnhombcthuocDp,
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs,
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1,
			Set<DmPhanNhomThuoc> dmPhanNhomThuocs,
			Set<DmPhanNhomThuoc> dmPhanNhomThuocs_1) {
		this.dmnhombcthuocMa = dmnhombcthuocMa;
		this.dmnhombcthuocMaphu = dmnhombcthuocMaphu;
		this.dmnhombcthuocTen = dmnhombcthuocTen;
		this.dmnhombcthuocThutu = dmnhombcthuocThutu;
		this.dmnhombcthuocGhichu = dmnhombcthuocGhichu;
		this.dmnhanvienCn = dmnhanvienCn;
		this.dmnhombcthuocNgaygiocn = dmnhombcthuocNgaygiocn;
		this.dmnhombcthuocDt = dmnhombcthuocDt;
		this.dmnhombcthuocQl = dmnhombcthuocQl;
		this.dmnhombcthuocDp = dmnhombcthuocDp;
		this.dmNhomBaoCaoLoaiThuocs = dmNhomBaoCaoLoaiThuocs;
		this.dmNhomBaoCaoLoaiThuocs_1 = dmNhomBaoCaoLoaiThuocs_1;
		this.dmPhanNhomThuocs = dmPhanNhomThuocs;
		this.dmPhanNhomThuocs_1 = dmPhanNhomThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NHOM_BAO_CAO_THUOC")
	@SequenceGenerator(name = "DM_NHOM_BAO_CAO_THUOC", sequenceName = "DM_NHOM_BAO_CAO_THUOC_DMNHOMBC", allocationSize = 1)
	@Column(name = "DMNHOMBCTHUOC_MASO", unique = true, nullable = false)
	public Integer getDmnhombcthuocMaso() {
		return this.dmnhombcthuocMaso;
	}

	public void setDmnhombcthuocMaso(Integer dmnhombcthuocMaso) {
		this.dmnhombcthuocMaso = dmnhombcthuocMaso;
	}

	@Column(name = "DMNHOMBCTHUOC_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmnhombcthuocMa() {
		return this.dmnhombcthuocMa;
	}

	public void setDmnhombcthuocMa(String dmnhombcthuocMa) {
		this.dmnhombcthuocMa = dmnhombcthuocMa;
	}

	@Column(name = "DMNHOMBCTHUOC_MAPHU", length = 2)
	@Length(max = 2)
	public String getDmnhombcthuocMaphu() {
		return this.dmnhombcthuocMaphu;
	}

	public void setDmnhombcthuocMaphu(String dmnhombcthuocMaphu) {
		this.dmnhombcthuocMaphu = dmnhombcthuocMaphu;
	}

	@Column(name = "DMNHOMBCTHUOC_TEN", nullable = false, length = 36)
	@NotNull
	@Length(max = 36)
	public String getDmnhombcthuocTen() {
		return this.dmnhombcthuocTen;
	}

	public void setDmnhombcthuocTen(String dmnhombcthuocTen) {
		this.dmnhombcthuocTen = dmnhombcthuocTen;
	}

	@Column(name = "DMNHOMBCTHUOC_THUTU", length = 6)
	@Length(max = 6)
	public String getDmnhombcthuocThutu() {
		return this.dmnhombcthuocThutu;
	}

	public void setDmnhombcthuocThutu(String dmnhombcthuocThutu) {
		this.dmnhombcthuocThutu = dmnhombcthuocThutu;
	}

	@Column(name = "DMNHOMBCTHUOC_GHICHU", length = 60)
	@Length(max = 60)
	public String getDmnhombcthuocGhichu() {
		return this.dmnhombcthuocGhichu;
	}

	public void setDmnhombcthuocGhichu(String dmnhombcthuocGhichu) {
		this.dmnhombcthuocGhichu = dmnhombcthuocGhichu;
	}

	@Column(name = "DMNHANVIEN_CN", length = 8)
	@Length(max = 8)
	public String getDmnhanvienCn() {
		return this.dmnhanvienCn;
	}

	public void setDmnhanvienCn(String dmnhanvienCn) {
		this.dmnhanvienCn = dmnhanvienCn;
	}

	@Column(name = "DMNHOMBCTHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnhombcthuocNgaygiocn() {
		return this.dmnhombcthuocNgaygiocn;
	}

	public void setDmnhombcthuocNgaygiocn(Double dmnhombcthuocNgaygiocn) {
		this.dmnhombcthuocNgaygiocn = dmnhombcthuocNgaygiocn;
	}

	@Column(name = "DMNHOMBCTHUOC_DT")
	public Boolean getDmnhombcthuocDt() {
		return this.dmnhombcthuocDt;
	}

	public void setDmnhombcthuocDt(Boolean dmnhombcthuocDt) {
		this.dmnhombcthuocDt = dmnhombcthuocDt;
	}

	@Column(name = "DMNHOMBCTHUOC_QL")
	public Boolean getDmnhombcthuocQl() {
		return this.dmnhombcthuocQl;
	}

	public void setDmnhombcthuocQl(Boolean dmnhombcthuocQl) {
		this.dmnhombcthuocQl = dmnhombcthuocQl;
	}

	@Column(name = "DMNHOMBCTHUOC_DP")
	public Boolean getDmnhombcthuocDp() {
		return this.dmnhombcthuocDp;
	}

	public void setDmnhombcthuocDp(Boolean dmnhombcthuocDp) {
		this.dmnhombcthuocDp = dmnhombcthuocDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomBaoCaoThuoc")
	public Set<DmNhomBaoCaoLoaiThuoc> getDmNhomBaoCaoLoaiThuocs() {
		return this.dmNhomBaoCaoLoaiThuocs;
	}

	public void setDmNhomBaoCaoLoaiThuocs(
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs) {
		this.dmNhomBaoCaoLoaiThuocs = dmNhomBaoCaoLoaiThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomBaoCaoThuoc")
	public Set<DmNhomBaoCaoLoaiThuoc> getDmNhomBaoCaoLoaiThuocs_1() {
		return this.dmNhomBaoCaoLoaiThuocs_1;
	}

	public void setDmNhomBaoCaoLoaiThuocs_1(
			Set<DmNhomBaoCaoLoaiThuoc> dmNhomBaoCaoLoaiThuocs_1) {
		this.dmNhomBaoCaoLoaiThuocs_1 = dmNhomBaoCaoLoaiThuocs_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomBaoCaoThuoc")
	public Set<DmPhanNhomThuoc> getDmPhanNhomThuocs() {
		return this.dmPhanNhomThuocs;
	}

	public void setDmPhanNhomThuocs(Set<DmPhanNhomThuoc> dmPhanNhomThuocs) {
		this.dmPhanNhomThuocs = dmPhanNhomThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomBaoCaoThuoc")
	public Set<DmPhanNhomThuoc> getDmPhanNhomThuocs_1() {
		return this.dmPhanNhomThuocs_1;
	}

	public void setDmPhanNhomThuocs_1(Set<DmPhanNhomThuoc> dmPhanNhomThuocs_1) {
		this.dmPhanNhomThuocs_1 = dmPhanNhomThuocs_1;
	}

}
