package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * DmNhomBaoCaoLoaiThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NHOM_BAO_CAO_LOAI_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DMNHOMBCTHUOC_MASO", "DMLOAITHUOC_MASO" }))
public class DmNhomBaoCaoLoaiThuoc implements java.io.Serializable {

	private Integer dmnhombcthuocloaithuocMaso;
	private DmLoaiThuoc dmLoaiThuoc;
	private DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc;
	private Boolean dmnhombcthuocloaithuocDt;
	private Double dmnhombcthuocloaithuocNgaygiocn;
	private Boolean dmnhombcthuocloaithuocDp;
	private Boolean dmnhombcthuocloaithuocQl;

	public DmNhomBaoCaoLoaiThuoc() {
	}

	public DmNhomBaoCaoLoaiThuoc(DmLoaiThuoc dmLoaiThuoc,
			DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc) {
		this.dmLoaiThuoc = dmLoaiThuoc;
		this.dmNhomBaoCaoThuoc = dmNhomBaoCaoThuoc;
	}

	public DmNhomBaoCaoLoaiThuoc(DmLoaiThuoc dmLoaiThuoc,
			DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc,
			Boolean dmnhombcthuocloaithuocDt,
			Double dmnhombcthuocloaithuocNgaygiocn,
			Boolean dmnhombcthuocloaithuocDp, Boolean dmnhombcthuocloaithuocQl) {
		this.dmLoaiThuoc = dmLoaiThuoc;
		this.dmNhomBaoCaoThuoc = dmNhomBaoCaoThuoc;
		this.dmnhombcthuocloaithuocDt = dmnhombcthuocloaithuocDt;
		this.dmnhombcthuocloaithuocNgaygiocn = dmnhombcthuocloaithuocNgaygiocn;
		this.dmnhombcthuocloaithuocDp = dmnhombcthuocloaithuocDp;
		this.dmnhombcthuocloaithuocQl = dmnhombcthuocloaithuocQl;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NHOM_BAO_CAO_LOAI_THUOC")
	@SequenceGenerator(name = "DM_NHOM_BAO_CAO_LOAI_THUOC", sequenceName = "DM_NHOM_BAO_CAO_LOAI_THUOC_DMN", allocationSize = 1)
	@Column(name = "DMNHOMBCTHUOCLOAITHUOC_MASO", unique = true, nullable = false)
	public Integer getDmnhombcthuocloaithuocMaso() {
		return this.dmnhombcthuocloaithuocMaso;
	}

	public void setDmnhombcthuocloaithuocMaso(Integer dmnhombcthuocloaithuocMaso) {
		this.dmnhombcthuocloaithuocMaso = dmnhombcthuocloaithuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMLOAITHUOC_MASO", nullable = false)
	@NotNull
	public DmLoaiThuoc getDmLoaiThuoc() {
		return this.dmLoaiThuoc;
	}

	public void setDmLoaiThuoc(DmLoaiThuoc dmLoaiThuoc) {
		this.dmLoaiThuoc = dmLoaiThuoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNHOMBCTHUOC_MASO", nullable = false)
	@NotNull
	public DmNhomBaoCaoThuoc getDmNhomBaoCaoThuoc() {
		return this.dmNhomBaoCaoThuoc;
	}

	public void setDmNhomBaoCaoThuoc(DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc) {
		this.dmNhomBaoCaoThuoc = dmNhomBaoCaoThuoc;
	}

	@Column(name = "DMNHOMBCTHUOCLOAITHUOC_DT")
	public Boolean getDmnhombcthuocloaithuocDt() {
		return this.dmnhombcthuocloaithuocDt;
	}

	public void setDmnhombcthuocloaithuocDt(Boolean dmnhombcthuocloaithuocDt) {
		this.dmnhombcthuocloaithuocDt = dmnhombcthuocloaithuocDt;
	}

	@Column(name = "DMNHOMBCTHUOCLOAITHUOC_NGGIOCN", precision = 22, scale = 0)
	public Double getDmnhombcthuocloaithuocNgaygiocn() {
		return this.dmnhombcthuocloaithuocNgaygiocn;
	}

	public void setDmnhombcthuocloaithuocNgaygiocn(
			Double dmnhombcthuocloaithuocNgaygiocn) {
		this.dmnhombcthuocloaithuocNgaygiocn = dmnhombcthuocloaithuocNgaygiocn;
	}

	@Column(name = "DMNHOMBCTHUOCLOAITHUOC_DP")
	public Boolean getDmnhombcthuocloaithuocDp() {
		return this.dmnhombcthuocloaithuocDp;
	}

	public void setDmnhombcthuocloaithuocDp(Boolean dmnhombcthuocloaithuocDp) {
		this.dmnhombcthuocloaithuocDp = dmnhombcthuocloaithuocDp;
	}

	@Column(name = "DMNHOMBCTHUOCLOAITHUOC_QL")
	public Boolean getDmnhombcthuocloaithuocQl() {
		return this.dmnhombcthuocloaithuocQl;
	}

	public void setDmnhombcthuocloaithuocQl(Boolean dmnhombcthuocloaithuocQl) {
		this.dmnhombcthuocloaithuocQl = dmnhombcthuocloaithuocQl;
	}

}
