package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNhaSanXuat generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NHA_SAN_XUAT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNHASANXUAT_MA"))
public class DmNhaSanXuat implements java.io.Serializable {

	private Integer dmnhasanxuatMaso;
	private String dmnhasanxuatMa;
	private String dmnhasanxuatTen;
	private String dmnhasanxuatTenvn;
	private String dmnhasanxuatPhanbiet;
	private String dmnhasanxuatPhanloai;
	private Boolean dmnhasanxuatHang;
	private Double dmnhasanxuatNgaygiocn;
	private Boolean dmnhasanxuatDt;
	private Boolean dmnhasanxuatQl;
	private Boolean dmnhasanxuatDp;
	private Set<DmThuoc> dmThuocs = new HashSet<DmThuoc>(0);
	private Set<DmThuoc> dmThuocs_1 = new HashSet<DmThuoc>(0);

	public DmNhaSanXuat() {
	}

	public DmNhaSanXuat(String dmnhasanxuatMa, String dmnhasanxuatTen) {
		this.dmnhasanxuatMa = dmnhasanxuatMa;
		this.dmnhasanxuatTen = dmnhasanxuatTen;
	}

	public DmNhaSanXuat(String dmnhasanxuatMa, String dmnhasanxuatTen,
			String dmnhasanxuatTenvn, String dmnhasanxuatPhanbiet,
			String dmnhasanxuatPhanloai, Boolean dmnhasanxuatHang,
			Double dmnhasanxuatNgaygiocn, Boolean dmnhasanxuatDt,
			Boolean dmnhasanxuatQl, Boolean dmnhasanxuatDp,
			Set<DmThuoc> dmThuocs, Set<DmThuoc> dmThuocs_1) {
		this.dmnhasanxuatMa = dmnhasanxuatMa;
		this.dmnhasanxuatTen = dmnhasanxuatTen;
		this.dmnhasanxuatTenvn = dmnhasanxuatTenvn;
		this.dmnhasanxuatPhanbiet = dmnhasanxuatPhanbiet;
		this.dmnhasanxuatPhanloai = dmnhasanxuatPhanloai;
		this.dmnhasanxuatHang = dmnhasanxuatHang;
		this.dmnhasanxuatNgaygiocn = dmnhasanxuatNgaygiocn;
		this.dmnhasanxuatDt = dmnhasanxuatDt;
		this.dmnhasanxuatQl = dmnhasanxuatQl;
		this.dmnhasanxuatDp = dmnhasanxuatDp;
		this.dmThuocs = dmThuocs;
		this.dmThuocs_1 = dmThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NHA_SAN_XUAT")
	@SequenceGenerator(name = "DM_NHA_SAN_XUAT", sequenceName = "DM_NHA_SAN_XUAT_DMNHASANXUAT_M", allocationSize = 1)
	@Column(name = "DMNHASANXUAT_MASO", unique = true, nullable = false)
	public Integer getDmnhasanxuatMaso() {
		return this.dmnhasanxuatMaso;
	}

	public void setDmnhasanxuatMaso(Integer dmnhasanxuatMaso) {
		this.dmnhasanxuatMaso = dmnhasanxuatMaso;
	}

	@Column(name = "DMNHASANXUAT_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmnhasanxuatMa() {
		return this.dmnhasanxuatMa;
	}

	public void setDmnhasanxuatMa(String dmnhasanxuatMa) {
		this.dmnhasanxuatMa = dmnhasanxuatMa;
	}

	@Column(name = "DMNHASANXUAT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmnhasanxuatTen() {
		return this.dmnhasanxuatTen;
	}

	public void setDmnhasanxuatTen(String dmnhasanxuatTen) {
		this.dmnhasanxuatTen = dmnhasanxuatTen;
	}

	@Column(name = "DMNHASANXUAT_TENVN", length = 250)
	@Length(max = 250)
	public String getDmnhasanxuatTenvn() {
		return this.dmnhasanxuatTenvn;
	}

	public void setDmnhasanxuatTenvn(String dmnhasanxuatTenvn) {
		this.dmnhasanxuatTenvn = dmnhasanxuatTenvn;
	}

	@Column(name = "DMNHASANXUAT_PHANBIET", length = 3)
	@Length(max = 3)
	public String getDmnhasanxuatPhanbiet() {
		return this.dmnhasanxuatPhanbiet;
	}

	public void setDmnhasanxuatPhanbiet(String dmnhasanxuatPhanbiet) {
		this.dmnhasanxuatPhanbiet = dmnhasanxuatPhanbiet;
	}

	@Column(name = "DMNHASANXUAT_PHANLOAI", length = 3)
	@Length(max = 3)
	public String getDmnhasanxuatPhanloai() {
		return this.dmnhasanxuatPhanloai;
	}

	public void setDmnhasanxuatPhanloai(String dmnhasanxuatPhanloai) {
		this.dmnhasanxuatPhanloai = dmnhasanxuatPhanloai;
	}

	@Column(name = "DMNHASANXUAT_HANG")
	public Boolean getDmnhasanxuatHang() {
		return this.dmnhasanxuatHang;
	}

	public void setDmnhasanxuatHang(Boolean dmnhasanxuatHang) {
		this.dmnhasanxuatHang = dmnhasanxuatHang;
	}

	@Column(name = "DMNHASANXUAT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnhasanxuatNgaygiocn() {
		return this.dmnhasanxuatNgaygiocn;
	}

	public void setDmnhasanxuatNgaygiocn(Double dmnhasanxuatNgaygiocn) {
		this.dmnhasanxuatNgaygiocn = dmnhasanxuatNgaygiocn;
	}

	@Column(name = "DMNHASANXUAT_DT")
	public Boolean getDmnhasanxuatDt() {
		return this.dmnhasanxuatDt;
	}

	public void setDmnhasanxuatDt(Boolean dmnhasanxuatDt) {
		this.dmnhasanxuatDt = dmnhasanxuatDt;
	}

	@Column(name = "DMNHASANXUAT_QL")
	public Boolean getDmnhasanxuatQl() {
		return this.dmnhasanxuatQl;
	}

	public void setDmnhasanxuatQl(Boolean dmnhasanxuatQl) {
		this.dmnhasanxuatQl = dmnhasanxuatQl;
	}

	@Column(name = "DMNHASANXUAT_DP")
	public Boolean getDmnhasanxuatDp() {
		return this.dmnhasanxuatDp;
	}

	public void setDmnhasanxuatDp(Boolean dmnhasanxuatDp) {
		this.dmnhasanxuatDp = dmnhasanxuatDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhaSanXuat")
	public Set<DmThuoc> getDmThuocs() {
		return this.dmThuocs;
	}

	public void setDmThuocs(Set<DmThuoc> dmThuocs) {
		this.dmThuocs = dmThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhaSanXuat")
	public Set<DmThuoc> getDmThuocs_1() {
		return this.dmThuocs_1;
	}

	public void setDmThuocs_1(Set<DmThuoc> dmThuocs_1) {
		this.dmThuocs_1 = dmThuocs_1;
	}

}
