package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNhaCungCap generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NHA_CUNG_CAP", catalog = "DB_YTDT_BD")
public class DmNhaCungCap implements java.io.Serializable {

	private Integer dmnhacungcapMaso;
	private DmTinh dmTinh;
	private DmNguonChuongTrinh dmNguonChuongTrinh;
	private String dmnhacungcapMa;
	private String dmnhacungcapTen;
	private String dmnhacungcapDiachi;
	private String dmnhacungcapDienthoai;
	private String dmnhacungcapMasothue;
	private String dmnhacungcapFax;
	private String dmnhacungcapPhanloai;
	private String dmnhacungcapPhanbiet;
	private Date dmnhacungcapNgaylv;
	private Double dmnhacungcapNgaygiocn;
	private Boolean dmnhacungcapQl;
	private Boolean dmnhacungcapDt;
	private Boolean dmnhacungcapDp;

	public DmNhaCungCap() {
	}

	public DmNhaCungCap(String dmnhacungcapMa, String dmnhacungcapTen) {
		this.dmnhacungcapMa = dmnhacungcapMa;
		this.dmnhacungcapTen = dmnhacungcapTen;
	}

	public DmNhaCungCap(DmTinh dmTinh, DmNguonChuongTrinh dmNguonChuongTrinh,
			String dmnhacungcapMa, String dmnhacungcapTen,
			String dmnhacungcapDiachi, String dmnhacungcapDienthoai,
			String dmnhacungcapMasothue, String dmnhacungcapFax,
			String dmnhacungcapPhanloai, String dmnhacungcapPhanbiet,
			Date dmnhacungcapNgaylv, Double dmnhacungcapNgaygiocn,
			Boolean dmnhacungcapQl, Boolean dmnhacungcapDt,
			Boolean dmnhacungcapDp) {
		this.dmTinh = dmTinh;
		this.dmNguonChuongTrinh = dmNguonChuongTrinh;
		this.dmnhacungcapMa = dmnhacungcapMa;
		this.dmnhacungcapTen = dmnhacungcapTen;
		this.dmnhacungcapDiachi = dmnhacungcapDiachi;
		this.dmnhacungcapDienthoai = dmnhacungcapDienthoai;
		this.dmnhacungcapMasothue = dmnhacungcapMasothue;
		this.dmnhacungcapFax = dmnhacungcapFax;
		this.dmnhacungcapPhanloai = dmnhacungcapPhanloai;
		this.dmnhacungcapPhanbiet = dmnhacungcapPhanbiet;
		this.dmnhacungcapNgaylv = dmnhacungcapNgaylv;
		this.dmnhacungcapNgaygiocn = dmnhacungcapNgaygiocn;
		this.dmnhacungcapQl = dmnhacungcapQl;
		this.dmnhacungcapDt = dmnhacungcapDt;
		this.dmnhacungcapDp = dmnhacungcapDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NHA_CUNG_CAP")
	@SequenceGenerator(name = "DM_NHA_CUNG_CAP", sequenceName = "DM_NHA_CUNG_CAP_DMNHACUNGCAP_M", allocationSize = 1)
	@Column(name = "DMNHACUNGCAP_MASO", unique = true, nullable = false)
	public Integer getDmnhacungcapMaso() {
		return this.dmnhacungcapMaso;
	}

	public void setDmnhacungcapMaso(Integer dmnhacungcapMaso) {
		this.dmnhacungcapMaso = dmnhacungcapMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTINH_MASO")
	public DmTinh getDmTinh() {
		return this.dmTinh;
	}

	public void setDmTinh(DmTinh dmTinh) {
		this.dmTinh = dmTinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNCT_MASO")
	public DmNguonChuongTrinh getDmNguonChuongTrinh() {
		return this.dmNguonChuongTrinh;
	}

	public void setDmNguonChuongTrinh(DmNguonChuongTrinh dmNguonChuongTrinh) {
		this.dmNguonChuongTrinh = dmNguonChuongTrinh;
	}

	@Column(name = "DMNHACUNGCAP_MA", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmnhacungcapMa() {
		return this.dmnhacungcapMa;
	}

	public void setDmnhacungcapMa(String dmnhacungcapMa) {
		this.dmnhacungcapMa = dmnhacungcapMa;
	}

	@Column(name = "DMNHACUNGCAP_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmnhacungcapTen() {
		return this.dmnhacungcapTen;
	}

	public void setDmnhacungcapTen(String dmnhacungcapTen) {
		this.dmnhacungcapTen = dmnhacungcapTen;
	}

	@Column(name = "DMNHACUNGCAP_DIACHI", length = 30)
	@Length(max = 30)
	public String getDmnhacungcapDiachi() {
		return this.dmnhacungcapDiachi;
	}

	public void setDmnhacungcapDiachi(String dmnhacungcapDiachi) {
		this.dmnhacungcapDiachi = dmnhacungcapDiachi;
	}

	@Column(name = "DMNHACUNGCAP_DIENTHOAI", length = 18)
	@Length(max = 18)
	public String getDmnhacungcapDienthoai() {
		return this.dmnhacungcapDienthoai;
	}

	public void setDmnhacungcapDienthoai(String dmnhacungcapDienthoai) {
		this.dmnhacungcapDienthoai = dmnhacungcapDienthoai;
	}

	@Column(name = "DMNHACUNGCAP_MASOTHUE", length = 25)
	@Length(max = 25)
	public String getDmnhacungcapMasothue() {
		return this.dmnhacungcapMasothue;
	}

	public void setDmnhacungcapMasothue(String dmnhacungcapMasothue) {
		this.dmnhacungcapMasothue = dmnhacungcapMasothue;
	}

	@Column(name = "DMNHACUNGCAP_FAX", length = 18)
	@Length(max = 18)
	public String getDmnhacungcapFax() {
		return this.dmnhacungcapFax;
	}

	public void setDmnhacungcapFax(String dmnhacungcapFax) {
		this.dmnhacungcapFax = dmnhacungcapFax;
	}

	@Column(name = "DMNHACUNGCAP_PHANLOAI", length = 4)
	@Length(max = 4)
	public String getDmnhacungcapPhanloai() {
		return this.dmnhacungcapPhanloai;
	}

	public void setDmnhacungcapPhanloai(String dmnhacungcapPhanloai) {
		this.dmnhacungcapPhanloai = dmnhacungcapPhanloai;
	}

	@Column(name = "DMNHACUNGCAP_PHANBIET", length = 4)
	@Length(max = 4)
	public String getDmnhacungcapPhanbiet() {
		return this.dmnhacungcapPhanbiet;
	}

	public void setDmnhacungcapPhanbiet(String dmnhacungcapPhanbiet) {
		this.dmnhacungcapPhanbiet = dmnhacungcapPhanbiet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DMNHACUNGCAP_NGAYLV", length = 0)
	public Date getDmnhacungcapNgaylv() {
		return this.dmnhacungcapNgaylv;
	}

	public void setDmnhacungcapNgaylv(Date dmnhacungcapNgaylv) {
		this.dmnhacungcapNgaylv = dmnhacungcapNgaylv;
	}

	@Column(name = "DMNHACUNGCAP_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnhacungcapNgaygiocn() {
		return this.dmnhacungcapNgaygiocn;
	}

	public void setDmnhacungcapNgaygiocn(Double dmnhacungcapNgaygiocn) {
		this.dmnhacungcapNgaygiocn = dmnhacungcapNgaygiocn;
	}

	@Column(name = "DMNHACUNGCAP_QL")
	public Boolean getDmnhacungcapQl() {
		return this.dmnhacungcapQl;
	}

	public void setDmnhacungcapQl(Boolean dmnhacungcapQl) {
		this.dmnhacungcapQl = dmnhacungcapQl;
	}

	@Column(name = "DMNHACUNGCAP_DT")
	public Boolean getDmnhacungcapDt() {
		return this.dmnhacungcapDt;
	}

	public void setDmnhacungcapDt(Boolean dmnhacungcapDt) {
		this.dmnhacungcapDt = dmnhacungcapDt;
	}

	@Column(name = "DMNHACUNGCAP_DP")
	public Boolean getDmnhacungcapDp() {
		return this.dmnhacungcapDp;
	}

	public void setDmnhacungcapDp(Boolean dmnhacungcapDp) {
		this.dmnhacungcapDp = dmnhacungcapDp;
	}

}
