package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmNhomHocVi generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_NHOM_HOC_VI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMNHOMHOCVI_MA"))
public class DmNhomHocVi implements java.io.Serializable {

	private Integer dmnhomhocviMaso;
	private String dmnhomhocviMa;
	private String dmnhomhocviTen;
	private Boolean dmnhomhocviDaihoc;
	private String dmnhomhocviTenbc;
	private Short dmnhomhocviThutu;
	private Double dmnhomhocviNgaygiocn;
	private Boolean dmnhomhocviDt;
	private Boolean dmnhomhocviDl;
	private Boolean dmnhomhocviDp;
	private Set<DmHocVi> dmHocVis = new HashSet<DmHocVi>(0);
	private Set<DmHocVi> dmHocVis_1 = new HashSet<DmHocVi>(0);

	public DmNhomHocVi() {
	}

	public DmNhomHocVi(String dmnhomhocviMa, String dmnhomhocviTen) {
		this.dmnhomhocviMa = dmnhomhocviMa;
		this.dmnhomhocviTen = dmnhomhocviTen;
	}

	public DmNhomHocVi(String dmnhomhocviMa, String dmnhomhocviTen,
			Boolean dmnhomhocviDaihoc, String dmnhomhocviTenbc,
			Short dmnhomhocviThutu, Double dmnhomhocviNgaygiocn,
			Boolean dmnhomhocviDt, Boolean dmnhomhocviDl,
			Boolean dmnhomhocviDp, Set<DmHocVi> dmHocVis,
			Set<DmHocVi> dmHocVis_1) {
		this.dmnhomhocviMa = dmnhomhocviMa;
		this.dmnhomhocviTen = dmnhomhocviTen;
		this.dmnhomhocviDaihoc = dmnhomhocviDaihoc;
		this.dmnhomhocviTenbc = dmnhomhocviTenbc;
		this.dmnhomhocviThutu = dmnhomhocviThutu;
		this.dmnhomhocviNgaygiocn = dmnhomhocviNgaygiocn;
		this.dmnhomhocviDt = dmnhomhocviDt;
		this.dmnhomhocviDl = dmnhomhocviDl;
		this.dmnhomhocviDp = dmnhomhocviDp;
		this.dmHocVis = dmHocVis;
		this.dmHocVis_1 = dmHocVis_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_NHOM_HOC_VI")
	@SequenceGenerator(name = "DM_NHOM_HOC_VI", sequenceName = "DM_NHOM_HOC_VI_DMNHOMHOCVI_MAS", allocationSize = 1)
	@Column(name = "DMNHOMHOCVI_MASO", unique = true, nullable = false)
	public Integer getDmnhomhocviMaso() {
		return this.dmnhomhocviMaso;
	}

	public void setDmnhomhocviMaso(Integer dmnhomhocviMaso) {
		this.dmnhomhocviMaso = dmnhomhocviMaso;
	}

	@Column(name = "DMNHOMHOCVI_MA", unique = true, nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDmnhomhocviMa() {
		return this.dmnhomhocviMa;
	}

	public void setDmnhomhocviMa(String dmnhomhocviMa) {
		this.dmnhomhocviMa = dmnhomhocviMa;
	}

	@Column(name = "DMNHOMHOCVI_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmnhomhocviTen() {
		return this.dmnhomhocviTen;
	}

	public void setDmnhomhocviTen(String dmnhomhocviTen) {
		this.dmnhomhocviTen = dmnhomhocviTen;
	}

	@Column(name = "DMNHOMHOCVI_DAIHOC")
	public Boolean getDmnhomhocviDaihoc() {
		return this.dmnhomhocviDaihoc;
	}

	public void setDmnhomhocviDaihoc(Boolean dmnhomhocviDaihoc) {
		this.dmnhomhocviDaihoc = dmnhomhocviDaihoc;
	}

	@Column(name = "DMNHOMHOCVI_TENBC", length = 250)
	@Length(max = 250)
	public String getDmnhomhocviTenbc() {
		return this.dmnhomhocviTenbc;
	}

	public void setDmnhomhocviTenbc(String dmnhomhocviTenbc) {
		this.dmnhomhocviTenbc = dmnhomhocviTenbc;
	}

	@Column(name = "DMNHOMHOCVI_THUTU")
	public Short getDmnhomhocviThutu() {
		return this.dmnhomhocviThutu;
	}

	public void setDmnhomhocviThutu(Short dmnhomhocviThutu) {
		this.dmnhomhocviThutu = dmnhomhocviThutu;
	}

	@Column(name = "DMNHOMHOCVI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmnhomhocviNgaygiocn() {
		return this.dmnhomhocviNgaygiocn;
	}

	public void setDmnhomhocviNgaygiocn(Double dmnhomhocviNgaygiocn) {
		this.dmnhomhocviNgaygiocn = dmnhomhocviNgaygiocn;
	}

	@Column(name = "DMNHOMHOCVI_DT")
	public Boolean getDmnhomhocviDt() {
		return this.dmnhomhocviDt;
	}

	public void setDmnhomhocviDt(Boolean dmnhomhocviDt) {
		this.dmnhomhocviDt = dmnhomhocviDt;
	}

	@Column(name = "DMNHOMHOCVI_DL")
	public Boolean getDmnhomhocviDl() {
		return this.dmnhomhocviDl;
	}

	public void setDmnhomhocviDl(Boolean dmnhomhocviDl) {
		this.dmnhomhocviDl = dmnhomhocviDl;
	}

	@Column(name = "DMNHOMHOCVI_DP")
	public Boolean getDmnhomhocviDp() {
		return this.dmnhomhocviDp;
	}

	public void setDmnhomhocviDp(Boolean dmnhomhocviDp) {
		this.dmnhomhocviDp = dmnhomhocviDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomHocVi")
	public Set<DmHocVi> getDmHocVis() {
		return this.dmHocVis;
	}

	public void setDmHocVis(Set<DmHocVi> dmHocVis) {
		this.dmHocVis = dmHocVis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmNhomHocVi")
	public Set<DmHocVi> getDmHocVis_1() {
		return this.dmHocVis_1;
	}

	public void setDmHocVis_1(Set<DmHocVi> dmHocVis_1) {
		this.dmHocVis_1 = dmHocVis_1;
	}

}
