package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmPhanNhomThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy=false)

@Table(name = "DM_PHAN_NHOM_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMPHANNHOMTHUOC_MA"))
public class DmPhanNhomThuoc implements java.io.Serializable {

	private Integer dmphannhomthuocMaso;
	private DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc;
	private String dmphannhomthuocMa;
	private String dmphannhomthuocMaphu;
	private String dmphannhomthuocTen;
	private String dmphannhomthuocThutu;
	private String dmphannhomthuocGhichu;
	private String dmnhanvienCn;
	private Double dmphannhomthuocNgaygiocn;
	private Boolean dmphannhomthuocDt;
	private Boolean dmphannhomthuocQl;
	private Boolean dmphannhomthuocDp;
	private Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2 = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphannhomthuocMaso = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphannhomthuocMaso_1 = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2_1 = new HashSet<DmThuoc>(
			0);

	public DmPhanNhomThuoc() {
	}

	public DmPhanNhomThuoc(String dmphannhomthuocMa, String dmphannhomthuocTen) {
		this.dmphannhomthuocMa = dmphannhomthuocMa;
		this.dmphannhomthuocTen = dmphannhomthuocTen;
	}

	public DmPhanNhomThuoc(DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc,
			String dmphannhomthuocMa, String dmphannhomthuocMaphu,
			String dmphannhomthuocTen, String dmphannhomthuocThutu,
			String dmphannhomthuocGhichu, String dmnhanvienCn,
			Double dmphannhomthuocNgaygiocn, Boolean dmphannhomthuocDt,
			Boolean dmphannhomthuocQl, Boolean dmphannhomthuocDp,
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2,
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso,
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso_1,
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2_1) {
		this.dmNhomBaoCaoThuoc = dmNhomBaoCaoThuoc;
		this.dmphannhomthuocMa = dmphannhomthuocMa;
		this.dmphannhomthuocMaphu = dmphannhomthuocMaphu;
		this.dmphannhomthuocTen = dmphannhomthuocTen;
		this.dmphannhomthuocThutu = dmphannhomthuocThutu;
		this.dmphannhomthuocGhichu = dmphannhomthuocGhichu;
		this.dmnhanvienCn = dmnhanvienCn;
		this.dmphannhomthuocNgaygiocn = dmphannhomthuocNgaygiocn;
		this.dmphannhomthuocDt = dmphannhomthuocDt;
		this.dmphannhomthuocQl = dmphannhomthuocQl;
		this.dmphannhomthuocDp = dmphannhomthuocDp;
		this.dmThuocsForDmphannhomthuocMaso2 = dmThuocsForDmphannhomthuocMaso2;
		this.dmThuocsForDmphannhomthuocMaso = dmThuocsForDmphannhomthuocMaso;
		this.dmThuocsForDmphannhomthuocMaso_1 = dmThuocsForDmphannhomthuocMaso_1;
		this.dmThuocsForDmphannhomthuocMaso2_1 = dmThuocsForDmphannhomthuocMaso2_1;
	}

	@Id
	  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_PHAN_NHOM_THUOC")
	  @SequenceGenerator(name = "DM_PHAN_NHOM_THUOC", sequenceName = "DM_PHAN_NHOM_THUOC_DMPHANNHOMT", allocationSize = 1)
	  @Column(name = "DMPHANNHOMTHUOC_MASO", unique = true, nullable = false)
	public Integer getDmphannhomthuocMaso() {
		return this.dmphannhomthuocMaso;
	}

	public void setDmphannhomthuocMaso(Integer dmphannhomthuocMaso) {
		this.dmphannhomthuocMaso = dmphannhomthuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNHOMBCTHUOC_MASO")
	public DmNhomBaoCaoThuoc getDmNhomBaoCaoThuoc() {
		return this.dmNhomBaoCaoThuoc;
	}

	public void setDmNhomBaoCaoThuoc(DmNhomBaoCaoThuoc dmNhomBaoCaoThuoc) {
		this.dmNhomBaoCaoThuoc = dmNhomBaoCaoThuoc;
	}

	@Column(name = "DMPHANNHOMTHUOC_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmphannhomthuocMa() {
		return this.dmphannhomthuocMa;
	}

	public void setDmphannhomthuocMa(String dmphannhomthuocMa) {
		this.dmphannhomthuocMa = dmphannhomthuocMa;
	}

	@Column(name = "DMPHANNHOMTHUOC_MAPHU", length = 2)
	@Length(max = 2)
	public String getDmphannhomthuocMaphu() {
		return this.dmphannhomthuocMaphu;
	}

	public void setDmphannhomthuocMaphu(String dmphannhomthuocMaphu) {
		this.dmphannhomthuocMaphu = dmphannhomthuocMaphu;
	}

	@Column(name = "DMPHANNHOMTHUOC_TEN", nullable = false, length = 36)
	@NotNull
	@Length(max = 36)
	public String getDmphannhomthuocTen() {
		return this.dmphannhomthuocTen;
	}

	public void setDmphannhomthuocTen(String dmphannhomthuocTen) {
		this.dmphannhomthuocTen = dmphannhomthuocTen;
	}

	@Column(name = "DMPHANNHOMTHUOC_THUTU", length = 6)
	@Length(max = 6)
	public String getDmphannhomthuocThutu() {
		return this.dmphannhomthuocThutu;
	}

	public void setDmphannhomthuocThutu(String dmphannhomthuocThutu) {
		this.dmphannhomthuocThutu = dmphannhomthuocThutu;
	}

	@Column(name = "DMPHANNHOMTHUOC_GHICHU", length = 60)
	@Length(max = 60)
	public String getDmphannhomthuocGhichu() {
		return this.dmphannhomthuocGhichu;
	}

	public void setDmphannhomthuocGhichu(String dmphannhomthuocGhichu) {
		this.dmphannhomthuocGhichu = dmphannhomthuocGhichu;
	}

	@Column(name = "DMNHANVIEN_CN", length = 8)
	@Length(max = 8)
	public String getDmnhanvienCn() {
		return this.dmnhanvienCn;
	}

	public void setDmnhanvienCn(String dmnhanvienCn) {
		this.dmnhanvienCn = dmnhanvienCn;
	}

	@Column(name = "DMPHANNHOMTHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmphannhomthuocNgaygiocn() {
		return this.dmphannhomthuocNgaygiocn;
	}

	public void setDmphannhomthuocNgaygiocn(Double dmphannhomthuocNgaygiocn) {
		this.dmphannhomthuocNgaygiocn = dmphannhomthuocNgaygiocn;
	}

	@Column(name = "DMPHANNHOMTHUOC_DT")
	public Boolean getDmphannhomthuocDt() {
		return this.dmphannhomthuocDt;
	}

	public void setDmphannhomthuocDt(Boolean dmphannhomthuocDt) {
		this.dmphannhomthuocDt = dmphannhomthuocDt;
	}

	@Column(name = "DMPHANNHOMTHUOC_QL")
	public Boolean getDmphannhomthuocQl() {
		return this.dmphannhomthuocQl;
	}

	public void setDmphannhomthuocQl(Boolean dmphannhomthuocQl) {
		this.dmphannhomthuocQl = dmphannhomthuocQl;
	}

	@Column(name = "DMPHANNHOMTHUOC_DP")
	public Boolean getDmphannhomthuocDp() {
		return this.dmphannhomthuocDp;
	}

	public void setDmphannhomthuocDp(Boolean dmphannhomthuocDp) {
		this.dmphannhomthuocDp = dmphannhomthuocDp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanNhomThuocByDmphannhomthuocMaso2")
	public Set<DmThuoc> getDmThuocsForDmphannhomthuocMaso2() {
		return this.dmThuocsForDmphannhomthuocMaso2;
	}

	public void setDmThuocsForDmphannhomthuocMaso2(
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2) {
		this.dmThuocsForDmphannhomthuocMaso2 = dmThuocsForDmphannhomthuocMaso2;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanNhomThuocByDmphannhomthuocMaso")
	public Set<DmThuoc> getDmThuocsForDmphannhomthuocMaso() {
		return this.dmThuocsForDmphannhomthuocMaso;
	}

	public void setDmThuocsForDmphannhomthuocMaso(
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso) {
		this.dmThuocsForDmphannhomthuocMaso = dmThuocsForDmphannhomthuocMaso;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanNhomThuocByDmphannhomthuocMaso")
	public Set<DmThuoc> getDmThuocsForDmphannhomthuocMaso_1() {
		return this.dmThuocsForDmphannhomthuocMaso_1;
	}

	public void setDmThuocsForDmphannhomthuocMaso_1(
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso_1) {
		this.dmThuocsForDmphannhomthuocMaso_1 = dmThuocsForDmphannhomthuocMaso_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanNhomThuocByDmphannhomthuocMaso2")
	public Set<DmThuoc> getDmThuocsForDmphannhomthuocMaso2_1() {
		return this.dmThuocsForDmphannhomthuocMaso2_1;
	}

	public void setDmThuocsForDmphannhomthuocMaso2_1(
			Set<DmThuoc> dmThuocsForDmphannhomthuocMaso2_1) {
		this.dmThuocsForDmphannhomthuocMaso2_1 = dmThuocsForDmphannhomthuocMaso2_1;
	}

}
