package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmPhanLoaiTaiNan generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_PHAN_LOAI_TAI_NAN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMPLTAINAN_MA"))
public class DmPhanLoaiTaiNan implements java.io.Serializable {

	private Integer dmpltainanMaso;
	private DmTaiNan dmTaiNan;
	private String dmpltainanMa;
	private String dmpltainanTen;
	private String dmpltainanTen2;
	private Boolean dmpltainanBhyt;
	private Boolean dmpltainanBhyt2;
	private String dmpltainanTaptin;
	private Double dmpltainanNgaygiocn;
	private Boolean dmpltainanDt;
	private Boolean dmpltainanQl;
	private Boolean dmpltainanDp;

	public DmPhanLoaiTaiNan() {
	}

	public DmPhanLoaiTaiNan(String dmpltainanMa, String dmpltainanTen) {
		this.dmpltainanMa = dmpltainanMa;
		this.dmpltainanTen = dmpltainanTen;
	}

	public DmPhanLoaiTaiNan(DmTaiNan dmTaiNan, String dmpltainanMa,
			String dmpltainanTen, String dmpltainanTen2,
			Boolean dmpltainanBhyt, Boolean dmpltainanBhyt2,
			String dmpltainanTaptin, Double dmpltainanNgaygiocn,
			Boolean dmpltainanDt, Boolean dmpltainanQl, Boolean dmpltainanDp) {
		this.dmTaiNan = dmTaiNan;
		this.dmpltainanMa = dmpltainanMa;
		this.dmpltainanTen = dmpltainanTen;
		this.dmpltainanTen2 = dmpltainanTen2;
		this.dmpltainanBhyt = dmpltainanBhyt;
		this.dmpltainanBhyt2 = dmpltainanBhyt2;
		this.dmpltainanTaptin = dmpltainanTaptin;
		this.dmpltainanNgaygiocn = dmpltainanNgaygiocn;
		this.dmpltainanDt = dmpltainanDt;
		this.dmpltainanQl = dmpltainanQl;
		this.dmpltainanDp = dmpltainanDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_PHAN_LOAI_TAI_NAN")
	@SequenceGenerator(name = "DM_PHAN_LOAI_TAI_NAN", sequenceName = "DM_PHAN_LOAI_TAI_NAN_DMPLTAINA", allocationSize = 1)
	@Column(name = "DMPLTAINAN_MASO", unique = true, nullable = false)
	public Integer getDmpltainanMaso() {
		return this.dmpltainanMaso;
	}

	public void setDmpltainanMaso(Integer dmpltainanMaso) {
		this.dmpltainanMaso = dmpltainanMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTAINAN_MASO")
	public DmTaiNan getDmTaiNan() {
		return this.dmTaiNan;
	}

	public void setDmTaiNan(DmTaiNan dmTaiNan) {
		this.dmTaiNan = dmTaiNan;
	}

	@Column(name = "DMPLTAINAN_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmpltainanMa() {
		return this.dmpltainanMa;
	}

	public void setDmpltainanMa(String dmpltainanMa) {
		this.dmpltainanMa = dmpltainanMa;
	}

	@Column(name = "DMPLTAINAN_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmpltainanTen() {
		return this.dmpltainanTen;
	}

	public void setDmpltainanTen(String dmpltainanTen) {
		this.dmpltainanTen = dmpltainanTen;
	}

	@Column(name = "DMPLTAINAN_TEN2", length = 250)
	@Length(max = 250)
	public String getDmpltainanTen2() {
		return this.dmpltainanTen2;
	}

	public void setDmpltainanTen2(String dmpltainanTen2) {
		this.dmpltainanTen2 = dmpltainanTen2;
	}

	@Column(name = "DMPLTAINAN_BHYT")
	public Boolean getDmpltainanBhyt() {
		return this.dmpltainanBhyt;
	}

	public void setDmpltainanBhyt(Boolean dmpltainanBhyt) {
		this.dmpltainanBhyt = dmpltainanBhyt;
	}

	@Column(name = "DMPLTAINAN_BHYT2")
	public Boolean getDmpltainanBhyt2() {
		return this.dmpltainanBhyt2;
	}

	public void setDmpltainanBhyt2(Boolean dmpltainanBhyt2) {
		this.dmpltainanBhyt2 = dmpltainanBhyt2;
	}

	@Column(name = "DMPLTAINAN_TAPTIN", length = 250)
	@Length(max = 250)
	public String getDmpltainanTaptin() {
		return this.dmpltainanTaptin;
	}

	public void setDmpltainanTaptin(String dmpltainanTaptin) {
		this.dmpltainanTaptin = dmpltainanTaptin;
	}

	@Column(name = "DMPLTAINAN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmpltainanNgaygiocn() {
		return this.dmpltainanNgaygiocn;
	}

	public void setDmpltainanNgaygiocn(Double dmpltainanNgaygiocn) {
		this.dmpltainanNgaygiocn = dmpltainanNgaygiocn;
	}

	@Column(name = "DMPLTAINAN_DT")
	public Boolean getDmpltainanDt() {
		return this.dmpltainanDt;
	}

	public void setDmpltainanDt(Boolean dmpltainanDt) {
		this.dmpltainanDt = dmpltainanDt;
	}

	@Column(name = "DMPLTAINAN_QL")
	public Boolean getDmpltainanQl() {
		return this.dmpltainanQl;
	}

	public void setDmpltainanQl(Boolean dmpltainanQl) {
		this.dmpltainanQl = dmpltainanQl;
	}

	@Column(name = "DMPLTAINAN_DP")
	public Boolean getDmpltainanDp() {
		return this.dmpltainanDp;
	}

	public void setDmpltainanDp(Boolean dmpltainanDp) {
		this.dmpltainanDp = dmpltainanDp;
	}

}
