package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmPhanLoaiThuoc generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_PHAN_LOAI_THUOC", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMPHANLOAITHUOC_MA"))
public class DmPhanLoaiThuoc implements java.io.Serializable {

	private Integer dmphanloaithuocMaso;
	private DmLoaiThuoc dmLoaiThuoc;
	private String dmphanloaithuocMa;
	private String dmphanloaithuocTen;
	private String dmphanloaithuocNhom2;
	private String dmphanloaithuocNhom3;
	private Boolean dmphanloaithuocDungtich;
	private String dmphanloaithuocGhichu;
	private Integer dmphanloaithuocThutubc;
	private Integer dmphanloaithuocLoai;
	private Boolean dmphanloaithuocDt;
	private Boolean dmphanloaithuocQl;
	private Boolean dmphanloaithuocDp;
	private Double dmphanloaithuocNgaygiocn;
	private Set<DmThuoc> dmThuocsForDmphanloaithuocMaso = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphanloaithuocMaso_1 = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2 = new HashSet<DmThuoc>(
			0);
	private Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2_1 = new HashSet<DmThuoc>(
			0);

	public DmPhanLoaiThuoc() {
	}

	public DmPhanLoaiThuoc(String dmphanloaithuocMa, String dmphanloaithuocTen) {
		this.dmphanloaithuocMa = dmphanloaithuocMa;
		this.dmphanloaithuocTen = dmphanloaithuocTen;
	}

	public DmPhanLoaiThuoc(DmLoaiThuoc dmLoaiThuoc, String dmphanloaithuocMa,
			String dmphanloaithuocTen, String dmphanloaithuocNhom2,
			String dmphanloaithuocNhom3, Boolean dmphanloaithuocDungtich,
			String dmphanloaithuocGhichu, Integer dmphanloaithuocThutubc,
			Integer dmphanloaithuocLoai, Boolean dmphanloaithuocDt,
			Boolean dmphanloaithuocQl, Boolean dmphanloaithuocDp,
			Double dmphanloaithuocNgaygiocn,
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso,
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso_1,
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2,
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2_1) {
		this.dmLoaiThuoc = dmLoaiThuoc;
		this.dmphanloaithuocMa = dmphanloaithuocMa;
		this.dmphanloaithuocTen = dmphanloaithuocTen;
		this.dmphanloaithuocNhom2 = dmphanloaithuocNhom2;
		this.dmphanloaithuocNhom3 = dmphanloaithuocNhom3;
		this.dmphanloaithuocDungtich = dmphanloaithuocDungtich;
		this.dmphanloaithuocGhichu = dmphanloaithuocGhichu;
		this.dmphanloaithuocThutubc = dmphanloaithuocThutubc;
		this.dmphanloaithuocLoai = dmphanloaithuocLoai;
		this.dmphanloaithuocDt = dmphanloaithuocDt;
		this.dmphanloaithuocQl = dmphanloaithuocQl;
		this.dmphanloaithuocDp = dmphanloaithuocDp;
		this.dmphanloaithuocNgaygiocn = dmphanloaithuocNgaygiocn;
		this.dmThuocsForDmphanloaithuocMaso = dmThuocsForDmphanloaithuocMaso;
		this.dmThuocsForDmphanloaithuocMaso_1 = dmThuocsForDmphanloaithuocMaso_1;
		this.dmThuocsForDmphanloaithuocMaso2 = dmThuocsForDmphanloaithuocMaso2;
		this.dmThuocsForDmphanloaithuocMaso2_1 = dmThuocsForDmphanloaithuocMaso2_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_PHAN_LOAI_THUOC")
	@SequenceGenerator(name = "DM_PHAN_LOAI_THUOC", sequenceName = "DM_PHAN_LOAI_THUOC_DMPHANLOAIT", allocationSize = 1)
	@Column(name = "DMPHANLOAITHUOC_MASO", unique = true, nullable = false)
	public Integer getDmphanloaithuocMaso() {
		return this.dmphanloaithuocMaso;
	}

	public void setDmphanloaithuocMaso(Integer dmphanloaithuocMaso) {
		this.dmphanloaithuocMaso = dmphanloaithuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMLOAITHUOC_MASO")
	public DmLoaiThuoc getDmLoaiThuoc() {
		return this.dmLoaiThuoc;
	}

	public void setDmLoaiThuoc(DmLoaiThuoc dmLoaiThuoc) {
		this.dmLoaiThuoc = dmLoaiThuoc;
	}

	@Column(name = "DMPHANLOAITHUOC_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmphanloaithuocMa() {
		return this.dmphanloaithuocMa;
	}

	public void setDmphanloaithuocMa(String dmphanloaithuocMa) {
		this.dmphanloaithuocMa = dmphanloaithuocMa;
	}

	@Column(name = "DMPHANLOAITHUOC_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmphanloaithuocTen() {
		return this.dmphanloaithuocTen;
	}

	public void setDmphanloaithuocTen(String dmphanloaithuocTen) {
		this.dmphanloaithuocTen = dmphanloaithuocTen;
	}

	@Column(name = "DMPHANLOAITHUOC_NHOM2", length = 2)
	@Length(max = 2)
	public String getDmphanloaithuocNhom2() {
		return this.dmphanloaithuocNhom2;
	}

	public void setDmphanloaithuocNhom2(String dmphanloaithuocNhom2) {
		this.dmphanloaithuocNhom2 = dmphanloaithuocNhom2;
	}

	@Column(name = "DMPHANLOAITHUOC_NHOM3", length = 2)
	@Length(max = 2)
	public String getDmphanloaithuocNhom3() {
		return this.dmphanloaithuocNhom3;
	}

	public void setDmphanloaithuocNhom3(String dmphanloaithuocNhom3) {
		this.dmphanloaithuocNhom3 = dmphanloaithuocNhom3;
	}

	@Column(name = "DMPHANLOAITHUOC_DUNGTICH")
	public Boolean getDmphanloaithuocDungtich() {
		return this.dmphanloaithuocDungtich;
	}

	public void setDmphanloaithuocDungtich(Boolean dmphanloaithuocDungtich) {
		this.dmphanloaithuocDungtich = dmphanloaithuocDungtich;
	}

	@Column(name = "DMPHANLOAITHUOC_GHICHU", length = 8)
	@Length(max = 8)
	public String getDmphanloaithuocGhichu() {
		return this.dmphanloaithuocGhichu;
	}

	public void setDmphanloaithuocGhichu(String dmphanloaithuocGhichu) {
		this.dmphanloaithuocGhichu = dmphanloaithuocGhichu;
	}

	@Column(name = "DMPHANLOAITHUOC_THUTUBC")
	public Integer getDmphanloaithuocThutubc() {
		return this.dmphanloaithuocThutubc;
	}

	public void setDmphanloaithuocThutubc(Integer dmphanloaithuocThutubc) {
		this.dmphanloaithuocThutubc = dmphanloaithuocThutubc;
	}

	@Column(name = "DMPHANLOAITHUOC_LOAI")
	public Integer getDmphanloaithuocLoai() {
		return this.dmphanloaithuocLoai;
	}

	public void setDmphanloaithuocLoai(Integer dmphanloaithuocLoai) {
		this.dmphanloaithuocLoai = dmphanloaithuocLoai;
	}

	@Column(name = "DMPHANLOAITHUOC_DT")
	public Boolean getDmphanloaithuocDt() {
		return this.dmphanloaithuocDt;
	}

	public void setDmphanloaithuocDt(Boolean dmphanloaithuocDt) {
		this.dmphanloaithuocDt = dmphanloaithuocDt;
	}

	@Column(name = "DMPHANLOAITHUOC_QL")
	public Boolean getDmphanloaithuocQl() {
		return this.dmphanloaithuocQl;
	}

	public void setDmphanloaithuocQl(Boolean dmphanloaithuocQl) {
		this.dmphanloaithuocQl = dmphanloaithuocQl;
	}

	@Column(name = "DMPHANLOAITHUOC_DP")
	public Boolean getDmphanloaithuocDp() {
		return this.dmphanloaithuocDp;
	}

	public void setDmphanloaithuocDp(Boolean dmphanloaithuocDp) {
		this.dmphanloaithuocDp = dmphanloaithuocDp;
	}

	@Column(name = "DMPHANLOAITHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmphanloaithuocNgaygiocn() {
		return this.dmphanloaithuocNgaygiocn;
	}

	public void setDmphanloaithuocNgaygiocn(Double dmphanloaithuocNgaygiocn) {
		this.dmphanloaithuocNgaygiocn = dmphanloaithuocNgaygiocn;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanLoaiThuocByDmphanloaithuocMaso")
	public Set<DmThuoc> getDmThuocsForDmphanloaithuocMaso() {
		return this.dmThuocsForDmphanloaithuocMaso;
	}

	public void setDmThuocsForDmphanloaithuocMaso(
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso) {
		this.dmThuocsForDmphanloaithuocMaso = dmThuocsForDmphanloaithuocMaso;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanLoaiThuocByDmphanloaithuocMaso")
	public Set<DmThuoc> getDmThuocsForDmphanloaithuocMaso_1() {
		return this.dmThuocsForDmphanloaithuocMaso_1;
	}

	public void setDmThuocsForDmphanloaithuocMaso_1(
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso_1) {
		this.dmThuocsForDmphanloaithuocMaso_1 = dmThuocsForDmphanloaithuocMaso_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanLoaiThuocByDmphanloaithuocMaso2")
	public Set<DmThuoc> getDmThuocsForDmphanloaithuocMaso2() {
		return this.dmThuocsForDmphanloaithuocMaso2;
	}

	public void setDmThuocsForDmphanloaithuocMaso2(
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2) {
		this.dmThuocsForDmphanloaithuocMaso2 = dmThuocsForDmphanloaithuocMaso2;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmPhanLoaiThuocByDmphanloaithuocMaso2")
	public Set<DmThuoc> getDmThuocsForDmphanloaithuocMaso2_1() {
		return this.dmThuocsForDmphanloaithuocMaso2_1;
	}

	public void setDmThuocsForDmphanloaithuocMaso2_1(
			Set<DmThuoc> dmThuocsForDmphanloaithuocMaso2_1) {
		this.dmThuocsForDmphanloaithuocMaso2_1 = dmThuocsForDmphanloaithuocMaso2_1;
	}

}
