package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmPhuongThucGayTaiNan generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_PHUONG_THUC_GAY_TAI_NAN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMPTGTN_MA"))
public class DmPhuongThucGayTaiNan implements java.io.Serializable {

	private Integer dmptgtnMaso;
	private DmTaiNan dmTaiNan;
	private String dmptgtnMa;
	private String dmptgtnTen;
	private Boolean dmptgtnBhyt;
	private Boolean dmptgtnDt;
	private Boolean dmptgtnQl;
	private Boolean dmptgtnDp;
	private Double dmptgtnNgaygiocn;

	public DmPhuongThucGayTaiNan() {
	}

	public DmPhuongThucGayTaiNan(String dmptgtnMa, String dmptgtnTen) {
		this.dmptgtnMa = dmptgtnMa;
		this.dmptgtnTen = dmptgtnTen;
	}

	public DmPhuongThucGayTaiNan(DmTaiNan dmTaiNan, String dmptgtnMa,
			String dmptgtnTen, Boolean dmptgtnBhyt, Boolean dmptgtnDt,
			Boolean dmptgtnQl, Boolean dmptgtnDp, Double dmptgtnNgaygiocn) {
		this.dmTaiNan = dmTaiNan;
		this.dmptgtnMa = dmptgtnMa;
		this.dmptgtnTen = dmptgtnTen;
		this.dmptgtnBhyt = dmptgtnBhyt;
		this.dmptgtnDt = dmptgtnDt;
		this.dmptgtnQl = dmptgtnQl;
		this.dmptgtnDp = dmptgtnDp;
		this.dmptgtnNgaygiocn = dmptgtnNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_PHUONG_THUC_GAY_TAI_NAN")
	@SequenceGenerator(name = "DM_PHUONG_THUC_GAY_TAI_NAN", sequenceName = "DM_PHUONG_THUC_GAY_TAI_NAN_DMP", allocationSize = 1)
	@Column(name = "DMPTGTN_MASO", unique = true, nullable = false)
	public Integer getDmptgtnMaso() {
		return this.dmptgtnMaso;
	}

	public void setDmptgtnMaso(Integer dmptgtnMaso) {
		this.dmptgtnMaso = dmptgtnMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTAINAN_MASO")
	public DmTaiNan getDmTaiNan() {
		return this.dmTaiNan;
	}

	public void setDmTaiNan(DmTaiNan dmTaiNan) {
		this.dmTaiNan = dmTaiNan;
	}

	@Column(name = "DMPTGTN_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmptgtnMa() {
		return this.dmptgtnMa;
	}

	public void setDmptgtnMa(String dmptgtnMa) {
		this.dmptgtnMa = dmptgtnMa;
	}

	@Column(name = "DMPTGTN_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmptgtnTen() {
		return this.dmptgtnTen;
	}

	public void setDmptgtnTen(String dmptgtnTen) {
		this.dmptgtnTen = dmptgtnTen;
	}

	@Column(name = "DMPTGTN_BHYT")
	public Boolean getDmptgtnBhyt() {
		return this.dmptgtnBhyt;
	}

	public void setDmptgtnBhyt(Boolean dmptgtnBhyt) {
		this.dmptgtnBhyt = dmptgtnBhyt;
	}

	@Column(name = "DMPTGTN_DT")
	public Boolean getDmptgtnDt() {
		return this.dmptgtnDt;
	}

	public void setDmptgtnDt(Boolean dmptgtnDt) {
		this.dmptgtnDt = dmptgtnDt;
	}

	@Column(name = "DMPTGTN_QL")
	public Boolean getDmptgtnQl() {
		return this.dmptgtnQl;
	}

	public void setDmptgtnQl(Boolean dmptgtnQl) {
		this.dmptgtnQl = dmptgtnQl;
	}

	@Column(name = "DMPTGTN_DP")
	public Boolean getDmptgtnDp() {
		return this.dmptgtnDp;
	}

	public void setDmptgtnDp(Boolean dmptgtnDp) {
		this.dmptgtnDp = dmptgtnDp;
	}

	@Column(name = "DMPTGTN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmptgtnNgaygiocn() {
		return this.dmptgtnNgaygiocn;
	}

	public void setDmptgtnNgaygiocn(Double dmptgtnNgaygiocn) {
		this.dmptgtnNgaygiocn = dmptgtnNgaygiocn;
	}

}
