package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmQuocGia generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_QUOC_GIA", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMQUOCGIA_MA"))
public class DmQuocGia implements java.io.Serializable {

	private Integer dmquocgiaMaso;
	private String dmquocgiaMa;
	private String dmquocgiaTen;
	private String dmquocgiaTenvn;
	private Double dmquocgiaNgaygiocn;
	private Boolean dmquocgiaChon;
	private Set<DmThuoc> dmThuocs = new HashSet<DmThuoc>(0);
	private Set<DmThuoc> dmThuocs_1 = new HashSet<DmThuoc>(0);

	public DmQuocGia() {
	}

	public DmQuocGia(String dmquocgiaMa, String dmquocgiaTen) {
		this.dmquocgiaMa = dmquocgiaMa;
		this.dmquocgiaTen = dmquocgiaTen;
	}

	public DmQuocGia(String dmquocgiaMa, String dmquocgiaTen,
			String dmquocgiaTenvn, Double dmquocgiaNgaygiocn,
			Boolean dmquocgiaChon, Set<DmThuoc> dmThuocs,
			Set<DmThuoc> dmThuocs_1) {
		this.dmquocgiaMa = dmquocgiaMa;
		this.dmquocgiaTen = dmquocgiaTen;
		this.dmquocgiaTenvn = dmquocgiaTenvn;
		this.dmquocgiaNgaygiocn = dmquocgiaNgaygiocn;
		this.dmquocgiaChon = dmquocgiaChon;
		this.dmThuocs = dmThuocs;
		this.dmThuocs_1 = dmThuocs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_QUOC_GIA")
	@SequenceGenerator(name = "DM_QUOC_GIA", sequenceName = "DM_QUOC_GIA_DMQUOCGIA_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMQUOCGIA_MASO", unique = true, nullable = false)
	public Integer getDmquocgiaMaso() {
		return this.dmquocgiaMaso;
	}

	public void setDmquocgiaMaso(Integer dmquocgiaMaso) {
		this.dmquocgiaMaso = dmquocgiaMaso;
	}

	@Column(name = "DMQUOCGIA_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmquocgiaMa() {
		return this.dmquocgiaMa;
	}

	public void setDmquocgiaMa(String dmquocgiaMa) {
		this.dmquocgiaMa = dmquocgiaMa;
	}

	@Column(name = "DMQUOCGIA_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDmquocgiaTen() {
		return this.dmquocgiaTen;
	}

	public void setDmquocgiaTen(String dmquocgiaTen) {
		this.dmquocgiaTen = dmquocgiaTen;
	}

	@Column(name = "DMQUOCGIA_TENVN", length = 250)
	@Length(max = 250)
	public String getDmquocgiaTenvn() {
		return this.dmquocgiaTenvn;
	}

	public void setDmquocgiaTenvn(String dmquocgiaTenvn) {
		this.dmquocgiaTenvn = dmquocgiaTenvn;
	}

	@Column(name = "DMQUOCGIA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmquocgiaNgaygiocn() {
		return this.dmquocgiaNgaygiocn;
	}

	public void setDmquocgiaNgaygiocn(Double dmquocgiaNgaygiocn) {
		this.dmquocgiaNgaygiocn = dmquocgiaNgaygiocn;
	}

	@Column(name = "DMQUOCGIA_CHON")
	public Boolean getDmquocgiaChon() {
		return this.dmquocgiaChon;
	}

	public void setDmquocgiaChon(Boolean dmquocgiaChon) {
		this.dmquocgiaChon = dmquocgiaChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmQuocGia")
	public Set<DmThuoc> getDmThuocs() {
		return this.dmThuocs;
	}

	public void setDmThuocs(Set<DmThuoc> dmThuocs) {
		this.dmThuocs = dmThuocs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmQuocGia")
	public Set<DmThuoc> getDmThuocs_1() {
		return this.dmThuocs_1;
	}

	public void setDmThuocs_1(Set<DmThuoc> dmThuocs_1) {
		this.dmThuocs_1 = dmThuocs_1;
	}

}
