package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmQuanHeGiaDinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_QUAN_HE_GIA_DINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMQHGD_MA"))
public class DmQuanHeGiaDinh implements java.io.Serializable {

	private Integer dmqhgdMaso;
	private String dmqhgdMa;
	private String dmqhgdTen;
	private Boolean dmqhgdDt;
	private Boolean dmqhgdQl;
	private Boolean dmqhgdDp;
	private Double dmqhgdNgaygiocn;

	public DmQuanHeGiaDinh() {
	}

	public DmQuanHeGiaDinh(String dmqhgdTen) {
		this.dmqhgdTen = dmqhgdTen;
	}

	public DmQuanHeGiaDinh(String dmqhgdMa, String dmqhgdTen, Boolean dmqhgdDt,
			Boolean dmqhgdQl, Boolean dmqhgdDp, Double dmqhgdNgaygiocn) {
		this.dmqhgdMa = dmqhgdMa;
		this.dmqhgdTen = dmqhgdTen;
		this.dmqhgdDt = dmqhgdDt;
		this.dmqhgdQl = dmqhgdQl;
		this.dmqhgdDp = dmqhgdDp;
		this.dmqhgdNgaygiocn = dmqhgdNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_QUAN_HE_GIA_DINH")
	@SequenceGenerator(name = "DM_QUAN_HE_GIA_DINH", sequenceName = "DM_QUAN_HE_GIA_DINH_DMQHGD_MAS", allocationSize = 1)
	@Column(name = "DMQHGD_MASO", unique = true, nullable = false)
	public Integer getDmqhgdMaso() {
		return this.dmqhgdMaso;
	}

	public void setDmqhgdMaso(Integer dmqhgdMaso) {
		this.dmqhgdMaso = dmqhgdMaso;
	}

	@Column(name = "DMQHGD_MA", unique = true, length = 10)
	@Length(max = 10)
	public String getDmqhgdMa() {
		return this.dmqhgdMa;
	}

	public void setDmqhgdMa(String dmqhgdMa) {
		this.dmqhgdMa = dmqhgdMa;
	}

	@Column(name = "DMQHGD_TEN", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDmqhgdTen() {
		return this.dmqhgdTen;
	}

	public void setDmqhgdTen(String dmqhgdTen) {
		this.dmqhgdTen = dmqhgdTen;
	}

	@Column(name = "DMQHGD_DT")
	public Boolean getDmqhgdDt() {
		return this.dmqhgdDt;
	}

	public void setDmqhgdDt(Boolean dmqhgdDt) {
		this.dmqhgdDt = dmqhgdDt;
	}

	@Column(name = "DMQHGD_QL")
	public Boolean getDmqhgdQl() {
		return this.dmqhgdQl;
	}

	public void setDmqhgdQl(Boolean dmqhgdQl) {
		this.dmqhgdQl = dmqhgdQl;
	}

	@Column(name = "DMQHGD_DP")
	public Boolean getDmqhgdDp() {
		return this.dmqhgdDp;
	}

	public void setDmqhgdDp(Boolean dmqhgdDp) {
		this.dmqhgdDp = dmqhgdDp;
	}

	@Column(name = "DMQHGD_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmqhgdNgaygiocn() {
		return this.dmqhgdNgaygiocn;
	}

	public void setDmqhgdNgaygiocn(Double dmqhgdNgaygiocn) {
		this.dmqhgdNgaygiocn = dmqhgdNgaygiocn;
	}

}
