package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmThanhPhanGiaDinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_THANH_PHAN_GIA_DINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMTPGD_MA"))
public class DmThanhPhanGiaDinh implements java.io.Serializable {

	private Integer dmtpgdMaso;
	private String dmtpgdMa;
	private String dmtpgdTen;
	private Double dmtpgdNgaygiocn;
	private Boolean dmtpgdDt;
	private Boolean dmtpgdQl;
	private Boolean dmtpgdDp;

	public DmThanhPhanGiaDinh() {
	}

	public DmThanhPhanGiaDinh(String dmtpgdMa) {
		this.dmtpgdMa = dmtpgdMa;
	}

	public DmThanhPhanGiaDinh(String dmtpgdMa, String dmtpgdTen,
			Double dmtpgdNgaygiocn, Boolean dmtpgdDt, Boolean dmtpgdQl,
			Boolean dmtpgdDp) {
		this.dmtpgdMa = dmtpgdMa;
		this.dmtpgdTen = dmtpgdTen;
		this.dmtpgdNgaygiocn = dmtpgdNgaygiocn;
		this.dmtpgdDt = dmtpgdDt;
		this.dmtpgdQl = dmtpgdQl;
		this.dmtpgdDp = dmtpgdDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_THANH_PHAN_GIA_DINH")
	@SequenceGenerator(name = "DM_THANH_PHAN_GIA_DINH", sequenceName = "DM_THANH_PHAN_GIA_DINH_DMTPGD_", allocationSize = 1)
	@Column(name = "DMTPGD_MASO", unique = true, nullable = false)
	public Integer getDmtpgdMaso() {
		return this.dmtpgdMaso;
	}

	public void setDmtpgdMaso(Integer dmtpgdMaso) {
		this.dmtpgdMaso = dmtpgdMaso;
	}

	@Column(name = "DMTPGD_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmtpgdMa() {
		return this.dmtpgdMa;
	}

	public void setDmtpgdMa(String dmtpgdMa) {
		this.dmtpgdMa = dmtpgdMa;
	}

	@Column(name = "DMTPGD_TEN", length = 100)
	@Length(max = 100)
	public String getDmtpgdTen() {
		return this.dmtpgdTen;
	}

	public void setDmtpgdTen(String dmtpgdTen) {
		this.dmtpgdTen = dmtpgdTen;
	}

	@Column(name = "DMTPGD_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmtpgdNgaygiocn() {
		return this.dmtpgdNgaygiocn;
	}

	public void setDmtpgdNgaygiocn(Double dmtpgdNgaygiocn) {
		this.dmtpgdNgaygiocn = dmtpgdNgaygiocn;
	}

	@Column(name = "DMTPGD_DT")
	public Boolean getDmtpgdDt() {
		return this.dmtpgdDt;
	}

	public void setDmtpgdDt(Boolean dmtpgdDt) {
		this.dmtpgdDt = dmtpgdDt;
	}

	@Column(name = "DMTPGD_QL")
	public Boolean getDmtpgdQl() {
		return this.dmtpgdQl;
	}

	public void setDmtpgdQl(Boolean dmtpgdQl) {
		this.dmtpgdQl = dmtpgdQl;
	}

	@Column(name = "DMTPGD_DP")
	public Boolean getDmtpgdDp() {
		return this.dmtpgdDp;
	}

	public void setDmtpgdDp(Boolean dmtpgdDp) {
		this.dmtpgdDp = dmtpgdDp;
	}

}
