package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmThuoc generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_THUOC", catalog = "DB_YTDT_BD")
public class DmThuoc implements java.io.Serializable {

	private Integer dmthuocMaso;
	private DmDonViTinh dmDonViTinh;
	private DmCachDungThuoc dmCachDungThuoc;
	private DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso;
	private DmNhaSanXuat dmNhaSanXuat;
	private DmHoatChat dmHoatChat;
	private DmBaoQuanThuoc dmBaoQuanThuoc;
	private DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso;
	private DmQuocGia dmQuocGia;
	private DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso2;
	private DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso2;
	private String dmthuocMa;
	private String dmthuocTenkh;
	private String dmthuocMaphu;
	private String dmthuocSets;
	private String dmthuocTen;
	private String dmthuocHamluong;
	private Integer dmthuocDungtich;
	private String dmthuocCapphat;
	private Boolean dmthuocNchu;
	private Double dmthuocTonmax;
	private Double dmthuocTonmin;
	private Boolean dmthuocThuvo;
	private Boolean dmthuocYeucau;
	private Boolean dmthuocYcu;
	private Boolean dmthuocHoichan;
	private Boolean dmthuocTruongkhoa;
	private String dmthuocNuoc;
	private Boolean dmthuocMien;
	private Boolean dmthuocDam;
	private Boolean dmthuocCorti;
	private Boolean dmthuocKhongthu;
	private Short dmthuocTylebh;
	private Boolean dmthuocDutru;
	private Integer dmthuocDonggoi;
	private Boolean dmthuocPhatbn;
	private Double dmthuocDongiabh;
	private String dmthuocPhankhoc;
	private String dmthuocPhankhol;
	private String dmthuocPhankhob;
	private String dmthuocThutu;
	private Double dmthuocLieu;
	private String dmthuocDacbiet;
	private String dmthuocMahang2;
	private Boolean dmthuocKetoa;
	private Boolean dmthuocLinhgop;
	private Boolean dmthuocIndanhmuc;
	private Boolean dmthuocInplinh;
	private Boolean dmthuocInylenh;
	private String dmthuocGchu;
	private Boolean dmthuocNgoaitru;
	private Boolean dmthuocNoitru;
	private Boolean dmthuocTreem;
	private Date dmthuocNgaybosung;
	private Double dmthuocNgaygiocn;
	private Boolean dmthuocDt;
	private Boolean dmthuocDp;
	private Boolean dmthuocQl;
	private String dtdmnhanvienCn;
	private Double dmthuocDonggiaDauthau;
	private String dmthuocSodk;
	private Boolean dmthuocKhongxuat;
	private Short dmthuocPlbhyt;

	public DmThuoc() {
	}

	public DmThuoc(String dmthuocMa, String dmthuocTen) {
		this.dmthuocMa = dmthuocMa;
		this.dmthuocTen = dmthuocTen;
	}

	public DmThuoc(DmDonViTinh dmDonViTinh, DmCachDungThuoc dmCachDungThuoc,
			DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso,
			DmNhaSanXuat dmNhaSanXuat, DmHoatChat dmHoatChat,
			DmBaoQuanThuoc dmBaoQuanThuoc,
			DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso,
			DmQuocGia dmQuocGia,
			DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso2,
			DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso2,
			String dmthuocMa, String dmthuocTenkh, String dmthuocMaphu,
			String dmthuocSets, String dmthuocTen, String dmthuocHamluong,
			Integer dmthuocDungtich, String dmthuocCapphat,
			Boolean dmthuocNchu, Double dmthuocTonmax, Double dmthuocTonmin,
			Boolean dmthuocThuvo, Boolean dmthuocYeucau, Boolean dmthuocYcu,
			Boolean dmthuocHoichan, Boolean dmthuocTruongkhoa,
			String dmthuocNuoc, Boolean dmthuocMien, Boolean dmthuocDam,
			Boolean dmthuocCorti, Boolean dmthuocKhongthu, Short dmthuocTylebh,
			Boolean dmthuocDutru, Integer dmthuocDonggoi,
			Boolean dmthuocPhatbn, Double dmthuocDongiabh,
			String dmthuocPhankhoc, String dmthuocPhankhol,
			String dmthuocPhankhob, String dmthuocThutu, Double dmthuocLieu,
			String dmthuocDacbiet, String dmthuocMahang2, Boolean dmthuocKetoa,
			Boolean dmthuocLinhgop, Boolean dmthuocIndanhmuc,
			Boolean dmthuocInplinh, Boolean dmthuocInylenh, String dmthuocGchu,
			Boolean dmthuocNgoaitru, Boolean dmthuocNoitru,
			Boolean dmthuocTreem, Date dmthuocNgaybosung,
			Double dmthuocNgaygiocn, Boolean dmthuocDt, Boolean dmthuocDp,
			Boolean dmthuocQl, String dtdmnhanvienCn,
			Double dmthuocDonggiaDauthau, String dmthuocSodk,
			Boolean dmthuocKhongxuat, Short dmthuocPlbhyt) {
		this.dmDonViTinh = dmDonViTinh;
		this.dmCachDungThuoc = dmCachDungThuoc;
		this.dmPhanLoaiThuocByDmphanloaithuocMaso = dmPhanLoaiThuocByDmphanloaithuocMaso;
		this.dmNhaSanXuat = dmNhaSanXuat;
		this.dmHoatChat = dmHoatChat;
		this.dmBaoQuanThuoc = dmBaoQuanThuoc;
		this.dmPhanNhomThuocByDmphannhomthuocMaso = dmPhanNhomThuocByDmphannhomthuocMaso;
		this.dmQuocGia = dmQuocGia;
		this.dmPhanLoaiThuocByDmphanloaithuocMaso2 = dmPhanLoaiThuocByDmphanloaithuocMaso2;
		this.dmPhanNhomThuocByDmphannhomthuocMaso2 = dmPhanNhomThuocByDmphannhomthuocMaso2;
		this.dmthuocMa = dmthuocMa;
		this.dmthuocTenkh = dmthuocTenkh;
		this.dmthuocMaphu = dmthuocMaphu;
		this.dmthuocSets = dmthuocSets;
		this.dmthuocTen = dmthuocTen;
		this.dmthuocHamluong = dmthuocHamluong;
		this.dmthuocDungtich = dmthuocDungtich;
		this.dmthuocCapphat = dmthuocCapphat;
		this.dmthuocNchu = dmthuocNchu;
		this.dmthuocTonmax = dmthuocTonmax;
		this.dmthuocTonmin = dmthuocTonmin;
		this.dmthuocThuvo = dmthuocThuvo;
		this.dmthuocYeucau = dmthuocYeucau;
		this.dmthuocYcu = dmthuocYcu;
		this.dmthuocHoichan = dmthuocHoichan;
		this.dmthuocTruongkhoa = dmthuocTruongkhoa;
		this.dmthuocNuoc = dmthuocNuoc;
		this.dmthuocMien = dmthuocMien;
		this.dmthuocDam = dmthuocDam;
		this.dmthuocCorti = dmthuocCorti;
		this.dmthuocKhongthu = dmthuocKhongthu;
		this.dmthuocTylebh = dmthuocTylebh;
		this.dmthuocDutru = dmthuocDutru;
		this.dmthuocDonggoi = dmthuocDonggoi;
		this.dmthuocPhatbn = dmthuocPhatbn;
		this.dmthuocDongiabh = dmthuocDongiabh;
		this.dmthuocPhankhoc = dmthuocPhankhoc;
		this.dmthuocPhankhol = dmthuocPhankhol;
		this.dmthuocPhankhob = dmthuocPhankhob;
		this.dmthuocThutu = dmthuocThutu;
		this.dmthuocLieu = dmthuocLieu;
		this.dmthuocDacbiet = dmthuocDacbiet;
		this.dmthuocMahang2 = dmthuocMahang2;
		this.dmthuocKetoa = dmthuocKetoa;
		this.dmthuocLinhgop = dmthuocLinhgop;
		this.dmthuocIndanhmuc = dmthuocIndanhmuc;
		this.dmthuocInplinh = dmthuocInplinh;
		this.dmthuocInylenh = dmthuocInylenh;
		this.dmthuocGchu = dmthuocGchu;
		this.dmthuocNgoaitru = dmthuocNgoaitru;
		this.dmthuocNoitru = dmthuocNoitru;
		this.dmthuocTreem = dmthuocTreem;
		this.dmthuocNgaybosung = dmthuocNgaybosung;
		this.dmthuocNgaygiocn = dmthuocNgaygiocn;
		this.dmthuocDt = dmthuocDt;
		this.dmthuocDp = dmthuocDp;
		this.dmthuocQl = dmthuocQl;
		this.dtdmnhanvienCn = dtdmnhanvienCn;
		this.dmthuocDonggiaDauthau = dmthuocDonggiaDauthau;
		this.dmthuocSodk = dmthuocSodk;
		this.dmthuocKhongxuat = dmthuocKhongxuat;
		this.dmthuocPlbhyt = dmthuocPlbhyt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_THUOC")
	@SequenceGenerator(name = "DM_THUOC", sequenceName = "DM_THUOC_DMTHUOC_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMTHUOC_MASO", unique = true, nullable = false)
	public Integer getDmthuocMaso() {
		return this.dmthuocMaso;
	}

	public void setDmthuocMaso(Integer dmthuocMaso) {
		this.dmthuocMaso = dmthuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMDONVITINH_MASO")
	public DmDonViTinh getDmDonViTinh() {
		return this.dmDonViTinh;
	}

	public void setDmDonViTinh(DmDonViTinh dmDonViTinh) {
		this.dmDonViTinh = dmDonViTinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMCACHDUNG_MASO")
	public DmCachDungThuoc getDmCachDungThuoc() {
		return this.dmCachDungThuoc;
	}

	public void setDmCachDungThuoc(DmCachDungThuoc dmCachDungThuoc) {
		this.dmCachDungThuoc = dmCachDungThuoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMPHANLOAITHUOC_MASO")
	public DmPhanLoaiThuoc getDmPhanLoaiThuocByDmphanloaithuocMaso() {
		return this.dmPhanLoaiThuocByDmphanloaithuocMaso;
	}

	public void setDmPhanLoaiThuocByDmphanloaithuocMaso(
			DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso) {
		this.dmPhanLoaiThuocByDmphanloaithuocMaso = dmPhanLoaiThuocByDmphanloaithuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMNHASANXUAT_MASO")
	public DmNhaSanXuat getDmNhaSanXuat() {
		return this.dmNhaSanXuat;
	}

	public void setDmNhaSanXuat(DmNhaSanXuat dmNhaSanXuat) {
		this.dmNhaSanXuat = dmNhaSanXuat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTHUOC_HOATCHAT")
	public DmHoatChat getDmHoatChat() {
		return this.dmHoatChat;
	}

	public void setDmHoatChat(DmHoatChat dmHoatChat) {
		this.dmHoatChat = dmHoatChat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMBAOQUAN_MASO")
	public DmBaoQuanThuoc getDmBaoQuanThuoc() {
		return this.dmBaoQuanThuoc;
	}

	public void setDmBaoQuanThuoc(DmBaoQuanThuoc dmBaoQuanThuoc) {
		this.dmBaoQuanThuoc = dmBaoQuanThuoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMPHANNHOMTHUOC_MASO")
	public DmPhanNhomThuoc getDmPhanNhomThuocByDmphannhomthuocMaso() {
		return this.dmPhanNhomThuocByDmphannhomthuocMaso;
	}

	public void setDmPhanNhomThuocByDmphannhomthuocMaso(
			DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso) {
		this.dmPhanNhomThuocByDmphannhomthuocMaso = dmPhanNhomThuocByDmphannhomthuocMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTHUOC_NUOCDEFA")
	public DmQuocGia getDmQuocGia() {
		return this.dmQuocGia;
	}

	public void setDmQuocGia(DmQuocGia dmQuocGia) {
		this.dmQuocGia = dmQuocGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMPHANLOAITHUOC_MASO2")
	public DmPhanLoaiThuoc getDmPhanLoaiThuocByDmphanloaithuocMaso2() {
		return this.dmPhanLoaiThuocByDmphanloaithuocMaso2;
	}

	public void setDmPhanLoaiThuocByDmphanloaithuocMaso2(
			DmPhanLoaiThuoc dmPhanLoaiThuocByDmphanloaithuocMaso2) {
		this.dmPhanLoaiThuocByDmphanloaithuocMaso2 = dmPhanLoaiThuocByDmphanloaithuocMaso2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMPHANNHOMTHUOC_MASO2")
	public DmPhanNhomThuoc getDmPhanNhomThuocByDmphannhomthuocMaso2() {
		return this.dmPhanNhomThuocByDmphannhomthuocMaso2;
	}

	public void setDmPhanNhomThuocByDmphannhomthuocMaso2(
			DmPhanNhomThuoc dmPhanNhomThuocByDmphannhomthuocMaso2) {
		this.dmPhanNhomThuocByDmphannhomthuocMaso2 = dmPhanNhomThuocByDmphannhomthuocMaso2;
	}

	@Column(name = "DMTHUOC_MA", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDmthuocMa() {
		return this.dmthuocMa;
	}

	public void setDmthuocMa(String dmthuocMa) {
		this.dmthuocMa = dmthuocMa;
	}

	@Column(name = "DMTHUOC_TENKH", length = 250)
	@Length(max = 250)
	public String getDmthuocTenkh() {
		return this.dmthuocTenkh;
	}

	public void setDmthuocTenkh(String dmthuocTenkh) {
		this.dmthuocTenkh = dmthuocTenkh;
	}

	@Column(name = "DMTHUOC_MAPHU", length = 8)
	@Length(max = 8)
	public String getDmthuocMaphu() {
		return this.dmthuocMaphu;
	}

	public void setDmthuocMaphu(String dmthuocMaphu) {
		this.dmthuocMaphu = dmthuocMaphu;
	}

	@Column(name = "DMTHUOC_SETS", length = 4)
	@Length(max = 4)
	public String getDmthuocSets() {
		return this.dmthuocSets;
	}

	public void setDmthuocSets(String dmthuocSets) {
		this.dmthuocSets = dmthuocSets;
	}

	@Column(name = "DMTHUOC_TEN", nullable = false)
	@NotNull
	public String getDmthuocTen() {
		return this.dmthuocTen;
	}

	public void setDmthuocTen(String dmthuocTen) {
		this.dmthuocTen = dmthuocTen;
	}

	@Column(name = "DMTHUOC_HAMLUONG", length = 250)
	@Length(max = 250)
	public String getDmthuocHamluong() {
		return this.dmthuocHamluong;
	}

	public void setDmthuocHamluong(String dmthuocHamluong) {
		this.dmthuocHamluong = dmthuocHamluong;
	}

	@Column(name = "DMTHUOC_DUNGTICH")
	public Integer getDmthuocDungtich() {
		return this.dmthuocDungtich;
	}

	public void setDmthuocDungtich(Integer dmthuocDungtich) {
		this.dmthuocDungtich = dmthuocDungtich;
	}

	@Column(name = "DMTHUOC_CAPPHAT", length = 2)
	@Length(max = 2)
	public String getDmthuocCapphat() {
		return this.dmthuocCapphat;
	}

	public void setDmthuocCapphat(String dmthuocCapphat) {
		this.dmthuocCapphat = dmthuocCapphat;
	}

	@Column(name = "DMTHUOC_NCHU")
	public Boolean getDmthuocNchu() {
		return this.dmthuocNchu;
	}

	public void setDmthuocNchu(Boolean dmthuocNchu) {
		this.dmthuocNchu = dmthuocNchu;
	}

	@Column(name = "DMTHUOC_TONMAX", precision = 22, scale = 0)
	public Double getDmthuocTonmax() {
		return this.dmthuocTonmax;
	}

	public void setDmthuocTonmax(Double dmthuocTonmax) {
		this.dmthuocTonmax = dmthuocTonmax;
	}

	@Column(name = "DMTHUOC_TONMIN", precision = 22, scale = 0)
	public Double getDmthuocTonmin() {
		return this.dmthuocTonmin;
	}

	public void setDmthuocTonmin(Double dmthuocTonmin) {
		this.dmthuocTonmin = dmthuocTonmin;
	}

	@Column(name = "DMTHUOC_THUVO")
	public Boolean getDmthuocThuvo() {
		return this.dmthuocThuvo;
	}

	public void setDmthuocThuvo(Boolean dmthuocThuvo) {
		this.dmthuocThuvo = dmthuocThuvo;
	}

	@Column(name = "DMTHUOC_YEUCAU")
	public Boolean getDmthuocYeucau() {
		return this.dmthuocYeucau;
	}

	public void setDmthuocYeucau(Boolean dmthuocYeucau) {
		this.dmthuocYeucau = dmthuocYeucau;
	}

	@Column(name = "DMTHUOC_YCU")
	public Boolean getDmthuocYcu() {
		return this.dmthuocYcu;
	}

	public void setDmthuocYcu(Boolean dmthuocYcu) {
		this.dmthuocYcu = dmthuocYcu;
	}

	@Column(name = "DMTHUOC_HOICHAN")
	public Boolean getDmthuocHoichan() {
		return this.dmthuocHoichan;
	}

	public void setDmthuocHoichan(Boolean dmthuocHoichan) {
		this.dmthuocHoichan = dmthuocHoichan;
	}

	@Column(name = "DMTHUOC_TRUONGKHOA")
	public Boolean getDmthuocTruongkhoa() {
		return this.dmthuocTruongkhoa;
	}

	public void setDmthuocTruongkhoa(Boolean dmthuocTruongkhoa) {
		this.dmthuocTruongkhoa = dmthuocTruongkhoa;
	}

	@Column(name = "DMTHUOC_NUOC", length = 3)
	@Length(max = 3)
	public String getDmthuocNuoc() {
		return this.dmthuocNuoc;
	}

	public void setDmthuocNuoc(String dmthuocNuoc) {
		this.dmthuocNuoc = dmthuocNuoc;
	}

	@Column(name = "DMTHUOC_MIEN")
	public Boolean getDmthuocMien() {
		return this.dmthuocMien;
	}

	public void setDmthuocMien(Boolean dmthuocMien) {
		this.dmthuocMien = dmthuocMien;
	}

	@Column(name = "DMTHUOC_DAM")
	public Boolean getDmthuocDam() {
		return this.dmthuocDam;
	}

	public void setDmthuocDam(Boolean dmthuocDam) {
		this.dmthuocDam = dmthuocDam;
	}

	@Column(name = "DMTHUOC_CORTI")
	public Boolean getDmthuocCorti() {
		return this.dmthuocCorti;
	}

	public void setDmthuocCorti(Boolean dmthuocCorti) {
		this.dmthuocCorti = dmthuocCorti;
	}

	@Column(name = "DMTHUOC_KHONGTHU")
	public Boolean getDmthuocKhongthu() {
		return this.dmthuocKhongthu;
	}

	public void setDmthuocKhongthu(Boolean dmthuocKhongthu) {
		this.dmthuocKhongthu = dmthuocKhongthu;
	}

	@Column(name = "DMTHUOC_TYLEBH")
	public Short getDmthuocTylebh() {
		return this.dmthuocTylebh;
	}

	public void setDmthuocTylebh(Short dmthuocTylebh) {
		this.dmthuocTylebh = dmthuocTylebh;
	}

	@Column(name = "DMTHUOC_DUTRU")
	public Boolean getDmthuocDutru() {
		return this.dmthuocDutru;
	}

	public void setDmthuocDutru(Boolean dmthuocDutru) {
		this.dmthuocDutru = dmthuocDutru;
	}

	@Column(name = "DMTHUOC_DONGGOI")
	public Integer getDmthuocDonggoi() {
		return this.dmthuocDonggoi;
	}

	public void setDmthuocDonggoi(Integer dmthuocDonggoi) {
		this.dmthuocDonggoi = dmthuocDonggoi;
	}

	@Column(name = "DMTHUOC_PHATBN")
	public Boolean getDmthuocPhatbn() {
		return this.dmthuocPhatbn;
	}

	public void setDmthuocPhatbn(Boolean dmthuocPhatbn) {
		this.dmthuocPhatbn = dmthuocPhatbn;
	}

	@Column(name = "DMTHUOC_DONGIABH", precision = 22, scale = 0)
	public Double getDmthuocDongiabh() {
		return this.dmthuocDongiabh;
	}

	public void setDmthuocDongiabh(Double dmthuocDongiabh) {
		this.dmthuocDongiabh = dmthuocDongiabh;
	}

	@Column(name = "DMTHUOC_PHANKHOC", length = 2)
	@Length(max = 2)
	public String getDmthuocPhankhoc() {
		return this.dmthuocPhankhoc;
	}

	public void setDmthuocPhankhoc(String dmthuocPhankhoc) {
		this.dmthuocPhankhoc = dmthuocPhankhoc;
	}

	@Column(name = "DMTHUOC_PHANKHOL", length = 2)
	@Length(max = 2)
	public String getDmthuocPhankhol() {
		return this.dmthuocPhankhol;
	}

	public void setDmthuocPhankhol(String dmthuocPhankhol) {
		this.dmthuocPhankhol = dmthuocPhankhol;
	}

	@Column(name = "DMTHUOC_PHANKHOB", length = 2)
	@Length(max = 2)
	public String getDmthuocPhankhob() {
		return this.dmthuocPhankhob;
	}

	public void setDmthuocPhankhob(String dmthuocPhankhob) {
		this.dmthuocPhankhob = dmthuocPhankhob;
	}

	@Column(name = "DMTHUOC_THUTU", length = 6)
	@Length(max = 6)
	public String getDmthuocThutu() {
		return this.dmthuocThutu;
	}

	public void setDmthuocThutu(String dmthuocThutu) {
		this.dmthuocThutu = dmthuocThutu;
	}

	@Column(name = "DMTHUOC_LIEU", precision = 22, scale = 0)
	public Double getDmthuocLieu() {
		return this.dmthuocLieu;
	}

	public void setDmthuocLieu(Double dmthuocLieu) {
		this.dmthuocLieu = dmthuocLieu;
	}

	@Column(name = "DMTHUOC_DACBIET", length = 2)
	@Length(max = 2)
	public String getDmthuocDacbiet() {
		return this.dmthuocDacbiet;
	}

	public void setDmthuocDacbiet(String dmthuocDacbiet) {
		this.dmthuocDacbiet = dmthuocDacbiet;
	}

	@Column(name = "DMTHUOC_MAHANG2", length = 12)
	@Length(max = 12)
	public String getDmthuocMahang2() {
		return this.dmthuocMahang2;
	}

	public void setDmthuocMahang2(String dmthuocMahang2) {
		this.dmthuocMahang2 = dmthuocMahang2;
	}

	@Column(name = "DMTHUOC_KETOA")
	public Boolean getDmthuocKetoa() {
		return this.dmthuocKetoa;
	}

	public void setDmthuocKetoa(Boolean dmthuocKetoa) {
		this.dmthuocKetoa = dmthuocKetoa;
	}

	@Column(name = "DMTHUOC_LINHGOP")
	public Boolean getDmthuocLinhgop() {
		return this.dmthuocLinhgop;
	}

	public void setDmthuocLinhgop(Boolean dmthuocLinhgop) {
		this.dmthuocLinhgop = dmthuocLinhgop;
	}

	@Column(name = "DMTHUOC_INDANHMUC")
	public Boolean getDmthuocIndanhmuc() {
		return this.dmthuocIndanhmuc;
	}

	public void setDmthuocIndanhmuc(Boolean dmthuocIndanhmuc) {
		this.dmthuocIndanhmuc = dmthuocIndanhmuc;
	}

	@Column(name = "DMTHUOC_INPLINH")
	public Boolean getDmthuocInplinh() {
		return this.dmthuocInplinh;
	}

	public void setDmthuocInplinh(Boolean dmthuocInplinh) {
		this.dmthuocInplinh = dmthuocInplinh;
	}

	@Column(name = "DMTHUOC_INYLENH")
	public Boolean getDmthuocInylenh() {
		return this.dmthuocInylenh;
	}

	public void setDmthuocInylenh(Boolean dmthuocInylenh) {
		this.dmthuocInylenh = dmthuocInylenh;
	}

	@Column(name = "DMTHUOC_GCHU", length = 25)
	@Length(max = 25)
	public String getDmthuocGchu() {
		return this.dmthuocGchu;
	}

	public void setDmthuocGchu(String dmthuocGchu) {
		this.dmthuocGchu = dmthuocGchu;
	}

	@Column(name = "DMTHUOC_NGOAITRU")
	public Boolean getDmthuocNgoaitru() {
		return this.dmthuocNgoaitru;
	}

	public void setDmthuocNgoaitru(Boolean dmthuocNgoaitru) {
		this.dmthuocNgoaitru = dmthuocNgoaitru;
	}

	@Column(name = "DMTHUOC_NOITRU")
	public Boolean getDmthuocNoitru() {
		return this.dmthuocNoitru;
	}

	public void setDmthuocNoitru(Boolean dmthuocNoitru) {
		this.dmthuocNoitru = dmthuocNoitru;
	}

	@Column(name = "DMTHUOC_TREEM")
	public Boolean getDmthuocTreem() {
		return this.dmthuocTreem;
	}

	public void setDmthuocTreem(Boolean dmthuocTreem) {
		this.dmthuocTreem = dmthuocTreem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DMTHUOC_NGAYBOSUNG", length = 0)
	public Date getDmthuocNgaybosung() {
		return this.dmthuocNgaybosung;
	}

	public void setDmthuocNgaybosung(Date dmthuocNgaybosung) {
		this.dmthuocNgaybosung = dmthuocNgaybosung;
	}

	@Column(name = "DMTHUOC_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmthuocNgaygiocn() {
		return this.dmthuocNgaygiocn;
	}

	public void setDmthuocNgaygiocn(Double dmthuocNgaygiocn) {
		this.dmthuocNgaygiocn = dmthuocNgaygiocn;
	}

	@Column(name = "DMTHUOC_DT")
	public Boolean getDmthuocDt() {
		return this.dmthuocDt;
	}

	public void setDmthuocDt(Boolean dmthuocDt) {
		this.dmthuocDt = dmthuocDt;
	}

	@Column(name = "DMTHUOC_DP")
	public Boolean getDmthuocDp() {
		return this.dmthuocDp;
	}

	public void setDmthuocDp(Boolean dmthuocDp) {
		this.dmthuocDp = dmthuocDp;
	}

	@Column(name = "DMTHUOC_QL")
	public Boolean getDmthuocQl() {
		return this.dmthuocQl;
	}

	public void setDmthuocQl(Boolean dmthuocQl) {
		this.dmthuocQl = dmthuocQl;
	}

	@Column(name = "DTDMNHANVIEN_CN", length = 25)
	@Length(max = 25)
	public String getDtdmnhanvienCn() {
		return this.dtdmnhanvienCn;
	}

	public void setDtdmnhanvienCn(String dtdmnhanvienCn) {
		this.dtdmnhanvienCn = dtdmnhanvienCn;
	}

	@Column(name = "DMTHUOC_DONGGIA_DAUTHAU", precision = 22, scale = 0)
	public Double getDmthuocDonggiaDauthau() {
		return this.dmthuocDonggiaDauthau;
	}

	public void setDmthuocDonggiaDauthau(Double dmthuocDonggiaDauthau) {
		this.dmthuocDonggiaDauthau = dmthuocDonggiaDauthau;
	}

	@Column(name = "DMTHUOC_SODK", length = 200)
	@Length(max = 200)
	public String getDmthuocSodk() {
		return this.dmthuocSodk;
	}

	public void setDmthuocSodk(String dmthuocSodk) {
		this.dmthuocSodk = dmthuocSodk;
	}

	@Column(name = "DMTHUOC_KHONGXUAT")
	public Boolean getDmthuocKhongxuat() {
		return this.dmthuocKhongxuat;
	}

	public void setDmthuocKhongxuat(Boolean dmthuocKhongxuat) {
		this.dmthuocKhongxuat = dmthuocKhongxuat;
	}

	@Column(name = "DMTHUOC_PLBHYT")
	public Short getDmthuocPlbhyt() {
		return this.dmthuocPlbhyt;
	}

	public void setDmthuocPlbhyt(Short dmthuocPlbhyt) {
		this.dmthuocPlbhyt = dmthuocPlbhyt;
	}

}
