package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmTinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_TINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DMTINH_MA"))
public class DmTinh implements java.io.Serializable {

	private Integer dmtinhMaso;
	private String dmtinhMa;
	private Boolean dmhuyenMa;
	private Boolean dmxaMa;
	private String dmtinhTen;
	private Boolean dmtinhDefa;
	private Double dmtinhNgaygiocn;
	private Boolean dmtinhChon;
	private String dmtinhMabhyt;
	private Set<DmHuyen> dmHuyens = new HashSet<DmHuyen>(0);
	private Set<DmBenhVien> dmBenhViens = new HashSet<DmBenhVien>(0);
	private Set<DmDonVi> dmDonVis = new HashSet<DmDonVi>(0);
	private Set<DmDonVi> dmDonVis_1 = new HashSet<DmDonVi>(0);
	private Set<DmNhaCungCap> dmNhaCungCaps = new HashSet<DmNhaCungCap>(0);
	private Set<DmBenhVien> dmBenhViens_1 = new HashSet<DmBenhVien>(0);
	private Set<DtDmKhach> dtDmKhachs = new HashSet<DtDmKhach>(0);
	private Set<DmHuyen> dmHuyens_1 = new HashSet<DmHuyen>(0);
	private Set<DtDmKhach> dtDmKhachs_1 = new HashSet<DtDmKhach>(0);
	private Set<DmNhaCungCap> dmNhaCungCaps_1 = new HashSet<DmNhaCungCap>(0);

	public DmTinh() {
	}

	public DmTinh(String dmtinhMa, String dmtinhTen) {
		this.dmtinhMa = dmtinhMa;
		this.dmtinhTen = dmtinhTen;
	}

	public DmTinh(String dmtinhMa, Boolean dmhuyenMa, Boolean dmxaMa,
			String dmtinhTen, Boolean dmtinhDefa, Double dmtinhNgaygiocn,
			Boolean dmtinhChon, String dmtinhMabhyt, Set<DmHuyen> dmHuyens,
			Set<DmBenhVien> dmBenhViens, Set<DmDonVi> dmDonVis,
			Set<DmDonVi> dmDonVis_1, Set<DmNhaCungCap> dmNhaCungCaps,
			Set<DmBenhVien> dmBenhViens_1, Set<DtDmKhach> dtDmKhachs,
			Set<DmHuyen> dmHuyens_1, Set<DtDmKhach> dtDmKhachs_1,
			Set<DmNhaCungCap> dmNhaCungCaps_1) {
		this.dmtinhMa = dmtinhMa;
		this.dmhuyenMa = dmhuyenMa;
		this.dmxaMa = dmxaMa;
		this.dmtinhTen = dmtinhTen;
		this.dmtinhDefa = dmtinhDefa;
		this.dmtinhNgaygiocn = dmtinhNgaygiocn;
		this.dmtinhChon = dmtinhChon;
		this.dmtinhMabhyt = dmtinhMabhyt;
		this.dmHuyens = dmHuyens;
		this.dmBenhViens = dmBenhViens;
		this.dmDonVis = dmDonVis;
		this.dmDonVis_1 = dmDonVis_1;
		this.dmNhaCungCaps = dmNhaCungCaps;
		this.dmBenhViens_1 = dmBenhViens_1;
		this.dtDmKhachs = dtDmKhachs;
		this.dmHuyens_1 = dmHuyens_1;
		this.dtDmKhachs_1 = dtDmKhachs_1;
		this.dmNhaCungCaps_1 = dmNhaCungCaps_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_TINH")
	@SequenceGenerator(name = "DM_TINH", sequenceName = "DM_TINH_DMTINH_MASO_SEQ", allocationSize = 1)
	@Column(name = "DMTINH_MASO", unique = true, nullable = false)
	public Integer getDmtinhMaso() {
		return this.dmtinhMaso;
	}

	public void setDmtinhMaso(Integer dmtinhMaso) {
		this.dmtinhMaso = dmtinhMaso;
	}

	@Column(name = "DMTINH_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDmtinhMa() {
		return this.dmtinhMa;
	}

	public void setDmtinhMa(String dmtinhMa) {
		this.dmtinhMa = dmtinhMa;
	}

	@Column(name = "DMHUYEN_MA")
	public Boolean getDmhuyenMa() {
		return this.dmhuyenMa;
	}

	public void setDmhuyenMa(Boolean dmhuyenMa) {
		this.dmhuyenMa = dmhuyenMa;
	}

	@Column(name = "DMXA_MA")
	public Boolean getDmxaMa() {
		return this.dmxaMa;
	}

	public void setDmxaMa(Boolean dmxaMa) {
		this.dmxaMa = dmxaMa;
	}

	@Column(name = "DMTINH_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDmtinhTen() {
		return this.dmtinhTen;
	}

	public void setDmtinhTen(String dmtinhTen) {
		this.dmtinhTen = dmtinhTen;
	}

	@Column(name = "DMTINH_DEFA")
	public Boolean getDmtinhDefa() {
		return this.dmtinhDefa;
	}

	public void setDmtinhDefa(Boolean dmtinhDefa) {
		this.dmtinhDefa = dmtinhDefa;
	}

	@Column(name = "DMTINH_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmtinhNgaygiocn() {
		return this.dmtinhNgaygiocn;
	}

	public void setDmtinhNgaygiocn(Double dmtinhNgaygiocn) {
		this.dmtinhNgaygiocn = dmtinhNgaygiocn;
	}

	@Column(name = "DMTINH_CHON")
	public Boolean getDmtinhChon() {
		return this.dmtinhChon;
	}

	public void setDmtinhChon(Boolean dmtinhChon) {
		this.dmtinhChon = dmtinhChon;
	}

	@Column(name = "DMTINH_MABHYT", length = 2)
	@Length(max = 2)
	public String getDmtinhMabhyt() {
		return this.dmtinhMabhyt;
	}

	public void setDmtinhMabhyt(String dmtinhMabhyt) {
		this.dmtinhMabhyt = dmtinhMabhyt;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmHuyen> getDmHuyens() {
		return this.dmHuyens;
	}

	public void setDmHuyens(Set<DmHuyen> dmHuyens) {
		this.dmHuyens = dmHuyens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmBenhVien> getDmBenhViens() {
		return this.dmBenhViens;
	}

	public void setDmBenhViens(Set<DmBenhVien> dmBenhViens) {
		this.dmBenhViens = dmBenhViens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmDonVi> getDmDonVis() {
		return this.dmDonVis;
	}

	public void setDmDonVis(Set<DmDonVi> dmDonVis) {
		this.dmDonVis = dmDonVis;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmDonVi> getDmDonVis_1() {
		return this.dmDonVis_1;
	}

	public void setDmDonVis_1(Set<DmDonVi> dmDonVis_1) {
		this.dmDonVis_1 = dmDonVis_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmNhaCungCap> getDmNhaCungCaps() {
		return this.dmNhaCungCaps;
	}

	public void setDmNhaCungCaps(Set<DmNhaCungCap> dmNhaCungCaps) {
		this.dmNhaCungCaps = dmNhaCungCaps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmBenhVien> getDmBenhViens_1() {
		return this.dmBenhViens_1;
	}

	public void setDmBenhViens_1(Set<DmBenhVien> dmBenhViens_1) {
		this.dmBenhViens_1 = dmBenhViens_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DtDmKhach> getDtDmKhachs() {
		return this.dtDmKhachs;
	}

	public void setDtDmKhachs(Set<DtDmKhach> dtDmKhachs) {
		this.dtDmKhachs = dtDmKhachs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmHuyen> getDmHuyens_1() {
		return this.dmHuyens_1;
	}

	public void setDmHuyens_1(Set<DmHuyen> dmHuyens_1) {
		this.dmHuyens_1 = dmHuyens_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DtDmKhach> getDtDmKhachs_1() {
		return this.dtDmKhachs_1;
	}

	public void setDtDmKhachs_1(Set<DtDmKhach> dtDmKhachs_1) {
		this.dtDmKhachs_1 = dtDmKhachs_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dmTinh")
	public Set<DmNhaCungCap> getDmNhaCungCaps_1() {
		return this.dmNhaCungCaps_1;
	}

	public void setDmNhaCungCaps_1(Set<DmNhaCungCap> dmNhaCungCaps_1) {
		this.dmNhaCungCaps_1 = dmNhaCungCaps_1;
	}

}
