package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * DmTrangThaiHoSo generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_TRANG_THAI_HO_SO", catalog = "DB_YTDT_BD")
public class DmTrangThaiHoSo implements java.io.Serializable {

	private Integer dmtthsMaso;
	private String dmtthsMa;
	private String dmtthsTen;
	private String dmtthsGhichu;
	private Boolean dmtthsDt;
	private Boolean dmtthsQl;
	private Boolean dmtthsDp;

	public DmTrangThaiHoSo() {
	}

	public DmTrangThaiHoSo(String dmtthsMa, String dmtthsTen,
			String dmtthsGhichu, Boolean dmtthsDt, Boolean dmtthsQl,
			Boolean dmtthsDp) {
		this.dmtthsMa = dmtthsMa;
		this.dmtthsTen = dmtthsTen;
		this.dmtthsGhichu = dmtthsGhichu;
		this.dmtthsDt = dmtthsDt;
		this.dmtthsQl = dmtthsQl;
		this.dmtthsDp = dmtthsDp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DM_TRANG_THAI_HO_SO")
	@SequenceGenerator(name = "DM_TRANG_THAI_HO_SO", sequenceName = "DM_TRANG_THAI_HO_SO_DMTTHS_MAS", allocationSize = 1)
	@Column(name = "DMTTHS_MASO", unique = true, nullable = false)
	public Integer getDmtthsMaso() {
		return this.dmtthsMaso;
	}

	public void setDmtthsMaso(Integer dmtthsMaso) {
		this.dmtthsMaso = dmtthsMaso;
	}

	@Column(name = "DMTTHS_MA", length = 15)
	@Length(max = 15)
	public String getDmtthsMa() {
		return this.dmtthsMa;
	}

	public void setDmtthsMa(String dmtthsMa) {
		this.dmtthsMa = dmtthsMa;
	}

	@Column(name = "DMTTHS_TEN", length = 100)
	@Length(max = 100)
	public String getDmtthsTen() {
		return this.dmtthsTen;
	}

	public void setDmtthsTen(String dmtthsTen) {
		this.dmtthsTen = dmtthsTen;
	}

	@Column(name = "DMTTHS_GHICHU", length = 100)
	@Length(max = 100)
	public String getDmtthsGhichu() {
		return this.dmtthsGhichu;
	}

	public void setDmtthsGhichu(String dmtthsGhichu) {
		this.dmtthsGhichu = dmtthsGhichu;
	}

	@Column(name = "DMTTHS_DT")
	public Boolean getDmtthsDt() {
		return this.dmtthsDt;
	}

	public void setDmtthsDt(Boolean dmtthsDt) {
		this.dmtthsDt = dmtthsDt;
	}

	@Column(name = "DMTTHS_QL")
	public Boolean getDmtthsQl() {
		return this.dmtthsQl;
	}

	public void setDmtthsQl(Boolean dmtthsQl) {
		this.dmtthsQl = dmtthsQl;
	}

	@Column(name = "DMTTHS_DP")
	public Boolean getDmtthsDp() {
		return this.dmtthsDp;
	}

	public void setDmtthsDp(Boolean dmtthsDp) {
		this.dmtthsDp = dmtthsDp;
	}

}
