package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DmTuyenDonVi generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DM_TUYEN_DON_VI", catalog = "DB_YTDT_BD")
public class DmTuyenDonVi implements java.io.Serializable {

	private DmTuyenDonViId id;
	private DmDonVi dmDonVi;
	private DmTuyen dmTuyen;
	private String dmtuyenMa;
	private Double dmtuyendonviNgaygiocn;
	private Boolean dmtuyendonviDt;
	private Boolean dmtuyendonviQl;
	private Boolean dmtuyendonviDp;

	public DmTuyenDonVi() {
	}

	public DmTuyenDonVi(DmTuyenDonViId id, DmDonVi dmDonVi, DmTuyen dmTuyen,
			String dmtuyenMa) {
		this.id = id;
		this.dmDonVi = dmDonVi;
		this.dmTuyen = dmTuyen;
		this.dmtuyenMa = dmtuyenMa;
	}

	public DmTuyenDonVi(DmTuyenDonViId id, DmDonVi dmDonVi, DmTuyen dmTuyen,
			String dmtuyenMa, Double dmtuyendonviNgaygiocn,
			Boolean dmtuyendonviDt, Boolean dmtuyendonviQl,
			Boolean dmtuyendonviDp) {
		this.id = id;
		this.dmDonVi = dmDonVi;
		this.dmTuyen = dmTuyen;
		this.dmtuyenMa = dmtuyenMa;
		this.dmtuyendonviNgaygiocn = dmtuyendonviNgaygiocn;
		this.dmtuyendonviDt = dmtuyendonviDt;
		this.dmtuyendonviQl = dmtuyendonviQl;
		this.dmtuyendonviDp = dmtuyendonviDp;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "dmtuyenMaso", column = @Column(name = "DMTUYEN_MASO", nullable = false)),
			@AttributeOverride(name = "dmdonviMaso", column = @Column(name = "DMDONVI_MASO", nullable = false)) })
	@NotNull
	public DmTuyenDonViId getId() {
		return this.id;
	}

	public void setId(DmTuyenDonViId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMDONVI_MASO", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DmDonVi getDmDonVi() {
		return this.dmDonVi;
	}

	public void setDmDonVi(DmDonVi dmDonVi) {
		this.dmDonVi = dmDonVi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMTUYEN_MASO", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DmTuyen getDmTuyen() {
		return this.dmTuyen;
	}

	public void setDmTuyen(DmTuyen dmTuyen) {
		this.dmTuyen = dmTuyen;
	}

	@Column(name = "DMTUYEN_MA", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDmtuyenMa() {
		return this.dmtuyenMa;
	}

	public void setDmtuyenMa(String dmtuyenMa) {
		this.dmtuyenMa = dmtuyenMa;
	}

	@Column(name = "DMTUYENDONVI_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDmtuyendonviNgaygiocn() {
		return this.dmtuyendonviNgaygiocn;
	}

	public void setDmtuyendonviNgaygiocn(Double dmtuyendonviNgaygiocn) {
		this.dmtuyendonviNgaygiocn = dmtuyendonviNgaygiocn;
	}

	@Column(name = "DMTUYENDONVI_DT")
	public Boolean getDmtuyendonviDt() {
		return this.dmtuyendonviDt;
	}

	public void setDmtuyendonviDt(Boolean dmtuyendonviDt) {
		this.dmtuyendonviDt = dmtuyendonviDt;
	}

	@Column(name = "DMTUYENDONVI_QL")
	public Boolean getDmtuyendonviQl() {
		return this.dmtuyendonviQl;
	}

	public void setDmtuyendonviQl(Boolean dmtuyendonviQl) {
		this.dmtuyendonviQl = dmtuyendonviQl;
	}

	@Column(name = "DMTUYENDONVI_DP")
	public Boolean getDmtuyendonviDp() {
		return this.dmtuyendonviDp;
	}

	public void setDmtuyendonviDp(Boolean dmtuyendonviDp) {
		this.dmtuyendonviDp = dmtuyendonviDp;
	}

}
