package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DonMien generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DON_MIEN", catalog = "DB_YTDT_BD")
public class DonMien implements java.io.Serializable {

	private String donmienMa;
	private DmKhoa dmKhoa;
	private DtDmNhanVien dtDmNhanVien;
	private String hsbaSovaovien;
	private Double donmienChiphi;
	private Double donmienMiengiam;
	private Double donmienMienphi;
	private Double donmienBhyt;
	private Double donmienBntra;
	private Double donmienTamung;
	private Date donmienNgay;
	private Short donmienCum;
	private Date donmienNgaygiocn;
	private String donmienLydo;
	private Boolean donmienMienphong;
	private Boolean donmienMiencpdt;
	private Short donmienMienmau;
	private Boolean donmienMienktc;
	private Boolean donmienMienconlai;
	private Boolean donmienMienngay;
	private Date donmienNgay1;
	private Date donmienNgay2;
	private String donmienMienkhac;
	private String donmienStatus;

	public DonMien() {
	}

	public DonMien(String donmienMa, DtDmNhanVien dtDmNhanVien,
			String hsbaSovaovien) {
		this.donmienMa = donmienMa;
		this.dtDmNhanVien = dtDmNhanVien;
		this.hsbaSovaovien = hsbaSovaovien;
	}

	public DonMien(String donmienMa, DmKhoa dmKhoa, DtDmNhanVien dtDmNhanVien,
			String hsbaSovaovien, Double donmienChiphi, Double donmienMiengiam,
			Double donmienMienphi, Double donmienBhyt, Double donmienBntra,
			Double donmienTamung, Date donmienNgay, Short donmienCum,
			Date donmienNgaygiocn, String donmienLydo,
			Boolean donmienMienphong, Boolean donmienMiencpdt,
			Short donmienMienmau, Boolean donmienMienktc,
			Boolean donmienMienconlai, Boolean donmienMienngay,
			Date donmienNgay1, Date donmienNgay2, String donmienMienkhac,
			String donmienStatus) {
		this.donmienMa = donmienMa;
		this.dmKhoa = dmKhoa;
		this.dtDmNhanVien = dtDmNhanVien;
		this.hsbaSovaovien = hsbaSovaovien;
		this.donmienChiphi = donmienChiphi;
		this.donmienMiengiam = donmienMiengiam;
		this.donmienMienphi = donmienMienphi;
		this.donmienBhyt = donmienBhyt;
		this.donmienBntra = donmienBntra;
		this.donmienTamung = donmienTamung;
		this.donmienNgay = donmienNgay;
		this.donmienCum = donmienCum;
		this.donmienNgaygiocn = donmienNgaygiocn;
		this.donmienLydo = donmienLydo;
		this.donmienMienphong = donmienMienphong;
		this.donmienMiencpdt = donmienMiencpdt;
		this.donmienMienmau = donmienMienmau;
		this.donmienMienktc = donmienMienktc;
		this.donmienMienconlai = donmienMienconlai;
		this.donmienMienngay = donmienMienngay;
		this.donmienNgay1 = donmienNgay1;
		this.donmienNgay2 = donmienNgay2;
		this.donmienMienkhac = donmienMienkhac;
		this.donmienStatus = donmienStatus;
	}

	@Id
	@Column(name = "DONMIEN_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDonmienMa() {
		return this.donmienMa;
	}

	public void setDonmienMa(String donmienMa) {
		this.donmienMa = donmienMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DONMIEN_KHOA")
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DONMIEN_NHANVIENCN", nullable = false)
	@NotNull
	public DtDmNhanVien getDtDmNhanVien() {
		return this.dtDmNhanVien;
	}

	public void setDtDmNhanVien(DtDmNhanVien dtDmNhanVien) {
		this.dtDmNhanVien = dtDmNhanVien;
	}

	@Column(name = "HSBA_SOVAOVIEN", nullable = false, length = 17)
	@NotNull
	@Length(max = 17)
	public String getHsbaSovaovien() {
		return this.hsbaSovaovien;
	}

	public void setHsbaSovaovien(String hsbaSovaovien) {
		this.hsbaSovaovien = hsbaSovaovien;
	}

	@Column(name = "DONMIEN_CHIPHI", precision = 22, scale = 0)
	public Double getDonmienChiphi() {
		return this.donmienChiphi;
	}

	public void setDonmienChiphi(Double donmienChiphi) {
		this.donmienChiphi = donmienChiphi;
	}

	@Column(name = "DONMIEN_MIENGIAM", precision = 22, scale = 0)
	public Double getDonmienMiengiam() {
		return this.donmienMiengiam;
	}

	public void setDonmienMiengiam(Double donmienMiengiam) {
		this.donmienMiengiam = donmienMiengiam;
	}

	@Column(name = "DONMIEN_MIENPHI", precision = 22, scale = 0)
	public Double getDonmienMienphi() {
		return this.donmienMienphi;
	}

	public void setDonmienMienphi(Double donmienMienphi) {
		this.donmienMienphi = donmienMienphi;
	}

	@Column(name = "DONMIEN_BHYT", precision = 22, scale = 0)
	public Double getDonmienBhyt() {
		return this.donmienBhyt;
	}

	public void setDonmienBhyt(Double donmienBhyt) {
		this.donmienBhyt = donmienBhyt;
	}

	@Column(name = "DONMIEN_BNTRA", precision = 22, scale = 0)
	public Double getDonmienBntra() {
		return this.donmienBntra;
	}

	public void setDonmienBntra(Double donmienBntra) {
		this.donmienBntra = donmienBntra;
	}

	@Column(name = "DONMIEN_TAMUNG", precision = 22, scale = 0)
	public Double getDonmienTamung() {
		return this.donmienTamung;
	}

	public void setDonmienTamung(Double donmienTamung) {
		this.donmienTamung = donmienTamung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DONMIEN_NGAY", length = 0)
	public Date getDonmienNgay() {
		return this.donmienNgay;
	}

	public void setDonmienNgay(Date donmienNgay) {
		this.donmienNgay = donmienNgay;
	}

	@Column(name = "DONMIEN_CUM")
	public Short getDonmienCum() {
		return this.donmienCum;
	}

	public void setDonmienCum(Short donmienCum) {
		this.donmienCum = donmienCum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DONMIEN_NGAYGIOCN", length = 0)
	public Date getDonmienNgaygiocn() {
		return this.donmienNgaygiocn;
	}

	public void setDonmienNgaygiocn(Date donmienNgaygiocn) {
		this.donmienNgaygiocn = donmienNgaygiocn;
	}

	@Column(name = "DONMIEN_LYDO", length = 512)
	@Length(max = 512)
	public String getDonmienLydo() {
		return this.donmienLydo;
	}

	public void setDonmienLydo(String donmienLydo) {
		this.donmienLydo = donmienLydo;
	}

	@Column(name = "DONMIEN_MIENPHONG")
	public Boolean getDonmienMienphong() {
		return this.donmienMienphong;
	}

	public void setDonmienMienphong(Boolean donmienMienphong) {
		this.donmienMienphong = donmienMienphong;
	}

	@Column(name = "DONMIEN_MIENCPDT")
	public Boolean getDonmienMiencpdt() {
		return this.donmienMiencpdt;
	}

	public void setDonmienMiencpdt(Boolean donmienMiencpdt) {
		this.donmienMiencpdt = donmienMiencpdt;
	}

	@Column(name = "DONMIEN_MIENMAU")
	public Short getDonmienMienmau() {
		return this.donmienMienmau;
	}

	public void setDonmienMienmau(Short donmienMienmau) {
		this.donmienMienmau = donmienMienmau;
	}

	@Column(name = "DONMIEN_MIENKTC")
	public Boolean getDonmienMienktc() {
		return this.donmienMienktc;
	}

	public void setDonmienMienktc(Boolean donmienMienktc) {
		this.donmienMienktc = donmienMienktc;
	}

	@Column(name = "DONMIEN_MIENCONLAI")
	public Boolean getDonmienMienconlai() {
		return this.donmienMienconlai;
	}

	public void setDonmienMienconlai(Boolean donmienMienconlai) {
		this.donmienMienconlai = donmienMienconlai;
	}

	@Column(name = "DONMIEN_MIENNGAY")
	public Boolean getDonmienMienngay() {
		return this.donmienMienngay;
	}

	public void setDonmienMienngay(Boolean donmienMienngay) {
		this.donmienMienngay = donmienMienngay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DONMIEN_NGAY1", length = 0)
	public Date getDonmienNgay1() {
		return this.donmienNgay1;
	}

	public void setDonmienNgay1(Date donmienNgay1) {
		this.donmienNgay1 = donmienNgay1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DONMIEN_NGAY2", length = 0)
	public Date getDonmienNgay2() {
		return this.donmienNgay2;
	}

	public void setDonmienNgay2(Date donmienNgay2) {
		this.donmienNgay2 = donmienNgay2;
	}

	@Column(name = "DONMIEN_MIENKHAC", length = 4)
	@Length(max = 4)
	public String getDonmienMienkhac() {
		return this.donmienMienkhac;
	}

	public void setDonmienMienkhac(String donmienMienkhac) {
		this.donmienMienkhac = donmienMienkhac;
	}

	@Column(name = "DONMIEN_STATUS", length = 4)
	@Length(max = 4)
	public String getDonmienStatus() {
		return this.donmienStatus;
	}

	public void setDonmienStatus(String donmienStatus) {
		this.donmienStatus = donmienStatus;
	}

}
