package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmCls generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CLS", catalog = "DB_YTDT_BD")
public class DtDmCls implements java.io.Serializable {

	private Integer dtdmclsMaso;
	private DtDmPbCls dtDmPbCls;
	private String dtdmclsMa;
	private String dtdmclsTen;
	private String dtdmclsChudau;
	private Short dtdmclsThutubc;
	private Double dtdmclsNgaygiocn;
	private Boolean dtdmclsChon;
	private String dtdmpbclsMa;
	private String dtdmclsTendbf;
	private Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgPhanloai = new HashSet<DtDmClsBangGia>(
			0);
	private Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgMaloai = new HashSet<DtDmClsBangGia>(
			0);

	public DtDmCls() {
	}

	public DtDmCls(String dtdmclsMa, String dtdmclsTen) {
		this.dtdmclsMa = dtdmclsMa;
		this.dtdmclsTen = dtdmclsTen;
	}

	public DtDmCls(DtDmPbCls dtDmPbCls, String dtdmclsMa, String dtdmclsTen,
			String dtdmclsChudau, Short dtdmclsThutubc,
			Double dtdmclsNgaygiocn, Boolean dtdmclsChon, String dtdmpbclsMa,
			String dtdmclsTendbf,
			Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgPhanloai,
			Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgMaloai) {
		this.dtDmPbCls = dtDmPbCls;
		this.dtdmclsMa = dtdmclsMa;
		this.dtdmclsTen = dtdmclsTen;
		this.dtdmclsChudau = dtdmclsChudau;
		this.dtdmclsThutubc = dtdmclsThutubc;
		this.dtdmclsNgaygiocn = dtdmclsNgaygiocn;
		this.dtdmclsChon = dtdmclsChon;
		this.dtdmpbclsMa = dtdmpbclsMa;
		this.dtdmclsTendbf = dtdmclsTendbf;
		this.dtDmClsBangGiasForDtdmclsbgPhanloai = dtDmClsBangGiasForDtdmclsbgPhanloai;
		this.dtDmClsBangGiasForDtdmclsbgMaloai = dtDmClsBangGiasForDtdmclsbgMaloai;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CLS")
	@SequenceGenerator(name = "DT_DM_CLS", sequenceName = "DT_DM_CLS_DTDMCLS_MASO_SEQ", allocationSize = 1)
	@Column(name = "DTDMCLS_MASO", unique = true, nullable = false)
	public Integer getDtdmclsMaso() {
		return this.dtdmclsMaso;
	}

	public void setDtdmclsMaso(Integer dtdmclsMaso) {
		this.dtdmclsMaso = dtdmclsMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMCLS_PHANBIET")
	public DtDmPbCls getDtDmPbCls() {
		return this.dtDmPbCls;
	}

	public void setDtDmPbCls(DtDmPbCls dtDmPbCls) {
		this.dtDmPbCls = dtDmPbCls;
	}

	@Column(name = "DTDMCLS_MA", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDtdmclsMa() {
		return this.dtdmclsMa;
	}

	public void setDtdmclsMa(String dtdmclsMa) {
		this.dtdmclsMa = dtdmclsMa;
	}

	@Column(name = "DTDMCLS_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmclsTen() {
		return this.dtdmclsTen;
	}

	public void setDtdmclsTen(String dtdmclsTen) {
		this.dtdmclsTen = dtdmclsTen;
	}

	@Column(name = "DTDMCLS_CHUDAU", length = 1)
	@Length(max = 1)
	public String getDtdmclsChudau() {
		return this.dtdmclsChudau;
	}

	public void setDtdmclsChudau(String dtdmclsChudau) {
		this.dtdmclsChudau = dtdmclsChudau;
	}

	@Column(name = "DTDMCLS_THUTUBC")
	public Short getDtdmclsThutubc() {
		return this.dtdmclsThutubc;
	}

	public void setDtdmclsThutubc(Short dtdmclsThutubc) {
		this.dtdmclsThutubc = dtdmclsThutubc;
	}

	@Column(name = "DTDMCLS_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmclsNgaygiocn() {
		return this.dtdmclsNgaygiocn;
	}

	public void setDtdmclsNgaygiocn(Double dtdmclsNgaygiocn) {
		this.dtdmclsNgaygiocn = dtdmclsNgaygiocn;
	}

	@Column(name = "DTDMCLS_CHON")
	public Boolean getDtdmclsChon() {
		return this.dtdmclsChon;
	}

	public void setDtdmclsChon(Boolean dtdmclsChon) {
		this.dtdmclsChon = dtdmclsChon;
	}

	@Column(name = "DTDMPBCLS_MA", length = 3)
	@Length(max = 3)
	public String getDtdmpbclsMa() {
		return this.dtdmpbclsMa;
	}

	public void setDtdmpbclsMa(String dtdmpbclsMa) {
		this.dtdmpbclsMa = dtdmpbclsMa;
	}

	@Column(name = "DTDMCLS_TENDBF", length = 4)
	@Length(max = 4)
	public String getDtdmclsTendbf() {
		return this.dtdmclsTendbf;
	}

	public void setDtdmclsTendbf(String dtdmclsTendbf) {
		this.dtdmclsTendbf = dtdmclsTendbf;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmClsByDtdmclsbgPhanloai")
	public Set<DtDmClsBangGia> getDtDmClsBangGiasForDtdmclsbgPhanloai() {
		return this.dtDmClsBangGiasForDtdmclsbgPhanloai;
	}

	public void setDtDmClsBangGiasForDtdmclsbgPhanloai(
			Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgPhanloai) {
		this.dtDmClsBangGiasForDtdmclsbgPhanloai = dtDmClsBangGiasForDtdmclsbgPhanloai;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmClsByDtdmclsbgMaloai")
	public Set<DtDmClsBangGia> getDtDmClsBangGiasForDtdmclsbgMaloai() {
		return this.dtDmClsBangGiasForDtdmclsbgMaloai;
	}

	public void setDtDmClsBangGiasForDtdmclsbgMaloai(
			Set<DtDmClsBangGia> dtDmClsBangGiasForDtdmclsbgMaloai) {
		this.dtDmClsBangGiasForDtdmclsbgMaloai = dtDmClsBangGiasForDtdmclsbgMaloai;
	}

}
