package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmDoiTuongAn generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_DOI_TUONG_AN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMDTA_MA"))
public class DtDmDoiTuongAn implements java.io.Serializable {

	private Integer dtdmdtaMaso;
	private String dtdmdtaMa;
	private String dtdmdtaTen;
	private Double dtdmdtaNgaygiocn;
	private Boolean dtdmdtaChon;

	public DtDmDoiTuongAn() {
	}

	public DtDmDoiTuongAn(String dtdmdtaMa) {
		this.dtdmdtaMa = dtdmdtaMa;
	}

	public DtDmDoiTuongAn(String dtdmdtaMa, String dtdmdtaTen,
			Double dtdmdtaNgaygiocn, Boolean dtdmdtaChon) {
		this.dtdmdtaMa = dtdmdtaMa;
		this.dtdmdtaTen = dtdmdtaTen;
		this.dtdmdtaNgaygiocn = dtdmdtaNgaygiocn;
		this.dtdmdtaChon = dtdmdtaChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_DOI_TUONG_AN")
	@SequenceGenerator(name = "DT_DM_DOI_TUONG_AN", sequenceName = "DT_DM_DOI_TUONG_AN_DTDMDTA_MAS", allocationSize = 1)
	@Column(name = "DTDMDTA_MASO", unique = true, nullable = false)
	public Integer getDtdmdtaMaso() {
		return this.dtdmdtaMaso;
	}

	public void setDtdmdtaMaso(Integer dtdmdtaMaso) {
		this.dtdmdtaMaso = dtdmdtaMaso;
	}

	@Column(name = "DTDMDTA_MA", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDtdmdtaMa() {
		return this.dtdmdtaMa;
	}

	public void setDtdmdtaMa(String dtdmdtaMa) {
		this.dtdmdtaMa = dtdmdtaMa;
	}

	@Column(name = "DTDMDTA_TEN", length = 100)
	@Length(max = 100)
	public String getDtdmdtaTen() {
		return this.dtdmdtaTen;
	}

	public void setDtdmdtaTen(String dtdmdtaTen) {
		this.dtdmdtaTen = dtdmdtaTen;
	}

	@Column(name = "DTDMDTA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmdtaNgaygiocn() {
		return this.dtdmdtaNgaygiocn;
	}

	public void setDtdmdtaNgaygiocn(Double dtdmdtaNgaygiocn) {
		this.dtdmdtaNgaygiocn = dtdmdtaNgaygiocn;
	}

	@Column(name = "DTDMDTA_CHON")
	public Boolean getDtdmdtaChon() {
		return this.dtdmdtaChon;
	}

	public void setDtdmdtaChon(Boolean dtdmdtaChon) {
		this.dtdmdtaChon = dtdmdtaChon;
	}

}
