package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmCapCuuPhien generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CAP_CUU_PHIEN", catalog = "DB_YTDT_BD")
public class DtDmCapCuuPhien implements java.io.Serializable {

	private Integer dtdmccpMaso;
	private String dtdmccpMa;
	private String dtdmccpTen;
	private Double dtdmccpNgaygiocn;
	private Boolean dtdmccpChon;

	public DtDmCapCuuPhien() {
	}

	public DtDmCapCuuPhien(String dtdmccpMa, String dtdmccpTen) {
		this.dtdmccpMa = dtdmccpMa;
		this.dtdmccpTen = dtdmccpTen;
	}

	public DtDmCapCuuPhien(String dtdmccpMa, String dtdmccpTen,
			Double dtdmccpNgaygiocn, Boolean dtdmccpChon) {
		this.dtdmccpMa = dtdmccpMa;
		this.dtdmccpTen = dtdmccpTen;
		this.dtdmccpNgaygiocn = dtdmccpNgaygiocn;
		this.dtdmccpChon = dtdmccpChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CAP_CUU_PHIEN")
	@SequenceGenerator(name = "DT_DM_CAP_CUU_PHIEN", sequenceName = "DT_DM_CAP_CUU_PHIEN_DTDMCCP_MA", allocationSize = 1)
	@Column(name = "DTDMCCP_MASO", unique = true, nullable = false)
	public Integer getDtdmccpMaso() {
		return this.dtdmccpMaso;
	}

	public void setDtdmccpMaso(Integer dtdmccpMaso) {
		this.dtdmccpMaso = dtdmccpMaso;
	}

	@Column(name = "DTDMCCP_MA", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDtdmccpMa() {
		return this.dtdmccpMa;
	}

	public void setDtdmccpMa(String dtdmccpMa) {
		this.dtdmccpMa = dtdmccpMa;
	}

	@Column(name = "DTDMCCP_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmccpTen() {
		return this.dtdmccpTen;
	}

	public void setDtdmccpTen(String dtdmccpTen) {
		this.dtdmccpTen = dtdmccpTen;
	}

	@Column(name = "DTDMCCP_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmccpNgaygiocn() {
		return this.dtdmccpNgaygiocn;
	}

	public void setDtdmccpNgaygiocn(Double dtdmccpNgaygiocn) {
		this.dtdmccpNgaygiocn = dtdmccpNgaygiocn;
	}

	@Column(name = "DTDMCCP_CHON")
	public Boolean getDtdmccpChon() {
		return this.dtdmccpChon;
	}

	public void setDtdmccpChon(Boolean dtdmccpChon) {
		this.dtdmccpChon = dtdmccpChon;
	}

}
