package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmNhomBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NHOM_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMNHOMBHYT_MA"))
public class DtDmNhomBhyt implements java.io.Serializable {

	private Integer dtdmnhombhytMaso;
	private DtDmLopBhyt dtDmLopBhyt;
	private DtDmPlBhyt dtDmPlBhyt;
	private String dtdmnhombhytMa;
	private String dtdmnhombhytTen;
	private Double dtdmnhombhytNgaygiocn;
	private Boolean dtdmnhombhytChon;
	private Boolean dtdmnhombhytDefa;
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts = new HashSet<DtDmKhoiBhyt>(0);

	public DtDmNhomBhyt() {
	}

	public DtDmNhomBhyt(String dtdmnhombhytMa, String dtdmnhombhytTen) {
		this.dtdmnhombhytMa = dtdmnhombhytMa;
		this.dtdmnhombhytTen = dtdmnhombhytTen;
	}

	public DtDmNhomBhyt(DtDmLopBhyt dtDmLopBhyt, DtDmPlBhyt dtDmPlBhyt,
			String dtdmnhombhytMa, String dtdmnhombhytTen,
			Double dtdmnhombhytNgaygiocn, Boolean dtdmnhombhytChon,
			Boolean dtdmnhombhytDefa, Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtDmLopBhyt = dtDmLopBhyt;
		this.dtDmPlBhyt = dtDmPlBhyt;
		this.dtdmnhombhytMa = dtdmnhombhytMa;
		this.dtdmnhombhytTen = dtdmnhombhytTen;
		this.dtdmnhombhytNgaygiocn = dtdmnhombhytNgaygiocn;
		this.dtdmnhombhytChon = dtdmnhombhytChon;
		this.dtdmnhombhytDefa = dtdmnhombhytDefa;
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NHOM_BHYT")
	@SequenceGenerator(name = "DT_DM_NHOM_BHYT", sequenceName = "DT_DM_NHOM_BHYT_DTDMNHOMBHYT_M", allocationSize = 1)
	@Column(name = "DTDMNHOMBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmnhombhytMaso() {
		return this.dtdmnhombhytMaso;
	}

	public void setDtdmnhombhytMaso(Integer dtdmnhombhytMaso) {
		this.dtdmnhombhytMaso = dtdmnhombhytMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMLOPBHYT_MASO")
	public DtDmLopBhyt getDtDmLopBhyt() {
		return this.dtDmLopBhyt;
	}

	public void setDtDmLopBhyt(DtDmLopBhyt dtDmLopBhyt) {
		this.dtDmLopBhyt = dtDmLopBhyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMPHLOAIBHYT_MASO")
	public DtDmPlBhyt getDtDmPlBhyt() {
		return this.dtDmPlBhyt;
	}

	public void setDtDmPlBhyt(DtDmPlBhyt dtDmPlBhyt) {
		this.dtDmPlBhyt = dtDmPlBhyt;
	}

	@Column(name = "DTDMNHOMBHYT_MA", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getDtdmnhombhytMa() {
		return this.dtdmnhombhytMa;
	}

	public void setDtdmnhombhytMa(String dtdmnhombhytMa) {
		this.dtdmnhombhytMa = dtdmnhombhytMa;
	}

	@Column(name = "DTDMNHOMBHYT_TEN", nullable = false, length = 512)
	@NotNull
	@Length(max = 512)
	public String getDtdmnhombhytTen() {
		return this.dtdmnhombhytTen;
	}

	public void setDtdmnhombhytTen(String dtdmnhombhytTen) {
		this.dtdmnhombhytTen = dtdmnhombhytTen;
	}

	@Column(name = "DTDMNHOMBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnhombhytNgaygiocn() {
		return this.dtdmnhombhytNgaygiocn;
	}

	public void setDtdmnhombhytNgaygiocn(Double dtdmnhombhytNgaygiocn) {
		this.dtdmnhombhytNgaygiocn = dtdmnhombhytNgaygiocn;
	}

	@Column(name = "DTDMNHOMBHYT_CHON")
	public Boolean getDtdmnhombhytChon() {
		return this.dtdmnhombhytChon;
	}

	public void setDtdmnhombhytChon(Boolean dtdmnhombhytChon) {
		this.dtdmnhombhytChon = dtdmnhombhytChon;
	}

	@Column(name = "DTDMNHOMBHYT_DEFA")
	public Boolean getDtdmnhombhytDefa() {
		return this.dtdmnhombhytDefa;
	}

	public void setDtdmnhombhytDefa(Boolean dtdmnhombhytDefa) {
		this.dtdmnhombhytDefa = dtdmnhombhytDefa;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhomBhyt")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts() {
		return this.dtDmKhoiBhyts;
	}

	public void setDtDmKhoiBhyts(Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

}
