package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmKhoiBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_KHOI_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMKHOIBHYT_MA"))
public class DtDmKhoiBhyt implements java.io.Serializable {

	private Integer dtdmkhoibhytMaso;
	private DtDmNhomBhyt dtDmNhomBhyt;
	private DtDmPlBhyt dtDmPlBhyt;
	private DtDmLoaiBhyt dtDmLoaiBhyt;
	private DtDmNhomBhyt2 dtDmNhomBhyt2;
	private String dtdmkhoibhytMa;
	private String dtdmkhoibhytTen;
	private Short dtdmkhoibhytTylebhyt1;
	private Short dtdmkhoibhytTylebhyt2;
	private Short dtdmkhoibhytTylektc;
	private Short dtdmkhoibhytGomyc;
	private String dtdmkhoibhytGhichu;
	private Double dtdmkhoibhytNgaygiocn;
	private Boolean dtdmkhoibhytChon;
	private Double dtdmkhoibhytGhtyle;
	private Double dtdmkhoibhytMinktc;
	private Double dtdmkhoibhytTlminktc;
	private Double dtdmkhoibhytMaxktc;
	private Double dtdmkhoibhytTlmaxktc;
	private Double dtdmkhoibhytLimitktc;
	private Double dtdmkhoibhytTylebhyt1NoiTru;
	private Double dtdmkhoibhytTylebhyt2NoiTru;
	private Double dtdmkhoibhytGhtyleNoiTru;

	public DtDmKhoiBhyt() {
	}

	public DtDmKhoiBhyt(String dtdmkhoibhytMa, String dtdmkhoibhytTen) {
		this.dtdmkhoibhytMa = dtdmkhoibhytMa;
		this.dtdmkhoibhytTen = dtdmkhoibhytTen;
	}

	public DtDmKhoiBhyt(DtDmNhomBhyt dtDmNhomBhyt, DtDmPlBhyt dtDmPlBhyt,
			DtDmLoaiBhyt dtDmLoaiBhyt, DtDmNhomBhyt2 dtDmNhomBhyt2,
			String dtdmkhoibhytMa, String dtdmkhoibhytTen,
			Short dtdmkhoibhytTylebhyt1, Short dtdmkhoibhytTylebhyt2,
			Short dtdmkhoibhytTylektc, Short dtdmkhoibhytGomyc,
			String dtdmkhoibhytGhichu, Double dtdmkhoibhytNgaygiocn,
			Boolean dtdmkhoibhytChon, Double dtdmkhoibhytGhtyle,
			Double dtdmkhoibhytMinktc, Double dtdmkhoibhytTlminktc,
			Double dtdmkhoibhytMaxktc, Double dtdmkhoibhytTlmaxktc,
			Double dtdmkhoibhytLimitktc, Double dtdmkhoibhytTylebhyt1NoiTru,
			Double dtdmkhoibhytTylebhyt2NoiTru, Double dtdmkhoibhytGhtyleNoiTru) {
		this.dtDmNhomBhyt = dtDmNhomBhyt;
		this.dtDmPlBhyt = dtDmPlBhyt;
		this.dtDmLoaiBhyt = dtDmLoaiBhyt;
		this.dtDmNhomBhyt2 = dtDmNhomBhyt2;
		this.dtdmkhoibhytMa = dtdmkhoibhytMa;
		this.dtdmkhoibhytTen = dtdmkhoibhytTen;
		this.dtdmkhoibhytTylebhyt1 = dtdmkhoibhytTylebhyt1;
		this.dtdmkhoibhytTylebhyt2 = dtdmkhoibhytTylebhyt2;
		this.dtdmkhoibhytTylektc = dtdmkhoibhytTylektc;
		this.dtdmkhoibhytGomyc = dtdmkhoibhytGomyc;
		this.dtdmkhoibhytGhichu = dtdmkhoibhytGhichu;
		this.dtdmkhoibhytNgaygiocn = dtdmkhoibhytNgaygiocn;
		this.dtdmkhoibhytChon = dtdmkhoibhytChon;
		this.dtdmkhoibhytGhtyle = dtdmkhoibhytGhtyle;
		this.dtdmkhoibhytMinktc = dtdmkhoibhytMinktc;
		this.dtdmkhoibhytTlminktc = dtdmkhoibhytTlminktc;
		this.dtdmkhoibhytMaxktc = dtdmkhoibhytMaxktc;
		this.dtdmkhoibhytTlmaxktc = dtdmkhoibhytTlmaxktc;
		this.dtdmkhoibhytLimitktc = dtdmkhoibhytLimitktc;
		this.dtdmkhoibhytTylebhyt1NoiTru = dtdmkhoibhytTylebhyt1NoiTru;
		this.dtdmkhoibhytTylebhyt2NoiTru = dtdmkhoibhytTylebhyt2NoiTru;
		this.dtdmkhoibhytGhtyleNoiTru = dtdmkhoibhytGhtyleNoiTru;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_KHOI_BHYT")
	@SequenceGenerator(name = "DT_DM_KHOI_BHYT", sequenceName = "DT_DM_KHOI_BHYT_DTDMKHOIBHYT_M", allocationSize = 1)
	@Column(name = "DTDMKHOIBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmkhoibhytMaso() {
		return this.dtdmkhoibhytMaso;
	}

	public void setDtdmkhoibhytMaso(Integer dtdmkhoibhytMaso) {
		this.dtdmkhoibhytMaso = dtdmkhoibhytMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHOMBHYT_MASO")
	public DtDmNhomBhyt getDtDmNhomBhyt() {
		return this.dtDmNhomBhyt;
	}

	public void setDtDmNhomBhyt(DtDmNhomBhyt dtDmNhomBhyt) {
		this.dtDmNhomBhyt = dtDmNhomBhyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMKHOIBHYT_PHANLOAI")
	public DtDmPlBhyt getDtDmPlBhyt() {
		return this.dtDmPlBhyt;
	}

	public void setDtDmPlBhyt(DtDmPlBhyt dtDmPlBhyt) {
		this.dtDmPlBhyt = dtDmPlBhyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMKHOIBHYT_LOAI")
	public DtDmLoaiBhyt getDtDmLoaiBhyt() {
		return this.dtDmLoaiBhyt;
	}

	public void setDtDmLoaiBhyt(DtDmLoaiBhyt dtDmLoaiBhyt) {
		this.dtDmLoaiBhyt = dtDmLoaiBhyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHOMBHYT2_MASO")
	public DtDmNhomBhyt2 getDtDmNhomBhyt2() {
		return this.dtDmNhomBhyt2;
	}

	public void setDtDmNhomBhyt2(DtDmNhomBhyt2 dtDmNhomBhyt2) {
		this.dtDmNhomBhyt2 = dtDmNhomBhyt2;
	}

	@Column(name = "DTDMKHOIBHYT_MA", unique = true, nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getDtdmkhoibhytMa() {
		return this.dtdmkhoibhytMa;
	}

	public void setDtdmkhoibhytMa(String dtdmkhoibhytMa) {
		this.dtdmkhoibhytMa = dtdmkhoibhytMa;
	}

	@Column(name = "DTDMKHOIBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmkhoibhytTen() {
		return this.dtdmkhoibhytTen;
	}

	public void setDtdmkhoibhytTen(String dtdmkhoibhytTen) {
		this.dtdmkhoibhytTen = dtdmkhoibhytTen;
	}

	@Column(name = "DTDMKHOIBHYT_TYLEBHYT1")
	public Short getDtdmkhoibhytTylebhyt1() {
		return this.dtdmkhoibhytTylebhyt1;
	}

	public void setDtdmkhoibhytTylebhyt1(Short dtdmkhoibhytTylebhyt1) {
		this.dtdmkhoibhytTylebhyt1 = dtdmkhoibhytTylebhyt1;
	}

	@Column(name = "DTDMKHOIBHYT_TYLEBHYT2")
	public Short getDtdmkhoibhytTylebhyt2() {
		return this.dtdmkhoibhytTylebhyt2;
	}

	public void setDtdmkhoibhytTylebhyt2(Short dtdmkhoibhytTylebhyt2) {
		this.dtdmkhoibhytTylebhyt2 = dtdmkhoibhytTylebhyt2;
	}

	@Column(name = "DTDMKHOIBHYT_TYLEKTC")
	public Short getDtdmkhoibhytTylektc() {
		return this.dtdmkhoibhytTylektc;
	}

	public void setDtdmkhoibhytTylektc(Short dtdmkhoibhytTylektc) {
		this.dtdmkhoibhytTylektc = dtdmkhoibhytTylektc;
	}

	@Column(name = "DTDMKHOIBHYT_GOMYC")
	public Short getDtdmkhoibhytGomyc() {
		return this.dtdmkhoibhytGomyc;
	}

	public void setDtdmkhoibhytGomyc(Short dtdmkhoibhytGomyc) {
		this.dtdmkhoibhytGomyc = dtdmkhoibhytGomyc;
	}

	@Column(name = "DTDMKHOIBHYT_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmkhoibhytGhichu() {
		return this.dtdmkhoibhytGhichu;
	}

	public void setDtdmkhoibhytGhichu(String dtdmkhoibhytGhichu) {
		this.dtdmkhoibhytGhichu = dtdmkhoibhytGhichu;
	}

	@Column(name = "DTDMKHOIBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmkhoibhytNgaygiocn() {
		return this.dtdmkhoibhytNgaygiocn;
	}

	public void setDtdmkhoibhytNgaygiocn(Double dtdmkhoibhytNgaygiocn) {
		this.dtdmkhoibhytNgaygiocn = dtdmkhoibhytNgaygiocn;
	}

	@Column(name = "DTDMKHOIBHYT_CHON")
	public Boolean getDtdmkhoibhytChon() {
		return this.dtdmkhoibhytChon;
	}

	public void setDtdmkhoibhytChon(Boolean dtdmkhoibhytChon) {
		this.dtdmkhoibhytChon = dtdmkhoibhytChon;
	}

	@Column(name = "DTDMKHOIBHYT_GHTYLE", precision = 22, scale = 0)
	public Double getDtdmkhoibhytGhtyle() {
		return this.dtdmkhoibhytGhtyle;
	}

	public void setDtdmkhoibhytGhtyle(Double dtdmkhoibhytGhtyle) {
		this.dtdmkhoibhytGhtyle = dtdmkhoibhytGhtyle;
	}

	@Column(name = "DTDMKHOIBHYT_MINKTC", precision = 22, scale = 0)
	public Double getDtdmkhoibhytMinktc() {
		return this.dtdmkhoibhytMinktc;
	}

	public void setDtdmkhoibhytMinktc(Double dtdmkhoibhytMinktc) {
		this.dtdmkhoibhytMinktc = dtdmkhoibhytMinktc;
	}

	@Column(name = "DTDMKHOIBHYT_TLMINKTC", precision = 22, scale = 0)
	public Double getDtdmkhoibhytTlminktc() {
		return this.dtdmkhoibhytTlminktc;
	}

	public void setDtdmkhoibhytTlminktc(Double dtdmkhoibhytTlminktc) {
		this.dtdmkhoibhytTlminktc = dtdmkhoibhytTlminktc;
	}

	@Column(name = "DTDMKHOIBHYT_MAXKTC", precision = 22, scale = 0)
	public Double getDtdmkhoibhytMaxktc() {
		return this.dtdmkhoibhytMaxktc;
	}

	public void setDtdmkhoibhytMaxktc(Double dtdmkhoibhytMaxktc) {
		this.dtdmkhoibhytMaxktc = dtdmkhoibhytMaxktc;
	}

	@Column(name = "DTDMKHOIBHYT_TLMAXKTC", precision = 22, scale = 0)
	public Double getDtdmkhoibhytTlmaxktc() {
		return this.dtdmkhoibhytTlmaxktc;
	}

	public void setDtdmkhoibhytTlmaxktc(Double dtdmkhoibhytTlmaxktc) {
		this.dtdmkhoibhytTlmaxktc = dtdmkhoibhytTlmaxktc;
	}

	@Column(name = "DTDMKHOIBHYT_LIMITKTC", precision = 22, scale = 0)
	public Double getDtdmkhoibhytLimitktc() {
		return this.dtdmkhoibhytLimitktc;
	}

	public void setDtdmkhoibhytLimitktc(Double dtdmkhoibhytLimitktc) {
		this.dtdmkhoibhytLimitktc = dtdmkhoibhytLimitktc;
	}

	@Column(name = "DTDMKHOIBHYT_TYLEBHYT1_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmkhoibhytTylebhyt1NoiTru() {
		return this.dtdmkhoibhytTylebhyt1NoiTru;
	}

	public void setDtdmkhoibhytTylebhyt1NoiTru(
			Double dtdmkhoibhytTylebhyt1NoiTru) {
		this.dtdmkhoibhytTylebhyt1NoiTru = dtdmkhoibhytTylebhyt1NoiTru;
	}

	@Column(name = "DTDMKHOIBHYT_TYLEBHYT2_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmkhoibhytTylebhyt2NoiTru() {
		return this.dtdmkhoibhytTylebhyt2NoiTru;
	}

	public void setDtdmkhoibhytTylebhyt2NoiTru(
			Double dtdmkhoibhytTylebhyt2NoiTru) {
		this.dtdmkhoibhytTylebhyt2NoiTru = dtdmkhoibhytTylebhyt2NoiTru;
	}

	@Column(name = "DTDMKHOIBHYT_GHTYLE_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmkhoibhytGhtyleNoiTru() {
		return this.dtdmkhoibhytGhtyleNoiTru;
	}

	public void setDtdmkhoibhytGhtyleNoiTru(Double dtdmkhoibhytGhtyleNoiTru) {
		this.dtdmkhoibhytGhtyleNoiTru = dtdmkhoibhytGhtyleNoiTru;
	}

}
