package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmVoCam generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_VO_CAM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMVOCAM_MA"))
public class DtDmVoCam implements java.io.Serializable {

	private Integer dtdmvocamMaso;
	private String dtdmvocamMa;
	private String dtdmvocamMaphu;
	private String dtdmvocamDiengiai;
	private String dtdmvocamPhanloai;
	private String dtdmvocamGhichu;
	private Double dtdmvocamNgaygiocn;
	private Boolean dtdmvocamChon;

	public DtDmVoCam() {
	}

	public DtDmVoCam(String dtdmvocamMa, String dtdmvocamDiengiai) {
		this.dtdmvocamMa = dtdmvocamMa;
		this.dtdmvocamDiengiai = dtdmvocamDiengiai;
	}

	public DtDmVoCam(String dtdmvocamMa, String dtdmvocamMaphu,
			String dtdmvocamDiengiai, String dtdmvocamPhanloai,
			String dtdmvocamGhichu, Double dtdmvocamNgaygiocn,
			Boolean dtdmvocamChon) {
		this.dtdmvocamMa = dtdmvocamMa;
		this.dtdmvocamMaphu = dtdmvocamMaphu;
		this.dtdmvocamDiengiai = dtdmvocamDiengiai;
		this.dtdmvocamPhanloai = dtdmvocamPhanloai;
		this.dtdmvocamGhichu = dtdmvocamGhichu;
		this.dtdmvocamNgaygiocn = dtdmvocamNgaygiocn;
		this.dtdmvocamChon = dtdmvocamChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_VO_CAM")
	@SequenceGenerator(name = "DT_DM_VO_CAM", sequenceName = "DT_DM_VO_CAM_DTDMVOCAM_MASO_SE", allocationSize = 1)
	@Column(name = "DTDMVOCAM_MASO", unique = true, nullable = false)
	public Integer getDtdmvocamMaso() {
		return this.dtdmvocamMaso;
	}

	public void setDtdmvocamMaso(Integer dtdmvocamMaso) {
		this.dtdmvocamMaso = dtdmvocamMaso;
	}

	@Column(name = "DTDMVOCAM_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDtdmvocamMa() {
		return this.dtdmvocamMa;
	}

	public void setDtdmvocamMa(String dtdmvocamMa) {
		this.dtdmvocamMa = dtdmvocamMa;
	}

	@Column(name = "DTDMVOCAM_MAPHU", length = 3)
	@Length(max = 3)
	public String getDtdmvocamMaphu() {
		return this.dtdmvocamMaphu;
	}

	public void setDtdmvocamMaphu(String dtdmvocamMaphu) {
		this.dtdmvocamMaphu = dtdmvocamMaphu;
	}

	@Column(name = "DTDMVOCAM_DIENGIAI", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmvocamDiengiai() {
		return this.dtdmvocamDiengiai;
	}

	public void setDtdmvocamDiengiai(String dtdmvocamDiengiai) {
		this.dtdmvocamDiengiai = dtdmvocamDiengiai;
	}

	@Column(name = "DTDMVOCAM_PHANLOAI", length = 5)
	@Length(max = 5)
	public String getDtdmvocamPhanloai() {
		return this.dtdmvocamPhanloai;
	}

	public void setDtdmvocamPhanloai(String dtdmvocamPhanloai) {
		this.dtdmvocamPhanloai = dtdmvocamPhanloai;
	}

	@Column(name = "DTDMVOCAM_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmvocamGhichu() {
		return this.dtdmvocamGhichu;
	}

	public void setDtdmvocamGhichu(String dtdmvocamGhichu) {
		this.dtdmvocamGhichu = dtdmvocamGhichu;
	}

	@Column(name = "DTDMVOCAM_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmvocamNgaygiocn() {
		return this.dtdmvocamNgaygiocn;
	}

	public void setDtdmvocamNgaygiocn(Double dtdmvocamNgaygiocn) {
		this.dtdmvocamNgaygiocn = dtdmvocamNgaygiocn;
	}

	@Column(name = "DTDMVOCAM_CHON")
	public Boolean getDtdmvocamChon() {
		return this.dtdmvocamChon;
	}

	public void setDtdmvocamChon(Boolean dtdmvocamChon) {
		this.dtdmvocamChon = dtdmvocamChon;
	}

}
