package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmTienKham generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_TIEN_KHAM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMTIENKHAM_MA"))
public class DtDmTienKham implements java.io.Serializable {

	private Integer dtdmtienkhamMaso;
	private String dtdmtienkhamMa;
	private String dtdmtienkhamTen;
	private Double dtdmtienkhamDongia;
	private String dtdmtienkhamMaloai;
	private Boolean dtdmtienkhamYeucau;
	private Double dtdmtienkhamNgaygiocn;
	private Boolean dtdmtienkhamChon;

	public DtDmTienKham() {
	}

	public DtDmTienKham(String dtdmtienkhamMa, String dtdmtienkhamTen) {
		this.dtdmtienkhamMa = dtdmtienkhamMa;
		this.dtdmtienkhamTen = dtdmtienkhamTen;
	}

	public DtDmTienKham(String dtdmtienkhamMa, String dtdmtienkhamTen,
			Double dtdmtienkhamDongia, String dtdmtienkhamMaloai,
			Boolean dtdmtienkhamYeucau, Double dtdmtienkhamNgaygiocn,
			Boolean dtdmtienkhamChon) {
		this.dtdmtienkhamMa = dtdmtienkhamMa;
		this.dtdmtienkhamTen = dtdmtienkhamTen;
		this.dtdmtienkhamDongia = dtdmtienkhamDongia;
		this.dtdmtienkhamMaloai = dtdmtienkhamMaloai;
		this.dtdmtienkhamYeucau = dtdmtienkhamYeucau;
		this.dtdmtienkhamNgaygiocn = dtdmtienkhamNgaygiocn;
		this.dtdmtienkhamChon = dtdmtienkhamChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_TIEN_KHAM")
	@SequenceGenerator(name = "DT_DM_TIEN_KHAM", sequenceName = "DT_DM_TIEN_KHAM_DTDMTIENKHAM_M", allocationSize = 1)
	@Column(name = "DTDMTIENKHAM_MASO", unique = true, nullable = false)
	public Integer getDtdmtienkhamMaso() {
		return this.dtdmtienkhamMaso;
	}

	public void setDtdmtienkhamMaso(Integer dtdmtienkhamMaso) {
		this.dtdmtienkhamMaso = dtdmtienkhamMaso;
	}

	@Column(name = "DTDMTIENKHAM_MA", unique = true, nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDtdmtienkhamMa() {
		return this.dtdmtienkhamMa;
	}

	public void setDtdmtienkhamMa(String dtdmtienkhamMa) {
		this.dtdmtienkhamMa = dtdmtienkhamMa;
	}

	@Column(name = "DTDMTIENKHAM_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmtienkhamTen() {
		return this.dtdmtienkhamTen;
	}

	public void setDtdmtienkhamTen(String dtdmtienkhamTen) {
		this.dtdmtienkhamTen = dtdmtienkhamTen;
	}

	@Column(name = "DTDMTIENKHAM_DONGIA", precision = 22, scale = 0)
	public Double getDtdmtienkhamDongia() {
		return this.dtdmtienkhamDongia;
	}

	public void setDtdmtienkhamDongia(Double dtdmtienkhamDongia) {
		this.dtdmtienkhamDongia = dtdmtienkhamDongia;
	}

	@Column(name = "DTDMTIENKHAM_MALOAI", length = 5)
	@Length(max = 5)
	public String getDtdmtienkhamMaloai() {
		return this.dtdmtienkhamMaloai;
	}

	public void setDtdmtienkhamMaloai(String dtdmtienkhamMaloai) {
		this.dtdmtienkhamMaloai = dtdmtienkhamMaloai;
	}

	@Column(name = "DTDMTIENKHAM_YEUCAU")
	public Boolean getDtdmtienkhamYeucau() {
		return this.dtdmtienkhamYeucau;
	}

	public void setDtdmtienkhamYeucau(Boolean dtdmtienkhamYeucau) {
		this.dtdmtienkhamYeucau = dtdmtienkhamYeucau;
	}

	@Column(name = "DTDMTIENKHAM_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmtienkhamNgaygiocn() {
		return this.dtdmtienkhamNgaygiocn;
	}

	public void setDtdmtienkhamNgaygiocn(Double dtdmtienkhamNgaygiocn) {
		this.dtdmtienkhamNgaygiocn = dtdmtienkhamNgaygiocn;
	}

	@Column(name = "DTDMTIENKHAM_CHON")
	public Boolean getDtdmtienkhamChon() {
		return this.dtdmtienkhamChon;
	}

	public void setDtdmtienkhamChon(Boolean dtdmtienkhamChon) {
		this.dtdmtienkhamChon = dtdmtienkhamChon;
	}

}
