package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmDienMien generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy=false)

@Table(name = "DT_DM_DIEN_MIEN", catalog = "DB_YTDT_BD")
public class DtDmDienMien implements java.io.Serializable {

	private Integer dtdmdienmienMaso;
	private String dtdmdienmienMa;
	private String dtdmdienmienTen;
	private Double dtdmdienmienNgaygiocn;
	private Boolean dtdmdienmienChon;

	public DtDmDienMien() {
	}

	public DtDmDienMien(String dtdmdienmienMa, String dtdmdienmienTen) {
		this.dtdmdienmienMa = dtdmdienmienMa;
		this.dtdmdienmienTen = dtdmdienmienTen;
	}

	public DtDmDienMien(String dtdmdienmienMa, String dtdmdienmienTen,
			Double dtdmdienmienNgaygiocn, Boolean dtdmdienmienChon) {
		this.dtdmdienmienMa = dtdmdienmienMa;
		this.dtdmdienmienTen = dtdmdienmienTen;
		this.dtdmdienmienNgaygiocn = dtdmdienmienNgaygiocn;
		this.dtdmdienmienChon = dtdmdienmienChon;
	}

	@Id
	  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_DIEN_MIEN")
	  @SequenceGenerator(name = "DT_DM_DIEN_MIEN", sequenceName = "DT_DM_DIEN_MIEN_DTDMDIENMIEN_M", allocationSize = 1)
	  @Column(name = "DTDMDIENMIEN_MASO", unique = true, nullable = false)
	public Integer getDtdmdienmienMaso() {
		return this.dtdmdienmienMaso;
	}

	public void setDtdmdienmienMaso(Integer dtdmdienmienMaso) {
		this.dtdmdienmienMaso = dtdmdienmienMaso;
	}

	@Column(name = "DTDMDIENMIEN_MA", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getDtdmdienmienMa() {
		return this.dtdmdienmienMa;
	}

	public void setDtdmdienmienMa(String dtdmdienmienMa) {
		this.dtdmdienmienMa = dtdmdienmienMa;
	}

	@Column(name = "DTDMDIENMIEN_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmdienmienTen() {
		return this.dtdmdienmienTen;
	}

	public void setDtdmdienmienTen(String dtdmdienmienTen) {
		this.dtdmdienmienTen = dtdmdienmienTen;
	}

	@Column(name = "DTDMDIENMIEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmdienmienNgaygiocn() {
		return this.dtdmdienmienNgaygiocn;
	}

	public void setDtdmdienmienNgaygiocn(Double dtdmdienmienNgaygiocn) {
		this.dtdmdienmienNgaygiocn = dtdmdienmienNgaygiocn;
	}

	@Column(name = "DTDMDIENMIEN_CHON")
	public Boolean getDtdmdienmienChon() {
		return this.dtdmdienmienChon;
	}

	public void setDtdmdienmienChon(Boolean dtdmdienmienChon) {
		this.dtdmdienmienChon = dtdmdienmienChon;
	}

}
