package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLopBhyt generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOP_BHY", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLOPBHYT_MA"))
public class DtDmLopBhyt implements java.io.Serializable {

	private Integer dtdmlopbhytMaso;
	private String dtdmlopbhytMa;
	private String dtdmlopbhytTen;
	private Double dtdmlopbhytNgaygiocn;
	private Boolean dtdmlopbhytChon;
	private Set<DtDmNhomBhyt> dtDmNhomBhyts = new HashSet<DtDmNhomBhyt>(0);

	public DtDmLopBhyt() {
	}

	public DtDmLopBhyt(String dtdmlopbhytMa, String dtdmlopbhytTen) {
		this.dtdmlopbhytMa = dtdmlopbhytMa;
		this.dtdmlopbhytTen = dtdmlopbhytTen;
	}

	public DtDmLopBhyt(String dtdmlopbhytMa, String dtdmlopbhytTen,
			Double dtdmlopbhytNgaygiocn, Boolean dtdmlopbhytChon,
			Set<DtDmNhomBhyt> dtDmNhomBhyts) {
		this.dtdmlopbhytMa = dtdmlopbhytMa;
		this.dtdmlopbhytTen = dtdmlopbhytTen;
		this.dtdmlopbhytNgaygiocn = dtdmlopbhytNgaygiocn;
		this.dtdmlopbhytChon = dtdmlopbhytChon;
		this.dtDmNhomBhyts = dtDmNhomBhyts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOP_BHY")
	@SequenceGenerator(name = "DT_DM_LOP_BHY", sequenceName = "DT_DM_LOP_BHYT_DTDMLOPBHYT_MAS", allocationSize = 1)
	@Column(name = "DTDMLOPBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmlopbhytMaso() {
		return this.dtdmlopbhytMaso;
	}

	public void setDtdmlopbhytMaso(Integer dtdmlopbhytMaso) {
		this.dtdmlopbhytMaso = dtdmlopbhytMaso;
	}

	@Column(name = "DTDMLOPBHYT_MA", unique = true, nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getDtdmlopbhytMa() {
		return this.dtdmlopbhytMa;
	}

	public void setDtdmlopbhytMa(String dtdmlopbhytMa) {
		this.dtdmlopbhytMa = dtdmlopbhytMa;
	}

	@Column(name = "DTDMLOPBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmlopbhytTen() {
		return this.dtdmlopbhytTen;
	}

	public void setDtdmlopbhytTen(String dtdmlopbhytTen) {
		this.dtdmlopbhytTen = dtdmlopbhytTen;
	}

	@Column(name = "DTDMLOPBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmlopbhytNgaygiocn() {
		return this.dtdmlopbhytNgaygiocn;
	}

	public void setDtdmlopbhytNgaygiocn(Double dtdmlopbhytNgaygiocn) {
		this.dtdmlopbhytNgaygiocn = dtdmlopbhytNgaygiocn;
	}

	@Column(name = "DTDMLOPBHYT_CHON")
	public Boolean getDtdmlopbhytChon() {
		return this.dtdmlopbhytChon;
	}

	public void setDtdmlopbhytChon(Boolean dtdmlopbhytChon) {
		this.dtdmlopbhytChon = dtdmlopbhytChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLopBhyt")
	public Set<DtDmNhomBhyt> getDtDmNhomBhyts() {
		return this.dtDmNhomBhyts;
	}

	public void setDtDmNhomBhyts(Set<DtDmNhomBhyt> dtDmNhomBhyts) {
		this.dtDmNhomBhyts = dtDmNhomBhyts;
	}

}
