package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoaiThucPham generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOAI_THUC_PHAM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLTP_MA"))
public class DtDmLoaiThucPham implements java.io.Serializable {

	private Integer dtdmltpMaso;
	private DmDonViTinh dmDonViTinh;
	private String dtdmltpMa;
	private String dtdmltpTen;
	private Double dtdmltpNgaygiocn;
	private Boolean dtdmltpChon;

	public DtDmLoaiThucPham() {
	}

	public DtDmLoaiThucPham(String dtdmltpMa) {
		this.dtdmltpMa = dtdmltpMa;
	}

	public DtDmLoaiThucPham(DmDonViTinh dmDonViTinh, String dtdmltpMa,
			String dtdmltpTen, Double dtdmltpNgaygiocn, Boolean dtdmltpChon) {
		this.dmDonViTinh = dmDonViTinh;
		this.dtdmltpMa = dtdmltpMa;
		this.dtdmltpTen = dtdmltpTen;
		this.dtdmltpNgaygiocn = dtdmltpNgaygiocn;
		this.dtdmltpChon = dtdmltpChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOAI_THUC_PHAM")
	@SequenceGenerator(name = "DT_DM_LOAI_THUC_PHAM", sequenceName = "DT_DM_LOAI_THUC_PHAM_DTDMLTP_M", allocationSize = 1)
	@Column(name = "DTDMLTP_MASO", unique = true, nullable = false)
	public Integer getDtdmltpMaso() {
		return this.dtdmltpMaso;
	}

	public void setDtdmltpMaso(Integer dtdmltpMaso) {
		this.dtdmltpMaso = dtdmltpMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMDONVITINH_MASO")
	public DmDonViTinh getDmDonViTinh() {
		return this.dmDonViTinh;
	}

	public void setDmDonViTinh(DmDonViTinh dmDonViTinh) {
		this.dmDonViTinh = dmDonViTinh;
	}

	@Column(name = "DTDMLTP_MA", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDtdmltpMa() {
		return this.dtdmltpMa;
	}

	public void setDtdmltpMa(String dtdmltpMa) {
		this.dtdmltpMa = dtdmltpMa;
	}

	@Column(name = "DTDMLTP_TEN", length = 100)
	@Length(max = 100)
	public String getDtdmltpTen() {
		return this.dtdmltpTen;
	}

	public void setDtdmltpTen(String dtdmltpTen) {
		this.dtdmltpTen = dtdmltpTen;
	}

	@Column(name = "DTDMLTP_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmltpNgaygiocn() {
		return this.dtdmltpNgaygiocn;
	}

	public void setDtdmltpNgaygiocn(Double dtdmltpNgaygiocn) {
		this.dtdmltpNgaygiocn = dtdmltpNgaygiocn;
	}

	@Column(name = "DTDMLTP_CHON")
	public Boolean getDtdmltpChon() {
		return this.dtdmltpChon;
	}

	public void setDtdmltpChon(Boolean dtdmltpChon) {
		this.dtdmltpChon = dtdmltpChon;
	}

}
