package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * DtDmClsKhoa generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CLS_KHOA", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DTDMCLS_MASO", "DMKHOA_MASO" }))
public class DtDmClsKhoa implements java.io.Serializable {

	private Integer dtdmclskhoaMaso;
	private DmKhoa dmKhoa;
	private DtDmClsBangGia dtDmClsBangGia;
	private Boolean dtdmclskhoaChon;
	private Double dtdmclskhoaNgaygiocn;

	public DtDmClsKhoa() {
	}

	public DtDmClsKhoa(DmKhoa dmKhoa, DtDmClsBangGia dtDmClsBangGia) {
		this.dmKhoa = dmKhoa;
		this.dtDmClsBangGia = dtDmClsBangGia;
	}

	public DtDmClsKhoa(DmKhoa dmKhoa, DtDmClsBangGia dtDmClsBangGia,
			Boolean dtdmclskhoaChon, Double dtdmclskhoaNgaygiocn) {
		this.dmKhoa = dmKhoa;
		this.dtDmClsBangGia = dtDmClsBangGia;
		this.dtdmclskhoaChon = dtdmclskhoaChon;
		this.dtdmclskhoaNgaygiocn = dtdmclskhoaNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CLS_KHOA")
	@SequenceGenerator(name = "DT_DM_CLS_KHOA", sequenceName = "DT_DM_CLS_KHOA_DTDMCLSKHOA_MAS", allocationSize = 1)
	@Column(name = "DTDMCLSKHOA_MASO", unique = true, nullable = false)
	public Integer getDtdmclskhoaMaso() {
		return this.dtdmclskhoaMaso;
	}

	public void setDtdmclskhoaMaso(Integer dtdmclskhoaMaso) {
		this.dtdmclskhoaMaso = dtdmclskhoaMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MASO", nullable = false)
	@NotNull
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMCLS_MASO", nullable = false)
	@NotNull
	public DtDmClsBangGia getDtDmClsBangGia() {
		return this.dtDmClsBangGia;
	}

	public void setDtDmClsBangGia(DtDmClsBangGia dtDmClsBangGia) {
		this.dtDmClsBangGia = dtDmClsBangGia;
	}

	@Column(name = "DTDMCLSKHOA_CHON")
	public Boolean getDtdmclskhoaChon() {
		return this.dtdmclskhoaChon;
	}

	public void setDtdmclskhoaChon(Boolean dtdmclskhoaChon) {
		this.dtdmclskhoaChon = dtdmclskhoaChon;
	}

	@Column(name = "DTDMCLSKHOA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmclskhoaNgaygiocn() {
		return this.dtdmclskhoaNgaygiocn;
	}

	public void setDtdmclskhoaNgaygiocn(Double dtdmclskhoaNgaygiocn) {
		this.dtdmclskhoaNgaygiocn = dtdmclskhoaNgaygiocn;
	}

}
