package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmPhong generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_PHONG", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMP_MA"))
public class DtDmPhong implements java.io.Serializable {

	private Integer dtdmpMaso;
	private String dtdmpMa;
	private String dtdmpTen;
	private double dtdmpNgaygiocn;
	private Integer dtdmpChon;

	public DtDmPhong() {
	}

	public DtDmPhong(String dtdmpMa, String dtdmpTen, double dtdmpNgaygiocn) {
		this.dtdmpMa = dtdmpMa;
		this.dtdmpTen = dtdmpTen;
		this.dtdmpNgaygiocn = dtdmpNgaygiocn;
	}

	public DtDmPhong(String dtdmpMa, String dtdmpTen, double dtdmpNgaygiocn,
			Integer dtdmpChon) {
		this.dtdmpMa = dtdmpMa;
		this.dtdmpTen = dtdmpTen;
		this.dtdmpNgaygiocn = dtdmpNgaygiocn;
		this.dtdmpChon = dtdmpChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_PHONG")
	@SequenceGenerator(name = "DT_DM_PHONG", sequenceName = "DT_DM_PHONG_DTDMP_MASO_SEQ", allocationSize = 1)
	@Column(name = "DTDMP_MASO", unique = true, nullable = false)
	public Integer getDtdmpMaso() {
		return this.dtdmpMaso;
	}

	public void setDtdmpMaso(Integer dtdmpMaso) {
		this.dtdmpMaso = dtdmpMaso;
	}

	@Column(name = "DTDMP_MA", unique = true, nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDtdmpMa() {
		return this.dtdmpMa;
	}

	public void setDtdmpMa(String dtdmpMa) {
		this.dtdmpMa = dtdmpMa;
	}

	@Column(name = "DTDMP_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmpTen() {
		return this.dtdmpTen;
	}

	public void setDtdmpTen(String dtdmpTen) {
		this.dtdmpTen = dtdmpTen;
	}

	@Column(name = "DTDMP_NGAYGIOCN", nullable = false, precision = 22, scale = 0)
	@NotNull
	public double getDtdmpNgaygiocn() {
		return this.dtdmpNgaygiocn;
	}

	public void setDtdmpNgaygiocn(double dtdmpNgaygiocn) {
		this.dtdmpNgaygiocn = dtdmpNgaygiocn;
	}

	@Column(name = "DTDMP_CHON")
	public Integer getDtdmpChon() {
		return this.dtdmpChon;
	}

	public void setDtdmpChon(Integer dtdmpChon) {
		this.dtdmpChon = dtdmpChon;
	}

}
