package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmCheDoAn generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CHE_DO_AN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMCDA_MA"))
public class DtDmCheDoAn implements java.io.Serializable {

	private Integer dtdmcdaMaso;
	private String dtdmcdaMa;
	private String dtdmcdaTen;
	private Double dtdmcdaNgaygiocn;
	private Boolean dtdmcdaChon;

	public DtDmCheDoAn() {
	}

	public DtDmCheDoAn(String dtdmcdaMa) {
		this.dtdmcdaMa = dtdmcdaMa;
	}

	public DtDmCheDoAn(String dtdmcdaMa, String dtdmcdaTen,
			Double dtdmcdaNgaygiocn, Boolean dtdmcdaChon) {
		this.dtdmcdaMa = dtdmcdaMa;
		this.dtdmcdaTen = dtdmcdaTen;
		this.dtdmcdaNgaygiocn = dtdmcdaNgaygiocn;
		this.dtdmcdaChon = dtdmcdaChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CHE_DO_AN")
	@SequenceGenerator(name = "DT_DM_CHE_DO_AN", sequenceName = "DT_DM_CHE_DO_AN_DTDMCDA_MASO_S", allocationSize = 1)
	@Column(name = "DTDMCDA_MASO", unique = true, nullable = false)
	public Integer getDtdmcdaMaso() {
		return this.dtdmcdaMaso;
	}

	public void setDtdmcdaMaso(Integer dtdmcdaMaso) {
		this.dtdmcdaMaso = dtdmcdaMaso;
	}

	@Column(name = "DTDMCDA_MA", unique = true, nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDtdmcdaMa() {
		return this.dtdmcdaMa;
	}

	public void setDtdmcdaMa(String dtdmcdaMa) {
		this.dtdmcdaMa = dtdmcdaMa;
	}

	@Column(name = "DTDMCDA_TEN", length = 100)
	@Length(max = 100)
	public String getDtdmcdaTen() {
		return this.dtdmcdaTen;
	}

	public void setDtdmcdaTen(String dtdmcdaTen) {
		this.dtdmcdaTen = dtdmcdaTen;
	}

	@Column(name = "DTDMCDA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmcdaNgaygiocn() {
		return this.dtdmcdaNgaygiocn;
	}

	public void setDtdmcdaNgaygiocn(Double dtdmcdaNgaygiocn) {
		this.dtdmcdaNgaygiocn = dtdmcdaNgaygiocn;
	}

	@Column(name = "DTDMCDA_CHON")
	public Boolean getDtdmcdaChon() {
		return this.dtdmcdaChon;
	}

	public void setDtdmcdaChon(Boolean dtdmcdaChon) {
		this.dtdmcdaChon = dtdmcdaChon;
	}

}
