package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmKcbBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_KCB_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMKCBBHYT_MA"))
public class DtDmKcbBhyt implements java.io.Serializable {

	private Integer dtdmkcbbhytMaso;
	private DtDmTuyenKcb dtDmTuyenKcb;
	private DtDmTinhBhyt dtDmTinhBhyt;
	private String dtdmkcbbhytMa;
	private String dtdmhuyenbhytMa;
	private String dtdmkcbbhytTen;
	private String dtdmkcbbhytGhichu;
	private Short dtdmkcbbhytMauthe;
	private Double dtdmkcbbhytNgaygiocn;
	private Boolean dtdmkcbbhytChon;
	private Boolean dtdmkcbbhytDefa;

	public DtDmKcbBhyt() {
	}

	public DtDmKcbBhyt(String dtdmkcbbhytMa, String dtdmkcbbhytTen) {
		this.dtdmkcbbhytMa = dtdmkcbbhytMa;
		this.dtdmkcbbhytTen = dtdmkcbbhytTen;
	}

	public DtDmKcbBhyt(DtDmTuyenKcb dtDmTuyenKcb, DtDmTinhBhyt dtDmTinhBhyt,
			String dtdmkcbbhytMa, String dtdmhuyenbhytMa,
			String dtdmkcbbhytTen, String dtdmkcbbhytGhichu,
			Short dtdmkcbbhytMauthe, Double dtdmkcbbhytNgaygiocn,
			Boolean dtdmkcbbhytChon, Boolean dtdmkcbbhytDefa) {
		this.dtDmTuyenKcb = dtDmTuyenKcb;
		this.dtDmTinhBhyt = dtDmTinhBhyt;
		this.dtdmkcbbhytMa = dtdmkcbbhytMa;
		this.dtdmhuyenbhytMa = dtdmhuyenbhytMa;
		this.dtdmkcbbhytTen = dtdmkcbbhytTen;
		this.dtdmkcbbhytGhichu = dtdmkcbbhytGhichu;
		this.dtdmkcbbhytMauthe = dtdmkcbbhytMauthe;
		this.dtdmkcbbhytNgaygiocn = dtdmkcbbhytNgaygiocn;
		this.dtdmkcbbhytChon = dtdmkcbbhytChon;
		this.dtdmkcbbhytDefa = dtdmkcbbhytDefa;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_KCB_BHYT")
	@SequenceGenerator(name = "DT_DM_KCB_BHYT", sequenceName = "DT_DM_KCB_BHYT_DTDMKCBBHYT_MAS", allocationSize = 1)
	@Column(name = "DTDMKCBBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmkcbbhytMaso() {
		return this.dtdmkcbbhytMaso;
	}

	public void setDtdmkcbbhytMaso(Integer dtdmkcbbhytMaso) {
		this.dtdmkcbbhytMaso = dtdmkcbbhytMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMTUYENKCB_MASO")
	public DtDmTuyenKcb getDtDmTuyenKcb() {
		return this.dtDmTuyenKcb;
	}

	public void setDtDmTuyenKcb(DtDmTuyenKcb dtDmTuyenKcb) {
		this.dtDmTuyenKcb = dtDmTuyenKcb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMTINHBHYT_MASO")
	public DtDmTinhBhyt getDtDmTinhBhyt() {
		return this.dtDmTinhBhyt;
	}

	public void setDtDmTinhBhyt(DtDmTinhBhyt dtDmTinhBhyt) {
		this.dtDmTinhBhyt = dtDmTinhBhyt;
	}

	@Column(name = "DTDMKCBBHYT_MA", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getDtdmkcbbhytMa() {
		return this.dtdmkcbbhytMa;
	}

	public void setDtdmkcbbhytMa(String dtdmkcbbhytMa) {
		this.dtdmkcbbhytMa = dtdmkcbbhytMa;
	}

	@Column(name = "DTDMHUYENBHYT_MA", length = 5)
	@Length(max = 5)
	public String getDtdmhuyenbhytMa() {
		return this.dtdmhuyenbhytMa;
	}

	public void setDtdmhuyenbhytMa(String dtdmhuyenbhytMa) {
		this.dtdmhuyenbhytMa = dtdmhuyenbhytMa;
	}

	@Column(name = "DTDMKCBBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmkcbbhytTen() {
		return this.dtdmkcbbhytTen;
	}

	public void setDtdmkcbbhytTen(String dtdmkcbbhytTen) {
		this.dtdmkcbbhytTen = dtdmkcbbhytTen;
	}

	@Column(name = "DTDMKCBBHYT_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmkcbbhytGhichu() {
		return this.dtdmkcbbhytGhichu;
	}

	public void setDtdmkcbbhytGhichu(String dtdmkcbbhytGhichu) {
		this.dtdmkcbbhytGhichu = dtdmkcbbhytGhichu;
	}

	@Column(name = "DTDMKCBBHYT_MAUTHE")
	public Short getDtdmkcbbhytMauthe() {
		return this.dtdmkcbbhytMauthe;
	}

	public void setDtdmkcbbhytMauthe(Short dtdmkcbbhytMauthe) {
		this.dtdmkcbbhytMauthe = dtdmkcbbhytMauthe;
	}

	@Column(name = "DTDMKCBBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmkcbbhytNgaygiocn() {
		return this.dtdmkcbbhytNgaygiocn;
	}

	public void setDtdmkcbbhytNgaygiocn(Double dtdmkcbbhytNgaygiocn) {
		this.dtdmkcbbhytNgaygiocn = dtdmkcbbhytNgaygiocn;
	}

	@Column(name = "DTDMKCBBHYT_CHON")
	public Boolean getDtdmkcbbhytChon() {
		return this.dtdmkcbbhytChon;
	}

	public void setDtdmkcbbhytChon(Boolean dtdmkcbbhytChon) {
		this.dtdmkcbbhytChon = dtdmkcbbhytChon;
	}

	@Column(name = "DTDMKCBBHYT_DEFA")
	public Boolean getDtdmkcbbhytDefa() {
		return this.dtdmkcbbhytDefa;
	}

	public void setDtdmkcbbhytDefa(Boolean dtdmkcbbhytDefa) {
		this.dtdmkcbbhytDefa = dtdmkcbbhytDefa;
	}

}
