package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoaiBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOAI_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLOAIBHYT_MA"))
public class DtDmLoaiBhyt implements java.io.Serializable {

	private Integer dtdmloaibhytMaso;
	private String dtdmloaibhytMa;
	private String dtdmloaibhytTen;
	private String dtdmloaibhytGhichu;
	private Double dtdmloaibhytNgaygiocn;
	private Boolean dtdmloaibhytChon;
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts = new HashSet<DtDmKhoiBhyt>(0);
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1 = new HashSet<DtDmKhoiBhyt>(0);

	public DtDmLoaiBhyt() {
	}

	public DtDmLoaiBhyt(String dtdmloaibhytMa) {
		this.dtdmloaibhytMa = dtdmloaibhytMa;
	}

	public DtDmLoaiBhyt(String dtdmloaibhytMa, String dtdmloaibhytTen,
			String dtdmloaibhytGhichu, Double dtdmloaibhytNgaygiocn,
			Boolean dtdmloaibhytChon, Set<DtDmKhoiBhyt> dtDmKhoiBhyts,
			Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1) {
		this.dtdmloaibhytMa = dtdmloaibhytMa;
		this.dtdmloaibhytTen = dtdmloaibhytTen;
		this.dtdmloaibhytGhichu = dtdmloaibhytGhichu;
		this.dtdmloaibhytNgaygiocn = dtdmloaibhytNgaygiocn;
		this.dtdmloaibhytChon = dtdmloaibhytChon;
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
		this.dtDmKhoiBhyts_1 = dtDmKhoiBhyts_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOAI_BHYT")
	@SequenceGenerator(name = "DT_DM_LOAI_BHYT", sequenceName = "DT_DM_LOAI_BHYT_DTDMLOAIBHYT_M", allocationSize = 1)
	@Column(name = "DTDMLOAIBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmloaibhytMaso() {
		return this.dtdmloaibhytMaso;
	}

	public void setDtdmloaibhytMaso(Integer dtdmloaibhytMaso) {
		this.dtdmloaibhytMaso = dtdmloaibhytMaso;
	}

	@Column(name = "DTDMLOAIBHYT_MA", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getDtdmloaibhytMa() {
		return this.dtdmloaibhytMa;
	}

	public void setDtdmloaibhytMa(String dtdmloaibhytMa) {
		this.dtdmloaibhytMa = dtdmloaibhytMa;
	}

	@Column(name = "DTDMLOAIBHYT_TEN", length = 250)
	@Length(max = 250)
	public String getDtdmloaibhytTen() {
		return this.dtdmloaibhytTen;
	}

	public void setDtdmloaibhytTen(String dtdmloaibhytTen) {
		this.dtdmloaibhytTen = dtdmloaibhytTen;
	}

	@Column(name = "DTDMLOAIBHYT_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmloaibhytGhichu() {
		return this.dtdmloaibhytGhichu;
	}

	public void setDtdmloaibhytGhichu(String dtdmloaibhytGhichu) {
		this.dtdmloaibhytGhichu = dtdmloaibhytGhichu;
	}

	@Column(name = "DTDMLOAIBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmloaibhytNgaygiocn() {
		return this.dtdmloaibhytNgaygiocn;
	}

	public void setDtdmloaibhytNgaygiocn(Double dtdmloaibhytNgaygiocn) {
		this.dtdmloaibhytNgaygiocn = dtdmloaibhytNgaygiocn;
	}

	@Column(name = "DTDMLOAIBHYT_CHON")
	public Boolean getDtdmloaibhytChon() {
		return this.dtdmloaibhytChon;
	}

	public void setDtdmloaibhytChon(Boolean dtdmloaibhytChon) {
		this.dtdmloaibhytChon = dtdmloaibhytChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLoaiBhyt")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts() {
		return this.dtDmKhoiBhyts;
	}

	public void setDtDmKhoiBhyts(Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLoaiBhyt")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts_1() {
		return this.dtDmKhoiBhyts_1;
	}

	public void setDtDmKhoiBhyts_1(Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1) {
		this.dtDmKhoiBhyts_1 = dtDmKhoiBhyts_1;
	}

}
