package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoaiSuaDuongNhi generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOAI_SUA_DUONG_NHI", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLSDN_MA"))
public class DtDmLoaiSuaDuongNhi implements java.io.Serializable {

	private Integer dtdmlsdnMaso;
	private String dtdmlsdnMa;
	private String dtdmlsdnTen;
	private Double dtdmlsdnNgaygiocn;
	private Boolean dtdmlsdnChon;

	public DtDmLoaiSuaDuongNhi() {
	}

	public DtDmLoaiSuaDuongNhi(String dtdmlsdnMa) {
		this.dtdmlsdnMa = dtdmlsdnMa;
	}

	public DtDmLoaiSuaDuongNhi(String dtdmlsdnMa, String dtdmlsdnTen,
			Double dtdmlsdnNgaygiocn, Boolean dtdmlsdnChon) {
		this.dtdmlsdnMa = dtdmlsdnMa;
		this.dtdmlsdnTen = dtdmlsdnTen;
		this.dtdmlsdnNgaygiocn = dtdmlsdnNgaygiocn;
		this.dtdmlsdnChon = dtdmlsdnChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOAI_SUA_DUONG_NHI")
	@SequenceGenerator(name = "DT_DM_LOAI_SUA_DUONG_NHI", sequenceName = "DT_DM_LOAI_SUA_DUONG_NHI_DTDML", allocationSize = 1)
	@Column(name = "DTDMLSDN_MASO", unique = true, nullable = false)
	public Integer getDtdmlsdnMaso() {
		return this.dtdmlsdnMaso;
	}

	public void setDtdmlsdnMaso(Integer dtdmlsdnMaso) {
		this.dtdmlsdnMaso = dtdmlsdnMaso;
	}

	@Column(name = "DTDMLSDN_MA", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDtdmlsdnMa() {
		return this.dtdmlsdnMa;
	}

	public void setDtdmlsdnMa(String dtdmlsdnMa) {
		this.dtdmlsdnMa = dtdmlsdnMa;
	}

	@Column(name = "DTDMLSDN_TEN", length = 100)
	@Length(max = 100)
	public String getDtdmlsdnTen() {
		return this.dtdmlsdnTen;
	}

	public void setDtdmlsdnTen(String dtdmlsdnTen) {
		this.dtdmlsdnTen = dtdmlsdnTen;
	}

	@Column(name = "DTDMLSDN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmlsdnNgaygiocn() {
		return this.dtdmlsdnNgaygiocn;
	}

	public void setDtdmlsdnNgaygiocn(Double dtdmlsdnNgaygiocn) {
		this.dtdmlsdnNgaygiocn = dtdmlsdnNgaygiocn;
	}

	@Column(name = "DTDMLSDN_CHON")
	public Boolean getDtdmlsdnChon() {
		return this.dtdmlsdnChon;
	}

	public void setDtdmlsdnChon(Boolean dtdmlsdnChon) {
		this.dtdmlsdnChon = dtdmlsdnChon;
	}

}
