package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmTinhBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_TINH_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMTINHBHYT_MA"))
public class DtDmTinhBhyt implements java.io.Serializable {

	private Integer dtdmtinhbhytMaso;
	private String dtdmtinhbhytMa;
	private String dtdmtinhbhytTen;
	private Date dtdmtinhbhytNgaytinh;
	private String dtdmtinhbhytTen1;
	private Date dtdmtinhbhytNgaytinh1;
	private String dtdmtinhbhytTen2;
	private Date dtdmtinhbhytNgaytinh2;
	private String dtdmtinhbhytTen3;
	private Date dtdmtinhbhytNgaytinh3;
	private Boolean dtdmtinhbhytNew;
	private String dtdmtinhbhytNoitinh;
	private Double dtdmtinhbhytNgaygiocn;
	private Boolean dtdmtinhbhytChon;
	private Boolean dtdmtinhbhytDefa;
	private Set<DtDmKcbBhyt> dtDmKcbBhyts = new HashSet<DtDmKcbBhyt>(0);
	private Set<DtDmKcbBhyt> dtDmKcbBhyts_1 = new HashSet<DtDmKcbBhyt>(0);

	public DtDmTinhBhyt() {
	}

	public DtDmTinhBhyt(String dtdmtinhbhytMa, String dtdmtinhbhytTen) {
		this.dtdmtinhbhytMa = dtdmtinhbhytMa;
		this.dtdmtinhbhytTen = dtdmtinhbhytTen;
	}

	public DtDmTinhBhyt(String dtdmtinhbhytMa, String dtdmtinhbhytTen,
			Date dtdmtinhbhytNgaytinh, String dtdmtinhbhytTen1,
			Date dtdmtinhbhytNgaytinh1, String dtdmtinhbhytTen2,
			Date dtdmtinhbhytNgaytinh2, String dtdmtinhbhytTen3,
			Date dtdmtinhbhytNgaytinh3, Boolean dtdmtinhbhytNew,
			String dtdmtinhbhytNoitinh, Double dtdmtinhbhytNgaygiocn,
			Boolean dtdmtinhbhytChon, Boolean dtdmtinhbhytDefa,
			Set<DtDmKcbBhyt> dtDmKcbBhyts, Set<DtDmKcbBhyt> dtDmKcbBhyts_1) {
		this.dtdmtinhbhytMa = dtdmtinhbhytMa;
		this.dtdmtinhbhytTen = dtdmtinhbhytTen;
		this.dtdmtinhbhytNgaytinh = dtdmtinhbhytNgaytinh;
		this.dtdmtinhbhytTen1 = dtdmtinhbhytTen1;
		this.dtdmtinhbhytNgaytinh1 = dtdmtinhbhytNgaytinh1;
		this.dtdmtinhbhytTen2 = dtdmtinhbhytTen2;
		this.dtdmtinhbhytNgaytinh2 = dtdmtinhbhytNgaytinh2;
		this.dtdmtinhbhytTen3 = dtdmtinhbhytTen3;
		this.dtdmtinhbhytNgaytinh3 = dtdmtinhbhytNgaytinh3;
		this.dtdmtinhbhytNew = dtdmtinhbhytNew;
		this.dtdmtinhbhytNoitinh = dtdmtinhbhytNoitinh;
		this.dtdmtinhbhytNgaygiocn = dtdmtinhbhytNgaygiocn;
		this.dtdmtinhbhytChon = dtdmtinhbhytChon;
		this.dtdmtinhbhytDefa = dtdmtinhbhytDefa;
		this.dtDmKcbBhyts = dtDmKcbBhyts;
		this.dtDmKcbBhyts_1 = dtDmKcbBhyts_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_TINH_BHYT")
	@SequenceGenerator(name = "DT_DM_TINH_BHYT", sequenceName = "DT_DM_TINH_BHYT_DTDMTINHBHYT_M", allocationSize = 1)
	@Column(name = "DTDMTINHBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmtinhbhytMaso() {
		return this.dtdmtinhbhytMaso;
	}

	public void setDtdmtinhbhytMaso(Integer dtdmtinhbhytMaso) {
		this.dtdmtinhbhytMaso = dtdmtinhbhytMaso;
	}

	@Column(name = "DTDMTINHBHYT_MA", unique = true, nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmtinhbhytMa() {
		return this.dtdmtinhbhytMa;
	}

	public void setDtdmtinhbhytMa(String dtdmtinhbhytMa) {
		this.dtdmtinhbhytMa = dtdmtinhbhytMa;
	}

	@Column(name = "DTDMTINHBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmtinhbhytTen() {
		return this.dtdmtinhbhytTen;
	}

	public void setDtdmtinhbhytTen(String dtdmtinhbhytTen) {
		this.dtdmtinhbhytTen = dtdmtinhbhytTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDMTINHBHYT_NGAYTINH", length = 0)
	public Date getDtdmtinhbhytNgaytinh() {
		return this.dtdmtinhbhytNgaytinh;
	}

	public void setDtdmtinhbhytNgaytinh(Date dtdmtinhbhytNgaytinh) {
		this.dtdmtinhbhytNgaytinh = dtdmtinhbhytNgaytinh;
	}

	@Column(name = "DTDMTINHBHYT_TEN1", length = 250)
	@Length(max = 250)
	public String getDtdmtinhbhytTen1() {
		return this.dtdmtinhbhytTen1;
	}

	public void setDtdmtinhbhytTen1(String dtdmtinhbhytTen1) {
		this.dtdmtinhbhytTen1 = dtdmtinhbhytTen1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDMTINHBHYT_NGAYTINH1", length = 0)
	public Date getDtdmtinhbhytNgaytinh1() {
		return this.dtdmtinhbhytNgaytinh1;
	}

	public void setDtdmtinhbhytNgaytinh1(Date dtdmtinhbhytNgaytinh1) {
		this.dtdmtinhbhytNgaytinh1 = dtdmtinhbhytNgaytinh1;
	}

	@Column(name = "DTDMTINHBHYT_TEN2", length = 250)
	@Length(max = 250)
	public String getDtdmtinhbhytTen2() {
		return this.dtdmtinhbhytTen2;
	}

	public void setDtdmtinhbhytTen2(String dtdmtinhbhytTen2) {
		this.dtdmtinhbhytTen2 = dtdmtinhbhytTen2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDMTINHBHYT_NGAYTINH2", length = 0)
	public Date getDtdmtinhbhytNgaytinh2() {
		return this.dtdmtinhbhytNgaytinh2;
	}

	public void setDtdmtinhbhytNgaytinh2(Date dtdmtinhbhytNgaytinh2) {
		this.dtdmtinhbhytNgaytinh2 = dtdmtinhbhytNgaytinh2;
	}

	@Column(name = "DTDMTINHBHYT_TEN3", length = 250)
	@Length(max = 250)
	public String getDtdmtinhbhytTen3() {
		return this.dtdmtinhbhytTen3;
	}

	public void setDtdmtinhbhytTen3(String dtdmtinhbhytTen3) {
		this.dtdmtinhbhytTen3 = dtdmtinhbhytTen3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDMTINHBHYT_NGAYTINH3", length = 0)
	public Date getDtdmtinhbhytNgaytinh3() {
		return this.dtdmtinhbhytNgaytinh3;
	}

	public void setDtdmtinhbhytNgaytinh3(Date dtdmtinhbhytNgaytinh3) {
		this.dtdmtinhbhytNgaytinh3 = dtdmtinhbhytNgaytinh3;
	}

	@Column(name = "DTDMTINHBHYT_NEW")
	public Boolean getDtdmtinhbhytNew() {
		return this.dtdmtinhbhytNew;
	}

	public void setDtdmtinhbhytNew(Boolean dtdmtinhbhytNew) {
		this.dtdmtinhbhytNew = dtdmtinhbhytNew;
	}

	@Column(name = "DTDMTINHBHYT_NOITINH", length = 50)
	@Length(max = 50)
	public String getDtdmtinhbhytNoitinh() {
		return this.dtdmtinhbhytNoitinh;
	}

	public void setDtdmtinhbhytNoitinh(String dtdmtinhbhytNoitinh) {
		this.dtdmtinhbhytNoitinh = dtdmtinhbhytNoitinh;
	}

	@Column(name = "DTDMTINHBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmtinhbhytNgaygiocn() {
		return this.dtdmtinhbhytNgaygiocn;
	}

	public void setDtdmtinhbhytNgaygiocn(Double dtdmtinhbhytNgaygiocn) {
		this.dtdmtinhbhytNgaygiocn = dtdmtinhbhytNgaygiocn;
	}

	@Column(name = "DTDMTINHBHYT_CHON")
	public Boolean getDtdmtinhbhytChon() {
		return this.dtdmtinhbhytChon;
	}

	public void setDtdmtinhbhytChon(Boolean dtdmtinhbhytChon) {
		this.dtdmtinhbhytChon = dtdmtinhbhytChon;
	}

	@Column(name = "DTDMTINHBHYT_DEFA")
	public Boolean getDtdmtinhbhytDefa() {
		return this.dtdmtinhbhytDefa;
	}

	public void setDtdmtinhbhytDefa(Boolean dtdmtinhbhytDefa) {
		this.dtdmtinhbhytDefa = dtdmtinhbhytDefa;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmTinhBhyt")
	public Set<DtDmKcbBhyt> getDtDmKcbBhyts() {
		return this.dtDmKcbBhyts;
	}

	public void setDtDmKcbBhyts(Set<DtDmKcbBhyt> dtDmKcbBhyts) {
		this.dtDmKcbBhyts = dtDmKcbBhyts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmTinhBhyt")
	public Set<DtDmKcbBhyt> getDtDmKcbBhyts_1() {
		return this.dtDmKcbBhyts_1;
	}

	public void setDtDmKcbBhyts_1(Set<DtDmKcbBhyt> dtDmKcbBhyts_1) {
		this.dtDmKcbBhyts_1 = dtDmKcbBhyts_1;
	}

}
