package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * DtDmChiDanDvt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CHI_DAN_DVT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DTDMCHIDAN_MASO", "DMDONVITINH_MASO" }))
public class DtDmChiDanDvt implements java.io.Serializable {

	private Integer dtdmchidandvtMaso;
	private DmDonViTinh dmDonViTinh;
	private DtDmChiDan dtDmChiDan;
	private Boolean dtdmchidandvtChon;
	private Double dtdmchidandvtNgaygiocn;

	public DtDmChiDanDvt() {
	}

	public DtDmChiDanDvt(DmDonViTinh dmDonViTinh, DtDmChiDan dtDmChiDan) {
		this.dmDonViTinh = dmDonViTinh;
		this.dtDmChiDan = dtDmChiDan;
	}

	public DtDmChiDanDvt(DmDonViTinh dmDonViTinh, DtDmChiDan dtDmChiDan,
			Boolean dtdmchidandvtChon, Double dtdmchidandvtNgaygiocn) {
		this.dmDonViTinh = dmDonViTinh;
		this.dtDmChiDan = dtDmChiDan;
		this.dtdmchidandvtChon = dtdmchidandvtChon;
		this.dtdmchidandvtNgaygiocn = dtdmchidandvtNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CHI_DAN_DVT")
	@SequenceGenerator(name = "DT_DM_CHI_DAN_DVT", sequenceName = "DT_DM_CHI_DAN_DVT_DTDMCHIDANDV", allocationSize = 1)
	@Column(name = "DTDMCHIDANDVT_MASO", unique = true, nullable = false)
	public Integer getDtdmchidandvtMaso() {
		return this.dtdmchidandvtMaso;
	}

	public void setDtdmchidandvtMaso(Integer dtdmchidandvtMaso) {
		this.dtdmchidandvtMaso = dtdmchidandvtMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMDONVITINH_MASO", nullable = false)
	@NotNull
	public DmDonViTinh getDmDonViTinh() {
		return this.dmDonViTinh;
	}

	public void setDmDonViTinh(DmDonViTinh dmDonViTinh) {
		this.dmDonViTinh = dmDonViTinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMCHIDAN_MASO", nullable = false)
	@NotNull
	public DtDmChiDan getDtDmChiDan() {
		return this.dtDmChiDan;
	}

	public void setDtDmChiDan(DtDmChiDan dtDmChiDan) {
		this.dtDmChiDan = dtDmChiDan;
	}

	@Column(name = "DTDMCHIDANDVT_CHON")
	public Boolean getDtdmchidandvtChon() {
		return this.dtdmchidandvtChon;
	}

	public void setDtdmchidandvtChon(Boolean dtdmchidandvtChon) {
		this.dtdmchidandvtChon = dtdmchidandvtChon;
	}

	@Column(name = "DTDMCHIDANDVT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmchidandvtNgaygiocn() {
		return this.dtdmchidandvtNgaygiocn;
	}

	public void setDtdmchidandvtNgaygiocn(Double dtdmchidandvtNgaygiocn) {
		this.dtdmchidandvtNgaygiocn = dtdmchidandvtNgaygiocn;
	}

}
