package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmNoiSinh generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NOI_SINH", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMNOISINH_MA"))
public class DtDmNoiSinh implements java.io.Serializable {

	private Integer dtdmnoisinhMaso;
	private String dtdmnoisinhMa;
	private String dtdmnoisinhTen;
	private String dtdmnoisinhMaphu;
	private String dtdmnoisinhPhanloai;
	private String dtdmnoisinhGhichu;
	private Double dtdmnoisinhNgaygiocn;
	private Boolean dtdmnoisinhChon;

	public DtDmNoiSinh() {
	}

	public DtDmNoiSinh(String dtdmnoisinhMa, String dtdmnoisinhTen) {
		this.dtdmnoisinhMa = dtdmnoisinhMa;
		this.dtdmnoisinhTen = dtdmnoisinhTen;
	}

	public DtDmNoiSinh(String dtdmnoisinhMa, String dtdmnoisinhTen,
			String dtdmnoisinhMaphu, String dtdmnoisinhPhanloai,
			String dtdmnoisinhGhichu, Double dtdmnoisinhNgaygiocn,
			Boolean dtdmnoisinhChon) {
		this.dtdmnoisinhMa = dtdmnoisinhMa;
		this.dtdmnoisinhTen = dtdmnoisinhTen;
		this.dtdmnoisinhMaphu = dtdmnoisinhMaphu;
		this.dtdmnoisinhPhanloai = dtdmnoisinhPhanloai;
		this.dtdmnoisinhGhichu = dtdmnoisinhGhichu;
		this.dtdmnoisinhNgaygiocn = dtdmnoisinhNgaygiocn;
		this.dtdmnoisinhChon = dtdmnoisinhChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NOI_SINH")
	@SequenceGenerator(name = "DT_DM_NOI_SINH", sequenceName = "DT_DM_NOI_SINH_DTDMNOISINH_MAS", allocationSize = 1)
	@Column(name = "DTDMNOISINH_MASO", unique = true, nullable = false)
	public Integer getDtdmnoisinhMaso() {
		return this.dtdmnoisinhMaso;
	}

	public void setDtdmnoisinhMaso(Integer dtdmnoisinhMaso) {
		this.dtdmnoisinhMaso = dtdmnoisinhMaso;
	}

	@Column(name = "DTDMNOISINH_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDtdmnoisinhMa() {
		return this.dtdmnoisinhMa;
	}

	public void setDtdmnoisinhMa(String dtdmnoisinhMa) {
		this.dtdmnoisinhMa = dtdmnoisinhMa;
	}

	@Column(name = "DTDMNOISINH_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmnoisinhTen() {
		return this.dtdmnoisinhTen;
	}

	public void setDtdmnoisinhTen(String dtdmnoisinhTen) {
		this.dtdmnoisinhTen = dtdmnoisinhTen;
	}

	@Column(name = "DTDMNOISINH_MAPHU", length = 3)
	@Length(max = 3)
	public String getDtdmnoisinhMaphu() {
		return this.dtdmnoisinhMaphu;
	}

	public void setDtdmnoisinhMaphu(String dtdmnoisinhMaphu) {
		this.dtdmnoisinhMaphu = dtdmnoisinhMaphu;
	}

	@Column(name = "DTDMNOISINH_PHANLOAI", length = 5)
	@Length(max = 5)
	public String getDtdmnoisinhPhanloai() {
		return this.dtdmnoisinhPhanloai;
	}

	public void setDtdmnoisinhPhanloai(String dtdmnoisinhPhanloai) {
		this.dtdmnoisinhPhanloai = dtdmnoisinhPhanloai;
	}

	@Column(name = "DTDMNOISINH_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmnoisinhGhichu() {
		return this.dtdmnoisinhGhichu;
	}

	public void setDtdmnoisinhGhichu(String dtdmnoisinhGhichu) {
		this.dtdmnoisinhGhichu = dtdmnoisinhGhichu;
	}

	@Column(name = "DTDMNOISINH_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnoisinhNgaygiocn() {
		return this.dtdmnoisinhNgaygiocn;
	}

	public void setDtdmnoisinhNgaygiocn(Double dtdmnoisinhNgaygiocn) {
		this.dtdmnoisinhNgaygiocn = dtdmnoisinhNgaygiocn;
	}

	@Column(name = "DTDMNOISINH_CHON")
	public Boolean getDtdmnoisinhChon() {
		return this.dtdmnoisinhChon;
	}

	public void setDtdmnoisinhChon(Boolean dtdmnoisinhChon) {
		this.dtdmnoisinhChon = dtdmnoisinhChon;
	}

}
