package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmNhanVien generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NHAN_VIEN", catalog = "DB_YTDT_BD")
public class DtDmNhanVien implements java.io.Serializable {

	private Integer dtdmnhanvienMaso;
	private DmHocVi dmHocVi;
	private NguoiDung nguoiDung;
	private String dtdmnhanvienMa;
	private String nhomMa;
	private String dtdmnhanvienTen;
	private String dtdmnhanvienGioitinh;
	private Date dtdmnhanvienNgaysinh;
	private String dtdmnhanvienMahh;
	private String dtdmnhanvienBienche;
	private String dtdmnhanvienDiachi;
	private String dtdmnhanvienMobile;
	private String dtdmnhanvienEmail;
	private Boolean dtdmnhanvienKyphieu;
	private Boolean dtdmnhanvienDuyet;
	private Boolean dtdmnhanvienMo;
	private Boolean dtdmnhanvienNghiviec;
	private String dtdmnhanvienMatma;
	private String dtdmnhanvienTkatm;
	private String dtdmnhanvienSobhxh;
	private Double dtdmnhanvienNgaygiocn;
	private Boolean dtdmnhanvienChon;
	private Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas = new HashSet<DtDmNhanvienKhoa>(
			0);
	private Set<DtDmBacSiBanKham> dtDmBacSiBanKhams = new HashSet<DtDmBacSiBanKham>(
			0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1 = new HashSet<DtDmBanKham>(
			0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2 = new HashSet<DtDmBanKham>(
			0);
	private Set<DtDmKho> dtDmKhos = new HashSet<DtDmKho>(0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3 = new HashSet<DtDmBanKham>(
			0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1_1 = new HashSet<DtDmBanKham>(
			0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2_1 = new HashSet<DtDmBanKham>(
			0);
	private Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3_1 = new HashSet<DtDmBanKham>(
			0);
	private Set<DonMien> donMiens = new HashSet<DonMien>(0);
	private Set<DtDmKho> dtDmKhos_1 = new HashSet<DtDmKho>(0);
	private Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1 = new HashSet<DtDmNhanvienKhoa>(
			0);
	private Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1 = new HashSet<DtDmBacSiBanKham>(
			0);

	public DtDmNhanVien() {
	}

	public DtDmNhanVien(String dtdmnhanvienMa, String dtdmnhanvienTen) {
		this.dtdmnhanvienMa = dtdmnhanvienMa;
		this.dtdmnhanvienTen = dtdmnhanvienTen;
	}

	public DtDmNhanVien(DmHocVi dmHocVi, NguoiDung nguoiDung,
			String dtdmnhanvienMa, String nhomMa, String dtdmnhanvienTen,
			String dtdmnhanvienGioitinh, Date dtdmnhanvienNgaysinh,
			String dtdmnhanvienMahh, String dtdmnhanvienBienche,
			String dtdmnhanvienDiachi, String dtdmnhanvienMobile,
			String dtdmnhanvienEmail, Boolean dtdmnhanvienKyphieu,
			Boolean dtdmnhanvienDuyet, Boolean dtdmnhanvienMo,
			Boolean dtdmnhanvienNghiviec, String dtdmnhanvienMatma,
			String dtdmnhanvienTkatm, String dtdmnhanvienSobhxh,
			Double dtdmnhanvienNgaygiocn, Boolean dtdmnhanvienChon,
			Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas,
			Set<DtDmBacSiBanKham> dtDmBacSiBanKhams,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2,
			Set<DtDmKho> dtDmKhos,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1_1,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2_1,
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3_1,
			Set<DonMien> donMiens, Set<DtDmKho> dtDmKhos_1,
			Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1,
			Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1) {
		this.dmHocVi = dmHocVi;
		this.nguoiDung = nguoiDung;
		this.dtdmnhanvienMa = dtdmnhanvienMa;
		this.nhomMa = nhomMa;
		this.dtdmnhanvienTen = dtdmnhanvienTen;
		this.dtdmnhanvienGioitinh = dtdmnhanvienGioitinh;
		this.dtdmnhanvienNgaysinh = dtdmnhanvienNgaysinh;
		this.dtdmnhanvienMahh = dtdmnhanvienMahh;
		this.dtdmnhanvienBienche = dtdmnhanvienBienche;
		this.dtdmnhanvienDiachi = dtdmnhanvienDiachi;
		this.dtdmnhanvienMobile = dtdmnhanvienMobile;
		this.dtdmnhanvienEmail = dtdmnhanvienEmail;
		this.dtdmnhanvienKyphieu = dtdmnhanvienKyphieu;
		this.dtdmnhanvienDuyet = dtdmnhanvienDuyet;
		this.dtdmnhanvienMo = dtdmnhanvienMo;
		this.dtdmnhanvienNghiviec = dtdmnhanvienNghiviec;
		this.dtdmnhanvienMatma = dtdmnhanvienMatma;
		this.dtdmnhanvienTkatm = dtdmnhanvienTkatm;
		this.dtdmnhanvienSobhxh = dtdmnhanvienSobhxh;
		this.dtdmnhanvienNgaygiocn = dtdmnhanvienNgaygiocn;
		this.dtdmnhanvienChon = dtdmnhanvienChon;
		this.dtDmNhanvienKhoas = dtDmNhanvienKhoas;
		this.dtDmBacSiBanKhams = dtDmBacSiBanKhams;
		this.dtDmBanKhamsForDtdmnhanvienBacsi1 = dtDmBanKhamsForDtdmnhanvienBacsi1;
		this.dtDmBanKhamsForDtdmnhanvienBacsi2 = dtDmBanKhamsForDtdmnhanvienBacsi2;
		this.dtDmKhos = dtDmKhos;
		this.dtDmBanKhamsForDtdmnhanvienBacsi3 = dtDmBanKhamsForDtdmnhanvienBacsi3;
		this.dtDmBanKhamsForDtdmnhanvienBacsi1_1 = dtDmBanKhamsForDtdmnhanvienBacsi1_1;
		this.dtDmBanKhamsForDtdmnhanvienBacsi2_1 = dtDmBanKhamsForDtdmnhanvienBacsi2_1;
		this.dtDmBanKhamsForDtdmnhanvienBacsi3_1 = dtDmBanKhamsForDtdmnhanvienBacsi3_1;
		this.donMiens = donMiens;
		this.dtDmKhos_1 = dtDmKhos_1;
		this.dtDmNhanvienKhoas_1 = dtDmNhanvienKhoas_1;
		this.dtDmBacSiBanKhams_1 = dtDmBacSiBanKhams_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NHAN_VIEN")
	@SequenceGenerator(name = "DT_DM_NHAN_VIEN", sequenceName = "DT_DM_NHAN_VIEN_DTDMNHANVIEN_M", allocationSize = 1)
	@Column(name = "DTDMNHANVIEN_MASO", unique = true, nullable = false)
	public Integer getDtdmnhanvienMaso() {
		return this.dtdmnhanvienMaso;
	}

	public void setDtdmnhanvienMaso(Integer dtdmnhanvienMaso) {
		this.dtdmnhanvienMaso = dtdmnhanvienMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMHOCVI_MASO")
	public DmHocVi getDmHocVi() {
		return this.dmHocVi;
	}

	public void setDmHocVi(DmHocVi dmHocVi) {
		this.dmHocVi = dmHocVi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_MASO")
	public NguoiDung getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(NguoiDung nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	@Column(name = "DTDMNHANVIEN_MA", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDtdmnhanvienMa() {
		return this.dtdmnhanvienMa;
	}

	public void setDtdmnhanvienMa(String dtdmnhanvienMa) {
		this.dtdmnhanvienMa = dtdmnhanvienMa;
	}

	@Column(name = "NHOM_MA", length = 8)
	@Length(max = 8)
	public String getNhomMa() {
		return this.nhomMa;
	}

	public void setNhomMa(String nhomMa) {
		this.nhomMa = nhomMa;
	}

	@Column(name = "DTDMNHANVIEN_TEN", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDtdmnhanvienTen() {
		return this.dtdmnhanvienTen;
	}

	public void setDtdmnhanvienTen(String dtdmnhanvienTen) {
		this.dtdmnhanvienTen = dtdmnhanvienTen;
	}

	@Column(name = "DTDMNHANVIEN_GIOITINH", length = 3)
	@Length(max = 3)
	public String getDtdmnhanvienGioitinh() {
		return this.dtdmnhanvienGioitinh;
	}

	public void setDtdmnhanvienGioitinh(String dtdmnhanvienGioitinh) {
		this.dtdmnhanvienGioitinh = dtdmnhanvienGioitinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDMNHANVIEN_NGAYSINH", length = 0)
	public Date getDtdmnhanvienNgaysinh() {
		return this.dtdmnhanvienNgaysinh;
	}

	public void setDtdmnhanvienNgaysinh(Date dtdmnhanvienNgaysinh) {
		this.dtdmnhanvienNgaysinh = dtdmnhanvienNgaysinh;
	}

	@Column(name = "DTDMNHANVIEN_MAHH", length = 8)
	@Length(max = 8)
	public String getDtdmnhanvienMahh() {
		return this.dtdmnhanvienMahh;
	}

	public void setDtdmnhanvienMahh(String dtdmnhanvienMahh) {
		this.dtdmnhanvienMahh = dtdmnhanvienMahh;
	}

	@Column(name = "DTDMNHANVIEN_BIENCHE", length = 1)
	@Length(max = 1)
	public String getDtdmnhanvienBienche() {
		return this.dtdmnhanvienBienche;
	}

	public void setDtdmnhanvienBienche(String dtdmnhanvienBienche) {
		this.dtdmnhanvienBienche = dtdmnhanvienBienche;
	}

	@Column(name = "DTDMNHANVIEN_DIACHI", length = 50)
	@Length(max = 50)
	public String getDtdmnhanvienDiachi() {
		return this.dtdmnhanvienDiachi;
	}

	public void setDtdmnhanvienDiachi(String dtdmnhanvienDiachi) {
		this.dtdmnhanvienDiachi = dtdmnhanvienDiachi;
	}

	@Column(name = "DTDMNHANVIEN_MOBILE", length = 12)
	@Length(max = 12)
	public String getDtdmnhanvienMobile() {
		return this.dtdmnhanvienMobile;
	}

	public void setDtdmnhanvienMobile(String dtdmnhanvienMobile) {
		this.dtdmnhanvienMobile = dtdmnhanvienMobile;
	}

	@Column(name = "DTDMNHANVIEN_EMAIL", length = 50)
	@Length(max = 50)
	public String getDtdmnhanvienEmail() {
		return this.dtdmnhanvienEmail;
	}

	public void setDtdmnhanvienEmail(String dtdmnhanvienEmail) {
		this.dtdmnhanvienEmail = dtdmnhanvienEmail;
	}

	@Column(name = "DTDMNHANVIEN_KYPHIEU")
	public Boolean getDtdmnhanvienKyphieu() {
		return this.dtdmnhanvienKyphieu;
	}

	public void setDtdmnhanvienKyphieu(Boolean dtdmnhanvienKyphieu) {
		this.dtdmnhanvienKyphieu = dtdmnhanvienKyphieu;
	}

	@Column(name = "DTDMNHANVIEN_DUYET")
	public Boolean getDtdmnhanvienDuyet() {
		return this.dtdmnhanvienDuyet;
	}

	public void setDtdmnhanvienDuyet(Boolean dtdmnhanvienDuyet) {
		this.dtdmnhanvienDuyet = dtdmnhanvienDuyet;
	}

	@Column(name = "DTDMNHANVIEN_MO")
	public Boolean getDtdmnhanvienMo() {
		return this.dtdmnhanvienMo;
	}

	public void setDtdmnhanvienMo(Boolean dtdmnhanvienMo) {
		this.dtdmnhanvienMo = dtdmnhanvienMo;
	}

	@Column(name = "DTDMNHANVIEN_NGHIVIEC")
	public Boolean getDtdmnhanvienNghiviec() {
		return this.dtdmnhanvienNghiviec;
	}

	public void setDtdmnhanvienNghiviec(Boolean dtdmnhanvienNghiviec) {
		this.dtdmnhanvienNghiviec = dtdmnhanvienNghiviec;
	}

	@Column(name = "DTDMNHANVIEN_MATMA", length = 20)
	@Length(max = 20)
	public String getDtdmnhanvienMatma() {
		return this.dtdmnhanvienMatma;
	}

	public void setDtdmnhanvienMatma(String dtdmnhanvienMatma) {
		this.dtdmnhanvienMatma = dtdmnhanvienMatma;
	}

	@Column(name = "DTDMNHANVIEN_TKATM", length = 12)
	@Length(max = 12)
	public String getDtdmnhanvienTkatm() {
		return this.dtdmnhanvienTkatm;
	}

	public void setDtdmnhanvienTkatm(String dtdmnhanvienTkatm) {
		this.dtdmnhanvienTkatm = dtdmnhanvienTkatm;
	}

	@Column(name = "DTDMNHANVIEN_SOBHXH", length = 12)
	@Length(max = 12)
	public String getDtdmnhanvienSobhxh() {
		return this.dtdmnhanvienSobhxh;
	}

	public void setDtdmnhanvienSobhxh(String dtdmnhanvienSobhxh) {
		this.dtdmnhanvienSobhxh = dtdmnhanvienSobhxh;
	}

	@Column(name = "DTDMNHANVIEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnhanvienNgaygiocn() {
		return this.dtdmnhanvienNgaygiocn;
	}

	public void setDtdmnhanvienNgaygiocn(Double dtdmnhanvienNgaygiocn) {
		this.dtdmnhanvienNgaygiocn = dtdmnhanvienNgaygiocn;
	}

	@Column(name = "DTDMNHANVIEN_CHON")
	public Boolean getDtdmnhanvienChon() {
		return this.dtdmnhanvienChon;
	}

	public void setDtdmnhanvienChon(Boolean dtdmnhanvienChon) {
		this.dtdmnhanvienChon = dtdmnhanvienChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmNhanvienKhoa> getDtDmNhanvienKhoas() {
		return this.dtDmNhanvienKhoas;
	}

	public void setDtDmNhanvienKhoas(Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas) {
		this.dtDmNhanvienKhoas = dtDmNhanvienKhoas;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmBacSiBanKham> getDtDmBacSiBanKhams() {
		return this.dtDmBacSiBanKhams;
	}

	public void setDtDmBacSiBanKhams(Set<DtDmBacSiBanKham> dtDmBacSiBanKhams) {
		this.dtDmBacSiBanKhams = dtDmBacSiBanKhams;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi1")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi1() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi1;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi1(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi1 = dtDmBanKhamsForDtdmnhanvienBacsi1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi2")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi2() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi2;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi2(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi2 = dtDmBanKhamsForDtdmnhanvienBacsi2;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmKho> getDtDmKhos() {
		return this.dtDmKhos;
	}

	public void setDtDmKhos(Set<DtDmKho> dtDmKhos) {
		this.dtDmKhos = dtDmKhos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi3")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi3() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi3;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi3(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi3 = dtDmBanKhamsForDtdmnhanvienBacsi3;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi1")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi1_1() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi1_1;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi1_1(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi1_1) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi1_1 = dtDmBanKhamsForDtdmnhanvienBacsi1_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi2")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi2_1() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi2_1;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi2_1(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi2_1) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi2_1 = dtDmBanKhamsForDtdmnhanvienBacsi2_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVienByDtdmnhanvienBacsi3")
	public Set<DtDmBanKham> getDtDmBanKhamsForDtdmnhanvienBacsi3_1() {
		return this.dtDmBanKhamsForDtdmnhanvienBacsi3_1;
	}

	public void setDtDmBanKhamsForDtdmnhanvienBacsi3_1(
			Set<DtDmBanKham> dtDmBanKhamsForDtdmnhanvienBacsi3_1) {
		this.dtDmBanKhamsForDtdmnhanvienBacsi3_1 = dtDmBanKhamsForDtdmnhanvienBacsi3_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DonMien> getDonMiens() {
		return this.donMiens;
	}

	public void setDonMiens(Set<DonMien> donMiens) {
		this.donMiens = donMiens;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmKho> getDtDmKhos_1() {
		return this.dtDmKhos_1;
	}

	public void setDtDmKhos_1(Set<DtDmKho> dtDmKhos_1) {
		this.dtDmKhos_1 = dtDmKhos_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmNhanvienKhoa> getDtDmNhanvienKhoas_1() {
		return this.dtDmNhanvienKhoas_1;
	}

	public void setDtDmNhanvienKhoas_1(Set<DtDmNhanvienKhoa> dtDmNhanvienKhoas_1) {
		this.dtDmNhanvienKhoas_1 = dtDmNhanvienKhoas_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhanVien")
	public Set<DtDmBacSiBanKham> getDtDmBacSiBanKhams_1() {
		return this.dtDmBacSiBanKhams_1;
	}

	public void setDtDmBacSiBanKhams_1(Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1) {
		this.dtDmBacSiBanKhams_1 = dtDmBacSiBanKhams_1;
	}

}
