package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoaiMien generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOAI_MIEN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLOAIMIEN_MA"))
public class DtDmLoaiMien implements java.io.Serializable {

	private Integer dtdmloaimienMaso;
	private String dtdmloaimienMa;
	private String dtdmloaimienTen;
	private Double dtdmloaimienNgaygiocn;
	private Boolean dtdmloaimienChon;

	public DtDmLoaiMien() {
	}

	public DtDmLoaiMien(String dtdmloaimienMa, String dtdmloaimienTen) {
		this.dtdmloaimienMa = dtdmloaimienMa;
		this.dtdmloaimienTen = dtdmloaimienTen;
	}

	public DtDmLoaiMien(String dtdmloaimienMa, String dtdmloaimienTen,
			Double dtdmloaimienNgaygiocn, Boolean dtdmloaimienChon) {
		this.dtdmloaimienMa = dtdmloaimienMa;
		this.dtdmloaimienTen = dtdmloaimienTen;
		this.dtdmloaimienNgaygiocn = dtdmloaimienNgaygiocn;
		this.dtdmloaimienChon = dtdmloaimienChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOAI_MIEN")
	@SequenceGenerator(name = "DT_DM_LOAI_MIEN", sequenceName = "DT_DM_LOAI_MIEN_DTDMLOAIMIEN_M", allocationSize = 1)
	@Column(name = "DTDMLOAIMIEN_MASO", unique = true, nullable = false)
	public Integer getDtdmloaimienMaso() {
		return this.dtdmloaimienMaso;
	}

	public void setDtdmloaimienMaso(Integer dtdmloaimienMaso) {
		this.dtdmloaimienMaso = dtdmloaimienMaso;
	}

	@Column(name = "DTDMLOAIMIEN_MA", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getDtdmloaimienMa() {
		return this.dtdmloaimienMa;
	}

	public void setDtdmloaimienMa(String dtdmloaimienMa) {
		this.dtdmloaimienMa = dtdmloaimienMa;
	}

	@Column(name = "DTDMLOAIMIEN_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmloaimienTen() {
		return this.dtdmloaimienTen;
	}

	public void setDtdmloaimienTen(String dtdmloaimienTen) {
		this.dtdmloaimienTen = dtdmloaimienTen;
	}

	@Column(name = "DTDMLOAIMIEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmloaimienNgaygiocn() {
		return this.dtdmloaimienNgaygiocn;
	}

	public void setDtdmloaimienNgaygiocn(Double dtdmloaimienNgaygiocn) {
		this.dtdmloaimienNgaygiocn = dtdmloaimienNgaygiocn;
	}

	@Column(name = "DTDMLOAIMIEN_CHON")
	public Boolean getDtdmloaimienChon() {
		return this.dtdmloaimienChon;
	}

	public void setDtdmloaimienChon(Boolean dtdmloaimienChon) {
		this.dtdmloaimienChon = dtdmloaimienChon;
	}

}
