package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoiDan generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOI_DAN", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLD_MA"))
public class DtDmLoiDan implements java.io.Serializable {

	private Integer dtdmldMaso;
	private String dtdmldMa;
	private String dtdmldTen;
	private double dtdmldNgaygiocn;
	private Integer dtdmldChon;

	public DtDmLoiDan() {
	}

	public DtDmLoiDan(String dtdmldMa, String dtdmldTen, double dtdmldNgaygiocn) {
		this.dtdmldMa = dtdmldMa;
		this.dtdmldTen = dtdmldTen;
		this.dtdmldNgaygiocn = dtdmldNgaygiocn;
	}

	public DtDmLoiDan(String dtdmldMa, String dtdmldTen,
			double dtdmldNgaygiocn, Integer dtdmldChon) {
		this.dtdmldMa = dtdmldMa;
		this.dtdmldTen = dtdmldTen;
		this.dtdmldNgaygiocn = dtdmldNgaygiocn;
		this.dtdmldChon = dtdmldChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOI_DAN")
	@SequenceGenerator(name = "DT_DM_LOI_DAN", sequenceName = "DT_DM_LOI_DAN_DTDMLD_MASO_SEQ", allocationSize = 1)
	@Column(name = "DTDMLD_MASO", unique = true, nullable = false)
	public Integer getDtdmldMaso() {
		return this.dtdmldMaso;
	}

	public void setDtdmldMaso(Integer dtdmldMaso) {
		this.dtdmldMaso = dtdmldMaso;
	}

	@Column(name = "DTDMLD_MA", unique = true, nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDtdmldMa() {
		return this.dtdmldMa;
	}

	public void setDtdmldMa(String dtdmldMa) {
		this.dtdmldMa = dtdmldMa;
	}

	@Column(name = "DTDMLD_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmldTen() {
		return this.dtdmldTen;
	}

	public void setDtdmldTen(String dtdmldTen) {
		this.dtdmldTen = dtdmldTen;
	}

	@Column(name = "DTDMLD_NGAYGIOCN", nullable = false, precision = 22, scale = 0)
	@NotNull
	public double getDtdmldNgaygiocn() {
		return this.dtdmldNgaygiocn;
	}

	public void setDtdmldNgaygiocn(double dtdmldNgaygiocn) {
		this.dtdmldNgaygiocn = dtdmldNgaygiocn;
	}

	@Column(name = "DTDMLD_CHON")
	public Integer getDtdmldChon() {
		return this.dtdmldChon;
	}

	public void setDtdmldChon(Integer dtdmldChon) {
		this.dtdmldChon = dtdmldChon;
	}

}
