package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * DtDmNhanvienKhoa generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NHANVIEN_KHOA", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DTDMNHANVIEN_MASO", "DMKHOA_MASO" }))
public class DtDmNhanvienKhoa implements java.io.Serializable {

	private Integer dtdmnhanvienkhoaMaso;
	private DtDmNhanVien dtDmNhanVien;
	private DmKhoa dmKhoa;
	private Boolean dtdmnvkhoaChon;
	private Double dtdmnvkhoaNgaygiocn;

	public DtDmNhanvienKhoa() {
	}

	public DtDmNhanvienKhoa(DtDmNhanVien dtDmNhanVien, DmKhoa dmKhoa) {
		this.dtDmNhanVien = dtDmNhanVien;
		this.dmKhoa = dmKhoa;
	}

	public DtDmNhanvienKhoa(DtDmNhanVien dtDmNhanVien, DmKhoa dmKhoa,
			Boolean dtdmnvkhoaChon, Double dtdmnvkhoaNgaygiocn) {
		this.dtDmNhanVien = dtDmNhanVien;
		this.dmKhoa = dmKhoa;
		this.dtdmnvkhoaChon = dtdmnvkhoaChon;
		this.dtdmnvkhoaNgaygiocn = dtdmnvkhoaNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NHANVIEN_KHOA")
	@SequenceGenerator(name = "DT_DM_NHANVIEN_KHOA", sequenceName = "DT_DM_NHANVIEN_KHOA_DTDMNHANVI", allocationSize = 1)
	@Column(name = "DTDMNHANVIENKHOA_MASO", unique = true, nullable = false)
	public Integer getDtdmnhanvienkhoaMaso() {
		return this.dtdmnhanvienkhoaMaso;
	}

	public void setDtdmnhanvienkhoaMaso(Integer dtdmnhanvienkhoaMaso) {
		this.dtdmnhanvienkhoaMaso = dtdmnhanvienkhoaMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHANVIEN_MASO", nullable = false)
	@NotNull
	public DtDmNhanVien getDtDmNhanVien() {
		return this.dtDmNhanVien;
	}

	public void setDtDmNhanVien(DtDmNhanVien dtDmNhanVien) {
		this.dtDmNhanVien = dtDmNhanVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MASO", nullable = false)
	@NotNull
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@Column(name = "DTDMNVKHOA_CHON")
	public Boolean getDtdmnvkhoaChon() {
		return this.dtdmnvkhoaChon;
	}

	public void setDtdmnvkhoaChon(Boolean dtdmnvkhoaChon) {
		this.dtdmnvkhoaChon = dtdmnvkhoaChon;
	}

	@Column(name = "DTDMNVKHOA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnvkhoaNgaygiocn() {
		return this.dtdmnvkhoaNgaygiocn;
	}

	public void setDtdmnvkhoaNgaygiocn(Double dtdmnvkhoaNgaygiocn) {
		this.dtdmnvkhoaNgaygiocn = dtdmnvkhoaNgaygiocn;
	}

}
