package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * DtDmClsKetQua generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_CLS_KET_QUA", catalog = "DB_YTDT_BD")
public class DtDmClsKetQua implements java.io.Serializable {

	private Integer dtdtclskqMaso;
	private DtDmClsBangGia dtDmClsBangGia;
	private String dtdmclskqMa;
	private String dtdmclskqTen;
	private String dtdmclskqGhiChu;
	private Double dtdmclskqNgaygiocn;

	public DtDmClsKetQua() {
	}

	public DtDmClsKetQua(DtDmClsBangGia dtDmClsBangGia, String dtdmclskqMa,
			String dtdmclskqTen, String dtdmclskqGhiChu,
			Double dtdmclskqNgaygiocn) {
		this.dtDmClsBangGia = dtDmClsBangGia;
		this.dtdmclskqMa = dtdmclskqMa;
		this.dtdmclskqTen = dtdmclskqTen;
		this.dtdmclskqGhiChu = dtdmclskqGhiChu;
		this.dtdmclskqNgaygiocn = dtdmclskqNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_CLS_KET_QUA")
	@SequenceGenerator(name = "DT_DM_CLS_KET_QUA", sequenceName = "DT_DM_CLS_KET_QUA_DTDTCLSKQ_MA", allocationSize = 1)
	@Column(name = "DTDTCLSKQ_MASO", unique = true, nullable = false)
	public Integer getDtdtclskqMaso() {
		return this.dtdtclskqMaso;
	}

	public void setDtdtclskqMaso(Integer dtdtclskqMaso) {
		this.dtdtclskqMaso = dtdtclskqMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMCLSBG_MASO")
	public DtDmClsBangGia getDtDmClsBangGia() {
		return this.dtDmClsBangGia;
	}

	public void setDtDmClsBangGia(DtDmClsBangGia dtDmClsBangGia) {
		this.dtDmClsBangGia = dtDmClsBangGia;
	}

	@Column(name = "DTDMCLSKQ_MA", length = 45)
	@Length(max = 45)
	public String getDtdmclskqMa() {
		return this.dtdmclskqMa;
	}

	public void setDtdmclskqMa(String dtdmclskqMa) {
		this.dtdmclskqMa = dtdmclskqMa;
	}

	@Column(name = "DTDMCLSKQ_TEN")
	public String getDtdmclskqTen() {
		return this.dtdmclskqTen;
	}

	public void setDtdmclskqTen(String dtdmclskqTen) {
		this.dtdmclskqTen = dtdmclskqTen;
	}

	@Column(name = "DTDMCLSKQ_GHI_CHU", length = 65535)
	@Length(max = 65535)
	public String getDtdmclskqGhiChu() {
		return this.dtdmclskqGhiChu;
	}

	public void setDtdmclskqGhiChu(String dtdmclskqGhiChu) {
		this.dtdmclskqGhiChu = dtdmclskqGhiChu;
	}

	@Column(name = "DTDMCLSKQ_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmclskqNgaygiocn() {
		return this.dtdmclskqNgaygiocn;
	}

	public void setDtdmclskqNgaygiocn(Double dtdmclskqNgaygiocn) {
		this.dtdmclskqNgaygiocn = dtdmclskqNgaygiocn;
	}

}
