package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmKho generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_KHO", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMKHO_MA"))
public class DtDmKho implements java.io.Serializable {

	private Integer dtdmkhoMaso;
	private DtDmNhanVien dtDmNhanVien;
	private DmKhoa dmKhoa;
	private String dtdmkhoMa;
	private String dtdmkhoTen;
	private Integer dtdmkhoThutubc;
	private Integer dtdmkhoChon;
	private Double dtdmkhoaNgaygiocn;

	public DtDmKho() {
	}

	public DtDmKho(String dtdmkhoMa, String dtdmkhoTen) {
		this.dtdmkhoMa = dtdmkhoMa;
		this.dtdmkhoTen = dtdmkhoTen;
	}

	public DtDmKho(DtDmNhanVien dtDmNhanVien, DmKhoa dmKhoa, String dtdmkhoMa,
			String dtdmkhoTen, Integer dtdmkhoThutubc, Integer dtdmkhoChon,
			Double dtdmkhoaNgaygiocn) {
		this.dtDmNhanVien = dtDmNhanVien;
		this.dmKhoa = dmKhoa;
		this.dtdmkhoMa = dtdmkhoMa;
		this.dtdmkhoTen = dtdmkhoTen;
		this.dtdmkhoThutubc = dtdmkhoThutubc;
		this.dtdmkhoChon = dtdmkhoChon;
		this.dtdmkhoaNgaygiocn = dtdmkhoaNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_KHO")
	@SequenceGenerator(name = "DT_DM_KHO", sequenceName = "DT_DM_KHO_DTDMKHO_MASO_SEQ", allocationSize = 1)
	@Column(name = "DTDMKHO_MASO", unique = true, nullable = false)
	public Integer getDtdmkhoMaso() {
		return this.dtdmkhoMaso;
	}

	public void setDtdmkhoMaso(Integer dtdmkhoMaso) {
		this.dtdmkhoMaso = dtdmkhoMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMKHO_THUKHO")
	public DtDmNhanVien getDtDmNhanVien() {
		return this.dtDmNhanVien;
	}

	public void setDtDmNhanVien(DtDmNhanVien dtDmNhanVien) {
		this.dtDmNhanVien = dtDmNhanVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMKHO_KHOCHA")
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@Column(name = "DTDMKHO_MA", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getDtdmkhoMa() {
		return this.dtdmkhoMa;
	}

	public void setDtdmkhoMa(String dtdmkhoMa) {
		this.dtdmkhoMa = dtdmkhoMa;
	}

	@Column(name = "DTDMKHO_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmkhoTen() {
		return this.dtdmkhoTen;
	}

	public void setDtdmkhoTen(String dtdmkhoTen) {
		this.dtdmkhoTen = dtdmkhoTen;
	}

	@Column(name = "DTDMKHO_THUTUBC")
	public Integer getDtdmkhoThutubc() {
		return this.dtdmkhoThutubc;
	}

	public void setDtdmkhoThutubc(Integer dtdmkhoThutubc) {
		this.dtdmkhoThutubc = dtdmkhoThutubc;
	}

	@Column(name = "DTDMKHO_CHON")
	public Integer getDtdmkhoChon() {
		return this.dtdmkhoChon;
	}

	public void setDtdmkhoChon(Integer dtdmkhoChon) {
		this.dtdmkhoChon = dtdmkhoChon;
	}

	@Column(name = "DTDMKHOA_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmkhoaNgaygiocn() {
		return this.dtdmkhoaNgaygiocn;
	}

	public void setDtdmkhoaNgaygiocn(Double dtdmkhoaNgaygiocn) {
		this.dtdmkhoaNgaygiocn = dtdmkhoaNgaygiocn;
	}

}
