package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmTuyenKcb generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_TUYEN_KCB", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMTUYENKCB_MA"))
public class DtDmTuyenKcb implements java.io.Serializable {

	private Integer dtdmtuyenkcbMaso;
	private String dtdmtuyenkcbMa;
	private String dtdmtuyenkcbTen;
	private Double dtdmtuyenkcbNgaygiocn;
	private Boolean dtdmtuyenkcbChon;
	private Set<DtDmKcbBhyt> dtDmKcbBhyts = new HashSet<DtDmKcbBhyt>(0);
	private Set<DtDmKcbBhyt> dtDmKcbBhyts_1 = new HashSet<DtDmKcbBhyt>(0);

	public DtDmTuyenKcb() {
	}

	public DtDmTuyenKcb(String dtdmtuyenkcbMa, String dtdmtuyenkcbTen) {
		this.dtdmtuyenkcbMa = dtdmtuyenkcbMa;
		this.dtdmtuyenkcbTen = dtdmtuyenkcbTen;
	}

	public DtDmTuyenKcb(String dtdmtuyenkcbMa, String dtdmtuyenkcbTen,
			Double dtdmtuyenkcbNgaygiocn, Boolean dtdmtuyenkcbChon,
			Set<DtDmKcbBhyt> dtDmKcbBhyts, Set<DtDmKcbBhyt> dtDmKcbBhyts_1) {
		this.dtdmtuyenkcbMa = dtdmtuyenkcbMa;
		this.dtdmtuyenkcbTen = dtdmtuyenkcbTen;
		this.dtdmtuyenkcbNgaygiocn = dtdmtuyenkcbNgaygiocn;
		this.dtdmtuyenkcbChon = dtdmtuyenkcbChon;
		this.dtDmKcbBhyts = dtDmKcbBhyts;
		this.dtDmKcbBhyts_1 = dtDmKcbBhyts_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_TUYEN_KCB")
	@SequenceGenerator(name = "DT_DM_TUYEN_KCB", sequenceName = "DT_DM_TUYEN_KCB_DTDMTUYENKCB_M", allocationSize = 1)
	@Column(name = "DTDMTUYENKCB_MASO", unique = true, nullable = false)
	public Integer getDtdmtuyenkcbMaso() {
		return this.dtdmtuyenkcbMaso;
	}

	public void setDtdmtuyenkcbMaso(Integer dtdmtuyenkcbMaso) {
		this.dtdmtuyenkcbMaso = dtdmtuyenkcbMaso;
	}

	@Column(name = "DTDMTUYENKCB_MA", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getDtdmtuyenkcbMa() {
		return this.dtdmtuyenkcbMa;
	}

	public void setDtdmtuyenkcbMa(String dtdmtuyenkcbMa) {
		this.dtdmtuyenkcbMa = dtdmtuyenkcbMa;
	}

	@Column(name = "DTDMTUYENKCB_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmtuyenkcbTen() {
		return this.dtdmtuyenkcbTen;
	}

	public void setDtdmtuyenkcbTen(String dtdmtuyenkcbTen) {
		this.dtdmtuyenkcbTen = dtdmtuyenkcbTen;
	}

	@Column(name = "DTDMTUYENKCB_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmtuyenkcbNgaygiocn() {
		return this.dtdmtuyenkcbNgaygiocn;
	}

	public void setDtdmtuyenkcbNgaygiocn(Double dtdmtuyenkcbNgaygiocn) {
		this.dtdmtuyenkcbNgaygiocn = dtdmtuyenkcbNgaygiocn;
	}

	@Column(name = "DTDMTUYENKCB_CHON")
	public Boolean getDtdmtuyenkcbChon() {
		return this.dtdmtuyenkcbChon;
	}

	public void setDtdmtuyenkcbChon(Boolean dtdmtuyenkcbChon) {
		this.dtdmtuyenkcbChon = dtdmtuyenkcbChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmTuyenKcb")
	public Set<DtDmKcbBhyt> getDtDmKcbBhyts() {
		return this.dtDmKcbBhyts;
	}

	public void setDtDmKcbBhyts(Set<DtDmKcbBhyt> dtDmKcbBhyts) {
		this.dtDmKcbBhyts = dtDmKcbBhyts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmTuyenKcb")
	public Set<DtDmKcbBhyt> getDtDmKcbBhyts_1() {
		return this.dtDmKcbBhyts_1;
	}

	public void setDtDmKcbBhyts_1(Set<DtDmKcbBhyt> dtDmKcbBhyts_1) {
		this.dtDmKcbBhyts_1 = dtDmKcbBhyts_1;
	}

}
