package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmMqlBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_MQL_BHYT", catalog = "DB_YTDT_BD")
public class DtDmMqlBhyt implements java.io.Serializable {

	private Integer dtdmmqlbhytMaso;
	private String dtdmmqlbhytMa;
	private String dtdmmqlbhytTen;
	private Short dtdmmqlbhytTylebhyt1;
	private Short dtdmmqlbhytTylebhyt2;
	private Double dtdmmqlbhytGhtyle;
	private Double dtdmmqlbhytTylebhyt1NoiTru;
	private Double dtdmmqlbhytTylebhyt2NoiTru;
	private Double dtdmmqlbhytGhtyleNoiTru;
	private Double dtdmmqlbhytMinktc;
	private Double dtdmmqlbhytMaxktc;
	private Short dtdmmqlbhytTylektc;
	private Double dtdmmqlbhytTlminktc;
	private Double dtdmmqlbhytTlmaxktc;
	private Boolean dtdmmqlbhytVanchuyen;
	private Double dtdmmqlbhytNgaygiocn;
	private Boolean dtdmmqlbhytChon;

	public DtDmMqlBhyt() {
	}

	public DtDmMqlBhyt(String dtdmmqlbhytMa, String dtdmmqlbhytTen) {
		this.dtdmmqlbhytMa = dtdmmqlbhytMa;
		this.dtdmmqlbhytTen = dtdmmqlbhytTen;
	}

	public DtDmMqlBhyt(String dtdmmqlbhytMa, String dtdmmqlbhytTen,
			Short dtdmmqlbhytTylebhyt1, Short dtdmmqlbhytTylebhyt2,
			Double dtdmmqlbhytGhtyle, Double dtdmmqlbhytTylebhyt1NoiTru,
			Double dtdmmqlbhytTylebhyt2NoiTru, Double dtdmmqlbhytGhtyleNoiTru,
			Double dtdmmqlbhytMinktc, Double dtdmmqlbhytMaxktc,
			Short dtdmmqlbhytTylektc, Double dtdmmqlbhytTlminktc,
			Double dtdmmqlbhytTlmaxktc, Boolean dtdmmqlbhytVanchuyen,
			Double dtdmmqlbhytNgaygiocn, Boolean dtdmmqlbhytChon) {
		this.dtdmmqlbhytMa = dtdmmqlbhytMa;
		this.dtdmmqlbhytTen = dtdmmqlbhytTen;
		this.dtdmmqlbhytTylebhyt1 = dtdmmqlbhytTylebhyt1;
		this.dtdmmqlbhytTylebhyt2 = dtdmmqlbhytTylebhyt2;
		this.dtdmmqlbhytGhtyle = dtdmmqlbhytGhtyle;
		this.dtdmmqlbhytTylebhyt1NoiTru = dtdmmqlbhytTylebhyt1NoiTru;
		this.dtdmmqlbhytTylebhyt2NoiTru = dtdmmqlbhytTylebhyt2NoiTru;
		this.dtdmmqlbhytGhtyleNoiTru = dtdmmqlbhytGhtyleNoiTru;
		this.dtdmmqlbhytMinktc = dtdmmqlbhytMinktc;
		this.dtdmmqlbhytMaxktc = dtdmmqlbhytMaxktc;
		this.dtdmmqlbhytTylektc = dtdmmqlbhytTylektc;
		this.dtdmmqlbhytTlminktc = dtdmmqlbhytTlminktc;
		this.dtdmmqlbhytTlmaxktc = dtdmmqlbhytTlmaxktc;
		this.dtdmmqlbhytVanchuyen = dtdmmqlbhytVanchuyen;
		this.dtdmmqlbhytNgaygiocn = dtdmmqlbhytNgaygiocn;
		this.dtdmmqlbhytChon = dtdmmqlbhytChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_MQL_BHYT")
	@SequenceGenerator(name = "DT_DM_MQL_BHYT", sequenceName = "DT_DM_MQL_BHYT_DTDMMQLBHYT_MAS", allocationSize = 1)
	@Column(name = "DTDMMQLBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmmqlbhytMaso() {
		return this.dtdmmqlbhytMaso;
	}

	public void setDtdmmqlbhytMaso(Integer dtdmmqlbhytMaso) {
		this.dtdmmqlbhytMaso = dtdmmqlbhytMaso;
	}

	@Column(name = "DTDMMQLBHYT_MA", nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getDtdmmqlbhytMa() {
		return this.dtdmmqlbhytMa;
	}

	public void setDtdmmqlbhytMa(String dtdmmqlbhytMa) {
		this.dtdmmqlbhytMa = dtdmmqlbhytMa;
	}

	@Column(name = "DTDMMQLBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmmqlbhytTen() {
		return this.dtdmmqlbhytTen;
	}

	public void setDtdmmqlbhytTen(String dtdmmqlbhytTen) {
		this.dtdmmqlbhytTen = dtdmmqlbhytTen;
	}

	@Column(name = "DTDMMQLBHYT_TYLEBHYT1")
	public Short getDtdmmqlbhytTylebhyt1() {
		return this.dtdmmqlbhytTylebhyt1;
	}

	public void setDtdmmqlbhytTylebhyt1(Short dtdmmqlbhytTylebhyt1) {
		this.dtdmmqlbhytTylebhyt1 = dtdmmqlbhytTylebhyt1;
	}

	@Column(name = "DTDMMQLBHYT_TYLEBHYT2")
	public Short getDtdmmqlbhytTylebhyt2() {
		return this.dtdmmqlbhytTylebhyt2;
	}

	public void setDtdmmqlbhytTylebhyt2(Short dtdmmqlbhytTylebhyt2) {
		this.dtdmmqlbhytTylebhyt2 = dtdmmqlbhytTylebhyt2;
	}

	@Column(name = "DTDMMQLBHYT_GHTYLE", precision = 22, scale = 0)
	public Double getDtdmmqlbhytGhtyle() {
		return this.dtdmmqlbhytGhtyle;
	}

	public void setDtdmmqlbhytGhtyle(Double dtdmmqlbhytGhtyle) {
		this.dtdmmqlbhytGhtyle = dtdmmqlbhytGhtyle;
	}

	@Column(name = "DTDMMQLBHYT_TYLEBHYT1_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmmqlbhytTylebhyt1NoiTru() {
		return this.dtdmmqlbhytTylebhyt1NoiTru;
	}

	public void setDtdmmqlbhytTylebhyt1NoiTru(Double dtdmmqlbhytTylebhyt1NoiTru) {
		this.dtdmmqlbhytTylebhyt1NoiTru = dtdmmqlbhytTylebhyt1NoiTru;
	}

	@Column(name = "DTDMMQLBHYT_TYLEBHYT2_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmmqlbhytTylebhyt2NoiTru() {
		return this.dtdmmqlbhytTylebhyt2NoiTru;
	}

	public void setDtdmmqlbhytTylebhyt2NoiTru(Double dtdmmqlbhytTylebhyt2NoiTru) {
		this.dtdmmqlbhytTylebhyt2NoiTru = dtdmmqlbhytTylebhyt2NoiTru;
	}

	@Column(name = "DTDMMQLBHYT_GHTYLE_NOI_TRU", precision = 22, scale = 0)
	public Double getDtdmmqlbhytGhtyleNoiTru() {
		return this.dtdmmqlbhytGhtyleNoiTru;
	}

	public void setDtdmmqlbhytGhtyleNoiTru(Double dtdmmqlbhytGhtyleNoiTru) {
		this.dtdmmqlbhytGhtyleNoiTru = dtdmmqlbhytGhtyleNoiTru;
	}

	@Column(name = "DTDMMQLBHYT_MINKTC", precision = 22, scale = 0)
	public Double getDtdmmqlbhytMinktc() {
		return this.dtdmmqlbhytMinktc;
	}

	public void setDtdmmqlbhytMinktc(Double dtdmmqlbhytMinktc) {
		this.dtdmmqlbhytMinktc = dtdmmqlbhytMinktc;
	}

	@Column(name = "DTDMMQLBHYT_MAXKTC", precision = 22, scale = 0)
	public Double getDtdmmqlbhytMaxktc() {
		return this.dtdmmqlbhytMaxktc;
	}

	public void setDtdmmqlbhytMaxktc(Double dtdmmqlbhytMaxktc) {
		this.dtdmmqlbhytMaxktc = dtdmmqlbhytMaxktc;
	}

	@Column(name = "DTDMMQLBHYT_TYLEKTC")
	public Short getDtdmmqlbhytTylektc() {
		return this.dtdmmqlbhytTylektc;
	}

	public void setDtdmmqlbhytTylektc(Short dtdmmqlbhytTylektc) {
		this.dtdmmqlbhytTylektc = dtdmmqlbhytTylektc;
	}

	@Column(name = "DTDMMQLBHYT_TLMINKTC", precision = 22, scale = 0)
	public Double getDtdmmqlbhytTlminktc() {
		return this.dtdmmqlbhytTlminktc;
	}

	public void setDtdmmqlbhytTlminktc(Double dtdmmqlbhytTlminktc) {
		this.dtdmmqlbhytTlminktc = dtdmmqlbhytTlminktc;
	}

	@Column(name = "DTDMMQLBHYT_TLMAXKTC", precision = 22, scale = 0)
	public Double getDtdmmqlbhytTlmaxktc() {
		return this.dtdmmqlbhytTlmaxktc;
	}

	public void setDtdmmqlbhytTlmaxktc(Double dtdmmqlbhytTlmaxktc) {
		this.dtdmmqlbhytTlmaxktc = dtdmmqlbhytTlmaxktc;
	}

	@Column(name = "DTDMMQLBHYT_VANCHUYEN")
	public Boolean getDtdmmqlbhytVanchuyen() {
		return this.dtdmmqlbhytVanchuyen;
	}

	public void setDtdmmqlbhytVanchuyen(Boolean dtdmmqlbhytVanchuyen) {
		this.dtdmmqlbhytVanchuyen = dtdmmqlbhytVanchuyen;
	}

	@Column(name = "DTDMMQLBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmmqlbhytNgaygiocn() {
		return this.dtdmmqlbhytNgaygiocn;
	}

	public void setDtdmmqlbhytNgaygiocn(Double dtdmmqlbhytNgaygiocn) {
		this.dtdmmqlbhytNgaygiocn = dtdmmqlbhytNgaygiocn;
	}

	@Column(name = "DTDMMQLBHYT_CHON")
	public Boolean getDtdmmqlbhytChon() {
		return this.dtdmmqlbhytChon;
	}

	public void setDtdmmqlbhytChon(Boolean dtdmmqlbhytChon) {
		this.dtdmmqlbhytChon = dtdmmqlbhytChon;
	}

}
