package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmLoaiPhauThuat generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_LOAI_PHAU_THUAT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMLOAIPT_MA"))
public class DtDmLoaiPhauThuat implements java.io.Serializable {

	private Integer dtdmloaiptMaso;
	private String dtdmloaiptMa;
	private String dtdmloaiptTen;
	private Boolean dtdmloaiptPhauthuat;
	private Short dtdmloaiptMabytp;
	private Boolean dtdmloaiptThuthuat;
	private Short dtdmloaiptMabytt;
	private Double dtdmloaiptNgaygiocn;
	private Boolean dtdmloaiptChon;
	private Set<DtDmPhauThuat> dtDmPhauThuats = new HashSet<DtDmPhauThuat>(0);
	private Set<DtDmPhauThuat> dtDmPhauThuats_1 = new HashSet<DtDmPhauThuat>(0);
	private Set<DtDmClsBangGia> dtDmClsBangGias = new HashSet<DtDmClsBangGia>(0);

	public DtDmLoaiPhauThuat() {
	}

	public DtDmLoaiPhauThuat(String dtdmloaiptMa, String dtdmloaiptTen) {
		this.dtdmloaiptMa = dtdmloaiptMa;
		this.dtdmloaiptTen = dtdmloaiptTen;
	}

	public DtDmLoaiPhauThuat(String dtdmloaiptMa, String dtdmloaiptTen,
			Boolean dtdmloaiptPhauthuat, Short dtdmloaiptMabytp,
			Boolean dtdmloaiptThuthuat, Short dtdmloaiptMabytt,
			Double dtdmloaiptNgaygiocn, Boolean dtdmloaiptChon,
			Set<DtDmPhauThuat> dtDmPhauThuats,
			Set<DtDmPhauThuat> dtDmPhauThuats_1,
			Set<DtDmClsBangGia> dtDmClsBangGias) {
		this.dtdmloaiptMa = dtdmloaiptMa;
		this.dtdmloaiptTen = dtdmloaiptTen;
		this.dtdmloaiptPhauthuat = dtdmloaiptPhauthuat;
		this.dtdmloaiptMabytp = dtdmloaiptMabytp;
		this.dtdmloaiptThuthuat = dtdmloaiptThuthuat;
		this.dtdmloaiptMabytt = dtdmloaiptMabytt;
		this.dtdmloaiptNgaygiocn = dtdmloaiptNgaygiocn;
		this.dtdmloaiptChon = dtdmloaiptChon;
		this.dtDmPhauThuats = dtDmPhauThuats;
		this.dtDmPhauThuats_1 = dtDmPhauThuats_1;
		this.dtDmClsBangGias = dtDmClsBangGias;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_LOAI_PHAU_THUAT")
	@SequenceGenerator(name = "DT_DM_LOAI_PHAU_THUAT", sequenceName = "DT_DM_LOAI_PHAU_THUAT_DTDMLOAI", allocationSize = 1)
	@Column(name = "DTDMLOAIPT_MASO", unique = true, nullable = false)
	public Integer getDtdmloaiptMaso() {
		return this.dtdmloaiptMaso;
	}

	public void setDtdmloaiptMaso(Integer dtdmloaiptMaso) {
		this.dtdmloaiptMaso = dtdmloaiptMaso;
	}

	@Column(name = "DTDMLOAIPT_MA", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDtdmloaiptMa() {
		return this.dtdmloaiptMa;
	}

	public void setDtdmloaiptMa(String dtdmloaiptMa) {
		this.dtdmloaiptMa = dtdmloaiptMa;
	}

	@Column(name = "DTDMLOAIPT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmloaiptTen() {
		return this.dtdmloaiptTen;
	}

	public void setDtdmloaiptTen(String dtdmloaiptTen) {
		this.dtdmloaiptTen = dtdmloaiptTen;
	}

	@Column(name = "DTDMLOAIPT_PHAUTHUAT")
	public Boolean getDtdmloaiptPhauthuat() {
		return this.dtdmloaiptPhauthuat;
	}

	public void setDtdmloaiptPhauthuat(Boolean dtdmloaiptPhauthuat) {
		this.dtdmloaiptPhauthuat = dtdmloaiptPhauthuat;
	}

	@Column(name = "DTDMLOAIPT_MABYTP")
	public Short getDtdmloaiptMabytp() {
		return this.dtdmloaiptMabytp;
	}

	public void setDtdmloaiptMabytp(Short dtdmloaiptMabytp) {
		this.dtdmloaiptMabytp = dtdmloaiptMabytp;
	}

	@Column(name = "DTDMLOAIPT_THUTHUAT")
	public Boolean getDtdmloaiptThuthuat() {
		return this.dtdmloaiptThuthuat;
	}

	public void setDtdmloaiptThuthuat(Boolean dtdmloaiptThuthuat) {
		this.dtdmloaiptThuthuat = dtdmloaiptThuthuat;
	}

	@Column(name = "DTDMLOAIPT_MABYTT")
	public Short getDtdmloaiptMabytt() {
		return this.dtdmloaiptMabytt;
	}

	public void setDtdmloaiptMabytt(Short dtdmloaiptMabytt) {
		this.dtdmloaiptMabytt = dtdmloaiptMabytt;
	}

	@Column(name = "DTDMLOAIPT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmloaiptNgaygiocn() {
		return this.dtdmloaiptNgaygiocn;
	}

	public void setDtdmloaiptNgaygiocn(Double dtdmloaiptNgaygiocn) {
		this.dtdmloaiptNgaygiocn = dtdmloaiptNgaygiocn;
	}

	@Column(name = "DTDMLOAIPT_CHON")
	public Boolean getDtdmloaiptChon() {
		return this.dtdmloaiptChon;
	}

	public void setDtdmloaiptChon(Boolean dtdmloaiptChon) {
		this.dtdmloaiptChon = dtdmloaiptChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLoaiPhauThuat")
	public Set<DtDmPhauThuat> getDtDmPhauThuats() {
		return this.dtDmPhauThuats;
	}

	public void setDtDmPhauThuats(Set<DtDmPhauThuat> dtDmPhauThuats) {
		this.dtDmPhauThuats = dtDmPhauThuats;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLoaiPhauThuat")
	public Set<DtDmPhauThuat> getDtDmPhauThuats_1() {
		return this.dtDmPhauThuats_1;
	}

	public void setDtDmPhauThuats_1(Set<DtDmPhauThuat> dtDmPhauThuats_1) {
		this.dtDmPhauThuats_1 = dtDmPhauThuats_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmLoaiPhauThuat")
	public Set<DtDmClsBangGia> getDtDmClsBangGias() {
		return this.dtDmClsBangGias;
	}

	public void setDtDmClsBangGias(Set<DtDmClsBangGia> dtDmClsBangGias) {
		this.dtDmClsBangGias = dtDmClsBangGias;
	}

}
