package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmTramYTeBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_TRAM_Y_TE_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMTRAMYTEBHYT_MA"))
public class DtDmTramYTeBhyt implements java.io.Serializable {

	private Integer dtdmtramytebhytMaso;
	private String dtdmtramytebhytMa;
	private String dtdmtramytebhytTen;
	private Double dtdmtramytebhytNgaygiocn;
	private Boolean dtdmtramytebhytChon;
	private Boolean dtdmtramytebhytDefa;

	public DtDmTramYTeBhyt() {
	}

	public DtDmTramYTeBhyt(String dtdmtramytebhytMa, String dtdmtramytebhytTen) {
		this.dtdmtramytebhytMa = dtdmtramytebhytMa;
		this.dtdmtramytebhytTen = dtdmtramytebhytTen;
	}

	public DtDmTramYTeBhyt(String dtdmtramytebhytMa, String dtdmtramytebhytTen,
			Double dtdmtramytebhytNgaygiocn, Boolean dtdmtramytebhytChon,
			Boolean dtdmtramytebhytDefa) {
		this.dtdmtramytebhytMa = dtdmtramytebhytMa;
		this.dtdmtramytebhytTen = dtdmtramytebhytTen;
		this.dtdmtramytebhytNgaygiocn = dtdmtramytebhytNgaygiocn;
		this.dtdmtramytebhytChon = dtdmtramytebhytChon;
		this.dtdmtramytebhytDefa = dtdmtramytebhytDefa;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_TRAM_Y_TE_BHYT")
	@SequenceGenerator(name = "DT_DM_TRAM_Y_TE_BHYT", sequenceName = "DT_DM_TRAM_Y_TE_BHYT_DTDMTRAMY", allocationSize = 1)
	@Column(name = "DTDMTRAMYTEBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmtramytebhytMaso() {
		return this.dtdmtramytebhytMaso;
	}

	public void setDtdmtramytebhytMaso(Integer dtdmtramytebhytMaso) {
		this.dtdmtramytebhytMaso = dtdmtramytebhytMaso;
	}

	@Column(name = "DTDMTRAMYTEBHYT_MA", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getDtdmtramytebhytMa() {
		return this.dtdmtramytebhytMa;
	}

	public void setDtdmtramytebhytMa(String dtdmtramytebhytMa) {
		this.dtdmtramytebhytMa = dtdmtramytebhytMa;
	}

	@Column(name = "DTDMTRAMYTEBHYT_TEN", nullable = false, length = 512)
	@NotNull
	@Length(max = 512)
	public String getDtdmtramytebhytTen() {
		return this.dtdmtramytebhytTen;
	}

	public void setDtdmtramytebhytTen(String dtdmtramytebhytTen) {
		this.dtdmtramytebhytTen = dtdmtramytebhytTen;
	}

	@Column(name = "DTDMTRAMYTEBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmtramytebhytNgaygiocn() {
		return this.dtdmtramytebhytNgaygiocn;
	}

	public void setDtdmtramytebhytNgaygiocn(Double dtdmtramytebhytNgaygiocn) {
		this.dtdmtramytebhytNgaygiocn = dtdmtramytebhytNgaygiocn;
	}

	@Column(name = "DTDMTRAMYTEBHYT_CHON")
	public Boolean getDtdmtramytebhytChon() {
		return this.dtdmtramytebhytChon;
	}

	public void setDtdmtramytebhytChon(Boolean dtdmtramytebhytChon) {
		this.dtdmtramytebhytChon = dtdmtramytebhytChon;
	}

	@Column(name = "DTDMTRAMYTEBHYT_DEFA")
	public Boolean getDtdmtramytebhytDefa() {
		return this.dtdmtramytebhytDefa;
	}

	public void setDtdmtramytebhytDefa(Boolean dtdmtramytebhytDefa) {
		this.dtdmtramytebhytDefa = dtdmtramytebhytDefa;
	}

}
