package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmNhaSxSpdd generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NHA_SX_SPDD", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMNSX_MA"))
public class DtDmNhaSxSpdd implements java.io.Serializable {

	private Integer dtdmnsxMaso;
	private String dtdmnsxMa;
	private String dtdmnsxTen;
	private Double dtdmnsxNgaygiocn;
	private Boolean dtdmnsxChon;

	public DtDmNhaSxSpdd() {
	}

	public DtDmNhaSxSpdd(String dtdmnsxMa) {
		this.dtdmnsxMa = dtdmnsxMa;
	}

	public DtDmNhaSxSpdd(String dtdmnsxMa, String dtdmnsxTen,
			Double dtdmnsxNgaygiocn, Boolean dtdmnsxChon) {
		this.dtdmnsxMa = dtdmnsxMa;
		this.dtdmnsxTen = dtdmnsxTen;
		this.dtdmnsxNgaygiocn = dtdmnsxNgaygiocn;
		this.dtdmnsxChon = dtdmnsxChon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NHA_SX_SPDD")
	@SequenceGenerator(name = "DT_DM_NHA_SX_SPDD", sequenceName = "DT_DM_NHA_SX_SPDD_DTDMNSX_MASO", allocationSize = 1)
	@Column(name = "DTDMNSX_MASO", unique = true, nullable = false)
	public Integer getDtdmnsxMaso() {
		return this.dtdmnsxMaso;
	}

	public void setDtdmnsxMaso(Integer dtdmnsxMaso) {
		this.dtdmnsxMaso = dtdmnsxMaso;
	}

	@Column(name = "DTDMNSX_MA", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDtdmnsxMa() {
		return this.dtdmnsxMa;
	}

	public void setDtdmnsxMa(String dtdmnsxMa) {
		this.dtdmnsxMa = dtdmnsxMa;
	}

	@Column(name = "DTDMNSX_TEN", length = 100)
	@Length(max = 100)
	public String getDtdmnsxTen() {
		return this.dtdmnsxTen;
	}

	public void setDtdmnsxTen(String dtdmnsxTen) {
		this.dtdmnsxTen = dtdmnsxTen;
	}

	@Column(name = "DTDMNSX_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnsxNgaygiocn() {
		return this.dtdmnsxNgaygiocn;
	}

	public void setDtdmnsxNgaygiocn(Double dtdmnsxNgaygiocn) {
		this.dtdmnsxNgaygiocn = dtdmnsxNgaygiocn;
	}

	@Column(name = "DTDMNSX_CHON")
	public Boolean getDtdmnsxChon() {
		return this.dtdmnsxChon;
	}

	public void setDtdmnsxChon(Boolean dtdmnsxChon) {
		this.dtdmnsxChon = dtdmnsxChon;
	}

}
