package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmNhomBhyt2 generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_NHOM_BHYT2", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMNHOMBHYT2_MA"))
public class DtDmNhomBhyt2 implements java.io.Serializable {

	private Integer dtdmnhombhyt2Maso;
	private String dtdmnhombhyt2Ma;
	private String dtdmnhombhyt2Ten;
	private Double dtdmnhombhyt2Ngaygiocn;
	private Boolean dtdmnhombhyt2Chon;
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts = new HashSet<DtDmKhoiBhyt>(0);

	public DtDmNhomBhyt2() {
	}

	public DtDmNhomBhyt2(String dtdmnhombhyt2Ma, String dtdmnhombhyt2Ten) {
		this.dtdmnhombhyt2Ma = dtdmnhombhyt2Ma;
		this.dtdmnhombhyt2Ten = dtdmnhombhyt2Ten;
	}

	public DtDmNhomBhyt2(String dtdmnhombhyt2Ma, String dtdmnhombhyt2Ten,
			Double dtdmnhombhyt2Ngaygiocn, Boolean dtdmnhombhyt2Chon,
			Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtdmnhombhyt2Ma = dtdmnhombhyt2Ma;
		this.dtdmnhombhyt2Ten = dtdmnhombhyt2Ten;
		this.dtdmnhombhyt2Ngaygiocn = dtdmnhombhyt2Ngaygiocn;
		this.dtdmnhombhyt2Chon = dtdmnhombhyt2Chon;
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_NHOM_BHYT2")
	@SequenceGenerator(name = "DT_DM_NHOM_BHYT2", sequenceName = "DT_DM_NHOM_BHYT2_DTDMNHOMBHYT2", allocationSize = 1)
	@Column(name = "DTDMNHOMBHYT2_MASO", unique = true, nullable = false)
	public Integer getDtdmnhombhyt2Maso() {
		return this.dtdmnhombhyt2Maso;
	}

	public void setDtdmnhombhyt2Maso(Integer dtdmnhombhyt2Maso) {
		this.dtdmnhombhyt2Maso = dtdmnhombhyt2Maso;
	}

	@Column(name = "DTDMNHOMBHYT2_MA", unique = true, nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getDtdmnhombhyt2Ma() {
		return this.dtdmnhombhyt2Ma;
	}

	public void setDtdmnhombhyt2Ma(String dtdmnhombhyt2Ma) {
		this.dtdmnhombhyt2Ma = dtdmnhombhyt2Ma;
	}

	@Column(name = "DTDMNHOMBHYT2_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmnhombhyt2Ten() {
		return this.dtdmnhombhyt2Ten;
	}

	public void setDtdmnhombhyt2Ten(String dtdmnhombhyt2Ten) {
		this.dtdmnhombhyt2Ten = dtdmnhombhyt2Ten;
	}

	@Column(name = "DTDMNHOMBHYT2_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnhombhyt2Ngaygiocn() {
		return this.dtdmnhombhyt2Ngaygiocn;
	}

	public void setDtdmnhombhyt2Ngaygiocn(Double dtdmnhombhyt2Ngaygiocn) {
		this.dtdmnhombhyt2Ngaygiocn = dtdmnhombhyt2Ngaygiocn;
	}

	@Column(name = "DTDMNHOMBHYT2_CHON")
	public Boolean getDtdmnhombhyt2Chon() {
		return this.dtdmnhombhyt2Chon;
	}

	public void setDtdmnhombhyt2Chon(Boolean dtdmnhombhyt2Chon) {
		this.dtdmnhombhyt2Chon = dtdmnhombhyt2Chon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmNhomBhyt2")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts() {
		return this.dtDmKhoiBhyts;
	}

	public void setDtDmKhoiBhyts(Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

}
