package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmPlBhyt generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_PL_BHYT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMPHLOAIBHYT_MA"))
public class DtDmPlBhyt implements java.io.Serializable {

	private Integer dtdmphloaibhytMaso;
	private String dtdmphloaibhytMa;
	private String dtdmphloaibhytTen;
	private String dtdmphloaibhytGhichu;
	private Double dtdmphloaibhytNgaygiocn;
	private Boolean dtdmphloaibhytChon;
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts = new HashSet<DtDmKhoiBhyt>(0);
	private Set<DtDmNhomBhyt> dtDmNhomBhyts = new HashSet<DtDmNhomBhyt>(0);
	private Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1 = new HashSet<DtDmKhoiBhyt>(0);

	public DtDmPlBhyt() {
	}

	public DtDmPlBhyt(String dtdmphloaibhytMa, String dtdmphloaibhytTen) {
		this.dtdmphloaibhytMa = dtdmphloaibhytMa;
		this.dtdmphloaibhytTen = dtdmphloaibhytTen;
	}

	public DtDmPlBhyt(String dtdmphloaibhytMa, String dtdmphloaibhytTen,
			String dtdmphloaibhytGhichu, Double dtdmphloaibhytNgaygiocn,
			Boolean dtdmphloaibhytChon, Set<DtDmKhoiBhyt> dtDmKhoiBhyts,
			Set<DtDmNhomBhyt> dtDmNhomBhyts, Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1) {
		this.dtdmphloaibhytMa = dtdmphloaibhytMa;
		this.dtdmphloaibhytTen = dtdmphloaibhytTen;
		this.dtdmphloaibhytGhichu = dtdmphloaibhytGhichu;
		this.dtdmphloaibhytNgaygiocn = dtdmphloaibhytNgaygiocn;
		this.dtdmphloaibhytChon = dtdmphloaibhytChon;
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
		this.dtDmNhomBhyts = dtDmNhomBhyts;
		this.dtDmKhoiBhyts_1 = dtDmKhoiBhyts_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_PL_BHYT")
	@SequenceGenerator(name = "DT_DM_PL_BHYT", sequenceName = "DT_DM_PL_BHYT_DTDMPHLOAIBHYT_M", allocationSize = 1)
	@Column(name = "DTDMPHLOAIBHYT_MASO", unique = true, nullable = false)
	public Integer getDtdmphloaibhytMaso() {
		return this.dtdmphloaibhytMaso;
	}

	public void setDtdmphloaibhytMaso(Integer dtdmphloaibhytMaso) {
		this.dtdmphloaibhytMaso = dtdmphloaibhytMaso;
	}

	@Column(name = "DTDMPHLOAIBHYT_MA", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getDtdmphloaibhytMa() {
		return this.dtdmphloaibhytMa;
	}

	public void setDtdmphloaibhytMa(String dtdmphloaibhytMa) {
		this.dtdmphloaibhytMa = dtdmphloaibhytMa;
	}

	@Column(name = "DTDMPHLOAIBHYT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmphloaibhytTen() {
		return this.dtdmphloaibhytTen;
	}

	public void setDtdmphloaibhytTen(String dtdmphloaibhytTen) {
		this.dtdmphloaibhytTen = dtdmphloaibhytTen;
	}

	@Column(name = "DTDMPHLOAIBHYT_GHICHU", length = 250)
	@Length(max = 250)
	public String getDtdmphloaibhytGhichu() {
		return this.dtdmphloaibhytGhichu;
	}

	public void setDtdmphloaibhytGhichu(String dtdmphloaibhytGhichu) {
		this.dtdmphloaibhytGhichu = dtdmphloaibhytGhichu;
	}

	@Column(name = "DTDMPHLOAIBHYT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmphloaibhytNgaygiocn() {
		return this.dtdmphloaibhytNgaygiocn;
	}

	public void setDtdmphloaibhytNgaygiocn(Double dtdmphloaibhytNgaygiocn) {
		this.dtdmphloaibhytNgaygiocn = dtdmphloaibhytNgaygiocn;
	}

	@Column(name = "DTDMPHLOAIBHYT_CHON")
	public Boolean getDtdmphloaibhytChon() {
		return this.dtdmphloaibhytChon;
	}

	public void setDtdmphloaibhytChon(Boolean dtdmphloaibhytChon) {
		this.dtdmphloaibhytChon = dtdmphloaibhytChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmPlBhyt")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts() {
		return this.dtDmKhoiBhyts;
	}

	public void setDtDmKhoiBhyts(Set<DtDmKhoiBhyt> dtDmKhoiBhyts) {
		this.dtDmKhoiBhyts = dtDmKhoiBhyts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmPlBhyt")
	public Set<DtDmNhomBhyt> getDtDmNhomBhyts() {
		return this.dtDmNhomBhyts;
	}

	public void setDtDmNhomBhyts(Set<DtDmNhomBhyt> dtDmNhomBhyts) {
		this.dtDmNhomBhyts = dtDmNhomBhyts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmPlBhyt")
	public Set<DtDmKhoiBhyt> getDtDmKhoiBhyts_1() {
		return this.dtDmKhoiBhyts_1;
	}

	public void setDtDmKhoiBhyts_1(Set<DtDmKhoiBhyt> dtDmKhoiBhyts_1) {
		this.dtDmKhoiBhyts_1 = dtDmKhoiBhyts_1;
	}

}
