package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmPhauThuat generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_PHAU_THUAT", catalog = "DB_YTDT_BD")
public class DtDmPhauThuat implements java.io.Serializable {

	private Integer dtdmphauthuatMaso;
	private DtDmPlPhauThuat dtDmPlPhauThuat;
	private DtDmLoaiPhauThuat dtDmLoaiPhauThuat;
	private String dtdmphauthuatMa;
	private String dtdmphauthuatTen;
	private Integer dtdmphauthuatLoai2;
	private String dtdmphauthuatPhanbiet;
	private Integer dtdmphauthuatPhanloai2;
	private Short dtdmphauthuatGopca;
	private Boolean dtdmphauthuatMo;
	private Boolean dtdmphauthuatChon1;
	private Boolean dtdmphauthuatChon2;
	private String dtdmphauthuatLienhe;
	private String dtdmphauthuatMamo;
	private Short dtdmphauthuatOrder;
	private Double dtdmphauthuatNgaygiocn;
	private Boolean dtdmphauthuatChon;
	private Boolean dtdmphauthuatTtPt;

	public DtDmPhauThuat() {
	}

	public DtDmPhauThuat(String dtdmphauthuatMa, String dtdmphauthuatTen) {
		this.dtdmphauthuatMa = dtdmphauthuatMa;
		this.dtdmphauthuatTen = dtdmphauthuatTen;
	}

	public DtDmPhauThuat(DtDmPlPhauThuat dtDmPlPhauThuat,
			DtDmLoaiPhauThuat dtDmLoaiPhauThuat, String dtdmphauthuatMa,
			String dtdmphauthuatTen, Integer dtdmphauthuatLoai2,
			String dtdmphauthuatPhanbiet, Integer dtdmphauthuatPhanloai2,
			Short dtdmphauthuatGopca, Boolean dtdmphauthuatMo,
			Boolean dtdmphauthuatChon1, Boolean dtdmphauthuatChon2,
			String dtdmphauthuatLienhe, String dtdmphauthuatMamo,
			Short dtdmphauthuatOrder, Double dtdmphauthuatNgaygiocn,
			Boolean dtdmphauthuatChon, Boolean dtdmphauthuatTtPt) {
		this.dtDmPlPhauThuat = dtDmPlPhauThuat;
		this.dtDmLoaiPhauThuat = dtDmLoaiPhauThuat;
		this.dtdmphauthuatMa = dtdmphauthuatMa;
		this.dtdmphauthuatTen = dtdmphauthuatTen;
		this.dtdmphauthuatLoai2 = dtdmphauthuatLoai2;
		this.dtdmphauthuatPhanbiet = dtdmphauthuatPhanbiet;
		this.dtdmphauthuatPhanloai2 = dtdmphauthuatPhanloai2;
		this.dtdmphauthuatGopca = dtdmphauthuatGopca;
		this.dtdmphauthuatMo = dtdmphauthuatMo;
		this.dtdmphauthuatChon1 = dtdmphauthuatChon1;
		this.dtdmphauthuatChon2 = dtdmphauthuatChon2;
		this.dtdmphauthuatLienhe = dtdmphauthuatLienhe;
		this.dtdmphauthuatMamo = dtdmphauthuatMamo;
		this.dtdmphauthuatOrder = dtdmphauthuatOrder;
		this.dtdmphauthuatNgaygiocn = dtdmphauthuatNgaygiocn;
		this.dtdmphauthuatChon = dtdmphauthuatChon;
		this.dtdmphauthuatTtPt = dtdmphauthuatTtPt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_PHAU_THUAT")
	@SequenceGenerator(name = "DT_DM_PHAU_THUAT", sequenceName = "DT_DM_PHAU_THUAT_DTDMPHAUTHUAT", allocationSize = 1)
	@Column(name = "DTDMPHAUTHUAT_MASO", unique = true, nullable = false)
	public Integer getDtdmphauthuatMaso() {
		return this.dtdmphauthuatMaso;
	}

	public void setDtdmphauthuatMaso(Integer dtdmphauthuatMaso) {
		this.dtdmphauthuatMaso = dtdmphauthuatMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMPHAUTHUAT_PHANLOAI1")
	public DtDmPlPhauThuat getDtDmPlPhauThuat() {
		return this.dtDmPlPhauThuat;
	}

	public void setDtDmPlPhauThuat(DtDmPlPhauThuat dtDmPlPhauThuat) {
		this.dtDmPlPhauThuat = dtDmPlPhauThuat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMPHAUTHUAT_LOAI1")
	public DtDmLoaiPhauThuat getDtDmLoaiPhauThuat() {
		return this.dtDmLoaiPhauThuat;
	}

	public void setDtDmLoaiPhauThuat(DtDmLoaiPhauThuat dtDmLoaiPhauThuat) {
		this.dtDmLoaiPhauThuat = dtDmLoaiPhauThuat;
	}

	@Column(name = "DTDMPHAUTHUAT_MA", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getDtdmphauthuatMa() {
		return this.dtdmphauthuatMa;
	}

	public void setDtdmphauthuatMa(String dtdmphauthuatMa) {
		this.dtdmphauthuatMa = dtdmphauthuatMa;
	}

	@Column(name = "DTDMPHAUTHUAT_TEN", nullable = false, length = 1024)
	@NotNull
	@Length(max = 1024)
	public String getDtdmphauthuatTen() {
		return this.dtdmphauthuatTen;
	}

	public void setDtdmphauthuatTen(String dtdmphauthuatTen) {
		this.dtdmphauthuatTen = dtdmphauthuatTen;
	}

	@Column(name = "DTDMPHAUTHUAT_LOAI2")
	public Integer getDtdmphauthuatLoai2() {
		return this.dtdmphauthuatLoai2;
	}

	public void setDtdmphauthuatLoai2(Integer dtdmphauthuatLoai2) {
		this.dtdmphauthuatLoai2 = dtdmphauthuatLoai2;
	}

	@Column(name = "DTDMPHAUTHUAT_PHANBIET", length = 5)
	@Length(max = 5)
	public String getDtdmphauthuatPhanbiet() {
		return this.dtdmphauthuatPhanbiet;
	}

	public void setDtdmphauthuatPhanbiet(String dtdmphauthuatPhanbiet) {
		this.dtdmphauthuatPhanbiet = dtdmphauthuatPhanbiet;
	}

	@Column(name = "DTDMPHAUTHUAT_PHANLOAI2")
	public Integer getDtdmphauthuatPhanloai2() {
		return this.dtdmphauthuatPhanloai2;
	}

	public void setDtdmphauthuatPhanloai2(Integer dtdmphauthuatPhanloai2) {
		this.dtdmphauthuatPhanloai2 = dtdmphauthuatPhanloai2;
	}

	@Column(name = "DTDMPHAUTHUAT_GOPCA")
	public Short getDtdmphauthuatGopca() {
		return this.dtdmphauthuatGopca;
	}

	public void setDtdmphauthuatGopca(Short dtdmphauthuatGopca) {
		this.dtdmphauthuatGopca = dtdmphauthuatGopca;
	}

	@Column(name = "DTDMPHAUTHUAT_MO")
	public Boolean getDtdmphauthuatMo() {
		return this.dtdmphauthuatMo;
	}

	public void setDtdmphauthuatMo(Boolean dtdmphauthuatMo) {
		this.dtdmphauthuatMo = dtdmphauthuatMo;
	}

	@Column(name = "DTDMPHAUTHUAT_CHON1")
	public Boolean getDtdmphauthuatChon1() {
		return this.dtdmphauthuatChon1;
	}

	public void setDtdmphauthuatChon1(Boolean dtdmphauthuatChon1) {
		this.dtdmphauthuatChon1 = dtdmphauthuatChon1;
	}

	@Column(name = "DTDMPHAUTHUAT_CHON2")
	public Boolean getDtdmphauthuatChon2() {
		return this.dtdmphauthuatChon2;
	}

	public void setDtdmphauthuatChon2(Boolean dtdmphauthuatChon2) {
		this.dtdmphauthuatChon2 = dtdmphauthuatChon2;
	}

	@Column(name = "DTDMPHAUTHUAT_LIENHE", length = 50)
	@Length(max = 50)
	public String getDtdmphauthuatLienhe() {
		return this.dtdmphauthuatLienhe;
	}

	public void setDtdmphauthuatLienhe(String dtdmphauthuatLienhe) {
		this.dtdmphauthuatLienhe = dtdmphauthuatLienhe;
	}

	@Column(name = "DTDMPHAUTHUAT_MAMO", length = 4)
	@Length(max = 4)
	public String getDtdmphauthuatMamo() {
		return this.dtdmphauthuatMamo;
	}

	public void setDtdmphauthuatMamo(String dtdmphauthuatMamo) {
		this.dtdmphauthuatMamo = dtdmphauthuatMamo;
	}

	@Column(name = "DTDMPHAUTHUAT_ORDER")
	public Short getDtdmphauthuatOrder() {
		return this.dtdmphauthuatOrder;
	}

	public void setDtdmphauthuatOrder(Short dtdmphauthuatOrder) {
		this.dtdmphauthuatOrder = dtdmphauthuatOrder;
	}

	@Column(name = "DTDMPHAUTHUAT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmphauthuatNgaygiocn() {
		return this.dtdmphauthuatNgaygiocn;
	}

	public void setDtdmphauthuatNgaygiocn(Double dtdmphauthuatNgaygiocn) {
		this.dtdmphauthuatNgaygiocn = dtdmphauthuatNgaygiocn;
	}

	@Column(name = "DTDMPHAUTHUAT_CHON")
	public Boolean getDtdmphauthuatChon() {
		return this.dtdmphauthuatChon;
	}

	public void setDtdmphauthuatChon(Boolean dtdmphauthuatChon) {
		this.dtdmphauthuatChon = dtdmphauthuatChon;
	}

	@Column(name = "DTDMPHAUTHUAT_TT_PT")
	public Boolean getDtdmphauthuatTtPt() {
		return this.dtdmphauthuatTtPt;
	}

	public void setDtdmphauthuatTtPt(Boolean dtdmphauthuatTtPt) {
		this.dtdmphauthuatTtPt = dtdmphauthuatTtPt;
	}

}
