package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * DtDmBacSiBanKham generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_BAC_SI_BAN_KHAM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DTDMBANKHAM_MASO", "DTDMNHANVIEN_MASO" }))
public class DtDmBacSiBanKham implements java.io.Serializable {

	private Integer dtdmbacsibankhamMaso;
	private DtDmNhanVien dtDmNhanVien;
	private DtDmBanKham dtDmBanKham;
	private Boolean dtdmnhanvienChon;
	private Double dtdmnhanvienNgaygiocn;

	public DtDmBacSiBanKham() {
	}

	public DtDmBacSiBanKham(DtDmNhanVien dtDmNhanVien, DtDmBanKham dtDmBanKham) {
		this.dtDmNhanVien = dtDmNhanVien;
		this.dtDmBanKham = dtDmBanKham;
	}

	public DtDmBacSiBanKham(DtDmNhanVien dtDmNhanVien, DtDmBanKham dtDmBanKham,
			Boolean dtdmnhanvienChon, Double dtdmnhanvienNgaygiocn) {
		this.dtDmNhanVien = dtDmNhanVien;
		this.dtDmBanKham = dtDmBanKham;
		this.dtdmnhanvienChon = dtdmnhanvienChon;
		this.dtdmnhanvienNgaygiocn = dtdmnhanvienNgaygiocn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_BAC_SI_BAN_KHAM")
	@SequenceGenerator(name = "DT_DM_BAC_SI_BAN_KHAM", sequenceName = "DT_DM_BAC_SI_BAN_KHAM_DTDMBACS", allocationSize = 1)
	@Column(name = "DTDMBACSIBANKHAM_MASO", unique = true, nullable = false)
	public Integer getDtdmbacsibankhamMaso() {
		return this.dtdmbacsibankhamMaso;
	}

	public void setDtdmbacsibankhamMaso(Integer dtdmbacsibankhamMaso) {
		this.dtdmbacsibankhamMaso = dtdmbacsibankhamMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHANVIEN_MASO", nullable = false)
	@NotNull
	public DtDmNhanVien getDtDmNhanVien() {
		return this.dtDmNhanVien;
	}

	public void setDtDmNhanVien(DtDmNhanVien dtDmNhanVien) {
		this.dtDmNhanVien = dtDmNhanVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMBANKHAM_MASO", nullable = false)
	@NotNull
	public DtDmBanKham getDtDmBanKham() {
		return this.dtDmBanKham;
	}

	public void setDtDmBanKham(DtDmBanKham dtDmBanKham) {
		this.dtDmBanKham = dtDmBanKham;
	}

	@Column(name = "DTDMNHANVIEN_CHON")
	public Boolean getDtdmnhanvienChon() {
		return this.dtdmnhanvienChon;
	}

	public void setDtdmnhanvienChon(Boolean dtdmnhanvienChon) {
		this.dtdmnhanvienChon = dtdmnhanvienChon;
	}

	@Column(name = "DTDMNHANVIEN_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmnhanvienNgaygiocn() {
		return this.dtdmnhanvienNgaygiocn;
	}

	public void setDtdmnhanvienNgaygiocn(Double dtdmnhanvienNgaygiocn) {
		this.dtdmnhanvienNgaygiocn = dtdmnhanvienNgaygiocn;
	}

}
