package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmBanKham generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_BAN_KHAM", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMBANKHAM_MA"))
public class DtDmBanKham implements java.io.Serializable {

	private Integer dtdmbankhamMaso;
	private DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi2;
	private DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi3;
	private DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi1;
	private DmKhoa dmKhoa;
	private String dtdmbankhamMa;
	private String dtdmbankhamMa0;
	private String dtdmbankhamMa2;
	private String dtdmbankhamTen;
	private String dtdmbankhamKyhieu;
	private Integer dtdmbankhamThoigian;
	private String dtdmbankhamTinhchat;
	private String dtdmnhanvienTenbc;
	private Double dtdmbankhamNgaygiocn;
	private Boolean dtdmbankhamChon;
	private String dtdmnhanvienNhom;
	private Integer dmloaikhoaMaso;
	private Set<DtDmBacSiBanKham> dtDmBacSiBanKhams = new HashSet<DtDmBacSiBanKham>(
			0);
	private Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1 = new HashSet<DtDmBacSiBanKham>(
			0);

	public DtDmBanKham() {
	}

	public DtDmBanKham(String dtdmbankhamMa) {
		this.dtdmbankhamMa = dtdmbankhamMa;
	}

	public DtDmBanKham(DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi2,
			DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi3,
			DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi1, DmKhoa dmKhoa,
			String dtdmbankhamMa, String dtdmbankhamMa0, String dtdmbankhamMa2,
			String dtdmbankhamTen, String dtdmbankhamKyhieu,
			Integer dtdmbankhamThoigian, String dtdmbankhamTinhchat,
			String dtdmnhanvienTenbc, Double dtdmbankhamNgaygiocn,
			Boolean dtdmbankhamChon, String dtdmnhanvienNhom,
			Integer dmloaikhoaMaso, Set<DtDmBacSiBanKham> dtDmBacSiBanKhams,
			Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1) {
		this.dtDmNhanVienByDtdmnhanvienBacsi2 = dtDmNhanVienByDtdmnhanvienBacsi2;
		this.dtDmNhanVienByDtdmnhanvienBacsi3 = dtDmNhanVienByDtdmnhanvienBacsi3;
		this.dtDmNhanVienByDtdmnhanvienBacsi1 = dtDmNhanVienByDtdmnhanvienBacsi1;
		this.dmKhoa = dmKhoa;
		this.dtdmbankhamMa = dtdmbankhamMa;
		this.dtdmbankhamMa0 = dtdmbankhamMa0;
		this.dtdmbankhamMa2 = dtdmbankhamMa2;
		this.dtdmbankhamTen = dtdmbankhamTen;
		this.dtdmbankhamKyhieu = dtdmbankhamKyhieu;
		this.dtdmbankhamThoigian = dtdmbankhamThoigian;
		this.dtdmbankhamTinhchat = dtdmbankhamTinhchat;
		this.dtdmnhanvienTenbc = dtdmnhanvienTenbc;
		this.dtdmbankhamNgaygiocn = dtdmbankhamNgaygiocn;
		this.dtdmbankhamChon = dtdmbankhamChon;
		this.dtdmnhanvienNhom = dtdmnhanvienNhom;
		this.dmloaikhoaMaso = dmloaikhoaMaso;
		this.dtDmBacSiBanKhams = dtDmBacSiBanKhams;
		this.dtDmBacSiBanKhams_1 = dtDmBacSiBanKhams_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_BAN_KHAM")
	@SequenceGenerator(name = "DT_DM_BAN_KHAM", sequenceName = "DT_DM_BAN_KHAM_DTDMBANKHAM_MAS", allocationSize = 1)
	@Column(name = "DTDMBANKHAM_MASO", unique = true, nullable = false)
	public Integer getDtdmbankhamMaso() {
		return this.dtdmbankhamMaso;
	}

	public void setDtdmbankhamMaso(Integer dtdmbankhamMaso) {
		this.dtdmbankhamMaso = dtdmbankhamMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHANVIEN_BACSI2")
	public DtDmNhanVien getDtDmNhanVienByDtdmnhanvienBacsi2() {
		return this.dtDmNhanVienByDtdmnhanvienBacsi2;
	}

	public void setDtDmNhanVienByDtdmnhanvienBacsi2(
			DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi2) {
		this.dtDmNhanVienByDtdmnhanvienBacsi2 = dtDmNhanVienByDtdmnhanvienBacsi2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHANVIEN_BACSI3")
	public DtDmNhanVien getDtDmNhanVienByDtdmnhanvienBacsi3() {
		return this.dtDmNhanVienByDtdmnhanvienBacsi3;
	}

	public void setDtDmNhanVienByDtdmnhanvienBacsi3(
			DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi3) {
		this.dtDmNhanVienByDtdmnhanvienBacsi3 = dtDmNhanVienByDtdmnhanvienBacsi3;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTDMNHANVIEN_BACSI1")
	public DtDmNhanVien getDtDmNhanVienByDtdmnhanvienBacsi1() {
		return this.dtDmNhanVienByDtdmnhanvienBacsi1;
	}

	public void setDtDmNhanVienByDtdmnhanvienBacsi1(
			DtDmNhanVien dtDmNhanVienByDtdmnhanvienBacsi1) {
		this.dtDmNhanVienByDtdmnhanvienBacsi1 = dtDmNhanVienByDtdmnhanvienBacsi1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMKHOA_MASO")
	public DmKhoa getDmKhoa() {
		return this.dmKhoa;
	}

	public void setDmKhoa(DmKhoa dmKhoa) {
		this.dmKhoa = dmKhoa;
	}

	@Column(name = "DTDMBANKHAM_MA", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getDtdmbankhamMa() {
		return this.dtdmbankhamMa;
	}

	public void setDtdmbankhamMa(String dtdmbankhamMa) {
		this.dtdmbankhamMa = dtdmbankhamMa;
	}

	@Column(name = "DTDMBANKHAM_MA0", length = 5)
	@Length(max = 5)
	public String getDtdmbankhamMa0() {
		return this.dtdmbankhamMa0;
	}

	public void setDtdmbankhamMa0(String dtdmbankhamMa0) {
		this.dtdmbankhamMa0 = dtdmbankhamMa0;
	}

	@Column(name = "DTDMBANKHAM_MA2", length = 5)
	@Length(max = 5)
	public String getDtdmbankhamMa2() {
		return this.dtdmbankhamMa2;
	}

	public void setDtdmbankhamMa2(String dtdmbankhamMa2) {
		this.dtdmbankhamMa2 = dtdmbankhamMa2;
	}

	@Column(name = "DTDMBANKHAM_TEN", length = 250)
	@Length(max = 250)
	public String getDtdmbankhamTen() {
		return this.dtdmbankhamTen;
	}

	public void setDtdmbankhamTen(String dtdmbankhamTen) {
		this.dtdmbankhamTen = dtdmbankhamTen;
	}

	@Column(name = "DTDMBANKHAM_KYHIEU", length = 5)
	@Length(max = 5)
	public String getDtdmbankhamKyhieu() {
		return this.dtdmbankhamKyhieu;
	}

	public void setDtdmbankhamKyhieu(String dtdmbankhamKyhieu) {
		this.dtdmbankhamKyhieu = dtdmbankhamKyhieu;
	}

	@Column(name = "DTDMBANKHAM_THOIGIAN")
	public Integer getDtdmbankhamThoigian() {
		return this.dtdmbankhamThoigian;
	}

	public void setDtdmbankhamThoigian(Integer dtdmbankhamThoigian) {
		this.dtdmbankhamThoigian = dtdmbankhamThoigian;
	}

	@Column(name = "DTDMBANKHAM_TINHCHAT", length = 5)
	@Length(max = 5)
	public String getDtdmbankhamTinhchat() {
		return this.dtdmbankhamTinhchat;
	}

	public void setDtdmbankhamTinhchat(String dtdmbankhamTinhchat) {
		this.dtdmbankhamTinhchat = dtdmbankhamTinhchat;
	}

	@Column(name = "DTDMNHANVIEN_TENBC", length = 250)
	@Length(max = 250)
	public String getDtdmnhanvienTenbc() {
		return this.dtdmnhanvienTenbc;
	}

	public void setDtdmnhanvienTenbc(String dtdmnhanvienTenbc) {
		this.dtdmnhanvienTenbc = dtdmnhanvienTenbc;
	}

	@Column(name = "DTDMBANKHAM_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmbankhamNgaygiocn() {
		return this.dtdmbankhamNgaygiocn;
	}

	public void setDtdmbankhamNgaygiocn(Double dtdmbankhamNgaygiocn) {
		this.dtdmbankhamNgaygiocn = dtdmbankhamNgaygiocn;
	}

	@Column(name = "DTDMBANKHAM_CHON")
	public Boolean getDtdmbankhamChon() {
		return this.dtdmbankhamChon;
	}

	public void setDtdmbankhamChon(Boolean dtdmbankhamChon) {
		this.dtdmbankhamChon = dtdmbankhamChon;
	}

	@Column(name = "DTDMNHANVIEN_NHOM", length = 5)
	@Length(max = 5)
	public String getDtdmnhanvienNhom() {
		return this.dtdmnhanvienNhom;
	}

	public void setDtdmnhanvienNhom(String dtdmnhanvienNhom) {
		this.dtdmnhanvienNhom = dtdmnhanvienNhom;
	}

	@Column(name = "DMLOAIKHOA_MASO")
	public Integer getDmloaikhoaMaso() {
		return this.dmloaikhoaMaso;
	}

	public void setDmloaikhoaMaso(Integer dmloaikhoaMaso) {
		this.dmloaikhoaMaso = dmloaikhoaMaso;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmBanKham")
	public Set<DtDmBacSiBanKham> getDtDmBacSiBanKhams() {
		return this.dtDmBacSiBanKhams;
	}

	public void setDtDmBacSiBanKhams(Set<DtDmBacSiBanKham> dtDmBacSiBanKhams) {
		this.dtDmBacSiBanKhams = dtDmBacSiBanKhams;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmBanKham")
	public Set<DtDmBacSiBanKham> getDtDmBacSiBanKhams_1() {
		return this.dtDmBacSiBanKhams_1;
	}

	public void setDtDmBacSiBanKhams_1(Set<DtDmBacSiBanKham> dtDmBacSiBanKhams_1) {
		this.dtDmBacSiBanKhams_1 = dtDmBacSiBanKhams_1;
	}

}
