package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DtDmPlPhauThuat generated by hbm2java
 */

@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "DT_DM_PL_PHAU_THUAT", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "DTDMPLPT_MA"))
public class DtDmPlPhauThuat implements java.io.Serializable {

	private Integer dtdmplptMaso;
	private String dtdmplptMa;
	private String dtdmplptMaphu;
	private String dtdmplptTen;
	private String dtdmplptThuockhoa;
	private Double dtdmplptNgaygiocn;
	private Boolean dtdmplptChon;
	private Set<DtDmPhauThuat> dtDmPhauThuats = new HashSet<DtDmPhauThuat>(0);
	private Set<DtDmPhauThuat> dtDmPhauThuats_1 = new HashSet<DtDmPhauThuat>(0);

	public DtDmPlPhauThuat() {
	}

	public DtDmPlPhauThuat(String dtdmplptMa, String dtdmplptTen) {
		this.dtdmplptMa = dtdmplptMa;
		this.dtdmplptTen = dtdmplptTen;
	}

	public DtDmPlPhauThuat(String dtdmplptMa, String dtdmplptMaphu,
			String dtdmplptTen, String dtdmplptThuockhoa,
			Double dtdmplptNgaygiocn, Boolean dtdmplptChon,
			Set<DtDmPhauThuat> dtDmPhauThuats,
			Set<DtDmPhauThuat> dtDmPhauThuats_1) {
		this.dtdmplptMa = dtdmplptMa;
		this.dtdmplptMaphu = dtdmplptMaphu;
		this.dtdmplptTen = dtdmplptTen;
		this.dtdmplptThuockhoa = dtdmplptThuockhoa;
		this.dtdmplptNgaygiocn = dtdmplptNgaygiocn;
		this.dtdmplptChon = dtdmplptChon;
		this.dtDmPhauThuats = dtDmPhauThuats;
		this.dtDmPhauThuats_1 = dtDmPhauThuats_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DT_DM_PL_PHAU_THUAT")
	@SequenceGenerator(name = "DT_DM_PL_PHAU_THUAT", sequenceName = "DT_DM_PL_PHAU_THUAT_DTDMPLPT_M", allocationSize = 1)
	@Column(name = "DTDMPLPT_MASO", unique = true, nullable = false)
	public Integer getDtdmplptMaso() {
		return this.dtdmplptMaso;
	}

	public void setDtdmplptMaso(Integer dtdmplptMaso) {
		this.dtdmplptMaso = dtdmplptMaso;
	}

	@Column(name = "DTDMPLPT_MA", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getDtdmplptMa() {
		return this.dtdmplptMa;
	}

	public void setDtdmplptMa(String dtdmplptMa) {
		this.dtdmplptMa = dtdmplptMa;
	}

	@Column(name = "DTDMPLPT_MAPHU", length = 3)
	@Length(max = 3)
	public String getDtdmplptMaphu() {
		return this.dtdmplptMaphu;
	}

	public void setDtdmplptMaphu(String dtdmplptMaphu) {
		this.dtdmplptMaphu = dtdmplptMaphu;
	}

	@Column(name = "DTDMPLPT_TEN", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDtdmplptTen() {
		return this.dtdmplptTen;
	}

	public void setDtdmplptTen(String dtdmplptTen) {
		this.dtdmplptTen = dtdmplptTen;
	}

	@Column(name = "DTDMPLPT_THUOCKHOA", length = 50)
	@Length(max = 50)
	public String getDtdmplptThuockhoa() {
		return this.dtdmplptThuockhoa;
	}

	public void setDtdmplptThuockhoa(String dtdmplptThuockhoa) {
		this.dtdmplptThuockhoa = dtdmplptThuockhoa;
	}

	@Column(name = "DTDMPLPT_NGAYGIOCN", precision = 22, scale = 0)
	public Double getDtdmplptNgaygiocn() {
		return this.dtdmplptNgaygiocn;
	}

	public void setDtdmplptNgaygiocn(Double dtdmplptNgaygiocn) {
		this.dtdmplptNgaygiocn = dtdmplptNgaygiocn;
	}

	@Column(name = "DTDMPLPT_CHON")
	public Boolean getDtdmplptChon() {
		return this.dtdmplptChon;
	}

	public void setDtdmplptChon(Boolean dtdmplptChon) {
		this.dtdmplptChon = dtdmplptChon;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmPlPhauThuat")
	public Set<DtDmPhauThuat> getDtDmPhauThuats() {
		return this.dtDmPhauThuats;
	}

	public void setDtDmPhauThuats(Set<DtDmPhauThuat> dtDmPhauThuats) {
		this.dtDmPhauThuats = dtDmPhauThuats;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dtDmPlPhauThuat")
	public Set<DtDmPhauThuat> getDtDmPhauThuats_1() {
		return this.dtDmPhauThuats_1;
	}

	public void setDtDmPhauThuats_1(Set<DtDmPhauThuat> dtDmPhauThuats_1) {
		this.dtDmPhauThuats_1 = dtDmPhauThuats_1;
	}

}
