package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * NguoiDungVaiTro generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "NGUOI_DUNG_VAI_TRO", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ND_MASO", "VAITRO_MASO" }))
public class NguoiDungVaiTro implements java.io.Serializable {

	private Integer ndvaitroMaso;
	private NguoiDung nguoiDung;
	private VaiTro vaiTro;

	public NguoiDungVaiTro() {
	}

	public NguoiDungVaiTro(NguoiDung nguoiDung, VaiTro vaiTro) {
		this.nguoiDung = nguoiDung;
		this.vaiTro = vaiTro;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NGUOI_DUNG_VAI_TRO")
	@SequenceGenerator(name = "NGUOI_DUNG_VAI_TRO", sequenceName = "NGUOI_DUNG_VAI_TRO_NDVAITRO_MA", allocationSize = 1)
	@Column(name = "NDVAITRO_MASO", unique = true, nullable = false)
	public Integer getNdvaitroMaso() {
		return this.ndvaitroMaso;
	}

	public void setNdvaitroMaso(Integer ndvaitroMaso) {
		this.ndvaitroMaso = ndvaitroMaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ND_MASO", nullable = false)
	@NotNull
	public NguoiDung getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(NguoiDung nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VAITRO_MASO", nullable = false)
	@NotNull
	public VaiTro getVaiTro() {
		return this.vaiTro;
	}

	public void setVaiTro(VaiTro vaiTro) {
		this.vaiTro = vaiTro;
	}

}
