package com.iesvn.dieutridanhmuc.entity;

// Generated Aug 3, 2011 2:01:45 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VaiTro generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy = false)
@Table(name = "VAI_TRO", catalog = "DB_YTDT_BD", uniqueConstraints = @UniqueConstraint(columnNames = "VAITRO_MA"))
public class VaiTro implements java.io.Serializable {

	private Integer vaitroMaso;
	private String vaitroMa;
	private String vaitroTen;
	private Set<NguoiDungVaiTro> nguoiDungVaiTros = new HashSet<NguoiDungVaiTro>(
			0);
	private Set<NguoiDungVaiTro> nguoiDungVaiTros_1 = new HashSet<NguoiDungVaiTro>(
			0);

	public VaiTro() {
	}

	public VaiTro(String vaitroMa) {
		this.vaitroMa = vaitroMa;
	}

	public VaiTro(String vaitroMa, String vaitroTen,
			Set<NguoiDungVaiTro> nguoiDungVaiTros,
			Set<NguoiDungVaiTro> nguoiDungVaiTros_1) {
		this.vaitroMa = vaitroMa;
		this.vaitroTen = vaitroTen;
		this.nguoiDungVaiTros = nguoiDungVaiTros;
		this.nguoiDungVaiTros_1 = nguoiDungVaiTros_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "VAI_TRO")
	@SequenceGenerator(name = "VAI_TRO", sequenceName = "VAI_TRO_VAITRO_MASO_SEQ", allocationSize = 1)
	@Column(name = "VAITRO_MASO", unique = true, nullable = false)
	public Integer getVaitroMaso() {
		return this.vaitroMaso;
	}

	public void setVaitroMaso(Integer vaitroMaso) {
		this.vaitroMaso = vaitroMaso;
	}

	@Column(name = "VAITRO_MA", unique = true, nullable = false, length = 128)
	@NotNull
	@Length(max = 128)
	public String getVaitroMa() {
		return this.vaitroMa;
	}

	public void setVaitroMa(String vaitroMa) {
		this.vaitroMa = vaitroMa;
	}

	@Column(name = "VAITRO_TEN", length = 128)
	@Length(max = 128)
	public String getVaitroTen() {
		return this.vaitroTen;
	}

	public void setVaitroTen(String vaitroTen) {
		this.vaitroTen = vaitroTen;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "vaiTro")
	public Set<NguoiDungVaiTro> getNguoiDungVaiTros() {
		return this.nguoiDungVaiTros;
	}

	public void setNguoiDungVaiTros(Set<NguoiDungVaiTro> nguoiDungVaiTros) {
		this.nguoiDungVaiTros = nguoiDungVaiTros;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "vaiTro")
	public Set<NguoiDungVaiTro> getNguoiDungVaiTros_1() {
		return this.nguoiDungVaiTros_1;
	}

	public void setNguoiDungVaiTros_1(Set<NguoiDungVaiTro> nguoiDungVaiTros_1) {
		this.nguoiDungVaiTros_1 = nguoiDungVaiTros_1;
	}

}
